### ISSUE TITLE
имя (номер) базы

### ISSUE THREAD

**Issue by stalker-druid** [redis/RedisDesktopManager#10]
Хотелось бы иметь перед глазами номер базы, в которой в данный момент ковыряемся. А в идеале - ее имя(алиас), которое можно было б как-то задавать у себя локально. Да и хост тоже чтоб был перед глазами, чтоб снизить вероятность "окошком ошибся". Возможно даже ввести цветовое маркирование хостов (при настройке коннекта задать цвет и этим цветом например будут табочки с данными..).

**Comment by uglide** [comment]
Я разбил этот таск на несколько. Отображение хоста и номера базы в табке уже реализовано. Остальные замечания будут реализованы позже: таск #22  и #23 

Спасибо за обратную связь!
