### ISSUE TITLE
After reinstall from 0.6.2 to 0.7.0 connections are lost

### ISSUE THREAD

**Issue by dtr0yan** [redis/RedisDesktopManager#107]
All connections lost after upgrade to 0.7.0
And I unable to import my old connections.xml file. After I press Manage Connections -> import and choose connections.xml message box appear with text "Connections imported from connections file" but they not appear in connections list.

**Comment by uglide** [comment]
Probably connections.xml is empty. Installer do not remove connections settings. 

Try to change working dir
![17-12-2013 17-15-04](https://f.cloud.github.com/assets/1655867/1764912/1fb3c056-672e-11e3-88d6-928f4807fc8a.jpg)

**Comment by dtr0yan** [comment]
connection.xml not empty. Working dir not changed.

**Comment by uglide** [comment]
OK. Please provide screencast with bug reproduction steps.

**Comment by dtr0yan** [comment]
Oh, I find real connections.xml file. You was right about working dir.
What about to save or ask user to use previous conf file in case of upgrading?
Because current behavior will confuse users that make upgrade.

**Comment by uglide** [comment]
You right - it's unclear behavior.  I will fix it in 0.7.1
