### ISSUE TITLE
Deleting keys causes invalid state in client, closes

### ISSUE THREAD

**Issue by TimNZ** [redis/RedisDesktopManager#1116]
Windows 7x64, client 0.7.5
1. Click Delete button to remove the key
2. Key removed
3. Try to continue using GUI and it closes

**Comment by uglide** [comment]
Hello,

Can you provide more info?
- Redis version
- Key type

**Comment by TimNZ** [comment]
Redis 2.6.12 - MS Windows Port
Any key

Basically deleting any key and then trying another operation or sometimes immediately results in client closing.  It's replicable 100% of the time.

![image](https://f.cloud.github.com/assets/1051701/2221531/330e43c4-9a5a-11e3-8dd7-1bcaeac217d1.png)

**Comment by uglide** [comment]
Please try new preview build http://redisdesktop.com/downloads/redis-desktop-manager-0.7.6.2.exe and send me feedback.

**Comment by TimNZ** [comment]
Thanks Igor, update works great.

On Delete key name in tree is grayed out, client remains stable
