### ISSUE TITLE
Reload crash

### ISSUE THREAD

**Issue by maljolani** [redis/RedisDesktopManager#114]
Version: 0.6.2 and 0.7.1
Environment: Ubuntu 12.04 x64
Redis Server Version: 2.8

Steps to reproduce:
1.Add new Redis connection.
2.Connect to the new added or Existed Redis connection 
3.Right click on mouse for context menu on Redis connection
4.Click on Reload link
5.Observe the result

Expected result: To reload connection and fetch new redis keys

Actual Result: 
1.Crash and auto application termination
2.Open the application again and you will not find the new connection added from "Steps to reproduce #1"

**Comment by uglide** [comment]
Do you use latest version of RDM (0.7.1)?

**Comment by maljolani** [comment]
And no crash report stored at "crashreporter" file

**Comment by uglide** [comment]
Fixed in 0.7.4
