### ISSUE TITLE
Debian 7 testing amd64:  This application failed to start because it could not find or load the Qt platform plugin "xcb".

### ISSUE THREAD

**Issue by ztripez** [redis/RedisDesktopManager#1143]
When i try to run:
ztripez@lucy:~$ /usr/share/redis-desktop-manager/bin/rdm
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted

I've install qt5 binding
apt-get build-dep qt5-qmake:i386
and libxcb 

apt-get install libxcb1 libxcb1:i386

Still get the error, i've event installed KDE desktop

**Comment by ztripez** [comment]
Hm.. the program started after i installed wine. Some dependency are clearly missing,

**Comment by uglide** [comment]
Fixed in 0.7.6
