### ISSUE TITLE
Dialogs appearing on incorrect monitor in Ubuntu

### ISSUE THREAD

**Issue by atrauzzi** [redis/RedisDesktopManager#1293]
At home I run a laptop with a dual monitor setup.  When the application is on my rightmost (attached) monitor, new dialogs still appear on the leftmost (laptop panel) screen.

I'm using an nvidia GTX670MX and their proprietary drivers.

**Comment by uglide** [comment]
I cannot reproduce this issue on latest 0.7.9.X builds. Looks like this issue was fixed somehow :)
