### ISSUE TITLE
Increase Font Size

### ISSUE THREAD

**Issue by atrauzzi** [redis/RedisDesktopManager#1367]
Just tried 0.7.6 on Ubuntu and the font style looks much better!

I think overall the font size could be bumped up and the left tree menu should be even a few pixels larger than that.  At least large enough so that the targets are easier to hit with a touchpad or even a touch display.

**Comment by uglide** [comment]
Since 0.9.0-aplha1 you can change app font family and size in settings.

**Comment by atrauzzi** [comment]
Any chance you're also detecting DPI?  Making this a custom setting won't be the right approach in those scenarios.  Especially because the padding and other aspects of the layout will need to shift.
