### ISSUE TITLE
Is there a shortcut to delete?

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#1391]
Is there a shortcut to delete?

**Comment by uglide** [comment]
https://github.com/uglide/RedisDesktopManager/wiki/How-to-uninstall-Redis-Desktop-Manager

**Comment by adriancooney** [comment]
I think he might mean delete a host. I'm looking for it too. Maybe an option in "Manage connections" called "Delete connection" which deletes the currently highlighted connection in the list?

**Comment by uglide** [comment]
Use context menu of server item in connections tree
22 июля 2014 г. 14:16 пользователь "Adrian Cooney" notifications@github.com
написал:

**Comment by adriancooney** [comment]
Ah I see. I had tried that but it wasn't working for some reason. Now it is. Thanks!
