### ISSUE TITLE
Can't run rdm

### ISSUE THREAD

**Issue by Zyles** [redis/RedisDesktopManager#1575]
Ubuntu 12.04

$ /usr/share/redis-desktop-manager/bin/rdm
/usr/share/redis-desktop-manager/bin/rdm: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory

$ locate libglib-2.0.so.0
/lib/x86_64-linux-gnu/libglib-2.0.so.0
/lib/x86_64-linux-gnu/libglib-2.0.so.0.3200.4
/usr/share/gdb/gdb/auto-load/libglib-2.0.so.0.3200.4-gdb.py

**Comment by uglide** [comment]
@Zyles Please try this package http://redisdesktop.com/builds/redis-desktop-manager_0.7.7.32_amd64.deb
