### ISSUE TITLE
SSH connection problems

### ISSUE THREAD

**Issue by npmdev** [redis/RedisDesktopManager#1611]
We have 330000+ entries in the database. I can load and index the keys, but I don't get the values. The activity indicator is shown the whole time, but no values are loaded. I also don't get any (timeout) error.

**Comment by uglide** [comment]
Please provide more details:
- RDM version
- Do you use SSH tunnel or not?
- What is shown in console ("System console" button) after you click on key in  key tree?
- Redis version
- OS

**Comment by npmdev** [comment]
RDM Version 0.7.6
Connection via SSH Tunnel
Redis Version 2.6.16
OSX Mavericks
Timeout 300s

Console output:
[14:12:10] NodeJSLive > [execute] select 0 -> response received: 
 +OK
+OK

[14:12:10] NodeJSLive > [runCommand] TTL entries:t9419:4 -> response recieved
[14:17:45] NodeJSLive > [execute] select 0 -> response partially received. Execution timeout
[14:17:45] NodeJSLive > [execute] select 0 -> response received: 

[14:17:45] NodeJSLive > [runCommand] TTL entries:t9419:4 -> response recieved

**Comment by npmdev** [comment]
Same problem in Windows 7

**Comment by uglide** [comment]
Thanks for info. I will investigate this problem

**Comment by pb30** [comment]
I believe I'm experience a similar issue

rdm 0.7.6
Redis 2.8.8
SSH Tunnel
OSX 10.9.3

It's a new Redis server with less than 20 keys. Nearly identical staging server works fine without SSH tunnel, but production server that requires SSH never returns any values, just a constant spinner. Console tab works fine on both.

**Comment by crackfoo** [comment]
I'm seeing the same issue using the lastest rdm on OSX 10.9

Any idea if there is a fix to this?

**Comment by uglide** [comment]
@crackfoo This issue not fixed yet

**Comment by crackfoo** [comment]
ok thanks for the update. Looking forward to testing this out proper.

**Comment by bykbtzr** [comment]
:+1:  +1

**Comment by uglide** [comment]
Fixed in 0.8.0
