### ISSUE TITLE
OSX: connections.xml is stored in user home and is left with mode 0644

### ISSUE THREAD

**Issue by adamierymenko** [redis/RedisDesktopManager#1645]
(1) connections.xml should be in Library/Application Support/rdm/... or something.

(2) it's left in mode 0644, which is insecure as it can contain passwords. Techically it should use keychain, but at least it should have mode set to 0600 to prevent other user processes from viewing its contents.

**Comment by uglide** [comment]
Thanks for advice

**Comment by josser** [comment]
+1, please, please! It's a bit annoying to see that file in users home.

**Comment by yonghanlee** [comment]
Thanks for info.

**Comment by uglide** [comment]
@adamierymenko @josser @yonghanlee This improvement implemented and will be available in 0.7.7
