### ISSUE TITLE
No way to refresh collection

### ISSUE THREAD

**Issue by DataGreed** [redis/RedisDesktopManager#1689]
Every time I do some changes to the redis database I have to restart RDM in order to view this changes. A simple "refresh" button could fix that.

**Comment by maxwellb** [comment]
Right click the host, click Refresh? If there were more UI, what would it look like, and where?

**Comment by uglide** [comment]
@DataGreed @maxwellb also in order to reload current value just do left click on key. UI improvements are coming, just want to figure out right way to do them.

**Comment by DataGreed** [comment]
> Right click the host, click Refresh? If there were more UI, what would it look like, and where?

Thanks, found it! I actually expected this menu to appear when right clicking on a particular database (i.e. db0) rather than on redis-server instance, that's why I could not find it. 

By the way, it would be cool for RDM to remember which DBs where collapsed and which ones were expanded after reload took place. 

Users also usually expect shortcuts like cmd+r (on mac) or ctrl+r (on windows/linux) to work :)

Thanks

**Comment by deanrad** [comment]
+1 on the shortcuts/menu items. Cmd-R is a fine one

**Comment by uglide** [comment]
Implemented in 0.8.0:
- Reload button 
- Ctrl+r / Cmd+r / F5 short-keys
  ![screenshot from 2015-01-24 11 24 39](https://cloud.githubusercontent.com/assets/1655867/5886853/b8e37152-a3bb-11e4-8500-3095294890c8.png)

**Comment by nello** [comment]
Why is this closed??? No way to do this on a Mac, guys.
