### ISSUE TITLE
Problem with deb package version 0.3.1 Beta Release

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#17]
When tryied launching rdm after install this message showed up:

$ /usr/share/redis-desktop-manager/bin/rdm 
/usr/share/redis-desktop-manager/bin/rdm: error while loading shared libraries: libssh2.so.1: cannot open shared object file: No such file or directory

**Comment by uglide** [comment]
Problem fixed. Download latest package from releases

**Comment by chienle** [comment]
Hi guys,
How to it ?
