### ISSUE TITLE
User Setting to view string value as JSON

### ISSUE THREAD

**Issue by jefflafay** [redis/RedisDesktopManager#1701]
For me, it would be nice to have a setting to default string values to be viewed with JSON formatting. That way when I look at an object, that tab opens with "Value" pre-selected with "JSON".

**Comment by cbigsby** [comment]
I think that this setting has been removed. It was partially commented out in commit 11f27d0a and then  completely removed in commit 8dac84df. It would be great if this setting could be re-added.

**Comment by uglide** [comment]
Hello @cbigsby 
This feature will be replaced by #3310 To make it happen faster please add bounty to this issue via BountySource.
