### ISSUE TITLE
F5 keystroke handler

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#1730]
Linked with #1689 . 
As a user I want to press some button in order to reload value.

_Given_  user works with a value tab
_When_ user presses some button 
_Then_ only current tab will be reloaded 

_Given_ user works with the tree
_When_ user presses some button 
_Then_ only selected DB will be reloaded and the tree expansion state will be kept

**Comment by jbrooksuk** [comment]
The same should apply when using <kbd>⌘+R</kbd> on OSX.

**Comment by uglide** [comment]
Implemented in 0.8.0. More info https://github.com/uglide/RedisDesktopManager/issues/1689#issuecomment-71307002
