### ISSUE TITLE
Support escaped characters in quoted strings in Console

### ISSUE THREAD

**Issue by maxwellb** [redis/RedisDesktopManager#1738]
With 6bc1073, a user can specify command arguments with spaces by enclosing the argument in quotes. However, arguments from the Console cannot contain quote literals, or nonprintable characters (and others?).

_Given_ user works with the console tab
_When_ user sends a command with escaped characters
_Then_ the argument is parsed with the literal value of the escaped characters

**Considerations**
What escaping convention should be used? C-style? SQL-style double-quotes?
Number and type of characters to support escaping? Just quotes? All code points?
Option: Just copy the parsing from sds.c in hiredis?

**Comment by uglide** [comment]
I think we should provide same behavior as redis-cli in this case, so parsing should be implemented similar to  parsing from sds.c in hiredis

P.S. please feel free to ask any questions in skype (igor.mal1novsk1y) or via twitter

**Comment by uglide** [comment]
Related to #1893

**Comment by uglide** [comment]
Hex escaping was Implemented in 0.8.0-RC5
