### ISSUE TITLE
Tablets not supported in Windows

### ISSUE THREAD

**Issue by russellseymour** [redis/RedisDesktopManager#1746]
Hello,

I am using Redis Desktop Manager on Windows 7 64bit with a Wacom bamboo tablet.  Unfortunately the application does not recognise the equivalent of mouse clicks from the pen on the tablet, e.g. pen down events, making the application unusable.

Please let me know if there are any logs or anything I can give you.

Thanks, Russell

**Comment by uglide** [comment]
Hello @russellseymour 
RedisDesktopManager is on beta stage now and I don't plan to support tables till official release for sure or even more later. Still source code is open, so if you want you can add changes to support tablet.
