### ISSUE TITLE
Hex Value format

### ISSUE THREAD

**Issue by windsent** [redis/RedisDesktopManager#1843]
Could you add view values as hex?

**Comment by uglide** [comment]
Nice suggestion! I will add hex view in feature releases

**Comment by uglide** [comment]
Hex value formatter was implemented in 0.8.0 (read-only)

![screenshot from 2015-01-29 20 35 17](https://cloud.githubusercontent.com/assets/1655867/5963622/90b5cccc-a7f6-11e4-9dd1-a39d528ef6d0.png)
