### ISSUE TITLE
Feature Request: support editing values in key-value pairs

### ISSUE THREAD

**Issue by tradetree** [redis/RedisDesktopManager#1846]
I would request that you support editing values in key-value pairs.

**Comment by uglide** [comment]
Implemented in 0.8.0 as part of new implementation of value-editor and will look like this:
![screenshot from 2014-12-13 14 14 50](https://cloud.githubusercontent.com/assets/1655867/5423678/794534a4-82d2-11e4-978d-7de63bc83b4d.png)

If you have any suggestions feel free to add comment. Thanks!
