### ISSUE TITLE
rdm mac version creates a `connections.xml` in home directory

### ISSUE THREAD

**Issue by reorx** [redis/RedisDesktopManager#1859]
This is a little bit annoying since we always want to keep our home directory clean on mac, I think this file can be placed and named more elegantly, how about  `~/.rdm.connections.xml` or `~/.rdm/connections.xml` in case there may be more configuration fils in the future?

P.S. my rdm version is 0.7.6.

**Comment by uglide** [comment]
Don't worry this issue fixed #1645 (https://github.com/uglide/RedisDesktopManager/issues/1645)

**Comment by uglide** [comment]
0.7.7 latest night build http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.30.dmg

**Comment by reorx** [comment]
Thanks, looking forward to 0.7.7 :smile:

**Comment by reorx** [comment]
And there it goes! :tada:
