### ISSUE TITLE
Connect from vagrant

### ISSUE THREAD

**Issue by Fynkymynky** [redis/RedisDesktopManager#1861]
I have a vagrant VM running redis and RedisDesktopManager running on the host, OSX. I've been unable to get the RedisDesktopManager to ssh into vagrant.

Is there a way I can ssh into vagrant with the GUI?

Thanks

**Comment by uglide** [comment]
@Fynkymynky 
If you faced this issue #1847, then download fixed night version http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.30.dmg

**Comment by Fynkymynky** [comment]
Upgrading to the lastest RedisDesktopManager was the solution. Thanks.
