### ISSUE TITLE
How to connect to the redis server via SSH keys (without password) ?

### ISSUE THREAD

**Issue by ingvar** [redis/RedisDesktopManager#1862]

**Comment by uglide** [comment]
Hello @ingvar,

this feature implemented in 0.7.7. Unfortunately this version is not released yet, but you can use latest night build for your platform 

Windows - http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.35.exe
Ubuntu i386 - http://redisdesktop.com/builds/redis-desktop-manager_Ubuntu12.04_0.7.7.30_i386.deb
Ubuntu amd64 - http://redisdesktop.com/builds/redis-desktop-manager_0.7.7.32_amd64.deb
Mac OS X - http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.30.dmg

**Comment by ingvar** [comment]
Thanks. it works!

**Comment by uglide** [comment]
you are welcome :+1:

**Comment by raymondjplante** [comment]
Do you have a date targeted for the next stable release with ssh keys feature included?

**Comment by sergiopvilar** [comment]
The download links aren't working anymore, please I need this feature =(

**Comment by uglide** [comment]
@sergiovilar Use links from bootom section of this page http://redisdesktop.com/download

**Comment by sergiopvilar** [comment]
Thanks!!
