### ISSUE TITLE
Allow definition of root namespaces of interest

### ISSUE THREAD

**Issue by ovanes** [redis/RedisDesktopManager#1872]
A a DB might contain lots of keys I think it might be beneficial not only to allow the definition of namespace separator like ':', but also the list of namespaces of interest to avoid downloading of all keys, i.e. the DB with statistics might contain:
- stats:daily
- stats:weekly
- stats:monthly

events. So I'd like to preferably define in the config some redis based globbing expression for namespaces of interest, e.g. `stats:weekly:*,stats:monthly:*`.

**Comment by uglide** [comment]
Partially implemented in 0.8.0:
![screen shot 2015-03-09 at 12 27 12 pm](https://cloud.githubusercontent.com/assets/1655867/6553280/d375c434-c657-11e4-898d-fa302fe2f7d0.png)
