### ISSUE TITLE
Honor .ssh/config file

### ISSUE THREAD

**Issue by ovanes** [redis/RedisDesktopManager#1874]
Our live Redis servers are all running on VMs at another server with some sort of complex SSH tunneling via bastion host. It be really cool if I could just use the definitions on how to reach the server from my .ssh/config file by typing just the host-name from it. Currently, I just get in the UI 'Invalid settings detected'.
##

**Comment by uglide** [comment]
Hi, Can you describe this feature more detailed?

**Comment by ovanes** [comment]
Sure, thanks for the prompt reply.

As you known, every *nix user might have an ssh-config file: ~/.ssh/config (actually ssh honors root ssh-config as well, but that is minor interest in that context). Users can define there the weirdest stuff :) for ssh-login, like keys to be used for login and all other ssh options. 

My ssh-config looks like this:

``` bash
Host bastion_host_name
  HostName 1.2.3.4
  Port 22
  IdentityFile ~/.ssh/id_rsa
  User bastion_host_user

Host vm_located_at.bastion_host_name
  HostName some_internal_host_name_can_be_localhost
  Port some_internal_port
  User vagrant
  ProxyCommand ssh -l bastion_host_user bastion_host_name -W %h:%p
```

To login to `vm_located_at.bastion_host_name` from the command line I just use:

``` bash
$ ssh vm_located_at.bastion_host_name
```

My desire would be just type into the SSH-Tunnel tab the host name `vm_located_at.bastion_host_name` and the rest is retrieved from the ssh-config. I might need to use the `-A` option to forward the ssh-agent as well, but I can put it in the config as well.

May be there can be a checkbox: 'Use ssh-config'.

**Comment by uglide** [comment]
Hi, ssh keys already has implemented in 0.7.7. Night build is available on
site
28 июня 2014 г. 7:55 пользователь "Igor Kryltsov" notifications@github.com
написал:

**Comment by whitehat101** [comment]
:+1:

I tried the 0.7.7 OS X nightly, and it seemed to work a little better, but I couldn't get it to tunnel correctly.

I ended up opening a manual tunnel, and then connecting via "localhost"

```
ssh SSH_HOST -L 7000:localhost:6379
```

_7000 chosen arbitrarily_

**Comment by uglide** [comment]
*Bad news:*
library libssh2 (which RAM uses) does not provide possibility to work with .ssh/config. So I forced to move this feature to 1.0.0 milestone.

*Good news:*
I will add automatic ssh authentication via system client.

**Comment by uglide** [comment]
Manual tunnelling documented and should be used for complicated ssh configs
