### ISSUE TITLE
Connection list freezes after redis server stopped.

### ISSUE THREAD

**Issue by tevino** [redis/RedisDesktopManager#1892]
Version: 0.7.6
Environment: OS X 10.9.3
Redis Server Version: 2.8.11

Steps to reproduce:
1. Add a new connection to `localhost`
2. Start `redis-server`
3. Click the newly created connection to `localhost`
4. Stop `redis-server`
5. Right click the connection name, choose `Reload`
6. Start `redis-server`
7. Click(or right click) the connection name

Expected result:
Show db list(or context menu)

Actual Result:
Nothing

**Comment by uglide** [comment]
Fixed in 0.8.0
