### ISSUE TITLE
Value contains zero-bytes ("\x00") can not be displayed correctly

### ISSUE THREAD

**Issue by tevino** [redis/RedisDesktopManager#1893]
Version: 0.7.6
Environment: OS X 10.9.3
Redis Server Version: 2.8.11

In redis-cli do:
    > SET test "123\x00456"
or 
    > SET test "123"
    > SETRANGE test 4 "456"

The value of `test` is then displayed as `123` in RedisDesktopManager, it seems that RedisDesktopManager treats `\x00` as **the end of that value**.

**Comment by uglide** [comment]
Duplicate of #1738
