### ISSUE TITLE
Implement data migration from one db to another [$50]

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#1924]
- Add ability to Copy keys;
  - Between db's in single redis-server
  - Between db's in different redis-servers
##

**Comment by uglide** [comment]
Superseded by #3529

**Comment by zoek1** [comment]
@uglide can i take this? :smile:

**Comment by uglide** [comment]
@zoek1 if you can do this - please do. This feature should be implemented in Bulk Operations module

**Comment by zoek1** [comment]
Sure @uglide, I've been working on this. Thanks for the advice! :smile:
