### ISSUE TITLE
Can not set ssh password on OS X 10.9.3

### ISSUE THREAD

**Issue by messense** [redis/RedisDesktopManager#1965]
![image](https://cloud.githubusercontent.com/assets/1556054/3383904/9c593ca4-fc51-11e3-9a67-d661cd1ec711.png)

The UI has some problems.

**Comment by crackfoo** [comment]
expand the box and you can see the field

**Comment by messense** [comment]
@crackfoo Yes, it worked.

**Comment by uglide** [comment]
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/1847
