### ISSUE TITLE
Invalid Settings Detected when "uncheck the password in ssh tab"

### ISSUE THREAD

**Issue by pankajsinghal** [redis/RedisDesktopManager#2099]
![screen shot 2014-07-05 at 6 11 27 pm](https://cloud.githubusercontent.com/assets/7523102/3486556/faccd3f2-0441-11e4-9c2a-4bcaad0d8a7f.png)
Why am i getting this error. I should be allowed to connect via ssh even without a password because key based authentication is there.

**Comment by uglide** [comment]
Please look at issue https://github.com/uglide/RedisDesktopManager/issues/1847
