### ISSUE TITLE
Never ending loading values

### ISSUE THREAD

**Issue by mcmorry** [redis/RedisDesktopManager#2208]
On osx, connected through ssh tunnel to remote server.

Any key I open, the loading rotating icon never disappears and it doesn't show any values.

![screenshot 2014-07-15 10 05 39](https://cloud.githubusercontent.com/assets/1020257/3582083/dbee1146-0bf6-11e4-8007-a70b4cb3403b.jpg)

**Comment by ur001** [comment]
![Same bug on osx](http://habrastorage.org/files/804/558/a93/804558a932834604bab7d2c352eb318f.png)

**Comment by ur001** [comment]
I upgrade Redis from 1.2.6 to 2.4.15, now works fine!

**Comment by uglide** [comment]
Fixed in 0.8.0
