### ISSUE TITLE
Consecutive Namespace Separator Bug

### ISSUE THREAD

**Issue by PvanHengel** [redis/RedisDesktopManager#2216]
When using a separator such as :: (two in a row), the tree structure breaks, but the folders contain a prefix of the 2nd ":" eg

ROOT::LEVEL1::LEVEL2::KEY 

ends up as

ROOT
      :LEVEL1
            :LEVEL2
                      ROOT::LEVEL1::LEVEL2::KEY

**Comment by raffian** [comment]
We need this fixed, same problem.

**Comment by uglide** [comment]
Fixed in 0.8.0

**Comment by raffian** [comment]
Sweet, thank you
