### ISSUE TITLE
Various small issues 0.7.6, windows build

### ISSUE THREAD

**Issue by tw-bert** [redis/RedisDesktopManager#2393]
It's a very nice tool, but (unsurprisingly) not completely finished. Thanks for your work so far.

Main issues:
1. a command like `CONFIG SET save ""` does not work
2. null characters are treated as end of string instead of escaping them (this makes all our data unreadable, since it's prefixed msgpack data). This happens in the console, as well as in both preview modes.
3. the `KEYS` statement is used, making this tool very unsafe for use in production, because of O(n). The tool should use `SCAN` and the likes (and support abort). We have the redis `SLOWLOG` set to the default of 10ms. Any command that takes longer is considered bad (by us, and since it's the default, by redis. that's how it's designed: beware of concurrency in a single threaded design like redis-server). 
4. accidentally clicking on a sorted set with millions of rows causes a long wait and then a crash
5. minor issue: manage connections doesn't support ordering (but we manage the connection.xml manually now, that's much easier. We actually put a junction point in place, to a dvcs sourcecode repo. we have about 60 running redis instances on various servers).

Kind regards, TW

**Comment by tw-bert** [comment]
Thx for milestoning!

**Comment by uglide** [comment]
- Issue №1 fixed in 0.7.7
- Issue №2 - already in bug tracker #2228 
- Issue №3 - already in bug tracker #52 
- Issue №4 - moved to #3283
- Issue №5 - moved to #3284
