### ISSUE TITLE
Not showing hash value

### ISSUE THREAD

**Issue by michaelminter** [redis/RedisDesktopManager#2470]
![screen shot 2014-09-02 at 12 37 37 pm 3](https://cloud.githubusercontent.com/assets/403262/4122758/e08d8770-32c7-11e4-80f7-2b504fe3bf76.png)

**Comment by uglide** [comment]
Hello, 
@michaelminter Please provide more detailed info about issue

**Comment by michaelminter** [comment]
It had something to do with Ruby's Marshall.dump

**Comment by michaelminter** [comment]
Switched to JSON
