### ISSUE TITLE
Search box - search by hitting enter

### ISSUE THREAD

**Issue by mindware** [redis/RedisDesktopManager#2486]
Guys,

Great job on the project. Here's a request: The current search box requires one to click the checkmark in order for the search to become active. I'd like to propose that if we hit enter, it activates the search while the search box is on focus. If one clicks escape, it activates the (X), which will basically undo the search.

**Comment by uglide** [comment]
Implementation of key filtering was changed in 0.8.0 and this issue is not valid now.
