### ISSUE TITLE
rpm support

### ISSUE THREAD

**Issue by ecournane** [redis/RedisDesktopManager#2494]
I have been trying to install this on Fedora with no luck from the *.deb packages using alien to convert them to rpm.  Keep getting a strange conflict which could be caused by alien:

Transaction check error:
  file / from install of redis-desktop-manager-0.7.6.18-2.x86_64 conflicts with file from package filesystem-3.2-19.fc20.x86_64
  file /usr/bin from install of redis-desktop-manager-0.7.6.18-2.x86_64 conflicts with file from package filesystem-3.2-19.fc20.x86_64

**Comment by uglide** [comment]
Hello @ecournane,
I have updated build instruction for Fedora https://github.com/uglide/RedisDesktopManager/wiki/Build-from-source#fedora So you can easily compile RDM from the source.
