### ISSUE TITLE
MSGPACK viewer in value viewer

### ISSUE THREAD

**Issue by bhoudu** [redis/RedisDesktopManager#2519]
MSGPACK format is easily used in redis. As we store a lot of JSON compressed with MSGPACK it would be great to show the MSGPACK value in the value viewer, or better the uncompressed original JSON. Maybe if we could apply a custom lua script on the redis value shown in the GUI, we could do so and much more.

**Comment by uglide** [comment]
MSGPACK value viewer was implemented in 0.8.0
