### ISSUE TITLE
On Mac OS X Mavericks I see only hash keys - not values

### ISSUE THREAD

**Issue by iparq** [redis/RedisDesktopManager#2528]
Just what it says above.  The cells for the hash values are always empty.

Sorted sets have the opposite problem - I see the scores but not the values.

Looks like a nice tool -  but these problems make it useless.

**Comment by taliesins** [comment]
I am experiencing the same problem in windows with version 0.7.6. I am using Redis for a session state server.

I am using chocolatey to install redis:
`choco install redis-64
redis-server.exe --service-install
redis-server.exe --service-start
choco install redis-desktop-manager`

I am using the nuget:

> Microsoft.Web.RedisSessionStateProvider 1.5.0

my web.config:
`<sessionState mode="Custom" customProvider="MySessionStateStore">
  <providers>
    <add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="127.0.0.1" accessKey="" ssl="false" />
  </providers>
</sessionState>`

The actual values are definately there, the GUI just does not display them. We see all the keys, just no values.

**Comment by uglide** [comment]
Fixed in 0.8.0
