### ISSUE TITLE
ssh tunnel

### ISSUE THREAD

**Issue by Zambiorix** [redis/RedisDesktopManager#2556]
Hi,

Great app!

I have a redis server on the cloud that has no acces from the outside world. 
The only way to access the server is via ssh + certificate, not via password.
So, I should be using a ssh tunnel then, but unfortunately it doesn't seem to work with certificates?
The app insists on typing a password. For security reasons I try to avoid access to my servers via a password...

Would be great if you could add that feature?

Thanks!
Cheers
Gerd

**Comment by Zambiorix** [comment]
oh, I'm on a OS X Mavericks ..

**Comment by uglide** [comment]
Hi @Zambiorix 
Thanks for feedback!

SSH keys support already has been implemented, and will be released officially  as part of 0.8.0 release. But you can try it in night build http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.52.dmg
