### ISSUE TITLE
build failed in windows 

### ISSUE THREAD

**Issue by yetuweiba** [redis/RedisDesktopManager#2573]
Hi, When I build the codes in windows,There will have an error:The error messages are:"
..\bin\windows\debug\ui\ui_main.h(29) : fatal error C1083: Can not open include file:“wi
dgets/basetab.h”: No such file or directory
NMAKE : fatal error U1077: “"C:\Program Files\Microsoft Visual Studio 10.0\VC\B
IN\cl.EXE"”: return “0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files\Microsoft Visual Studio 10.0\VC\B
IN\nmake.exe"”: return“0x2”
Stop."

My OS is win7 32bit, vs 2010, qt5.3。

**Comment by uglide** [comment]
Hi @yetuweiba 

Current release branch 0.8.0 is under active development, thats why it can fail to compile or run. After release (October 5, 2014) it will be more stable.
