### ISSUE TITLE
Some SSH Tunnel Settings Are Hidden on Mac

### ISSUE THREAD

**Issue by mulka** [redis/RedisDesktopManager#2631]
I am unable to type in my password for the SSH Tunnel.

See screenshot:
http://screencast.com/t/0hUs6Nx30

**Comment by sepulworld** [comment]
I have this same issue.  Running Mac 10.10

Why was this issue closed?

**Comment by sepulworld** [comment]
SSH keys support already has been implemented, and will be released officially as part of 0.8.0 release. But you can try it in night build http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.52.dmg

I found this in another issue.  That is why this one is closed.
