### ISSUE TITLE
Can't install from source

### ISSUE THREAD

**Issue by leebrooks0** [redis/RedisDesktopManager#2836]
I am following the instructions here: https://github.com/uglide/RedisDesktopManager#other-linux

I run `./configure && qmake redis-desktop-manager.pro && make`
and this is the error that I get: 

```
[lee@lee RedisDesktopManager]$ ./configure && qmake redis-desktop-manager.pro && make
bash: ./configure: No such file or directory
```

I am using Manjaro, although I have close to no experience in building from source so I might be missing something obvious.

**Comment by uglide** [comment]
Instructions was updated https://github.com/uglide/RedisDesktopManager#other-linux 
Feel free to ask questions in http://redisdesktop.com/community
