### ISSUE TITLE
CJK characters in keys and values are not displayed correctly

### ISSUE THREAD

**Issue by simonwiles** [redis/RedisDesktopManager#2886]
Version: 0.7.6
Environment: Linux Mint 17 (Ubuntu Trusty 14.04)
Redis Server Version: 2.8.17

Steps to reproduce:
1. add keys with, e.g., Chinese characters to a redis db.
2. connect to the db with RedisDesktopManager, and view the db.

Expected result: keys are displayed correctly

Actual Result: keys appear as boxes (see attached)
![rdm-screenshot](https://cloud.githubusercontent.com/assets/96218/4946886/c93759c6-661a-11e4-8930-f06210b336e8.png)

**Comment by uglide** [comment]
Fixed in 0.8.0. More info https://github.com/uglide/RedisDesktopManager/issues/1718#issuecomment-71362182
