### ISSUE TITLE
A dialog is show when I open the RDM 0.7.6

### ISSUE THREAD

**Issue by keniushadu** [redis/RedisDesktopManager#2988]
"Please download new version of Redis Desktop Manager : important update " 
But !!! 
It's the last version I can download.
Why would you do that???

**Comment by uglide** [comment]
Hello @keniushadu,
I do so, because I want to pay attention of all RedisDesktopManager user to fundraiser https://www.bountysource.com/teams/redisdesktopmanager/fundraiser

I'm sorry, if this dialog disturb you. It will disappear after 13th December or when fundraiser will be finished
