### ISSUE TITLE
SSH keys support

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#32]

**Comment by marcelaraujo** [comment]
+1

**Comment by stivni** [comment]
+1

**Comment by saizai** [comment]
+1. Also, note that it shouldn't ask for a keyfile — it should just punt to the SSH agent.

**Comment by uglide** [comment]
@saizai, Current implementation of ssh tunneling based on libssh2, and I will not change it in future

**Comment by saizai** [comment]
@uglide Do you have to? Take a look at how e.g. Sequel Pro does it.

In the meantime though, this is a workaround: `ssh -CNfqL 6380:localhost:6379 myserver.com` and add localhost:6380 as the connection for myserver in RDM.

**Comment by uglide** [comment]
@saizai You forgot about systems, which doesn't have `ssh` client by default (e.g. Windows). Thats why implementation based on libssh2 is better.

**Comment by petrlosa** [comment]
+1

**Comment by gr8bit** [comment]
+1

**Comment by uglide** [comment]
Implemented in 0.7.7, release coming soon!
