### ISSUE TITLE
You will got  ERR syntax error if you have blank in you value

### ISSUE THREAD

**Issue by yanyumiao** [redis/RedisDesktopManager#3304]
1 Redis Desktop Manager
192.168.186.135:1>set users:leto '{"name": "leto", "planet": "dune", "likes": ["spice"]}'
ERR syntax error
// You can run it if you remove blank spaces

2 CentOS Shell
127.0.0.1:6379[1]> set users:leto '{"name": "leto", "planet": "dune", "likes": ["spice"]}'
OK

**Comment by uglide** [comment]
Hello, 
Thank you for feedback. This bug was fixed in 0.7.7
