### ISSUE TITLE
GZipped JSON viewer in value viewer

### ISSUE THREAD

**Issue by neuecc** [redis/RedisDesktopManager#3306]
Storing compressed data in Redis/Memcached is a popular way for memory reduction.
I request RedisDesktopManager to support gzip JSON viewer.
already requested MSGPACK support at #2519 

(and I believe LZ4(fastest compression alogorithm) support is much better.)

**Comment by wildcatgerry** [comment]
I am working on this now. I have automatic decompression for viewing gzipped data working.

**Comment by uglide** [comment]
Pull request from @wildcatgerry was merged, but code should be tested on Windows. So I will move this issue to 0.8.0.

**Comment by wildcatgerry** [comment]
zlib is not apart of MSVC, much to my surprise. Do you know the best way to proceed? Include it as a submodule or as a binary?

**Comment by uglide** [comment]
@wildcatgerry My plan is to use MinGW on windows instead of MSVC. So I will address this problem with migration on MinGW.

**Comment by wildcatgerry** [comment]
Alright. Currently it doesnt build in windows with the missing zlib header. Should I make it build in windows for the time being?

**Comment by uglide** [comment]
@wildcatgerry please don't worry. I will fix it. If you have some free time, please feel free to hack https://github.com/uglide/RedisDesktopManager/issues
