### ISSUE TITLE
move ~/connections.xml to ~/.rdm/connections.xml

### ISSUE THREAD

**Issue by ovanes** [redis/RedisDesktopManager#3307]
I think it'd be better to use on unix based systems the convention to store all app-related files in $HOME/.rdm directory.

**Comment by uglide** [comment]
Hello @ovanes,

I made some changes to default configuration paths:
Windows/Linux : $HOME/.rdm/connections.xml
OSX: $HOME/Library/Preferences/rdm/connections.xml

**Comment by ovanes** [comment]
To be honest, I'd expect this path to be in ~/.rdm at Mac OS X. My vim etc, all put stuff there... Intuitively I would not look-up things in that directory :( But that might be the correct place. May be you can leave the stuff there, but create a symlink in ~/.rdm pointing to that directory, so that Users see where the configs are?
