### ISSUE TITLE
RDM does not work with Azure Redis Cache servers

### ISSUE THREAD

**Issue by smakus** [redis/RedisDesktopManager#3312]
RDM seems to connect to the Azure redis cache server with the auth key, however it fails on the PING command, and the connection hangs and eventually times out or is closed.

**Comment by undefinedstudio** [comment]
It worked for me by connecting to the non-ssl port.

**Comment by smakus** [comment]
Unfortunately we require SSL.

**Comment by imperugo** [comment]
Yep, it doesn't with SSL. Probably needs to add the certificate like [here](http://redsmin.uservoice.com/knowledgebase/articles/485711-how-to-connect-redsmin-to-azure-redis-cache)

**Comment by kobynet** [comment]
+1 for the ssl support

**Comment by ccnsolutions** [comment]
Any plans on adding SSL support?

**Comment by uglide** [comment]
@ccnsolutions currently - no.
If you really need this feature I recommend you to donate - https://www.bountysource.com/issues/8114835-rdm-does-not-work-with-azure-redis-cache-servers
And somebody will implement this in RDM.

**Comment by PureKrome** [comment]
@uglide Any chance there's some documentation about how to do this => **how to use RDM to connect to an Azure Redis Cache**.

**Comment by uglide** [comment]
@PureKrome https://github.com/uglide/RedisDesktopManager/wiki/Quick-Start#windows-azure-redis-cache

**Comment by PureKrome** [comment]
@uglide Woot! worked! 

@ everyone else : needs version 0.8 or greater. the current stable (at the time of me typing this) is 0.7.x and it does NOT include the SSL tab in it.

**Comment by subesokun** [comment]
I was following the [Windows Azure Redis Cache](http://docs.redisdesktop.com/en/latest/quick-start/) instructions but when I check the `Use SSL Protocol` checkbox I get a `Invalid Settings detected` warning which says that I need to select a public key but I don't have any.

Any ideas?

My Client: RDM 0.8.3-2550

**Comment by subesokun** [comment]
Ok, solved my issue by downloading the Microsoft certificate and add it as public key in RDM.

```
openssl s_client -connect go.microsoft.com:443 | openssl x509 -outform PEM -out microsoft.pem
```

**Comment by OskarKlintrot** [comment]
In 0.9.3 (Windows 10) there's no checkbox, just radio buttons. When I select the SSL radio button it's not working. When I add the MS cert as @subesokun said it still doesn't work.

**Comment by dinbtechit** [comment]
Can we add an option in the settings to ignore ssl errors?

**Comment by dinbtechit** [comment]
This worked for me:

Connection Settings:
 Select SSL/TLS radio button and Test Connection.

![image](https://user-images.githubusercontent.com/17984781/88494519-cecaf500-cf8c-11ea-9d29-1359e1b0ce96.png)
