### ISSUE TITLE
Support redis 3.0.0 Clusters [$60 awarded]

### ISSUE THREAD

**Issue by oy-ilho** [redis/RedisDesktopManager#3313]
It's not support cluster now ?
May you have any plan to support cluster later?
: ) 
##

**Comment by uglide** [comment]
Hello @soleaf 

RDM doesn't support redis cluster. I will consider adding limited support of redis cluster in 0.8.0:
- Detection of redis cluster
- Dealing with single db in connections tree
- Dealing with -MOVED and -ASK redirects 

If you expect that RDM should support more features of redis cluster, please let me know.

**Comment by oy-ilho** [comment]
Thank you !!

**Comment by allanwax** [comment]
Since Redis Cluster is out, ability to deal and work with it is high priority in my opinion.  We are already using it in production here and it works _very_ well.

**Comment by uglide** [comment]
Hello @allanwax 
Yes, you're right but unfortunatly RDM is open-source project which I mantain in my free time. That's why if you want to see Redis Clusters support in RDM please put some bounty on this issue via Bountysource. Thanks!

**Comment by allanwax** [comment]
@uglide Alas, I haven't programmed in C for two decades.  I hope to use it when it is eventually (hopefully) done.

**Comment by uglide** [comment]
@allanwax 
It's easy to stand aside but if you really want it in RDM - you should **donate some $ here** via Bountysource **or pay this $ to commercial companies** like Redsmin. The choice is yours.

**Comment by uglide** [comment]
Implemented in 0.9.0-alpha3
