### ISSUE TITLE
Silent fail / disappear into background

### ISSUE THREAD

**Issue by wkoot** [redis/RedisDesktopManager#3322]
If you leave any of the popup windows such as "Add new connection" or "Edit" open, RDM first drops out of the alt-tab sequence and after a while it disappears entirely. You can only find it still to be running when you check task manager, but it's not possible to get back to the application.

Windows 7 x64, RDM version 0.7.6.15

**Comment by uglide** [comment]
Hello @wkoot,
Could you please verify that bug is fixed in this build http://redisdesktop.com/builds/redis-desktop-manager-0.7.9.125.exe ?

**Comment by uglide** [comment]
Verified on Windows 7

**Comment by wkoot** [comment]
Yes indeed it works now, thanks
