### ISSUE TITLE
Ability to delete a hash / sorted set / set entry (HDEL, SREM, ZREM)

### ISSUE THREAD

**Issue by dmagliola** [redis/RedisDesktopManager#3324]
We can delete keys, and update the keys and values / scores of entries, but it'd be really valuable to be able to delete entries from these data structures.

**Comment by uglide** [comment]
Implemented in 0.8.0

**Comment by dmagliola** [comment]
Thank you! Is there a binary available to download? (I'd love to be able to build it myself, or even more, contribute, but C++ is really not my thing)
