### ISSUE TITLE
Select command doesn't work with index greater than 9

### ISSUE THREAD

**Issue by merlich** [redis/RedisDesktopManager#3332]
When using the select command in the console with an index greater than 9 (10 or above with two digits), it sets the database index to the second digit.  For example, 'select 12' sets the database index to 2 instead of 12.  However, it does properly know if the supplied index is valid.  If there are 16 databases, 'select 16' provides an invalid db index, but then sets the database to 6.

**Comment by uglide** [comment]
Cannot reproduce on 0.8.0. Probably bug from old 0.7.6 version
