### ISSUE TITLE
Implement  '--settings-dir ./foobar/' command line option

### ISSUE THREAD

**Issue by Analogreality** [redis/RedisDesktopManager#3333]
Is there any documentation on RedisDesktopManager's command line arguments?

It would be really awesome to be able to specify a server to connect to based on host, port, and AUTH string.
##

**Comment by uglide** [comment]
Hello @Analogreality 
Why do you need this? :) I'm asking because RDM is not simple console client as redis-cli, that's why it seems not really useful.

**Comment by Analogreality** [comment]
I believe Redis Desktop Manager's real power is the ability to quickly display all keys/configuration settings of the Redis server instance data at a glance. It's more than a debugging client, it's a complete top-down overview packaged in a UI. To be able to navigate to any arbitrary key or search visually is a very powerful feature... but for X instances, that requires configuring a server instance (ip address, auth, etc). That's hard to do for instances of Redis that are created on demand or instances that have a different AUTH during runtime. Not all Redis instances have their AUTH or port known until the redis instance is created, so it's a pain to manually enter it in a UI. 

To be able to explicitly be told what the working set's host/port/auth would go a long way to compliment automation. For instance, for unit testing/staging environments, the ability to spawn a new process of RDM and it just automatically connect and display the key store would definitely go a long way.

It's a beautiful client and I really think automation of "I want to view this explicit connection" would really help out.

The concept could be as simple as a --host "X" --port "XXXX" command line invocation or something more robust like a --load-profile "my_new_server.json" sorta deal.

**Comment by uglide** [comment]
@Analogreality 
Thanks for the exhaustive clarification! I really like idea of '--load-profile "my_new_server.json"' command line option. I will implement this feature in next releases.
