### ISSUE TITLE
UI layout issues

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3348]
---

**Comment by Jerry-Shaw** [comment]
HI, thanks for your hard work, I found there are still some layout issues on windows version, the buttons on the right is out of the border, and hard to see.

**Comment by uglide** [comment]
@Jerry

_Could you please provide screenshots? Thanks!_

2015-08-04 10:51 GMT+03:00 Jerry notifications@github.com:

**Comment by Jerry-Shaw** [comment]
![default-size](https://cloud.githubusercontent.com/assets/13212198/9055945/e270ec78-3ac1-11e5-8a45-395dd5d5c06d.jpg)
![full-screen-size](https://cloud.githubusercontent.com/assets/13212198/9055952/e9cad7a4-3ac1-11e5-80b1-ba881f99ebab.jpg)

Here they are, one is the default size, one is my full screen of 1920 x 1080

**Comment by uglide** [comment]
Thanks a lot! I will try to fix this layout issues in 0.8.0-RC2

2015-08-04 11:01 GMT+03:00 Jerry notifications@github.com:

**Comment by Jerry-Shaw** [comment]
OK, thanks. I'm waiting for that.

**Comment by Jerry-Shaw** [comment]
By the way, I just found that, the layout UI was good with my laptop, the screen is of 1366px \* 768px. 
Is there something wrong with showing only on HD screen?

**Comment by uglide** [comment]
@Jerry-Shaw Hmmm, thats interesting... Do you use same operation system (Windows 10) on laptop and desktop?

**Comment by Jerry-Shaw** [comment]
Yep, all are Windows 10, and most of the settings are the same.

**Comment by Jerry-Shaw** [comment]
And, I've tried to change the HD screen resolution to 1440 \* 900, the UI goes perfect good. 
Aha, very interesting...

**Comment by uglide** [comment]
@Jerry
Thanks for this details, it will help me with investigation.

2015-08-05 7:19 GMT+03:00 Jerry notifications@github.com:

**Comment by Jerry-Shaw** [comment]
RC2 still has these issues, even in welcome screen. But it doesn't matter so much. Much faster than RC1 now, good. Screen Resolution: 1920 x 1080.
![1](https://cloud.githubusercontent.com/assets/13212198/9241031/8dbab0b6-41a0-11e5-8f5e-9b7fce3bda44.png)
![2](https://cloud.githubusercontent.com/assets/13212198/9241032/8dbb5250-41a0-11e5-9ee2-04855c597af1.png)

**Comment by uglide** [comment]
@Jerry-Shaw Thanks for testing and great bug reports here! I will clean up UI on Windows in 0.8.1

**Comment by Jerry-Shaw** [comment]
By the way, the UI layout bug still exists in the 0.8.0 Release with Screen Resolution: 1920 x 1080. Almost the same as the one I reported in 0.8.0 RC. But, it works much better now.

Here is the screenshot:
![1](https://cloud.githubusercontent.com/assets/13212198/10475543/62f647e8-7277-11e5-992f-ddd996cfd1b2.png)

**Comment by uglide** [comment]
@Jerry-Shaw Thank you for feedback. I will work and (hopefully) fix all ui related issues in 0.8.1

**Comment by mellonedain** [comment]
Big Screen Support. My Screeb: 1920x1200 24 '' can looks after resize key column like:
![big_screen](https://cloud.githubusercontent.com/assets/8974627/10658913/c4cc713e-789b-11e5-9ef3-e16241d7583f.png)

**Comment by Jerry-Shaw** [comment]
The same UI layout issue exists in 0.8.2, screen 1920 x 1080, report over, thanks. HAHA.
![ay0qy _ifh5sxw y125 nr6](https://cloud.githubusercontent.com/assets/13212198/10838576/50ed6caa-7f03-11e5-891f-1aa3d3e096a1.png)
![e8 o0wl wc_kw 0f pf f](https://cloud.githubusercontent.com/assets/13212198/10838579/534937f4-7f03-11e5-94d4-cf45fc638b0b.png)

**Comment by Jerry-Shaw** [comment]
Ah... the issue of UI layout still exists in the new version, it stays the same.

Report over.

**Comment by uglide** [comment]
Fixed in 0.9 branch

**Comment by Jerry-Shaw** [comment]
Almost fixed in 0.8.4, good job, haha
