### ISSUE TITLE
Key management pane not displaying

### ISSUE THREAD

**Issue by taiidani** [redis/RedisDesktopManager#3355]
Version: 0.7.9.507 (also appearing in 0.7.9.506)
Environment: OS X Yosemite 10.10.3
Redis Server Version: 2.8.19

Steps to reproduce:
1. Open the application
2. Navigate to any key using the left treeview
3. Click on the key, right click => Open Key or right click => Open key value in new tab.

Expected result:
The pane to the upper-right should display the contents of the selected key with expiration time and actions.

Actual Result:
The upper-right pane continues to be blank. Does not display any content. The System Log tab and any Console connection tabs still display fine in the lower-right pane.

**Comment by ovanes** [comment]
+1

**Comment by uglide** [comment]
Fixed in 0.7.9.512+ http://redisdesktop.com/download#beta

**Comment by uglide** [comment]
Thanks guys!

**Comment by taiidani** [comment]
Thanks for fixing it so quickly!
