### ISSUE TITLE
Manual TERM in Tiling WMs

### ISSUE THREAD

**Issue by rbeer** [redis/RedisDesktopManager#3356]
Version: 0.7.6 (stable as of 2015-05-18)
Environment: GNU/Linux - (!) Tiling WM (!)
Redis Server Version: 2.8.17

Steps to reproduce:
1. Start RedisDesktopManager
2. Press Alt+F4, Ctrl+Q

Expected result: Closing RedisDesktopManager
Actual Result: Runs 'till the next blackout. :3

I am using Awesome WM, which strips all windows of their decorations (including title bar with control buttons for max-/minimizing and closing). There seems to be no way to close RDM without mentioned control buttons, forcing me to TERM it manually. :/
![rdm-0](https://cloud.githubusercontent.com/assets/3411649/7674178/1803b07e-fd22-11e4-8f9f-49103bbcfeea.png)
##

**Comment by uglide** [comment]
hello @rbeer
Thanks for the feedback!

Unfortunately, I don't have enough time to implement this enhancement, but you could try to implement it [by yourself](https://github.com/uglide/RedisDesktopManager/wiki/Build-from-source) in 0.8.0 branch or post a bounty and wait until someone implement it.
