### ISSUE TITLE
Support rename-command for security

### ISSUE THREAD

**Issue by jameshueston** [redis/RedisDesktopManager#3357]
Version: 0.7.6
Environment: Windows 8.1 SP1 x64 and Ubuntu 14.04
Redis Server Version: 2.8.17

Steps to reproduce:
1.Click RedisDesktopManager.lnk
2.Click Add Connection button
3.Setup connection
4.Click Menu -> Settings -> 'Import Rename Commands...' that is a plain text file in the same format requested by Redis config; one per line: COMMAND RenamedCommand, ie.
CONFIG b840fc02
INFO cc451322

Expected result: Successful connection to Redis maintaining security

Actual Result: Crash, failed connection, failed PING when PING command is renamed...
##

**Comment by uglide** [comment]
Hello @jameshueston 
Thanks for the feedback!
I will consider implementing this in feature releases.

**Comment by uglide** [comment]
I mark this as "won't fix" because it's rarely used feature of redis and nowadays exist a bunch of better ways to secure data stored in redis-server

**Comment by jameshueston** [comment]
uglide - nowadays, I agree; thanks for your consideration.
I'm a paid subscriber to your latest version, keep up the good work!
