### ISSUE TITLE
SSH Tunneling with Private key authentication - Feature Request

### ISSUE THREAD

**Issue by ryedog** [redis/RedisDesktopManager#3358]
It appears private key authentication is not available with SSH tunneling on the windows version. Just putting a feature request. Thanks!

**Comment by uglide** [comment]
Hello @ryedog 
This feature is available in 0.7.9.X versions of RDM. You can download latest one from RDM site.

**Comment by ryedog** [comment]
@uglide that's great. thanks! Btw since the get stable and beta links on the home page take you to the same download page I thought i was downloading the beta when i was actually downloading the 0.7.6 version. didn't realease in order to get the beta you have to download the nightly builds. 

Thanks again! looking forward to using RDM.
