### ISSUE TITLE
datetime value can't get in hash, but in redis-client can

### ISSUE THREAD

**Issue by caozhiyuan** [redis/RedisDesktopManager#3359]

**Comment by uglide** [comment]
Hello @caozhiyuan 
Could you please provide more detailed description of this issue? Which version of RDM do you use?

**Comment by caozhiyuan** [comment]
![qq 20150526155432](https://cloud.githubusercontent.com/assets/3415285/7807617/9237b694-03bf-11e5-8769-11bdd8edd60b.png)
![qq 20150526155453](https://cloud.githubusercontent.com/assets/3415285/7807618/925ffe2e-03bf-11e5-9b19-1dc790541f58.png)

**Comment by uglide** [comment]
@caozhiyuan thanks!

**Comment by uglide** [comment]
Related to #1738
