### ISSUE TITLE
Chinese characters don't display on OSX 10.10

### ISSUE THREAD

**Issue by Hao-Wu** [redis/RedisDesktopManager#3360]
RDM Version: 0.7.6
OS version: Mac OSX 10.10.3

How to reproduce：

**test in redis-cli**

```
127.0.0.1:6379> set Chinese CH
OK
127.0.0.1:6379> get Chinese
"CH"
127.0.0.1:6379> set Chinese 中文
OK
127.0.0.1:6379> get Chinese
"\xe4\xb8\xad\xe6\x96\x87"
127.0.0.1:6379> 
```

Set and get Chinese characters are both correct in redis-cli.

**What displays in RDM after** `set Chinese 中文`

![screen shot 2015-05-28 at 17 27 52](https://cloud.githubusercontent.com/assets/860738/7856883/07e6b016-055f-11e5-83dd-56a0e4344e07.png)

A similar issue #1718 on Ubuntu has been brought up and solved.

**Comment by uglide** [comment]
Hello @Hao-Wu
Unicode is fully supported in 0.7.9.X branch
