### ISSUE TITLE
SSH tunnel support PrivateKey

### ISSUE THREAD

**Issue by yourtion** [redis/RedisDesktopManager#3361]
SSH Auth Method should support Private Key login （like Robomongo）

![screen shot 2015-06-05 at 11 46 42 am](https://cloud.githubusercontent.com/assets/1475301/7999125/e6ccd7e6-0b78-11e5-8247-297e85afc455.JPG)

**Comment by uglide** [comment]
@yourtion This feature already supported in 0.7.9.X builds
