### ISSUE TITLE
Chinese problem also shows in 0.7.9.809.exe

### ISSUE THREAD

**Issue by PotatoLeo** [redis/RedisDesktopManager#3368]
i tryed redis-desktop-manager-0.7.9.809.exe
also has the problem 
its right after create a new connection but not right after reopen the program 
![qq 20150611181131](https://cloud.githubusercontent.com/assets/1586181/8104669/1e39d6b6-1065-11e5-87bb-871905a59ca6.png)
reopen 
![qq 20150611181232](https://cloud.githubusercontent.com/assets/1586181/8104683/323d88b0-1065-11e5-97af-c1a32243be3b.png)

**Comment by uglide** [comment]
@PotatoLeo Thank you for the detailed bug report! Seems that connections.xml is saved with wrong encoding.

**Comment by uglide** [comment]
This function should be modified https://github.com/uglide/RedisDesktopManager/blob/0.8.0/src/app/models/connectionsmanager.cpp#L159

**Comment by uglide** [comment]
I tested this bug on Ubuntu, OSX and Windows. And seems that it's Windows only problem.
