### ISSUE TITLE
No content shown when using ssh tunnel

### ISSUE THREAD

**Issue by hollodotme** [redis/RedisDesktopManager#3369]
When using ssh tunnel to connect to a reds instance, I can browse the tree, but rdm does not display any content in the right panel when selecting an item in the tree. I just can see the name of the selected key, disabled buttons "Rename" and "Delete" and a spinner. No error messages.

rdm version: 0.7.6.8
Host: OS X Yosemite (10.10.3)
Guest running redis-server: Ubuntu 14.04.2 LTS in a Virtualbox

I ssh tunnel to the guest machine and connect to redis-server via 127.0.0.1:6379

**Comment by uglide** [comment]
Hello @hollodotme 
Please try 0.7.9.X build.

**Comment by hollodotme** [comment]
Works like a charm! Thank you!
