### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by berimor** [redis/RedisDesktopManager#3370]
Hello! We are using RDM 0.7.6 for a long time, thank you very much for the great tool! However, we are missing the possibility to add new keys and hash values. Today I found out, that these features are going to be available in 0.7.9, great! 

My question: when are you going to release the new version (it is not just ready for use now, e.g. the key search box is missing)?

**Comment by uglide** [comment]
@berimor 
Thank you for the feedback,
You are right - 0.7.9.X is not perfect yet :) 
Unfortunately, RDM 1.0 fundraiser partially succeed and now I don't have enough resources to polish 0.7.9.X builds and release 0.8.0. 

There are several options to help me:
C++/Qt: Help me with fixing bugs and implementing new features
Python: Help me with UI tests - https://github.com/RedisDesktop/rdm-ui-tests
Money: Donate or post bounty via BountySource https://www.bountysource.com/teams/redisdesktopmanager
