### ISSUE TITLE
Key search box disappeared?

### ISSUE THREAD

**Issue by berimor** [redis/RedisDesktopManager#3371]
I just tried out the new version 0.7.9. There is no key search box in it. Why did the key search box disappeare?

**Comment by uglide** [comment]
Hello @berimor 
Search box was moved to DB context menu. More info #65

**Comment by berimor** [comment]
Hello!

Thank you, I didn't find that! But this is now much more difficult to 
use. We use the filter all the time, because our large data sets cannot 
be rendered otherwise (it hangs). So it means much problems for us. You 
normally see a serarch box in most contemporary visual interfaces 
(compare google, windows8, Mac). Can you restore the search box? If not,
 can you at least make the search dialog not disappear after the filter 
has been defined?

Thanks in advance, 
Alexander 

```
Igor Malinovskiy      
```

  19 Jun 2015 21:34
  Hello @berimor 
Search box was moved to DB context menu. More info #65

—Reply
 to this email directly or view
 it on GitHub.
