### ISSUE TITLE
Problems when rendering large data sets.

### ISSUE THREAD

**Issue by berimor** [redis/RedisDesktopManager#3372]
RDM can efficiently load large amount of keys, but when it comes to rendering the tree, it can't manage it and hangs, even if there are only a few items in the first level of the tree (before the first colon in the key names). As a result, you cannot open the first level of the tree at all without having a key filter set.

This could be optimized (I think this must be not very hard to do). For example, "redis-commander" tool manages it very well. We are using RDM, so I would really appreciate, if you would consider fixing this problem.

**Comment by uglide** [comment]
Latest 0.7.9.X on Ubuntu 14 loads 10M keys without any problems. It uses memory heavily but doesn't crash. I will try reproduce this problem on Windows and OSX

**Comment by berimor** [comment]
Hi, Igor!

I've downloaded the new beta version 0.7.9.514 yesterday. It looks like 
you've fixed some many-keys related problem, since it can now load our 
large databases and even show the data when expanding subfolders 
containing 400.000 items. And the application didn't crash yet since the
 update. This is really great, thank you very much!

There are still 2 problems really preventing us from completely 
switching to the new version. We could probably provide some support 
with solving them. Could you please write me a direct e-mail to 
ap@optobee.com? We could also communicate in Russian, if you want. 

Best regards,
Alexander

```
Igor Malinovskiy      
```

  17 Jul 2015 09:52
  Latest 0.7.9.X on Ubuntu 14 
loads 10M keys without any problems. It uses memory heavily but doesn't 
crash. I will try reproduce this problem on Windows and OSX

—Reply
 to this email directly or view
 it on GitHub.

**Comment by uglide** [comment]
Superseded by #3384
