### ISSUE TITLE
Incorrect GUI layout for long keys

### ISSUE THREAD

**Issue by win32nipuh** [redis/RedisDesktopManager#3374]
1. Incorrect layout for long keys
2. By some reasons I could not retrieve the field, values for this kind of records.
   I have checked: in the same db RedisClient (cao xinyu) displays values correctly.

![rdm](https://cloud.githubusercontent.com/assets/5189614/8311202/d9d9820e-19d4-11e5-8ecc-e298624c0085.png)

**Comment by win32nipuh** [comment]
Hi, I tried the stable version, it seems it is not stable: 
1. I connected
2. try to open databases (see the image)
3. try to add simple key- value: entered values and click Save or Cancel - no reaction.
After 10 secs I received messageBox that key as added and then c++ runtime error

![rdm_2](https://cloud.githubusercontent.com/assets/5189614/8901346/722553de-3448-11e5-9168-0a18e588f137.png)
![rdm_1](https://cloud.githubusercontent.com/assets/5189614/8901347/7226f194-3448-11e5-894a-e03fa2f6932e.png)

**Comment by uglide** [comment]
@win32nipuh 
Which version exacly do you use? 
On screenshot I see RDM from unstable branch 0.8.0 aka (0.7.9.X builds)

**Comment by win32nipuh** [comment]
Ok, i reinstalled it again. By GUI it seems a prev. version.
1.connected to server
2. run my app which generated some long keys with long values (>100kb)
3. I navigated by keys forward, backward and so on.
4. Then click on root and Reload - see the picture
5. after 3-4 secs app disappeared

btw, no comfortable interface to copy key, to see value, to see TTL and to change TTL
![rdm_3](https://cloud.githubusercontent.com/assets/5189614/8902547/035f8fc8-3452-11e5-8abc-c69ac29e3038.png)

**Comment by uglide** [comment]
Hello @win32nipuh 

You are right 0.7.6 has many ugly bugs, but intention of 0.8.0 is to replace it :)

Issue with installer on windows was fixed. Also I fixed issue with long keys. Please try new version - http://redisdesktop.com/builds/redis-desktop-manager-0.7.9.831.exe
