### ISSUE TITLE
Frequent crashes when filter added

### ISSUE THREAD

**Issue by abienkowski** [redis/RedisDesktopManager#3392]
Very unstable when filter is added and browsing through the entries.

My data has ':' namesapces.

**Comment by uglide** [comment]
@abienkowski Thank you for active testing and participation! I will investigate this problem on OSX.

**Comment by abienkowski** [comment]
It's not specific to OSX, I have a copy on my Win7 desktop as well, and I run into frequent cashes.

**Comment by uglide** [comment]
@abienkowski Please try this build on Windows http://redisdesktop.com/builds/redis-desktop-manager-0.7.9.821.exe

**Comment by uglide** [comment]
@abienkowski Can you confirm that this issue was fixed in latest WIndows build?

**Comment by uglide** [comment]
Looks similar to #3373, so I will close this issue as duplicate.
