### ISSUE TITLE
Failed to start, Win7

### ISSUE THREAD

**Issue by abienkowski** [redis/RedisDesktopManager#3396]
Installed the new release, as the popup window  suggesting new beta release.

After installing on Windows 7, and replacing my previously installed version, the programs fails to start now.

redis-desktop-manager-0.7.9.826

**Comment by uglide** [comment]
@abienkowski Thanks for the bug report! I will investigate the problem.

**Comment by uglide** [comment]
Fixed in http://redisdesktop.com/builds/redis-desktop-manager-0.7.9.827.exe
