### ISSUE TITLE
RDM has stopped working

### ISSUE THREAD

**Issue by Dyachenko** [redis/RedisDesktopManager#34]
При попытки просмотра занчений ключа RDM перестал работать 
вот описание проблемы

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: redis-desktop-manager.exe
  Application Version:  0.0.0.0
  Application Timestamp:    525271d9
  Fault Module Name:    MSVCR110.dll
  Fault Module Version: 11.0.51106.1
  Fault Module Timestamp:   5098858e
  Exception Code:   c0000005
  Exception Offset: 0000e33d
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1049
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by uglide** [comment]
Какая версия RDM? Какой тип ключа открывался? Какой тип соединения (с ssh туннелем или без) ?

**Comment by Dyachenko** [comment]
Версия 0.4.0
Тип ключа Hash
Тип соединения с ssh туннелем
проблема возникает при просмотре содержимого ключа

**Comment by uglide** [comment]
Fixed in 0.4.1
