### ISSUE TITLE
Where is my search box!!!

### ISSUE THREAD

**Issue by bolee** [redis/RedisDesktopManager#3410]
Because my db is very big,I always use the filter function, but now the filter search box not in the main view.Will it come back!back!!!

**Comment by uglide** [comment]
Hello @bolee 
Filter was moved to context menu of database items.
<img width="214" alt="screen shot 2015-08-05 at 6 56 37 am" src="https://cloud.githubusercontent.com/assets/1655867/9078073/36df3094-3b3f-11e5-9e78-c8268173e293.png">

Context menu is not super-fast way to access this feature but currently another ways are not implemented. However we already have related feature request in #3411. 
If you want to make it happen, please donate some $ to feature request #3411 via BountySource.
