### ISSUE TITLE
Fedora 22 Build problems

### ISSUE THREAD

**Issue by pollend** [redis/RedisDesktopManager#3412]
i'm getting this build error on fedora 22 using the manual installer. 

app/models/configmanager.cpp: In static member function ‘static QJsonArray ConfigManager::xmlConfigToJsonArray(const QString&)’:
app/models/configmanager.cpp:133:34: error: ‘fromVariantHash’ is not a member of ‘QJsonObject’
                 newConfig.append(QJsonObject::fromVariantHash(connection));

**Comment by uglide** [comment]
Hello @pollend 
Fixed in 1d5740de494abfd782af3a11d371f6acaba4084e, please try pull changes and rebuild. Thanks!
