### ISSUE TITLE
"msgpack" can't drop down to look more details

### ISSUE THREAD

**Issue by gitfancode** [redis/RedisDesktopManager#3416]
"msgpack" can't drop down to look more details, when values is too long.

**Comment by uglide** [comment]
@gitfancode 
Could you please provide test example?

**Comment by gitfancode** [comment]
sorry! when i try again, it is ok now.

**Comment by uglide** [comment]
Hm, ok. Anyway if you find any bugs - please fill issues. Thanks for testing!
