### ISSUE TITLE
Prevent Auto Selecting ALL dbs when click on db connection

### ISSUE THREAD

**Issue by Bossa573** [redis/RedisDesktopManager#3417]
Version: 0.8.0-2535
Environment: Mac OSX 10.9.5
Redis Server Version: 2.8.3

Steps to reproduce:
1. set a large number of database on the redis server
2. Click on the db connection

My redis server comes with 1000 dbs
And this is what I get when I click on the connection
(and have to wait about a minute to let it scan through all dbs)
RDM need to select every dbs on the redis before use?

![image](https://cloud.githubusercontent.com/assets/1013526/9107528/744a2788-3c5a-11e5-96ea-5882f5bfa9da.png)

**Comment by uglide** [comment]
Hello @Bossa573,
RDM uses SELECT command to discover all databases on redis server as fallback(it's required for old redis servers like 2.4). I will disable it for cases when INFO command available and returns db count > 0.
