### ISSUE TITLE
Lost I connections list after upgrade to release candidate

### ISSUE THREAD

**Issue by piotrkochan** [redis/RedisDesktopManager#3418]
That's little annoying that update to latest version clears connection list and I can't find a place where it was saved

**Comment by uglide** [comment]
Hello @piotrkochan 

Old config stored in xml, and new in json format:
**Windows**  `C:\Users\%Your user%\.rdm\connections.(xml|json)`
**OS X** `$HOME/Library/Preferences/rdm/connections.(xml|json)`
**Linux** `$HOME/.rdm/connections.(xml|json)`

Which version do you use before? 0.7.6 or older?

**Comment by blueberry-media** [comment]
I also upgraded to the latest version. (not sure which version i had before)

In the given location are indeed an xml and json file, but both are empty (0 bytes)

ps. suggested location for these type of config folders in Windows: %APPDATA%
also, starting a folder name with "." does nothing in Windows

**Comment by Jimbolino** [comment]
I also upgraded to the latest version. (not sure which version i had before)

In the given location are indeed an xml and json file, but both are empty (0 bytes)

ps. suggested location for these type of config folders in Windows: %APPDATA%
also, starting a folder name with "." does nothing in Windows

**Comment by uglide** [comment]
@Jimbolino I need to know your previous version to reproduce issue.

**Comment by Jimbolino** [comment]
my download history shows: redis-desktop-manager-0.7.6.15.exe

**Comment by uglide** [comment]
We can deduce it :) Do you remember, your prev version has SSH key in "Add
connection" dialog?

2015-08-10 17:47 GMT+03:00 Jimbolino notifications@github.com:

**Comment by Jimbolino** [comment]
after re-installing this version: https://github.com/uglide/RedisDesktopManager/releases/download/0.7.6/redis-desktop-manager-0.7.6.15.exe my old connections are back !

**Comment by Jimbolino** [comment]
the old version stores them in C:\Users\username\connections.xml
instead C:\Users\username.rdm\connections.xml

**Comment by uglide** [comment]
@Jimbolino

Copy your connections.xml from C:\Users\%Your user%\connections.xml
to C:\Users\%Your user%.rdm\connections.xml and install new version. It
should do the trick for you.

2015-08-10 17:54 GMT+03:00 Jimbolino notifications@github.com:

**Comment by Jimbolino** [comment]
yes just tried and copying the file does the job!

**Comment by uglide** [comment]
@piotrkochan

Please follow workaround which was discovered by @Jimbolino

I will fix this issue in 0.8.0-RC2

2015-08-10 17:58 GMT+03:00 Jimbolino notifications@github.com:

**Comment by Jimbolino** [comment]
FYI: as long as the .xml is present, it will automatically overwrite the json. So all new changes will be lost next time you start the application.
