### ISSUE TITLE
Number of keys not showing for db in RC

### ISSUE THREAD

**Issue by sabrehagen** [redis/RedisDesktopManager#3429]
In version 0.7.x the number of keys in a db would be shown next to the db name in the tree e.g. db0 (7640). This was extremely valuable. Now I am seeing db0 (2/0) which is less helpful, and unclear as to what (2/0) means. Can you restore the keys count functionality somewhere please?

**Comment by uglide** [comment]
Hello @sabrehagen 
Keys count functionality was restored and will be available in 0.8.0-RC2
