### ISSUE TITLE
Undesired behavior when redacting in JSON view

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#343]
Great feature which allow viewing JSON values formatted have undesirable behavior when saving.

If user try to save edited JSON formatted value it will be saved as is, without removing spaces and line end symbols and without JSON validation.

When user saves invalid JSON, next time he will see just "Invalid JSON" in JSON value view and will need to switch to plain text view and find issue with JSON.

Also the order of properties in JSON can change due to different implementation of JSON readers in code which saved it to redis and in rdm. This and previous space and line ending symbols addition can lead to change of hash values (md5 and so on) of JSON strings saved in redis. I assume it is probably a rare case but still can lead to undesirable behavior if some situations.

So, I'll probably resume the issue:
1. Save in JSON view shouldn't change the value other than the changes introduced by user.
2. Save in JSON view probably need validation.

**Comment by uglide** [comment]
Fixed in 0.7.5
