### ISSUE TITLE
connecting to db doesn't display anything

### ISSUE THREAD

**Issue by MegaManSE** [redis/RedisDesktopManager#3431]
when selecting a db, I get this in the log window:
2015-08-10 15:40:59 : Connection: WF dev user1 > [runCommand] scan 0 MATCH COUNT 10000 -> response received : 0

Then nothing happens.  I can bring up the console window and interact with the db itself via commands just fine but the old UI for graphically manipulating things appears to be gone.  Is this the intended use?

v 0.8.0.3835

**Comment by MegaManSE** [comment]
It appears that the ssh tunnel settings go away when you upgrade...

**Comment by MegaManSE** [comment]
ssh tunnel appears to not work anymore

**Comment by uglide** [comment]
Hello @MegaManSE 
Please follow instructions in #3407 
This issue already fixed. 0.8.0-RC2 will be more stable :)
