### ISSUE TITLE
No DB keys amount displayed anymore

### ISSUE THREAD

**Issue by piotrkochan** [redis/RedisDesktopManager#3435]
Hi, in newest RDM version there is no information about keys amount in databases.
Probably this is because of performance but I think that there should be some kind of setting to turn this on

**Comment by uglide** [comment]
Duplicate of #3429

@piotrkochan FYI 0.8.0-RC2 will be released today ;)

**Comment by piotrkochan** [comment]
@uglide nice, thanks for notification :)
