### ISSUE TITLE
the welcome page does not close completely

### ISSUE THREAD

**Issue by alexguerra** [redis/RedisDesktopManager#3437]
When I click the X next to the RDM word on the welcome tab. The content disappears, but not allow me to change the console tab height which is located just below.

I use the Mac OSX 10.9.5

![rdm-issue](https://cloud.githubusercontent.com/assets/5710480/9237145/b7460506-411f-11e5-9aa0-761c2d9a2279.gif)

**Comment by uglide** [comment]
@cdp-alexguerra Thanks for awesome bug report :)

**Comment by uglide** [comment]
Fixed in 0.9.0
