### ISSUE TITLE
Add Python Pickle view formatter

### ISSUE THREAD

**Issue by tshanec** [redis/RedisDesktopManager#3438]
Python serializes objects to a binary format called "pickle".  [PicklingTools](http://www.picklingtools.com/) is an example of a library that enables you to read pickle blobs from C++.  It would be nice to be able to preview pickle blobs that have been stored in Redis.

**Comment by uglide** [comment]
Hello @tshanec 
I have moved this feature request to 1.0.0 milestone. If you really need this feature please post a bounty on this issue via Bountysource. Thanks!

**Comment by uglide** [comment]
Issue moved to https://github.com/RedisDesktop/rdm-native-value-fromatters/issues/3
