### ISSUE TITLE
Cannot load key value if key contains space

### ISSUE THREAD

**Issue by pjrfigueiredo** [redis/RedisDesktopManager#3440]
Hello!

I'm facing a error on this new release/version (redis-desktop-manager-0.8.0-2539).
When I try to access a hash data I got the following error "Cannot load key value: Connection error: Cannot execute command.Run command: Cannot add command to worker. Lock timeout."

In version 0.7.6 it works perfectly!

![error 1](http://i.imgur.com/nZ5HaAX.jpg) 

![hash](http://i.imgur.com/EYO4Vhx.jpg) 

Best regards from Portugal!

**Comment by uglide** [comment]
Hello,
Which version of redis-server do you use? Do you use ssh tunnel? Also
please paste here system log. Thanks
13 авг. 2015 г. 16:02 пользователь "pjrfigueiredo" notifications@github.com
написал:

**Comment by pjrfigueiredo** [comment]
Tnks uglide.

Redis Version Compliance: 2.8.12
I'm not able to access system log since i'm using redislab.com redis-cloud.
The hash name have the following pattern: "model:paulo figueiredo".
Like I said, it's working/loading perfectly on 0.7.6.

Tnks!

**Comment by pjrfigueiredo** [comment]
Forgot to mention that I can read perfectly other hashes with different hash names, like for example "media:99999". That's why I mentioned that I'm trying to read something like "model:paulo figueiredo". "model" can be messing it up? :)
dunno!
peace!

**Comment by uglide** [comment]
@pjrfigueiredo You have found tasty bug, thank you for the feedback!

**Comment by pjrfigueiredo** [comment]
@uglide someone would find it.
I'm the one that has to thanks.
Yah! It is the space...

Peace

**Comment by uglide** [comment]
Fixed and will be released with 0.8.0-RC4
