### ISSUE TITLE
Treeview does not work as previous versions

### ISSUE THREAD

**Issue by jimshengli** [redis/RedisDesktopManager#3444]
In previous version, the items are listed as treeview if separated by ":", but now the feaure is disappear.
Can you please get that cool feature back?

**Comment by bp74** [comment]
Yes please add this back, i hope this is just a bug in the latest version. 
The treeview separated by colons was awesome!

**Comment by uglide** [comment]
Duplicate of #3442. Please see intstructions in original issue.
