### ISSUE TITLE
Tree-View truncate key names

### ISSUE THREAD

**Issue by darkbyte-pod** [redis/RedisDesktopManager#3456]
Not sure if its just me be I see an issue with the treeview on my windows system with the 0.8 beta series:

My keys get dotted even if there is room for them as can be seen on this screenshot
![redis-treeview-bug](https://cloud.githubusercontent.com/assets/13499617/9491903/d5ff191e-4bc0-11e5-96e8-efcad23dbf48.PNG)

**Comment by uglide** [comment]
Hello @darkbyte-pod 
Which version of RDM do you use? This issue #3442 was fixed in 0.8.0-RC4 https://github.com/uglide/RedisDesktopManager/releases/tag/0.8.0-rc4

**Comment by darkbyte-pod** [comment]
Version 0.8.0.3841, official release rc4 if im not crazy. I would help with the project but can't find a vstudio solution file.

**Comment by uglide** [comment]
@darkbyte-pod Please set ':'  in Edit Connection -> Advanced Settings -> Namespace separator.
Probably your connections file was broken by previous 0.8.0-RCX versions.

To open project in VS you should install Qt 5.5 first. Add qmake to PATH and run following command in src folder: `qmake -spec win32-msvc2013 -tp vc`. Feel free to change 2013 to version which you actually use

**Comment by darkbyte-pod** [comment]
Oh, its not the same as #3442, I figure this one and it works good. The issue is the keys don't use the whole width of the left pane.
I get:
xxxx-xxx-xxx-xx-xxxxxx-xxx--xxx--x-x-x...
instead of:
xxxx-xxx-xxx-xx-xxxxxx-xxx--xxx--x-x-xxx-xxxxx.xxxxx

**Comment by uglide** [comment]
@darkbyte-pod

But I recommend you to use Msys2 and QtCreator instead of VS because compiling dependencies in msvc will be challenging

**Comment by darkbyte-pod** [comment]
If you have a startup solution file, i could try to work on it.

**Comment by uglide** [comment]
@darkbyte-pod Currently width of the column in tree view is hardcoded here - https://github.com/uglide/RedisDesktopManager/blob/0.8.0/src/modules/connections-tree/model.cpp#L22

I doesn't have solution file in project, but you can easily generete it. See my comment https://github.com/uglide/RedisDesktopManager/issues/3456#issuecomment-134951726

**Comment by darkbyte-pod** [comment]
great, i'll look into that solution generator and will also try to help with the project, thanks a lot.

**Comment by uglide** [comment]
@darkbyte-pod You are welcome! If you have any questions feel free to ping me in RedisDesktopManager gitter chat https://gitter.im/uglide/RedisDesktopManager
