### ISSUE TITLE
Console -> Select all and delete

### ISSUE THREAD

**Issue by artis-mosties** [redis/RedisDesktopManager#3457]
Version: 0.8.0.3841
Environment: Windows 7 SP1 x64
Redis Server Version: 2.8.21

Steps to reproduce:
1. Right click on connection and open console.
2. Select all [CTRL+A or system menu] / Select part of text
3. Click CTRL+X [cut command]

Expected result: No action for CUT

Actual Result: Console text is deleted. Console becoms unresponsive but you can still type in the text that does nothing.

**Comment by uglide** [comment]
@artis-mosties Thanks for the feedback
