### ISSUE TITLE
Duplicating key in key-tree

### ISSUE THREAD

**Issue by vmarunov** [redis/RedisDesktopManager#3459]
Version: 0.8.0.3841
Environment: Windows 7 x64
Redis Server Version: 2.8.4

Steps to reproduce:
1. Reload keys from context menu on db
2. Some keys is duplicate (floating bug. picture is attached)

Expected result: Keys is not duplicated

Actual Result: Some keys is duplicate

![image](https://cloud.githubusercontent.com/assets/10268800/9680823/53f55de0-5302-11e5-9fa8-b05aad9ccaab.png)

**Comment by uglide** [comment]
@vmarunov Thanks for the feedback!

**Comment by uglide** [comment]
Hello @vmarunov 
Unfortunatly I cannot reproduce this problem on my Win7 machine, Could you please provide more specifics related to the problem?
Maybe some steps to reproduce or pre-requeremnts was missing.

Thanks in advance!

**Comment by uglide** [comment]
No feedback was provided since 0.8.0 release so I assume that problem was fixed.
