### ISSUE TITLE
Closing redis-server service whem redis desktop manager (RDM) is open and connected cause RDM crash

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#3460]
ENV:
- Windows 8.1 x64
- redis-64 v2.8.2101 - from chocolatey
- RDM v0.8.0.3841

1 - Starting a console window with 'redis-server' (running 127.0.0.1:6379 without Oauth)
2 - Open RDM
3 - Connect RDM to redis 127.0.0.1:6379 without Oauth
4 - Close redis-server console
5 - RDM crash

**Comment by uglide** [comment]
Fixed in 0.8.0-release
