### ISSUE TITLE
When connect to redis error on a loop that read all databases

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#3461]
![1](https://cloud.githubusercontent.com/assets/3471090/9709023/417e3f1e-54f2-11e5-8bd5-4b2424b5896c.jpg)

the problem is that the loop is trying to read position that dosent exist (17)

**Comment by uglide** [comment]
Hello @Karklis 
This error in log is not a bug - it's the way in which RDM discovers amount of db in redis-server if INFO command returns empty keyspace info.
