### ISSUE TITLE
Closing SSH tunnel causes crash

### ISSUE THREAD

**Issue by mcfedr** [redis/RedisDesktopManager#3462]
In my terminal I am forwarding a remote redis server using ssh.
In RDM I connect to this as if its a local redis server.
When I close the ssh connection RDM crashes.

**Comment by uglide** [comment]
@mcfedr Which OS do you use?

**Comment by mcfedr** [comment]
MacOS 10.10.5

**Comment by uglide** [comment]
Fixed in 0.8.0-release
