### ISSUE TITLE
Cannot run on VM due to Qt welcome screen possibly.

### ISSUE THREAD

**Issue by fractos** [redis/RedisDesktopManager#3471]
Seems to be an issue matching this post: [https://forum.qt.io/topic/42047/cannot-run-application-written-with-qt5-3-and-qml-in-win7-x86]

Error as follows:
"Getting error dialog with "Failed to create OpenGL context for format QSurfaceFormat(version 2.0 options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile 0) . This is most likely caused by not having the necessary graphics drivers installed.
Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure that ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH."

The advice in the post was to disable the Qt welcome screen in QtCreator. However, since that is a pre-compilation step, then there's nothing I can do about it. I am trying to run this on a Windows 7 VM.
I can see that the correct DLL files are present in the folder.

**Comment by uglide** [comment]
Please, Try to copy opengl.dll  from rdp_fix folder to folder with rdm.exe
and enable 3d acceleration on VM settings.
22 сент. 2015 г. 14:41 пользователь "Adam Christie" <
notifications@github.com> написал:

**Comment by fractos** [comment]
Awesome. That worked. Thanks!
