### ISSUE TITLE
Simplify compiling on OSX

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3472]

**Comment by dmagliola** [comment]
Thank you for the help! 
Now I managed to run it!!!

The process wasn't perfect, so I'm sending you a bit more info as to what I had to do this time, in case it helps others, or it helps improve the configure script.

Sadly, while I fixed these manually, I don't know enough to fix them "properly" and submit a PR. This is a little verbose, trying to give you all the relevant information.

With the previous version, I had 3 different issues:
1. Getting `configure` to work.
2. Getting it to compile later inside QtCreator
3. Getting it to run (this is the one I couldn't get past before)

---

## Getting `configure` to work.

Initially, I get this: (when running "configure")

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
xcodebuild: error: SDK "macosx10.9" cannot be located.
xcodebuild: error: SDK "macosx10.9" cannot be located.
Warning: libssh2-1.5.0 already installed
```

This is something I had previously too, I fixed it by changing this:

First, I comment out the "readlink" call at the top, and hard-code the path. I know this isn't exactly a solution to the problem, but I don't know how to do this better, unfortunately.

```
#DIR=$(dirname "$(readlink -f "$0")") && RDM_DIR=$DIR/../
DIR="/Users/daniel/Documents/code/rdm/src"
RDM_DIR=$DIR/../
```

In the `xcodebuild` lines, I change the SDK from "macosx10.9", which I just can't make that work, or can't make xcode find that SDK, to "macosx10.11".

I'm on OS X Yosemite 10.10.5, for what it's worth.

That got me past the first issue.

---

## Getting it to compile later inside QtCreator

Build failed with this error:

```
ld: warning: directory not found for option '-L/usr/local/Cellar/libssh2/1.6.0/lib/'
ld: library not found for -lssh2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../bin/osx/debug/rdm] Error 1
10:47:48: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project rdm (kit: Desktop Qt 5.5.0 clang 64bit)
When executing step "Make"
```

Running `configure` earlier finished with "Warning: libssh2-1.5.0 already installed", so it didn't install 1.6.0, which is the path that the build step is looking for. 

Running "brew upgrade libssh2" fixed that. Not sure if that's something the configure script can deal with better.

After that, the build passed. There's a lot of compile warnings (279). Just letting you know in case that isn't meant to be normal...

---

## Getting it to run

Now, with the changes you made, and those slight tweaks mentioned above, it runs!!!
Thank you!
Hopefully, I'll be able to make the changes I was planning to make. I'm a big fan of RDM, so really hope I can help develop small tweaks and improvements!

**Comment by uglide** [comment]
Hello @dmagliola 
Thank you for contribution!
1. To fix issue with `readlink` it will be enought to copy-paste lines from another build script https://github.com/uglide/RedisDesktopManager/blob/0.8.0/build/build_package.sh#L8-L12
2. In `xcodebuild` lines I think it's possible to remove specific versions and leave only `macosx`. I will test it.
3. `brew install libssh2 || brew upgrade libssh2` should do the trick for upgrading/installing libssh2

For now I will reopen this issue and commit another fix for `configure` script.
Thanks again @dmagliola !!!

**Comment by uglide** [comment]
@dmagliola I have applied improvements mentioned before, so using `configure` should be much easier now.

**Comment by dmagliola** [comment]
That seems to have worked! No idea if it having worked before made a different or not, but I cloned into a new directory, run configure and then built inside Qt Creator and it worked perfectly. 
configure seems to have done a lot less than before (homebrew instead building something, possibly?)
Anyway, awesome work, thank you!

**Comment by uglide** [comment]
@dmagliola I just made configure less verbose :)
