### ISSUE TITLE
Support AWS Elasticache

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3487]
```
Issue appears to be the INFO command. It doesn't work in AWS.
```

**Comment by rmolinag** [comment]
INFO command is indeed blocked on Elasticache, though they don't clearly specify that is one of the restricted commands on their documentation:

http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ClientConfig.RestrictedCommands.html

**Comment by uglide** [comment]
@rmolinag  I've double checked and seems that `INFO` command works correctly on AWS Elasticache. So I closing this issue as invalid.
