### ISSUE TITLE
Crash Reporting

### ISSUE THREAD

**Issue by nick-hs** [redis/RedisDesktopManager#3494]
Thank you for this awesome software!

I noticed when RDM crashes it automatically sends the crash report.
RDM does not display the data that will be sent or give the option to opt out of crash reporting.

**Comment by uglide** [comment]
RDM sends Google Breakpad [minidumps](https://code.google.com/p/google-breakpad/wiki/GettingStartedWithBreakpad#The_minidump_file_format). Minidumps doesn't contain any sensetive information. Only traces for debugging. 

If you want to disable crashreporting, you can remove `crashreporter` binary from RDM installation path. But I will never know about bugs (= I will never fix this bug).

**Comment by nick-hs** [comment]
The issue is not sending crash reports themselves.
It's that the data that was sent cannot be seen.

Of course you should get crash reports it's an important tool to aid in software development.
I totally understand.

Can you at least provide a uneditable box showing the information that was sent or that will be sent?

Again this app is awesome and it is much appreciated! :smile: 
Thank you for the prompt responses!

**Comment by uglide** [comment]
minidumps - is binary data format, so it doesn't contain any useful information which could be showed to end-user.
