### ISSUE TITLE
Escape unprintable Characters in keys

### ISSUE THREAD

**Issue by hannes-angst** [redis/RedisDesktopManager#3496]
When using Redis as cache provider in a java project, keys and values are stored as a serialized version of the objects.

In the Redis client this looks like this:
127.0.0.1:6379[2]> select 2
OK
127.0.0.1:6379[2]> scan 0 match \* count 1000
1) "0"
2) 1) "\xac\xed\x00\x05t\x00\nmandator_1"
   2) "\xac\xed\x00\x05t\x00\ncfg_notice"
   3) "\xac\xed\x00\x05t\x00\x0ccfg_2:notice"
   4) "configuration~keys"
   5) "\xac\xed\x00\x05t\x00\nmandator_2"
127.0.0.1:6379[2]>

In the Redis Desktop Manager, this will look like this
 ![](https://cloud.githubusercontent.com/assets/2822902/10387798/a3c68ca4-6e64-11e5-9994-d06e2e0743e1.png)

Sadly, this is not only a visual flaw but will actively prevent from showing the associated data.

![redisdesktopmanager](https://cloud.githubusercontent.com/assets/2822902/10387831/f4a908e0-6e64-11e5-8e0f-8b1410b7b0a5.png)

**Comment by uglide** [comment]
@hannes-angst Fixed in 0.8.0-RC5 (will be released soon). Thanks!

**Comment by hannes-angst** [comment]
Awesome!
