### ISSUE TITLE
filter keys work well, but I think `start:keys` will too

### ISSUE THREAD

**Issue by gshmu** [redis/RedisDesktopManager#3500]
I suggest add `start:keys` to Speed ​​up...

many time's focus some keys enough

**Comment by uglide** [comment]
Hello @mhohai 
Could you please provide more detailed description? What do you mean by adding `start:keys` ?

**Comment by gshmu** [comment]
@uglide filter keys, it's very usefully, but it load all keys.
![screenshot from 2015-10-14 13 13 28](https://cloud.githubusercontent.com/assets/1797676/10475376/729fdd6e-7275-11e5-8d02-2d1c25d10cc0.png)

I'm clearly know "key:start:with:str", I want just load "key:start:with:str:*"
    "key:start:with:str:any" load
    "yek:start:or:other:elsy" don't load
![screenshot from 2015-10-14 13 21 00](https://cloud.githubusercontent.com/assets/1797676/10475460/73502a74-7276-11e5-8b6d-8965314255d2.png)

**Comment by uglide** [comment]
OK, thank yo for clarification
Please look at issue #3411 . I think it is exactly what you need. 

Thanks!
