### ISSUE TITLE
Not Support domainName Connection

### ISSUE THREAD

**Issue by 8241796** [redis/RedisDesktopManager#3507]
I write domain name into the host field，port is 6379，can't connect to Redis-Server，but I use the redis own client by "redis-cli -h domainName -a password" is OK。

why?

**Comment by uglide** [comment]
Hello @8241796 
Could you please paster here app log from RDM?

**Comment by uglide** [comment]
No feedback was recieved, so I assume that you have tipo in host name or connectivity problems to your redis-server.

Feel free to reopen this bug if you can provide description of real issue.
