### ISSUE TITLE
Black Data window

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [redis/RedisDesktopManager#3508]
With any v8 release I get a Black top right window, where all the useful data should be. Left hand window with db info in is fine, as is the lower right window with debug info(?).

Running on Windows server 2008 v2 with no graphics card, so that may be the issue.

**Comment by uglide** [comment]
Hello @82ndab-Bravo17 
Try to copy this DLL to rdm installation dir 
https://github.com/uglide/RedisDesktopManager/tree/a58b0f5dd0910f52585cafb969b7bde2ee9edf4c/build/windows/installer/resources/rdp_fix

**Comment by 82ndab-Bravo17** [comment]
Still gives a black window i'm afraid

**Comment by uglide** [comment]
Will be fixed by #3560
