### ISSUE TITLE
RDM add  CBOR (http://cbor.io/)  view formatter,  like View Value as msgpack.

### ISSUE THREAD

**Issue by lefay1982** [redis/RedisDesktopManager#3511]
CBOR http://cbor.io/,  like JSON, but small and fast.
also like msgpack, and small and fast.

Performance benchmark:

test_count = 100000;
---------------------encode-----------------------
org.msgpack.MessagePack time :2262ms
org.msgpack.MessagePack size:691

jackson.Json time :940ms
jackson.Json size:805

jackson.dataformat.smile  time :890ms
jackson.dataformat.smile  size:687

jackson.dataformat.cbor  time :758ms
jackson.dataformat.cbor  size:688

---------------------decode-----------------------
org.msgpack.MessagePack  time :2358ms

jackson.Json   time :1782ms

jackson.dataformat.smile  time :1469ms

jackson.dataformat.cbor  time :1399ms

**Comment by uglide** [comment]
Issue moved to https://github.com/RedisDesktop/rdm-native-value-fromatters/issues/2
