### ISSUE TITLE
RDM 0.8.0 first connect to redis can not see db's key count,  but 0.7.6 have.

### ISSUE THREAD

**Issue by lefay1982** [redis/RedisDesktopManager#3512]
first connect to redis, 0.8.0 run `info` to get all info, but mostly info is not useful.

first connect to redis, can run `info keyspace` command only to get all db key count.

`info keyspace`

# Keyspace
db0:keys=1,expires=0,avg_ttl=0
db2:keys=107,expires=17,avg_ttl=24556683
db3:keys=24,expires=4,avg_ttl=32160945
db4:keys=20815,expires=20815,avg_ttl=12777452
db5:keys=2,expires=0,avg_ttl=0
db6:keys=1,expires=0,avg_ttl=0

**Comment by uglide** [comment]
Hello @lefay1982 RDM runs `info` command instead of `info keyspace` because old Redis versions doesn't support section parameter.
