### ISSUE TITLE
No ability to resize value pane

### ISSUE THREAD

**Issue by table-delete** [redis/RedisDesktopManager#3513]
Whereas the user could resize the value pane in 0.7, this capability was removed in 0.8.  This makes the UI nearly useless for large values; we are storing JSON CLOBs that are 50+ lines of text.

Our workflow with 0.8 is much less efficient.  We now have to copy the value into a text editor, edit our value, then paste back into RDM.

**Comment by uglide** [comment]
Hello @table-delete
Could you please explain with screenshot what exactly should be resizeble?

**Comment by table-delete** [comment]
Thanks, @uglide, please let me know if this illustrates the issue: ![annotated screenshot](http://i.imgur.com/M6uIf6C.png)

**Comment by uglide** [comment]
Fixed in 0.8.2 (will be released soon)
