### ISSUE TITLE
Documentation doesn't state where configuration is stored

### ISSUE THREAD

**Issue by xor-gate** [redis/RedisDesktopManager#3520]
Because the issue #3516 created duplicated entries and only one-by-one connection edit/remove is supported I would like to remove/edit the configuration directly. It would be nice to state where the configuration is saved for all supported operating systems to automatic backup configuration.

**Comment by uglide** [comment]
[FAQ](https://github.com/uglide/RedisDesktopManager/wiki/FAQ#where-stored-config-with-connections)
