### ISSUE TITLE
Filter keys bad regex

### ISSUE THREAD

**Issue by xunenz0** [redis/RedisDesktopManager#3524]
The regex like ^#000$ ,OK, you can get the result! Other regex ^000#$ ,can't get the result! I don't why? The # replaced Regular wildcard star,only start in this page editor can't show!

**Comment by xunenz0** [comment]
The regex like  ^#000$ ,OK, you can get the result! Other regex ^000#$ ,can't get the result! I don't why? The # replaced  Regular wildcard star,only start in this page editor can't show!

**Comment by uglide** [comment]
Hello @xunenz0 
To  understand why `^000*$` regex doesn't work for you I need to know which keys do you have in your redis-server (or subset of keys which much this regex but doesn't filtered properly by RDM).

Could you please provide such keys?

**Comment by xunenz0** [comment]
for example, there are three key
000100:2683c0c63bf34a7e887bd7b374c9e5c8:110110
000100:c364fbf69c15483f8fbd75658fbd7fa8:110110
000100:ed501c737aa740a1908678cded574b58:110110
the regex  ^#110110$ can get the result.
however,the regex ^000100#$ no result. It means "Ctrl + F" Filter Regex can't work?

 (note: # is replaced asterisk)

**Comment by uglide** [comment]
regex `^000100*$` doesn't work because you've missed `.` before `*`. So valid regex is `^000100.*$`

**Comment by xunenz0** [comment]
Thank you!  I don't know  the regex is used  in this way. Sometimes, I want to know the search  result size, maybe I want delete them. Is this  some feature in the later version?

**Comment by uglide** [comment]
@xunenz0 bulk operations not implemented in RDM yet. But you can help and [post bounty](https://github.com/uglide/RedisDesktopManager/issues/3529) or [make donation via Bountysource](https://www.bountysource.com/teams/redisdesktopmanager)
