### ISSUE TITLE
Cannot view individual keys/values of hash

### ISSUE THREAD

**Issue by michaelblyons** [redis/RedisDesktopManager#3525]
Version: 0.8.2
Environment: OSX El Capitan
Redis Server Version: Unknown

Steps to reproduce:
1. Connect to Redis server.
2. Load db
3. Click on Hash key
4. After Key/Value pairs populate in the top right pane, click on one.

Expected result:

Key and value appear in their respective boxes at the bottom of the top-right pane

Actual Result:

Key and value boxes remain blank

---

Also, changing the value's "View As" dropdown to (for instance) JSON loads "Error: Invalid JSON" in the Value box.

**Comment by uglide** [comment]
@michaelblyons Just double click on row :)
