### ISSUE TITLE
key search gone

### ISSUE THREAD

**Issue by dikkeduif** [redis/RedisDesktopManager#3527]
In version 8.0 and up the key search on the top left is gone or hidden.

![screenshot from 2015-11-08 14-34-38](https://cloud.githubusercontent.com/assets/5879625/11020362/3560309c-8626-11e5-8533-88e549c103e7.png)

**Comment by uglide** [comment]
Keys search/filtering [was moved](https://github.com/uglide/RedisDesktopManager/wiki/Features-overview#search-in-connection-tree)
