### ISSUE TITLE
some keys not showing up

### ISSUE THREAD

**Issue by dikkeduif** [redis/RedisDesktopManager#3528]
Since 0.8 some keys are not shown in the GUI.

If I do keys \* in the console, I will get two keys in the format:
- user:750473
- user:756122

But when opening the db0 > user > I only see one key: user:756122

When I try this in 0.7.6 both keys show up. I've tried 0.8.0, 0.8.1 and 0.8.2. Although I'm running rdm in linux, I've also tried via wine, with the same results.

**Comment by uglide** [comment]
Hello @dikkeduif , Have you tried to get keys with `SCAN` command?

Also please provide output from `INFO` command.

**Comment by dikkeduif** [comment]
@uglide Not sure what's going on, but the following happens
- When one hash is set user:750473 and I do a scan 0, this result never shows up
- When two hashes are set (above), scan 0 gives me one result
- 3 hashes, 2 results
- ...

So it seems the scan command doesn't return me the correct number of results. Or otherwise I'm missing something. Both keys are hashes. I see the exact same behavior in the GUI. I guess if you don't get the result back from scan you can't really render the folder in the GUI.

Also just for info, there's not a lot of data in this db at the moment. I went to the next page with scan 9 to see if anything was there, and the data wasn't there either.

# Server

redis_version:2.8.12
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:0000000000000000000000000000000000000000
redis_mode:standalone
os:Linux 3.2.0-48 virtual x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.6.3
process_id:7508092
run_id:2c36cd126b4cf514bfc731ae155ae3f1f27c08e6
tcp_port:12786
uptime_in_seconds:48296986
uptime_in_days:558
hz:10
lru_clock:0

# Clients

connected_clients:75
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory

used_memory:380213024
used_memory_human:362.59M
used_memory_rss:380213024
used_memory_peak:383905728
used_memory_peak_human:366.12M
used_memory_lua:966656
mem_fragmentation_ratio:1
mem_allocator:jemalloc-3.2.0

# Persistence

loading:0
rdb_changes_since_last_save:1249151
rdb_bgsave_in_progress:0
rdb_last_save_time:1442496280
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats

total_connections_received:4861943
total_commands_processed:124718964
instantaneous_ops_per_sec:5
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:5452683
keyspace_misses:2256093
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0

# Replication

role:master
connected_slaves:1
slave0:ip=0.0.0.0,port=0,state=online,offset=0,lag=0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU

used_cpu_sys:0.00
used_cpu_user:0.00
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Keyspace

db0:keys=16,expires=0,avg_ttl=0

**Comment by uglide** [comment]
Hmm, looks like overflowing bug in https://github.com/uglide/qredisclient/blob/master/src/qredisclient/scanresponse.h#L11 
The same was fixed in redis-cli

**Comment by uglide** [comment]
Hello @dikkeduif

Could you please try this version with fix? http://redisdesktop.com/builds/redis-desktop-manager_0.8.3-dev1-119_amd64.deb

Thanks in advance!

**Comment by donalddw** [comment]
@uglide Yes, I have to build from source though. I'm on fedora. Any chance you can push your branch?

**Comment by uglide** [comment]
@donalddw It's already in 0.8.0 branch, just pull it. Thanks!

**Comment by dikkeduif** [comment]
@uglide Ok, tested and looking good! thanks

**Comment by uglide** [comment]
@dikkeduif awesome!

**Comment by uglide** [comment]
Fixed will be released in 0.8.3
