### ISSUE TITLE
Add ability to import commands & export keys as commands  [$60]

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3529]
> I hope there will be also "batch command execution" loaded from file or pasted on screen, like
> 
> HSET key1 field1 value1
> HSET key1 field2 value2
> HSET key2 field2 value2
> ....
> 
> and its "export" counterpart, i.e. export a DB into a file as series of SET commands.
##

**Comment by tobsn** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28119244)](https://www.bountysource.com/issues/28119244-keys-bulk-operations?utm_source=28119244&utm_medium=shield&utm_campaign=ISSUE_BADGE)

there ya go :)

select multiple > action (mainly delete I guess) + FLUSHALL would be amazing.

**Comment by plamendp** [comment]
I hope there will be also "batch command execution" loaded from file or pasted on screen, like

HSET key1 field1 value1
HSET key1 field2 value2
HSET key2 field2 value2
....

and its "export" counterpart, i.e. export a DB into a file as series of SET commands.

**Comment by uglide** [comment]
@tobsn First part of your request was implemented in 0.8.7 version (ability to delete namespaces and keys from connection tree)
Second part of your request was implemented in https://github.com/uglide/RedisDesktopManager/pull/3661 and will be available in 0.8.8 beta

**Comment by uglide** [comment]
@plamendp

Your request was out of the scope of this issue, so I changed current issue description to get **what you actually need** done as fast as possible.

**Comment by uglide** [comment]
@plamendp 
Due to lack of time I forced to postpone this feature to 0.9.0 release. You will be able to try it in 0.9.0alpha1 (ETA is Sept 5)

**Comment by uglide** [comment]
Closing it because nobody upvoted or requested this feature since 2016
