### ISSUE TITLE
Implement possability to open key by name

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3530]
##

**Comment by donalddw** [comment]
@uglide what is this issue about? In the windows client when you select a hash and type the starting letter of a key, it will jump to that key. In the linux client this doesn't work. Is this related?

**Comment by uglide** [comment]
yes, it's good feature for cases when you know key name but don't want to search this key manually or via key filtering

**Comment by donalddw** [comment]
@uglide Yes that would very nice indeed, I'm using this all the time on 0.7.6 in the windows client. Also not really in this scope, but sorting a column by clicking on the column header would also be very nice :)
