### ISSUE TITLE
unable to navigation through tree with arrow keys

### ISSUE THREAD

**Issue by pc-jedi** [redis/RedisDesktopManager#3531]
OS: Mint 17.2
Version: 0.8.2-177

The navigation with the arrow keys does not work when a "key-folder" is selected.
![screenshot from 2015-11-11 11 37 07](https://cloud.githubusercontent.com/assets/9032867/11089235/984d4f52-8868-11e5-9429-edbd2a1a1ec4.png)
For keys and DBs everything works fine.
##

**Comment by uglide** [comment]
Hello @pc-jedi 
Thanks for the feedback!
