### ISSUE TITLE
Kryo format support...

### ISSUE THREAD

**Issue by damacheng009** [redis/RedisDesktopManager#3532]
Thanks in advanced：）

**Comment by uglide** [comment]
Hello @damacheng009 
It looks imposible to easily implement Kryo support in C++ or JS. But I'm open for implementing this support in native way. I can add support in RDM for external value view formatters.

Are you ready to implement in Java executable which will decode/encode data in Kryo format?

**Comment by uglide** [comment]
[More info and API](https://github.com/uglide/RedisDesktopManager/issues/3534)

**Comment by uglide** [comment]
Issue moved to https://github.com/RedisDesktop/rdm-native-value-fromatters
