### ISSUE TITLE
Feature Request: WDDX Format

### ISSUE THREAD

**Issue by rchavik** [redis/RedisDesktopManager#3533]
It would be good if rdm can display values serialized using wddx format.

Use case: Session data can be serialized using wddx: http://php.net/manual/en/session.configuration.php#ini.session.serialize-handler

**Comment by uglide** [comment]
Hello @rchavik 
I'm going to implement Native Formatters support in RDM. Are you ready to implement this formater in php?

**Comment by uglide** [comment]
More info and [API](https://github.com/uglide/RedisDesktopManager/issues/3534)

**Comment by rchavik** [comment]
Sure, I think I can do that.

**Comment by uglide** [comment]
Issue moved to https://github.com/RedisDesktop/rdm-native-value-fromatters/issues/4
