### ISSUE TITLE
Sorted sets: Integer scores are treated as float

### ISSUE THREAD

**Issue by halaei** [redis/RedisDesktopManager#3537]
In redis desktop manager Scores in sorted set are shown as float, but they really are integer, e.g. they can be linux timestamp

The real score: 1447852714. What desktop manager shows: 1.44785e+09

**Comment by uglide** [comment]
Duplicate of #3518

**Comment by halaei** [comment]
Great. Thanks. I didn't find that issue. Sorry to bother.

**Comment by uglide** [comment]
@halaei np, thanks for the feedback!
