### ISSUE TITLE
RDM window black when viewed over RDP connection in Windows.

### ISSUE THREAD

**Issue by duncan-bradley** [redis/RedisDesktopManager#3538]
When I use RDM via an RDP connection in windows, the main panel is shown black.
![rdmcapture](https://cloud.githubusercontent.com/assets/15477354/11267137/7798dc92-8ea1-11e5-9565-8778dd28ba33.PNG)

It works fine locally.

**Comment by uglide** [comment]
Hello @duncan-bradley 
Which version of RDM do you use?

**Comment by duncan-bradley** [comment]
Version 0.8.2.3849. on win7.
I have tried the dll suggested for the same issue on VirtualBox without success.

Thanks

**Comment by 82ndab-Bravo17** [comment]
Duplicate of #3508 Black Data Window?

**Comment by uglide** [comment]
Will be fixed by #3560

**Comment by gmichels** [comment]
I still have this issue when running 0.8.8.
