### ISSUE TITLE
Desktop Manager crashes on startup

### ISSUE THREAD

**Issue by shaldev** [redis/RedisDesktopManager#3540]
The version is redis-desktop-manager_0.8.2-117_amd64 on Ubuntu 14.04 with kernel version  3.19.0-33-generic.

**Comment by uglide** [comment]
Hello @shaldev
Please run RDM from command line and paste here output

**Comment by WesRateur** [comment]
Same error with RDM 0.8.3.3850 on Windows 10. Nothing appears when I run RDM from command line. Cannot uninstall it too. It very works fine and some day the bug appears.

**Comment by WesRateur** [comment]
Ok just solve my problem. I recently install a software that need Microsoft Visual C++ 2008 redistribuable. When I unistall the software and Microsoft Visual C++ 2008 redistribuable, RDM works again. Maybe it cannot be use with Microsoft Visual C++ 2008 redistribuable.

(sorry english isnt my native language)

**Comment by uglide** [comment]
@WesRateur thank's for sharing your solution. I will check it on Windows as well.

**Comment by maytione** [comment]
Uninstalling  Microsoft Visual C++ 2008 redistributable NOT solveing same problem here... :(

**Comment by droninn** [comment]
I'm running the latest RDM on Ubuntu 15.10 inside a VirtualBox and it crashes my virtual machine and VirtualBox reports "memory could not be read". This was working fine on Ubuntu 12.xx. I managed to start it once but it just froze.

**Comment by uglide** [comment]
@droninn try to disable 3d acceleration

**Comment by ghost** [comment]
@uglide that worked. Now it starts but the virtual machine is dead slow. So I have too choose, unusable environment or usable RDM :|

**Comment by uglide** [comment]
@ou-work Just install rdm on host and connect to redis in VM through SSH tunnel or forwarded port
