### ISSUE TITLE
Installing on Ubuntu 15.10

### ISSUE THREAD

**Issue by Envek** [redis/RedisDesktopManager#3542]
Can't install 0.8.3 neither from deb-package nor from sources on latest Ubuntu 15.10:

There is no `libicu52` package in repos, but there is `libicu55` instead:

```
# dpkg -i redis-desktop-manager_0.8.3-120_amd64.deb
Selecting previously unselected package redis-desktop-manager.
(Reading database ... 268295 files and directories currently installed.)
Preparing to unpack redis-desktop-manager_0.8.3-120_amd64.deb ...
Unpacking redis-desktop-manager (0.8.3-120) ...
dpkg: dependency problems prevent configuration of redis-desktop-manager:
 redis-desktop-manager depends on libicu52; however:
  Package libicu52:amd64 is not installed.

dpkg: error processing package redis-desktop-manager (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu1) ...
Processing triggers for bamfdaemon (0.5.2~bzr0+15.10.20150627.1-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for mime-support (3.58ubuntu1) ...
Errors were encountered while processing:
 redis-desktop-manager
```

When building from source configure script can't find Qt packages `qt54base`, `qt54tools`, and so on. There is no file `/opt/qt54/bin/qt54-env.sh`. Should I install Qt manually or should I add some repo?

Can you please update building from sources manual?

Thank you for RDM!

**Comment by uglide** [comment]
Hello @Envek 
Thanks for the feedback!
On Wily you can install Qt 5.4 from official repo http://packages.ubuntu.com/wily/qt5-default
I will update `configure` script for wily soon. Stay tunned.

**Comment by eddelbuettel** [comment]
FWIW your error above was `Package libicu52:amd64 is not installed.` and the package itself installs just fine.

**Comment by uglide** [comment]
@eddelbuettel Thanks for sharing!

**Comment by stuaxo** [comment]
Hi,
   This bug is shut, but the ./configure is still not updated - does that need a new ticket ??

S

**Comment by eddelbuettel** [comment]
I am happily running redis-desktop-manager on 15.10.  Just download the missing libicu package via packages.ubuntu.com.

**Comment by uglide** [comment]
@stuaxo This bug was fixed in 0.9 branch https://github.com/uglide/RedisDesktopManager/commit/cc9f2733ca20fb2f51972b3504d6be6b2fee8c76
I will cherry pick this commit to 0.8 branch

**Comment by czerasz** [comment]
Just downloaded the `redis-desktop-manager_0.8.3-120_amd64.deb` and get the following issue:`Dependency is not satisfiable: libicu52` :-(.

**Comment by eddelbuettel** [comment]
@czerasz See my comments from two days ago and [install the library from here](http://packages.ubuntu.com/search?keywords=libicu52) if you use Ubuntu; you probably know where to search for it from Debian too.

**Comment by czerasz** [comment]
@eddelbuettel thanks for your patience ;-). I thought it doesn't work if I had `libicu55` already installed.

Now I downloaded `libicu52` for Ubuntu vivid - `15.04` (I'm on `15.10`), from [here](http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8ubuntu0.2_amd64.deb) (see [this page](http://packages.ubuntu.com/vivid/amd64/libicu52/download) for more details).

Would be nice if it could work with `libicu55` ;-)
Anyway great software!

**Comment by eddelbuettel** [comment]
@czerasz I misread your comment at first.  Yes they _do_ allow parallel installation:

```
$ COLUMNS=70 dpkg -l | grep "^ii  libicu" | cut -c-70
ii  libicu-dev:amd 55.1-4ubuntu amd64        Development files for Int
ii  libicu52:amd64 52.1-8ubuntu amd64        International Components 
ii  libicu55:amd64 55.1-4ubuntu amd64        International Components 
$ 
```

And you _can_ get it to work wth libicu55, I guess, if you just recompile / rebuild the deb locally or in a PPA.   This approach was 'good enough' for me.
