### ISSUE TITLE
"'Add New" window placement when 2 screens

### ISSUE THREAD

**Issue by andyrooc** [redis/RedisDesktopManager#3544]
On Mac OSX 10.10.5:
1. Right-click -> Add New Key on first screen
2. New window opens on second screen (hidden if the screen is in full screen mode)
3. Can drag Add New Key window anywhere in second screen
4. Cannot move Add New Key window to first screen - it drags, but zips back to second screen

ie: pop-up window should probably center on main app window, not on screen location.

Cheers - (rdm is great, especially for noobs to redis)

**Comment by uglide** [comment]
Hello @andyrooc 
Thank you for the feedback!

**Comment by adfinlay** [comment]
This also affects Windows 7.

**Comment by uglide** [comment]
Fixed in 0.8.4
