### ISSUE TITLE
Implement flush db functionality

### ISSUE THREAD

**Issue by anealchandra** [redis/RedisDesktopManager#3546]

**Comment by uglide** [comment]
Hello @anealchandra 
Could you please add more details to you feature request? What exactly do you need?

**Comment by anealchandra** [comment]
"flushdb" redis-cli command. Could be implemented as a new menu item from existing pop-up context-menu for selected db node

**Comment by m3talstorm** [comment]
Yes please

**Comment by uglide** [comment]
Implemented in 0.8.8
