### ISSUE TITLE
Setting directory is not writable [Windows 10]

### ISSUE THREAD

**Issue by kuch4r** [redis/RedisDesktopManager#3548]
After installing RDM on Windows 10, when I trying to run it, I get message
![rdm](https://cloud.githubusercontent.com/assets/8859134/11589618/2501c788-9a8a-11e5-9ecc-8b9d72a3930a.jpg)
"Setting directory is not writable"
"Program can't save connections file to settings dir.Please change permissions or restart this program with administrative privileges."

Starting it with administrative privleges didn't solve that problem.

Reinstall also doesn't hellp. I use Windows 10 most recent version,

**Comment by uglide** [comment]
Hello @kuch4r Thanks for the feedback, I will try to reproduce this issue on vm with win 10

**Comment by uglide** [comment]
@kuch4r I tested RDM on Windows 10 and I cannot reproduce this error. Probably your antivirus sendboxed or blocked i/o of RDM. Please specify which antivirus software do you use. Thanks!
