### ISSUE TITLE
Does redis desktop manager support 32-bit ubuntu 14.10?

### ISSUE THREAD

**Issue by brahamshakti** [redis/RedisDesktopManager#3549]
Hi do you have build for 32 bit ubuntu 14.10 system. I didn't find any release related to i386. Any idea?

**Comment by uglide** [comment]
Hello @brahamshakti 
RDM officially doesn't support i386 on Ubuntu, but you can [build RDM from source](https://github.com/uglide/RedisDesktopManager/wiki/Build-from-source#ubuntu)
