### ISSUE TITLE
Error: Invalid PHP Serialized String when viewing keys holding raw HTML values

### ISSUE THREAD

**Issue by tribou** [redis/RedisDesktopManager#3552]
I've been getting an error when switching between keys in a Redis DB:

```
Error: Invalid PHP Serialized String: {"message":"Unknown type '<' at position 0\n Unprocessed part...
```

Version: 0.8.3-2550
Environment: OSX 10.11.2 El Capitan
Redis Server Version: 3.0.3
1. Store raw HTML in the value of a redis key
2. Use RDM to switch back and forth between viewing different keys

**Comment by moitias** [comment]
Another test case that causes it to default to PHP serialized when it certainly shouldn't; just the string 'C' or indeed pretty much _any_ string that starts with _any_ PHP serialization type specifier. 

For example, just the string 'N' (or 'Nice' or 'New' etc) gets deserialized into null (even though it is not valid - should be 'N;') which is quite misleading unless one notices that the PHP serialization mode is selected. At the very least RDM should check that the value is terminated with a semi-colon and has valid fields before trying to PHP deserialize. As it is, it's way way too aggressive.

**Comment by uglide** [comment]
@moitias Thanks for usefull testcases. I implemented following testcases in tests and fixed php-unserializer:
- html value
-  'N' (or 'Nice' or 'New' etc)
-  just the string 'C' or indeed pretty much any string that starts with any PHP serialization type specifier.

**Comment by uglide** [comment]
btw fix will be released in 0.8.4

**Comment by moitias** [comment]
Excellent! Thanks for a great piece of software!

**Comment by andrewleker** [comment]
I am seeing this same problem on 6/14/2016. I downloaded RDS a week ago. 
I can manually change from PHP Serializer to Plain Text, but I have to do this every time. Is there a way to get that setting to stick for simple, raw text values?
