### ISSUE TITLE
Unable to connect to Redis Server getting "Cant connect to redis server" error!

### ISSUE THREAD

**Issue by evivz** [redis/RedisDesktopManager#3553]
How to resolve it?

Screenshot: http://i.imgur.com/gxQBM1w.jpg

**Comment by uglide** [comment]
You should uncheck password if your private key is not encrypted with password

**Comment by evivz** [comment]
@uglide  Sorry had posted wrong screen: http://imgur.com/a/NxJpM

Same error.

**Comment by uglide** [comment]
@evivz Host on first tab should be localhost or 127.0.0.1

**Comment by evivz** [comment]
@uglide still the same error: http://imgur.com/nyFBFgm

**Comment by uglide** [comment]
Probably you are using private key in invalid format
18 дек. 2015 г. 15:58 пользователь "Vivek Sancheti" <
notifications@github.com> написал:

**Comment by uglide** [comment]
Private key should be in pem format, not ppk

**Comment by hemratna** [comment]
@uglide 
Hi,
We are running Redis Desktop Manager on Windows 8.
And private key is in the formate of .ppk file

I am using the same .ppk file to connect sqlyog to same server.

Thanks for your help. :)

**Comment by uglide** [comment]
See my previous comment

**Comment by hemratna** [comment]
@uglide 

Thanks a lot.
As I am new to this ecosystem.

Thank you very much.

**Comment by uglide** [comment]
@hemratna you're welcome!

**Comment by evivz** [comment]
@uglide I am unable to locate private key in mac as they are hidden what is the solution for it?
