### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by cinemast** [redis/RedisDesktopManager#3556]
Hi!

Thank you for providing RedisDesktopManager. It makes my everyday life easier. 

I am a Debian Maintainer and considering packaging your software. I see you provide ready to use binaries for Ubuntu. Is there any reason you wouldn't want your package in Debian (which would also mean full integration and compatibility for Ubuntu)?

Would you be open to collaborating with me on packaging your software for Debian?

Greetings
Peter

**Comment by uglide** [comment]
Hello Peter,

I'm open for collaboration and ready to provide help with packaging.

Main problem is absence of latest versions of Qt (RDM needs 5.4+) in
Debian/Ubuntu repos.

Please feel free to ping me back here or via email.
22 дек. 2015 г. 11:10 пользователь "Peter Spiess-Knafl" <
notifications@github.com> написал:
