### ISSUE TITLE
We need to customize the data analysis!

### ISSUE THREAD

**Issue by Trini7** [redis/RedisDesktopManager#3561]
When I put Redis through java serialized data, I can not and intuitive access to relevant data, we need to customize the data analysis!

**Comment by uglide** [comment]
Hello @Adar-w 
Could you please describe what exactly do you need in RDM?

**Comment by Trini7** [comment]
![image](https://cloud.githubusercontent.com/assets/12758600/12160084/67a9c5d2-b523-11e5-9d95-28fd9e9e1c44.png)

**Comment by Trini7** [comment]
Thank you.

**Comment by uglide** [comment]
Duplicate of #3534
