### ISSUE TITLE
Unable to connect via SSH Tunnel on ubuntu

### ISSUE THREAD

**Issue by addonis1990** [redis/RedisDesktopManager#3568]
I am trying to connect to a redis server via an ssh tunnel using a .pem file. On OS X, the connection gets established pretty easily and rdm actually works with no issues. However, on a ubuntu machine (14.04) and using the same credentials and pem file, I am having authentication issues that prevent tunnel establishment. 
![redis-error](https://cloud.githubusercontent.com/assets/5556023/12500236/8e9988aa-c0b1-11e5-881a-a22e09c96cfb.png)

**Comment by uglide** [comment]
@addonis1990 Have you tried to connect to this machine through ssh client on ubuntu?

**Comment by addonis1990** [comment]
@uglide yes it works with no issues

**Comment by uglide** [comment]
@addonis1990 Which encryption algo is used to generate this private key?

**Comment by Zincr0** [comment]
+1 rsa key auto-generated by amazon http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#having-ec2-create-your-key-pair

**Comment by uglide** [comment]
@Zincr0 Thanks for info

**Comment by fordodone** [comment]
Is there a build associated with this bugfix? or a commit? I could help test it...
