### ISSUE TITLE
Cannot connect SSH with passphrase

### ISSUE THREAD

**Issue by ducminhgd** [redis/RedisDesktopManager#3571]
Shortly: I'm using SSH tunnel with a private key and passphrase, I tried to input passphrase in password field, but it didn't work.

Details: I have two servers, Web and Redis, Redis server allows only Web server connect via 6379 port. I have to SSH to Web server and connect to Redis Server. It works on command line, but doesn't work in Redis Desktop Manager
##

**Comment by uglide** [comment]
Hello @ducminhgd 
Thanks for the feedback, I will ty to reproduce this issue

**Comment by uglide** [comment]
@ducminhgd btw Do you use key in PEM format?

**Comment by ducminhgd** [comment]
@uglide Yes.
And when will new version be released? I'm looking forward to its release day.

**Comment by uglide** [comment]
@ducminhgd I expect to release the first beta of 0.9.0 in the middle of February. Final release dates you can find on [milestones page](https://github.com/uglide/RedisDesktopManager/milestones)

**Comment by uglide** [comment]
@ducminhgd One more question, Which OS & Version Do you use?

**Comment by ducminhgd** [comment]
@uglide I'm using Windows 10, RDM 0.8.3. Windows 7 has the same issue too.

**Comment by uglide** [comment]
@ducminhgd ok, thanks

**Comment by laurencei** [comment]
I have this same issue. Is there any ability to use a passphrase for the key?

**Comment by uglide** [comment]
Cannot reproduce on current 0.9 branch (0.9.3 release). Probably duplicate of #4047 or already fixed
