### ISSUE TITLE
openSUSE Leap 42.1 (x86_64) waiting U

### ISSUE THREAD

**Issue by mingjunyang** [redis/RedisDesktopManager#3573]
openSUSE Leap 42.1 (x86_64) waiting U

``` shell
./configure 
Your operation system is not supported!
```

NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"

**Comment by uglide** [comment]
Hello @mingjunyang 
It's easy to update `configure` script to add support for OpenSUSE, so you can try to do it by yourself.

Anyway I'll add OpenSUSE support to 0.9.0 milestone

**Comment by mingjunyang** [comment]
@uglide  thx , wait good news.

**Comment by uglide** [comment]
@mingjunyang OpenSUSE is supported now. More info here http://docs.redisdesktop.com/en/latest/install/#fedora-centos-opensuse
