### ISSUE TITLE
Attempting to delete a server from the connections list with delete button does not work immediately after deleting another server

### ISSUE THREAD

**Issue by cyber-decker** [redis/RedisDesktopManager#3574]
The intent here is to delete many servers in the server list to remove old or incorrect servers from my list. I can't seem to do multiple deletes in a row over and over to delete many servers from my list.

Version: 0.8.3.3850
Environment: Windows 7 Enterprise
Redis Server Version: n/a

**Steps to reproduce:**
1) Select a server in a list of servers in RDM
2) Hit the delete button (on the keyboard) to delete that server
3) Hit enter to select Yes for the confirmation dialogue
4) Hit delete button (on the keyboard) to delete the next automatically highlighted server
5) Hit enter to select Yes for the confirmation dialogue

**Expected Result:**
The next highlighted server in the list will be deleted as well after accepting the confirmation.

**Actual Result:**
The highlighted server is not deleted from the server list.  It must be selected by clicking on it again or by pressing the down arrow multiple times to select it again.

**Notes**
It seems like the fact that when I press the down arrow that the next server that gets highlighted is higher up in the list.  Seems like the actual item selected after a delete is changed and not really the next item after the one that was just deleted. 
##

**Comment by uglide** [comment]
Hello @cyber-decker 
Thanks for detailed but report!

**Comment by cyber-decker** [comment]
You're very welcome. I hope this is helpful in improving the software.

**Comment by uglide** [comment]
Cannot reproduce it on 0.9.7. Looks like it's already fixed
