### ISSUE TITLE
Implement PPA for Ubuntu

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3575]
Create PPA for RedisDesktopManager on Launchpad to simplify installations and updates for Ubuntu users.

**Comment by uglide** [comment]
More info here #3638

**Comment by wingedrhino** [comment]
Hi, #3638 has been deleted. Can you talk about why the PPA wasn't implemented?

**Comment by uglide** [comment]
PPA implementation was superseded by snapcraft.
