### ISSUE TITLE
Show warning when user tries to load large amount of keys

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3581]
```
Given: Selected db in connections tree
When: User expand db
Then: 
  if db_size() > %LIMIT%:
    show_warning()
  else:
    load_db_keys()

```
##

**Comment by shmosel** [comment]
On a related note, is there any way to open a key in the UI view without expanding the tree?

**Comment by uglide** [comment]
yes, just enter key name in db filter and if it exists in db it will be opened without scanning db

**Comment by uglide** [comment]
@shmosel yes, just enter key name in db filter and it will be opened without scanning db

**Comment by shmosel** [comment]
It still took a while to filter 6 million keys. What's it doing if not scanning?

**Comment by uglide** [comment]
@shmosel Which version do you use? This "go to key" feature was added in latest 2019.5 version https://github.com/uglide/RedisDesktopManager/issues/4708

**Comment by shmosel** [comment]
I updated to the latest and it works now. Thanks!
