### ISSUE TITLE
Windows build crash at startup

### ISSUE THREAD

**Issue by raoulh** [redis/RedisDesktopManager#3587]
Version: 0.8.3.3850
Environment: Windows 8.1
Redis Server Version: not relevant

Steps to reproduce:
1. Install from http://redisdesktop.com/download
2. Start

Expected result:
Application starts

Actual Result:
Crash with:
![untitled](https://cloud.githubusercontent.com/assets/1115950/13049924/8238efd6-d3f0-11e5-852a-22bfad844e9a.png)

A fix is be to install a valid qt.conf file containing:

```
[Paths]
Prefix=..
```

It works perfectly then.

**Comment by uglide** [comment]
Related to #3586

**Comment by uglide** [comment]
Fixed in 0.8.6
