### ISSUE TITLE
Reload in background

### ISSUE THREAD

**Issue by hildoer** [redis/RedisDesktopManager#3589]
Version: 0.8.3-2550
Environment: OSX El Capitan
Redis Server Version: 3.0.7

General description: 

This isn't really a technical bug so much as maybe a UX bug.

Reloading DBs with LOTS of keys takes forever over WAN connections, which is to be expected. However, the UI blocks on the DB in the tree with an "hour glass" until it has loaded every key value. Any reason we can't let the UI continue to work and just allow the keys to populate in the background? 

Steps to reproduce:
1. Populate a redis db you access over WAN (a powerful AWS EC2 instance over SSH tunnel in my case). Put in like 100 million key/value pairs with TTLs of > 30 days
2. Open the application
3. Open a connection to a remote redis server
4. Double click db0 (or wherever you put in all the key/value pairs from step 1)

Desired result: The DB opens in the tree and populates counts and key/value pairs in the background as I immediately begin to browse the data already there.

Actual Result: The icon for the DB entry in the tree view turns into an hour glass and I can't access anything until the log window has finished listing all the "scan # MATCH \* COUNT" entries.

Thanks!

Also, great app!
##

**Comment by uglide** [comment]
Hello @ahildoer 
Thanks for the feedback!
In 0.9.0 versions (which is unstable currently) I've implemented "live reload" already. So your suggestion exactly about the same thing. Hopefully, I will be able to release 0.9.0 in a couple month.

**Comment by uglide** [comment]
The described problem was divided to live update (for background reloading, currently WIP) and server-side LUA loading
