### ISSUE TITLE
RDM путает базы.

### ISSUE THREAD

**Issue by niko-lay** [redis/RedisDesktopManager#3590]
Вот так выглядит rdm если быстро выбрать все три базы сразу после открытия приложения. 
![screen-shot-2016-02-17-at-13 04 42](https://cloud.githubusercontent.com/assets/5228230/13107848/6611ca2e-d578-11e5-81ff-9ec943ce3f92.png)
А вот так базы должны выглядеть на самом деле 
![screen-shot-2016-02-17-at-13 05 09](https://cloud.githubusercontent.com/assets/5228230/13107847/66104442-d578-11e5-95fb-9c655d995967.png)

Macos 10.11 rdm 0.8.3-2550 подключение к prod через vpn.

**Comment by gbatanov** [comment]
Такая же ситуация у меня возникает, если RDM просто "постоит" без дела с открытыми базами. В ~ 80% после этого вместо второй базы будет показано содержимое первой. Reload не помогает, только перезапуск программы.

**Comment by uglide** [comment]
Fixed in 0.8.7 (fix in qredisclient https://github.com/uglide/qredisclient/commit/23e6f066e2df9a891cbf2c462877ca05b7eefa1b)
