### ISSUE TITLE
ValueEditor::Compression::isCompressed not detecting gzipped values.

### ISSUE THREAD

**Issue by dac514** [redis/RedisDesktopManager#3592]
Version: 0.8.3
Environment: Ubuntu 14.0.4
Redis Server Version: 2.8.8

Steps to reproduce:
1. Click on gzcompressed value

Expected result: Uncompressed text
Actual result: Binary

-=-=-

I'm working on a project where none of the values are being detected as gzipped.

_(Code: https://github.com/uglide/RedisDesktopManager/blob/0.8.3/src/modules/value-editor/compression.cpp#L8 )_

For example, the following "View as HEX": 

```
x\x9CK\xB42\xB1\xAA.\xB62\xB2R\xCALQ\xB2.\xB62\xB6R2\xB44\x05\xB1L\xAC\x94\xF2\x12sSALS+\xA5\xE0\x82\xC4\xCC<\xA8pr~\x0AX\x18\xA8\xC95\x18\xC404\x04\x0A\x96\x16\x15\xA5\xE6%W\xC6C\xCC\x01\x8A\x18+Y\xD7\x02\x00\xF5c\x1A\xFE
```

Can be gzuncompressed() to show the text:

```
a:4:{s:2:"id";s:3:"195";s:4:"name";s:5:"Spain";s:4:"code";s:2:"ES";s:11:"currency_id";s:1:"3";}
```

But Redis Desktop Manager 0.8.3 does not detect.
##

**Comment by uglide** [comment]
@connerbw Thanks for detailed bug report!

**Comment by uglide** [comment]
Moved to https://github.com/RedisDesktop/rdm-native-value-formatters/issues/8
