### ISSUE TITLE
RDM uses discrete graphic on mac os x.

### ISSUE THREAD

**Issue by DmitryRibalka** [redis/RedisDesktopManager#3593]
When i start the app it switches on discrete graphics.
<img width="281" alt="discreet" src="https://cloud.githubusercontent.com/assets/1777603/13175073/9240bd78-d710-11e5-9aa4-0d4212676773.png">

Mac OS X El Capitan.

**Comment by uglide** [comment]
RDM from version 0.7.9 uses QML which uses OpenGL for UI rendering, that's why it switches to discrete graphics by default. If you want you can set "integrated only".
