### ISSUE TITLE
Add option to global settings - hide empty databases

### ISSUE THREAD

**Issue by joefrancia** [redis/RedisDesktopManager#3594]
As you can see, RDM is only showing the first three databases. Exiting and restarting doesn't help, nor does restarting Redis. Eventually, it may show the full list of dbs, but I have no idea how to make it do so. 

![image](https://cloud.githubusercontent.com/assets/1500865/13193105/319ceb1e-d728-11e5-9ae5-d0143882a7fa.png)
##

**Comment by uglide** [comment]
@scaba By default RDM doesn't show databases without keys

**Comment by joefrancia** [comment]
@uglide That's not been my experience. Two of the the three dbs listed in my screenshot have zero keys, and the db I was interested in seeing (db15) does have keys but it doesn't show up. Until now RDM has always shown me all databases. In fact, i just now launched RDM and now it shows me all 16 dbs again. Only db0 and db15 have keys.
![image](https://cloud.githubusercontent.com/assets/1500865/13198542/81addb0c-d7c0-11e5-8744-2b9125e0567b.png)

**Comment by uglide** [comment]
@scaba this behaviour was required due to support of old redis servers (2.2, and 2.4). In RDM 0.9.0 I will drop support for old redis versions, and make db loading more transparent for user.

**Comment by uglide** [comment]
Fixed in 0.9
