### ISSUE TITLE
can not show add new key dialog on multi-screen

### ISSUE THREAD

**Issue by antaintan** [redis/RedisDesktopManager#3598]
RDM Version: 1.0.0.0
Environment (OS name and version): win10
Redis Server Version: 3.0.7

Steps to reproduce:
1. ...add new key in context menu

Expected result: 

Actual Result:

**Comment by meteormanaged** [comment]
I've just run into the same bug.

I captured it on screen.  http://f.cl.ly/items/1r051g053Q140s280m3p/ioredis-rdm-bug.m4v

So what's happening is this.  If you open the rdm client and, on it's own or through your own actions, the main screen and the add key screen are on different screens, what occurs in the video is the result.

They'll be some flickering between screens, the add key screen will "disappear", and you'll be bonging and dinging around all day trying to click on anything.  After playing with this for a few minutes, I was able to determine that the window isn't flat out disappearing, but it's appearing just off of edge of one of the monitors.  I was able to get it back and do it a second time in the video.

OSX 10.11.2
