### ISSUE TITLE
Different type icons

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#36]
It would be useful to know type of the key from it's icon and also to have a legend with explained icons somewhere.

**Comment by uglide** [comment]
I will not implement this feature, because it's significantly reduce performance of loading keys.

**Comment by loginwashere** [comment]
Don't really understand the reason of rejection. It looks like it will take one extra type command call per key to determine it's type. 

Type command on it's own is pretty fast and it is suitable to show type only for end point keys (not for namespaces), so even type commands won't be called for all keys at the same time.

Can You explain what reduces performance in this situation because I'm clueless at this point.

**Comment by uglide** [comment]
Dmitry, you forgot about case, when all keys in database doesn't have namespaces. In this case we must send thousands requests in same time.

**Comment by loginwashere** [comment]
Yes, I see your point. It's more complicated than I thought.
