### ISSUE TITLE
Feature request: preserve the size of columns

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#3603]
Hello, can I please request a feature here?

It would be handy to preserve the column size in the rows list. 
When I set the width of the column and click to the next/previous page button or to any other list item, my column size resets. 

I am using the Debian based Linux version 0.8.3-120

Thank you!

**Comment by defmys** [comment]
Hello @uglide, It seems the following code in ValueTabs.qml:379 re-sizes the table columns (except for the 1st one) every time.
`if (index > 0) column.width = table.width / (columns.length - 1) - 50`
Simply remove this line of code works for me but I am afraid of causing some other issues. Just hope it helps.

**Comment by uglide** [comment]
@defmys thanks, I've removed this line in 0.9 branch
