### ISSUE TITLE
Cannot be installed on Ubuntu Wily Werewolf

### ISSUE THREAD

**Issue by matthewbaggett** [redis/RedisDesktopManager#3604]
RDM Version: 0.8.3
Environment (OS name and version): Ubuntu 15.10
Redis Server Version: n/a

Steps to reproduce:

```
1. Try to install using provided deb.
```

Expected result: 

```
Actually installs
```

Actual Result: 

```
Cannot install due to dependency on libicu52.
```

![screenshot-package installer - redis-desktop-manager](https://cloud.githubusercontent.com/assets/943948/14154686/c00ebd8a-f6b5-11e5-8957-69a5358454e7.png)

**Comment by emrahtoy** [comment]
It should become libicu55 instead of libicu52.

`apt-cache search libicu`

Gives you this result;

```
icu-devtools - Development utilities for International Components for Unicode
libicu-dev - Development files for International Components for Unicode
libicu55 - International Components for Unicode
libicu55-dbg - International Components for Unicode
libicu4j-4.4-java - Library for Unicode support and internationalization
libicu4j-49-java - Library for Unicode support and internationalization
libicu4j-java - Library for Unicode support and internationalization
```

**Comment by stroudmw** [comment]
I've got the same dependency error. Ubuntu 15.10. Will this be addressed in Ubuntu version 16.04? I plan on upgrading next week...

**Comment by shaun-ba** [comment]
I can confirm 16.04 doesn't work

**Comment by aPoCoMiLogin** [comment]
There found the solution: https://github.com/uglide/RedisDesktopManager/issues/3554#issuecomment-214606893

**Comment by uglide** [comment]
You always can build RDM from source, on linux it's quite easy. Deb packages for Ubuntu in near feature will be available only for users with paid subscription.
