### ISSUE TITLE
Specify bind address

### ISSUE THREAD

**Issue by garymissguided** [redis/RedisDesktopManager#3605]
Hi

Our Redis instance is bound to a specific IP only, not 127.0.0.1.  Is there any way this can be specified to connect to the non-default bind address?

Many thanks

**Comment by uglide** [comment]
Hi @garymissguided 
Just specify this IP in settings and it should work.

**Comment by garymissguided** [comment]
Many thanks for your reply. 

Sorry I may not have explained properly.  I 'believe' I am connecting to the server successfully through the SSH tunnel settings inc private key (this works from other apps), but once connected I effectively need it to do the equivalent of "redis-cli -h 123.123.123.123" - I can't see where this would be added, and I assume it is defaulting to looking at 127.0.0.1?  I just receive 'Can't connect to redis-server'.

Thanks again

**Comment by uglide** [comment]
Specify redis host in 'host' field on Connection tab, and SSH host in 'Remote host' field on SSH Tunnel tab
