### ISSUE TITLE
Cannot create new key. Popup window do not show but lock main window.

### ISSUE THREAD

**Issue by konsto** [redis/RedisDesktopManager#3606]
RDM Version: 0.8.3.3850

Environment (OS name and version): Win 7 64bit

Redis Server Version: Win Redis version 3.0.501, Linux Redis version 2.8.7

Steps to reproduce:
1. right click on database, choose Add new key. It will lock. Popup window do not show but lock main window
2. ...
3. ...

Expected result: 

Actual Result:

**Comment by uglide** [comment]
Duplicate of #3544
