### ISSUE TITLE
OS X Key Bindings - Feature Request

### ISSUE THREAD

**Issue by derekargueta** [redis/RedisDesktopManager#3607]
Environment (OS name and version): OS X 10.11

Normal OS X key bindings uses cmd (⌘) for keyboard shortcuts, which RDM does for closing a window (⌘+w), but the other shortcuts use control (^) such as reloading, opening terminal, and editing - these all should use ⌘ instead of ^.

Even though this issue is a bit nit-picky, users should have the ability to assign keyboard shortcuts as desired.
##

**Comment by uglide** [comment]
Meta key is used by default on OSX in 0.9 branch. shortcuts assignments will not be implemented because it's super minor feature
