### ISSUE TITLE
Good job! A few suggestions

### ISSUE THREAD

**Issue by xberg** [redis/RedisDesktopManager#3609]
Hi,

I'm so happy you developed this! Really useful for me! 
Here are 2 important suggestions:
1. Do not trim the keys.
In the left column you trim long keys: please do not do this. My keys are very long and I am unable to differentiate them:
http://prntscr.com/au6tvh
1. Is there a "search key" available?

thanks!

**Comment by teeberg** [comment]
One way to search keys (though not overly convenient) is:

![image](https://cloud.githubusercontent.com/assets/199071/15028811/7cc6a2e4-11ff-11e6-9719-e4bdba6a6604.png)

![image](https://cloud.githubusercontent.com/assets/199071/15028817/82a62a86-11ff-11e6-87d0-ac0091105bc2.png)

It would be nice if there was an easier way, like a find dialog or something, to do this.

**Comment by teeberg** [comment]
Also, might be worth splitting into two issues since you're asking for two independent things

**Comment by uglide** [comment]
Hello guys, sometimes it's useful to read the docs :) - http://docs.redisdesktop.com/en/latest/features/

**Comment by uglide** [comment]
@xberg I moved bug to separate issue #3614

**Comment by teeberg** [comment]
@uglide Filtering on individual databases is only convenient until you have more than one and don't know in which one the key that you are looking for is. For filtering across databases, what I suggested feels more convenient to me.
