### ISSUE TITLE
Feature suggestion: Delete branch of keys

### ISSUE THREAD

**Issue by plamendp** [redis/RedisDesktopManager#3610]
RDM Version: 0.8.3.3850<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: 2.8.4<br>

Actually, not an issue. Sorry, I could not find a place to file a request or suggestion.

Would be very nice to have an ability to delete key "branches", not key by key.

I guess you know what it is, but just in case:

b1:b2:key1
b1:b2:key2
b1:b2:key3
b1:b2:key4

Right Click on "b1"  > Delete Branch, deletes all keys above

Other than that, very, very good job, despite some crashes once in a while. I use it everyday!

**Comment by uglide** [comment]
Hello @plamendp 
Please post your bounty here https://github.com/uglide/RedisDesktopManager/issues/89 to speedup development of this feature. Thanks!
