### ISSUE TITLE
Can't move 'add new key' dialog between multiple monitors

### ISSUE THREAD

**Issue by tswaters** [redis/RedisDesktopManager#3611]
RDM Version: 0.8.3.3850 <br>
Environment (OS name and version): Windows 10 (x64)  <br>
Redis Server Version: Redis on Windows 2.8<br>

Steps to reproduce:
1. ... set up multiple displays
2. ... open 'add new key' dialog,  ctrl+n
3. ... drag dialog to different screen

Expected result: 

ability to drag the dialog to other windows

Actual Result: 

In my case, I have 3 monitors with the right-most is the laptop screen.  The add new key dialog starts on the laptop -- I should be able to drag the dialog to other monitors, or use the windows shortcut keys WIN+Left and move the dialog from 'restore' to 'stuck on left' and finally to the middle monitor -- but it won't move from the laptop screen.

Hard to describe this with screenshots, but when dragging the dialog appears to 'flash' between the drag position of the mouse and the initial position.  releasing the mouse does not move the dialog.  Furthermore, the position it snaps back to is the initial position the dialog was loaded at.  I can drag it around fine on the laptop monitor and release the mouse button and it will stay -- once I try to drag to another screen it will go back to the initial position it was loaded at (not where I dragged it).

All the other dialogs that I can see in the application (connect to redis server, rename key) appear to function properly -- it's only the add new key dialog that seems to get stuck on the one monitor.

**Comment by tswaters** [comment]
Whoa, then it crashed!  This may be unrelated -- if anything, it speaks to multiple monitors under windows.  My cat was messing around behind my desk and the hdmi cord to one of the monitors disconnected -- after plugging it back in, I saw that RDM had crashed.

**Comment by uglide** [comment]
Looks like this issue was fixed in 0.8.4. If not please reopen this issue with screencast. Thanks!
