### ISSUE TITLE
[Request] Option to only split colons by the first match?

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#3613]
Hey guys, for example:

![image](https://cloud.githubusercontent.com/assets/10387670/14939770/a53f9e76-0f0a-11e6-956e-7b528d3b5e85.png)

When I make keys with multiple `:`'s it actually splits them out into sub folders. My suggestion is maybe only split it by the first occurrence of the `:`?

I know having multiple colons can be utilized, that's why I'm suggesting maybe an option to only split by the first match.  My action RPG lets players create games and I want them to beable to use colons for their game name, but then it will be an absolute bitch to debug later when I got all those folders!
Thanks for reading ~
##

**Comment by uglide** [comment]
@Dillybob92 thanks for suggestion!
