### ISSUE TITLE
does not support ubuntu16.04 ?

### ISSUE THREAD

**Issue by jay-youngn** [redis/RedisDesktopManager#3615]
RDM Version: 0.8.3 
Environment (OS name and version): ubuntu 16.04 LTS 
Redis Server Version: 3.0.2 

An error occurred when run "sudo dpkg -i redis-desktop-manager_0.8.3-120_amd64.deb" 
error notice like: 
package libicu52 is not installed
And the "apt install -f" can't solve the problem. I think it has been replaced by libicu55.

**Comment by aPoCoMiLogin** [comment]
There found the solution: https://github.com/uglide/RedisDesktopManager/issues/3554#issuecomment-214606893

**Comment by jay-youngn** [comment]
@aPoCoMiLogin thx~
