### ISSUE TITLE
CPU utilization rate is very high.

### ISSUE THREAD

**Issue by springleng** [redis/RedisDesktopManager#3616]
RDM Version: 0.8.3 2550 <br>
Environment (OS name and version): Mac OS X EI Capitan 10.11.4 <br>
Redis Server Version: 3.0.4 64bit <br>

CPU utilization rate is very high. <br>

This is a screenshot: <br>

![cpu](https://cloud.githubusercontent.com/assets/1900972/15099608/81fa345c-158c-11e6-9082-0241917dd10c.jpg)
##

**Comment by uglide** [comment]
Fixed in 0.9 branch
