### ISSUE TITLE
DPI Scaling on Windows is faulty

### ISSUE THREAD

**Issue by tw-bert** [redis/RedisDesktopManager#3617]
![redis desktop manager on 200 procent dpi](https://cloud.githubusercontent.com/assets/3413888/15160932/56c25ee2-16fc-11e6-901a-96d15f3d4af2.png)
RDM Version: 0.8.3.3850<br>
Environment (OS name and version): Win10.1, Win7x64 Pro<br>
Redis Server Version: 3.0.6 <br>

Steps to reproduce:
1. Set Windows DPI to 200% (very common on ultrabooks with UHD)
2. Log out, log in
3. Start Redis Desktop Manager

Expected result: 
A workable user interface

Actual Result: 
A non-workable user interface; margins are too narrow for the labels and content of the Qt UI widgets

**Comment by uglide** [comment]
Issue was fixed in 0.8.4 release

**Comment by tw-bert** [comment]
That's great news. But... I can't verify this because 0.8.4 for Windows is not available on http://redisdesktop.com/download . Therefore this issue should not be Closed. Never mind, I'll keep an eye open for new releases. Thx.

**Comment by uglide** [comment]
@tw-bert download 0.8.4 from release page https://github.com/uglide/RedisDesktopManager/releases/tag/0.8.4 :)

**Comment by tw-bert** [comment]
That looks great. Thank you for fixing this issue.
