### ISSUE TITLE
Hardcoded icon path in Linux launcher file

### ISSUE THREAD

**Issue by palob** [redis/RedisDesktopManager#3618]
Environment (OS name and version): Any GNU/Linux distribution

Hi,
currently the icon path in the created [.desktop launcher file](https://github.com/uglide/RedisDesktopManager/blob/0.8.0/src/resources/rdm.desktop) is hardcoded to:
`Icon=/usr/share/redis-desktop-manager/bin/rdm.png`

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the `freedesktop.org` standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

According to the above resources standard icon locations are:

`/usr/share/icons/hicolor/[size]/apps/[icon name]`
`~/.local/share/icons/hicolor/[size]/apps/[icon name]`
`/usr/share/pixmaps/[icon name]`

The corresponding standard icon line in the .desktop launcher is:
`Icon=[icon name]` (without full path, without file extension)

For an icon `rdm.svg` or `rdm.png` stored in a standard location it would read:
`Icon=rdm`

Cf. this [example `.desktop` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example).

Could you please install the icon to one of those locations and adjust the icon path in the .desktop file accordingly?
##

**Comment by uglide** [comment]
Fixed in 0.9.4

**Comment by palob** [comment]
Thanks.
