### ISSUE TITLE
windows start redis desktop manager error

### ISSUE THREAD

**Issue by seanhot** [redis/RedisDesktopManager#3621]
error comment:
Now Redis Desktop Manager is sending crash report directly to developers.
This report will help us to imporve the stability in the feature
Uploaded 61 of 61 KB.
remark: redis version is 0.8.3.3850

**Comment by uglide** [comment]
@seanhot please describe your GPU hardware

**Comment by uglide** [comment]
I didn't receive the answer from you, so I'm closing this issue.
