### ISSUE TITLE
can not delete redis connection that already added

### ISSUE THREAD

**Issue by Bismarcharis** [redis/RedisDesktopManager#3622]
I can not delete the connection that I added before, can you please guide how to do?

**Comment by cytzrs** [comment]
yah, it's awful

**Comment by cytzrs** [comment]
can anyone has some sloutions work on it

**Comment by uglide** [comment]
@DevinLi886 @cytzrs Could you please describe problem in more detail?

**Comment by uglide** [comment]
I didn't receive the answer from you, so I'm closing this issue.

**Comment by wamdy** [comment]
If I added a error host ip to connect my redis server , I can't delete this connection until the connection time out,so just wait for a moment.
