### ISSUE TITLE
Renaming key to one that exists

### ISSUE THREAD

**Issue by kashav** [redis/RedisDesktopManager#3623]
RDM Version: <br> 0.8.3.3850
Environment (OS name and version): <br> Windows 7
Redis Server Version: <br> 2.4.6

Steps to reproduce:
1. Create a key with any name/value.
2. Open the key and click `Rename`.
3. Hit `OK` without typing anything (i.e. same name as before) or use a key name that already exists. You should get the following message:

```
Can't rename key: Key with new name already exist in database
```

Error is obviously expected, but keys cannot be opened anymore and reloading DB/connection does nothing. Only solution is restarting RDM.

**Comment by uglide** [comment]
Fixed in 0.8.5 by @defmys
