### ISSUE TITLE
RDM getting crashing on big string

### ISSUE THREAD

**Issue by hellowahab** [redis/RedisDesktopManager#3625]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:
1. ... Installed on windows 10 and just run
2. ... Setup a connection and check the keys

Expected result: 
I should show the keys

Actual Result: 
Get crashed and restarted
![rdm crash](https://cloud.githubusercontent.com/assets/12432/15705800/2d78c700-280a-11e6-852d-2274ce822631.png)

**Comment by mhectorgato** [comment]
Same issue with me. Runs fine on my office Win10 desktop. When I VPN in and RDC to that system from home, RDM crashes. When I restart it (remotely), it works fine again (until the next time I RDC into it).

**Comment by uglide** [comment]
@mhectorgato issue described by you was fixed in 0.8.6

**Comment by uglide** [comment]
@hellowahab Could you please describe your GPU hardware?

**Comment by uglide** [comment]
Fixed in 0.8.8
