### ISSUE TITLE
Compatible with redis 3.2

### ISSUE THREAD

**Issue by XenTerSeO** [redis/RedisDesktopManager#3627]
RDM Version: 0.8.3
Environment (OS name and version): Windows 10
Redis Server Version: 3.2

At the moment, RedisDesktopManager does not work with the new version of radis - 3.2
Should we expect in the near future compatibility?

**Comment by uglide** [comment]
Hello @XenTerSeO
Which incompatibilities have you noticed?

RDM 0.8.4 works just fine with redis-server 3.2, but yet do not support new features like lua debugger, etc.

**Comment by XenTerSeO** [comment]
It seems that it was my problem, not RDM.
RDM 0.8.4.258 works with redis-server 3.2.1
