### ISSUE TITLE
Console - execute multiple commands 

### ISSUE THREAD

**Issue by plamendp** [redis/RedisDesktopManager#3629]
**Feature Request:**

RDM Version: 0.8.6
Environment (OS name and version): all
Redis Server Version: all

I couldn't find a way to do this in current version, maybe I overlooked it. Also couldn't find similar request. Apologize if I am posting a duplicate.

So, would be nice to be able to execute BATCH of Redis commands through the console.

For example, lets say I have this set of commands to execute, saved in a file, or just having them prepared as a text.

SELECT 7
HSET "key1" "field1" "value1"
HSET "key1" "field2" "value2"
HSET "key2" "field3" "value3"

An "Import" or similar operation can be introduced, where user selects a local file like above (or copy and paste the text) and commands are execute on currently selected host.

Regards,
Plamen

**Comment by uglide** [comment]
@plamendp Thank you for suggestion, I'll implement it in 0.9.0 (first beta is planned in September)

**Comment by uglide** [comment]
Superseded by #3529
