### ISSUE TITLE
It crashes when I try to open a key that contains a PHP array serialized with json_encode

### ISSUE THREAD

**Issue by nick2012** [redis/RedisDesktopManager#3630]
RDM Version: <0.86>
Environment (OS name and version): <Windows 7>
Redis Server Version: <2.8.24>

It crashes when I try to open a key that contains a PHP array serialized with json_encode().
Probably due to value length?!

**Comment by uglide** [comment]
Could you please provide output of command `STRLEN <your-key-here>`?

**Comment by nick2012** [comment]
127.0.0.1:6379> STRLEN 101;120
(integer) 2559842

**Comment by uglide** [comment]
Duplicate of #3526
