### ISSUE TITLE
about redis cluster

### ISSUE THREAD

**Issue by microfisher** [redis/RedisDesktopManager#3631]
i'm not sure if i did anything wrong, i try to connect to redis cluster, but the redis-desktop-manager can not automatically to change the server ip address, does this normal? thanks !

**Comment by uglide** [comment]
Redis Cluster is not supported yet. More info here: https://github.com/uglide/RedisDesktopManager/issues/3313

**Comment by microfisher** [comment]
@uglide thanks, i hope the day will come soon.
