### ISSUE TITLE
Update SSL section in Quick Start

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3635]
Add RedisLabs instructions and fix Azure instructions.
Add logos for both Cloud providers

**Comment by rhythmnewt** [comment]
Any update on the Azure instructions?

**Comment by uglide** [comment]
@dimkanewtown More info here https://gitter.im/uglide/RedisDesktopManager?at=5784e2247aeb080527b7f743

**Comment by rhythmnewt** [comment]
Thanks, rolled back to 0.8.3 and everything is working.
