### ISSUE TITLE
"operation system is not supported!" on ubuntu 14.04 based distro (mint 17)

### ISSUE THREAD

**Issue by Zincr0** [redis/RedisDesktopManager#3636]
RDM Version: 0.8.6 <br>
Environment (OS name and version): linux mint 17<br>

Steps to reproduce:
1. ... `git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm`
2. ...
   `cd src/
   ./configure`

Expected result: 

it should configure ok, mint 17 it's ubuntu 14.04 based.

Actual Result: 

Your operation system is not supported!

**Comment by uglide** [comment]
Feel free to fix configure script for linux mint :)

**Comment by uglide** [comment]
More info here #3638
