### ISSUE TITLE
Change the info command when connect

### ISSUE THREAD

**Issue by CrytisMT** [redis/RedisDesktopManager#3640]
RDM Version: 0.8.6<br>
Environment (OS name and version):win7 <br>
Redis Server Version: 0.3<br>

Steps to reproduce:

1.connect the redis

2.2016-07-05 11:44:38 : Connection: j > [runCommand] info
2016-07-05 11:44:38 : Connection: j > [runCommand] info -> response received : -ERR No permission to execute this command
1. the remote client can't run info，so rds always fail.

**Comment by uglide** [comment]
@CrytisMT Why do you have disabled `INFO` command?

**Comment by uglide** [comment]
I didn't receive the answer from you, so I'm closing this issue.
