### ISSUE TITLE
Keys in JSON viewer are wrong

### ISSUE THREAD

**Issue by elliotykim** [redis/RedisDesktopManager#3641]
RDM Version: 0.8.3-2550<br>
Environment (OS name and version): OS X 10.10.5<br>
Redis Server Version: 2.6.12<br>

Steps to reproduce:
1. add a new hash called `myhash` with a key `mydata` and the following value:
   `{"9992137151":{"customerId":9992137151,"name":9992137151}}`
2. reload the db and select the key `myhash`
3. double click the row `mydata`
4. rdm defaults to "View as: JSON" and the value is displayed incorrectly

Expected result: 
`{
    "9992137151": {
        "customerId": 9992137151,
        "name": 9992137151
    }
}`

Actual Result: 
The key is some mysterious number:
`{
    "1402202559": {
        "customerId": 9992137151,
        "name": 9992137151
    }
}`

**Comment by uglide** [comment]
@elliotykim
I've reproduced this issue. Thanks!

**Comment by uglide** [comment]
Fixed in 0.8.8

**Comment by wangtaicheng** [comment]
This problem is reproduced in version 2020.5.
Expected result:
![image](https://user-images.githubusercontent.com/6257526/98911098-08ede180-24ff-11eb-94ab-afec758516fe.png)


Actual Result:
![image](https://user-images.githubusercontent.com/6257526/98911072-fd021f80-24fe-11eb-99ba-64bbdf9e893d.png)

**Comment by uglide** [comment]
@wangtaicheng 
https://tools.ietf.org/html/rfc7159

> Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

That means that numbers greater than `9007199254740992` should be encoded as string to not lose precision. 

PS: original issue doesn't reproduce on 2020.5 version
