### ISSUE TITLE
RDM crashes constantly and is unable to submit a crash report

### ISSUE THREAD

**Issue by myokapis** [redis/RedisDesktopManager#3646]
RDM Version: <br> 0.8.3.3850
Environment (OS name and version): <br> Windows 8.1
Redis Server Version: <br> 2.8.21.01

Steps to reproduce:
1. ... Perform an action that causes the Redis Desktop Manager to crash.
2. ... Observe that the RDM crashes when trying to report the error.
   ![rdmcrash](https://cloud.githubusercontent.com/assets/12815677/16844183/bb0fa640-49a9-11e6-80fa-ef9fdb169d7e.png)

Expected result: RDM would submit a crash report successfully

Actual Result: RDM fails to submit a crash report and throws an error instead
##

**Comment by uglide** [comment]
Since 0.9.5 only crash reports for latest version is collected for Windows & Mac users
