### ISSUE TITLE
crash at 40 million grouped keys (Implement lazy-loading in connections tree)

### ISSUE THREAD

**Issue by MIKEk8** [redis/RedisDesktopManager#3647]
RDM Version: 0.8.6.270
Environment (OS name and version): Windows 8/
Redis Server Version: Redis 3

Steps to reproduce:
1. Create very big count key (40 milions) in formate
   mykey:1:(key in range 0 - 10 000 000)
   mykey:2:(key in range 10 000 001 - 20 000 000)
   mykey:3:(key in range 20 000 001 - 30 000 000)
   mykey:4:(key in range 30 000 001 - 40 000 000)
2. Open this in RDM

Expected result: 
This data:
-mykey

after open mykey
+mykey
--1
--2
--3
--4

after open mykey:1
+mykey
-+1
--- 0
//... 1-999
--- 1000
--2
--3
--4

Actual Result: 
Crash RDM after open db0

P.S.: А теперь по русски т.к. английски знаю плохо, и мог что-то не так написать.
Так как всего ключей дофига, то можно ли сделать чтобы RDM "запоминал" только запрашиваемый уровень. т.е. в моём случаи при открытии уровня mykey были только 1, 2, 3, 4 и о конкретных ключах (40 000 000) он не знал. А при попытки открыть mykey:1: выводил перве 1000 элементов и сообщение что это не всё (но там уже и краш бует нормалент).

**Comment by uglide** [comment]
@MIKEk8
Спасибо за обратную связь. 

Lazy-loading в RDM быстро можно реализовать только на стороне клиента, т.е. RDM будет все равно загружать 100500 имен ключей из базы, но рендерить в дереве будет только нужный уровень вложености.

Также возможно реализовать серверный lazy-loading для уменьшения трафика/ускорения загруpки, но для этого нужно выполнять тоже самое что я описал выше, но с помощью lua скрипта непосредственно в Redis.

На текущий момент мне сложно сказать будет ли это когда-либо реализовано. Надеюсь что у мне будет на это время и я выпущу это в 0.9.X версии.

**Comment by uglide** [comment]
Duplicate of #1875
