### ISSUE TITLE
Unable to retrieve version of RDM from within RDM

### ISSUE THREAD

**Issue by rikvdh** [redis/RedisDesktopManager#3648]
RDM Version: 0.8.6<br>
Environment (OS name and version): Windows 10 64b<br>
Redis Server Version: n/a<br>

Steps to reproduce:
1. Open Redis Desktop manager

Expected result: See version number in title bar or via some context-menu

Actual Result: none

**Comment by uglide** [comment]
Will add version to title bar

**Comment by uglide** [comment]
Fixed in 0.8.7
