### ISSUE TITLE
When RDM reconnects it doesnt reselect DB

### ISSUE THREAD

**Issue by rikvdh** [redis/RedisDesktopManager#3649]
RDM Version: 0.8.6<br>
Environment (OS name and version): Windows 10 64b<br>
Redis Server Version: 3.0.7<br>

Steps to reproduce:
1. Open RDM and connect to database
2. Open key in any other database than db 0
3. Wait for connection timeout from server
4. Click reload
5. _pow_

Expected result: Values from my selected db

Actual Result: Values from db0 (if any, otherwise blank)

**Comment by uglide** [comment]
@rikvdh Thanks for the feedback, Will fix it in 0.8.7

**Comment by uglide** [comment]
Fixed (with delay :) ) in 0.8.8
