### ISSUE TITLE
JSON view shows wrong values for long numbers

### ISSUE THREAD

**Issue by alexandar** [redis/RedisDesktopManager#3650]
RDM Version: 0.8.6.270 <br>
Environment (OS name and version): Windows [Version 10.0.10586] <br>
Redis Server Version: 3.0.501<br>

Steps to reproduce:
1. Add new key with value `{
   "Instance": 732189744448016455
   }` 
2. Click on the added key

Expected result: `{
    "Instance": 732189744448016455
}` 

Actual Result: `{
    "Instance": 732189744448016400
}`

**Comment by uglide** [comment]
Duplicate of #3641
