### ISSUE TITLE
RDM fails to start: libQt5QuickWidgets.so.5

### ISSUE THREAD

**Issue by aaabidunique** [redis/RedisDesktopManager#3654]
RDM Version: 0.8.7<br>
Environment Ubuntu 14.04: <br>
Redis Server Version: 3.2<br>

Steps to reproduce:
1. Build from source
2. cd /usr/share/redis-desktop-manager/bin
3. ./rdm

Expected result: It should start rdm

Actual Result: ./rdm: error while loading shared libraries: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory

**Comment by uglide** [comment]
@aaabidunique 
I do not provide any help with building RDM from source anymore. You can download ready-to-use deb's for ubuntu with paid subscription from redisdesktop.com. More info here https://redisdesktop.com/subscribe
