### ISSUE TITLE
Windows binaries are not signed

### ISSUE THREAD

**Issue by rpouls** [redis/RedisDesktopManager#3655]
RDM Version: 0.8.7.317
Environment (OS name and version): Windows
Redis Server Version: NA

Steps to reproduce:

Just to let you know:

When I try to install the application, symentec presents me the following message:

Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: c:\users\royp\downloads\redis-desktop-manager-0.8.7.317.exe
Location: Quarantine

https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

I know this migth not be an actual risk, but it can scare people off to use this nice application. 

Expected result: No Message

Actual Result: The Message;)
##

**Comment by uglide** [comment]
@rpouls If it's critical for you, you [can donate **$84**](https://www.bountysource.com/teams/redisdesktopmanager) to this feature and I'll buy [Comodo Code Signing Cert](http://codesigning.ksoftware.net/) to avoid such false-positive alerts

**Comment by uglide** [comment]
Starting from 0.9.1 OSX builds will be signed (**Big Thanks to [supporters](https://redisdesktop.com/subscribe)**)

**Comment by uglide** [comment]
Starting from 2019.0 Windows builds & installers will be signed (**Big Thanks to [supporters](https://redisdesktop.com/subscribe)**)
