### ISSUE TITLE
HUGE security hole: sudo and system modifications in configure script!

### ISSUE THREAD

**Issue by hackel** [redis/RedisDesktopManager#3657]
I went to build the latest version of RDM, and was absolutely **horrified** to discover the use of the sudo command in the configure script!  This is an extremely disturbing security hole.  Check this out:

```
sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
sudo apt-get update -qq
sudo apt-get install gcc-4.9 g++-4.9 gdb -y -qq
sudo rm -f /usr/bin/gcov
sudo rm -f /usr/bin/gcc
sudo rm -f /usr/bin/g++
sudo ln -s /usr/bin/gcov-4.9 /usr/bin/gcov
sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
sudo add-apt-repository --yes ppa:beineri/opt-qt${RDM_QT_VERSION}-trusty
sudo add-apt-repository --yes ppa:beineri/opt-qt${RDM_QT_VERSION}
sudo apt-get update -y
sudo apt-get install qt${RDM_QT_VERSION:0:2}base qt${RDM_QT_VERSION:0:2}imageformats qt${RDM_QT_VERSION:0:2}tools \
sudo apt-get install automake libtool libssl-dev \
sudo yum install libssh2 libssh2-devel qt5-qtbase qt5-qtsvg-devel \
```

So you're attempting to fuck with people's systems, without even a WARNING, messing with files in /usr outside of the package manager's control.  What the hell is going on here?  It seems like you are new to software development, perhaps, but this is NOT the way to go about accomplishing what you are trying to.

First off, you simply tell people what the build dependencies are and let _them_ worry about meeting them, adding whatever PPAs and installing whatever packages may be required.

Second, if you require the gcc-4.9 toolset, the whole point of your configure script is to detect its presence and use them appropriately.  Don't go deleting files in people's /usr directory!  Seriously, I have half a mind to report this project for spreading damaging malware.

Third, look into using autotools and automake.  It will make your life a whole lot easier.

It looks like you just still have a lot to learn about software development—you probably waste too much of your time on proprietary operating systems trying to make your application compatible with them.  Don't.  Let the proprietary Windows and Mac users pay for their own software.  Focus your efforts on creating the best open source Redis client for open source operating systems you can.

**Comment by uglide** [comment]
Hello @hackel 

Let's review configure script line-by-line.
1. https://github.com/uglide/RedisDesktopManager/blob/633281f8511f901a77ab1f9295bbe14a238b714c/src/configure#L27-L38
   It's the most shitty code in configure script which was copypasted from travis build script where **fucking** system is OK because it's VM. Yes, **this code is shitty**. But it's for Ubuntu 12 which has almost died and I'll drop support for it in near feature.
2. https://github.com/uglide/RedisDesktopManager/blob/633281f8511f901a77ab1f9295bbe14a238b714c/src/configure#L41-L57
   **Yes, configure script shouldn't install deps**, but **people want easy to use onle-liners to build RDM**, I can move dependencies installation to separate script called `install_deps`, but who will need it? **Nobody**, Why people should run two scripts instead of one?

> It looks like you just still have a lot to learn about software development—you probably waste too much of your time on proprietary operating systems trying to make your application compatible with them. Don't. Let the proprietary Windows and Mac users pay for their own software. Focus your efforts on creating the best open source Redis client for open source operating systems you can.

### If you see shit in OSS project - make the world better, just **FIX IT**.

**Comment by hackel** [comment]
Hey, I never said _you_ had to fix this, and I completely agree it would be better if I fixed it myself, but since that is not something I have time to do at the moment (nor the inclination to do in a way that would maintain compatibility with proprietary operating systems), I am at least reporting the issue.  It is still a very serious issue and it is inappropriate for you to close it until it is actually fixed.

I suppose this is just a difference of opinion, but I don't believe building software should be reduced to an easy one-liner.  People need to understand what they are doing, what those dependencies are, etc. or else they should just be using the binary distribution.  It is normal for there to be a build script for CI systems separate from the configure script, so in that case I do think that two scripts makes complete sense and would be a great solution.  For individual users, simply posting the build-deps in the build instructions/readme should be sufficient.

Let me just repeat from an end-user's perspective just to let this sink in—you are attempting to install unknown binary code on my system, with root access, without even a warning about what you are doing.  This code is coming from some random PPAs that I have never heard of, and for all I know could contain a virus, could steal all of my personal information, install rootkits, or do anything else it pleases.  You're also possibly leaving my system in an unstable state by modifying files in /usr that might make future upgrades fail.  I'm sure you can understand why this is frightening.

Also, I just want to add, that this is a great piece of software and I thank you for all the time you've put into developing it.  I'm sorry for being overly harsh in the initial issue description.  I just would like to see the software succeed, and to be included in Debian/Ubuntu as well.
