### ISSUE TITLE
Incorrect rendering of some key names

### ISSUE THREAD

**Issue by rcmdh** [redis/RedisDesktopManager#3666]
RDM Version: v0.8.7.322<br>
Environment (OS name and version): Windows 7 Professional<br>
Redis Server Version: 2.8.9 <br>

Steps to reproduce:
1. Use separator : and make a key 2016:01:01
2. View 2nd level of nesting in UI

Expected result: 
db0
  -> 2016
      -> 01
          () 2016:01:01

Actual Result: 
db0
  -> 2016
      -> 201
          () 2016:01:01

**Comment by uglide** [comment]
Fixed in 0.8.8
