### ISSUE TITLE
Impossible to upgrade to latest version

### ISSUE THREAD

**Issue by Maykonn** [redis/RedisDesktopManager#3670]
RDM Version: 0.8.3-120_amd64.deb
Environment (OS name and version): Ubuntu 14.04
Redis Server Version: Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9

Steps to reproduce:
1. Have the 0.8.3-120_amd64.deb version installed
2. Install like described here: http://docs.redisdesktop.com/en/latest/install/#build-from-source with some changes(the line source /opt/qt55/bin/qt55-env.sh && make && sudo make install) not works, but run the command returned by ./configure result.
3. When I try to launch the app, the message to upgrade still appears on screen. If I close the message a black screen appears and the old version not works more.

Expected result: Current version working fine

Actual Result: Not working

**Comment by uglide** [comment]
Hello @Maykonn 
Please run `redis-desktop-manager` from terminal and provide here output. Thanks!

**Comment by Maykonn** [comment]
Yes, is running! Thanks!
