### ISSUE TITLE
Remove opengl32sw.dll and Copy this dll to RDM installation folder

### ISSUE THREAD

**Issue by yangjiebeijing** [redis/RedisDesktopManager#3671]
RDM Version: the 8.,7
Environment (OS name and version): windows 64

Remove opengl32sw.dll and Copy this dll to RDM installation folder

where is this dll？
please give me a link，thanks

**Comment by uglide** [comment]
https://github.com/uglide/RedisDesktopManager/tree/5f99aa22aa84dc55b5c9858de28d68facd1c58b7/build/windows/installer/resources/rdp_fix

**Comment by yangjiebeijing** [comment]
thx
