### ISSUE TITLE
suggestion:show key bytes length  and value bytes length

### ISSUE THREAD

**Issue by lizongbo** [redis/RedisDesktopManager#3677]
RDM Version:0.8.8。32 <br>
Environment (OS name and version): Mac OSX<br>
Redis Server Version: 3.0<br>

Steps to reproduce:
1. open rdm, connet to redis server
2. open redis data ,show row's key and value

Expected result: suggestion: show key bytes length  and value length,  then can estimate data size quickly. 

Actual Result: don't show key bytes length and value bytes length.

**Comment by uglide** [comment]
Hello @lizongbo 
Do you need length in bytes for STRINGS or for all types?

**Comment by lizongbo** [comment]
all types is perfect :)

**Comment by uglide** [comment]
Implemented and will be available in 0.8.8-beta2
