### ISSUE TITLE
Bug:don't show zset's score and hash key for rdm v0.8.8.32

### ISSUE THREAD

**Issue by lizongbo** [redis/RedisDesktopManager#3679]
RDM Version: 0.8.8.32<br>
Environment (OS name and version): Mac OSX<br>
Redis Server Version: 3.0<br>

Steps to reproduce:
1. open rdm 
2. connect to redis server
3. view zset score

Expected result: row values show correctly.

Actual Result:  score value don't show :(

![bug001](https://cloud.githubusercontent.com/assets/1670666/17798629/77995bb8-6605-11e6-820e-56dc0507c7f8.png)

**Comment by uglide** [comment]
@lizongbo Thanks for the feedback

**Comment by katuknow** [comment]
hi @lizongbo,

I checked reported issue on Mac OSX and score value displayed correctly. Can you add more details? 
<img width="1006" alt="zscore_bug" src="https://cloud.githubusercontent.com/assets/7568825/17813888/e8898642-6635-11e6-94af-2e48166874db.png">

**Comment by lizongbo** [comment]
@katuknow  I restart rdm app and see the score value displayed correctly just now , this is my second time to start rdm, maybe  it only happend when install new version rdm  and the first start rdm :) .

**Comment by lizongbo** [comment]
@uglide  I restart rdm today many times ,I found redis hash's key or zset's score not displayed correctly sometimes but not every time,I can't guess why.

**Comment by uglide** [comment]
Fixed in 0.8.8RC
