### ISSUE TITLE
RDM 0.8.7-1 sets off Antivirus Alarm around d3dcompiler_47.dll

### ISSUE THREAD

**Issue by dedayoa** [redis/RedisDesktopManager#3685]
RDM Version: 0.8.7-1
Environment (OS name and version): Windows 10
Redis Server Version: N/A

Steps to reproduce:
1. Windows 10, 360 Security Antivirus with Avast and BitDefender Engine Activated
2. Downloading RDM, a "Trojan" alert kicks in. 
3. Ignoring and trying to install, it fails (block by antivirus) around the installation of d3dcompiler_47.dll.

I reported issue via twitter, then tried to install 0.8.7 to see if I'd have the same issue, but it installed ok..I even saw the install of d3dcompiler... install OK.

Kindly confirm that 0.8.7-1 (windows installer) has not been compromised.

Expected result: Successful install

Actual Result: Failed install due to antivirus block on suspected Trojan/Virus

**Comment by uglide** [comment]
Have answeared in gitter chat
