### ISSUE TITLE
Build fail on OSX

### ISSUE THREAD

**Issue by p-golovin** [redis/RedisDesktopManager#3688]
Got error on build in QtCreator:
[../bin/osx/debug/ui/ui_connection.h] Error 1

**Comment by uglide** [comment]
Which revision are you trying to build? Please copy paste here compilation log

**Comment by p-golovin** [comment]
Версия системы:    OS X 10.11.4 (15E65)
Версия Kernel:    Darwin 15.4.0

Xcode Version 7.3.1 (7D1014)

Desktop Qt 5.7.0 clang 64bit

> git status
> On branch 0.8.0
> Your branch is up-to-date with 'origin/0.8.0'.

Compilation log:
OBJECTS_DIR: Cannot access directory '../bin/osx/debug/obj'
DESTDIR: Cannot access directory '../bin/osx/debug'
PRECOMPILED_DIR: Cannot access directory '../bin/osx/debug/obj'
rcc: Cannot access directory '../bin/osx/debug/obj'
rcc: Cannot access directory '../bin/osx/debug/obj'
moc_header: Cannot access directory '../bin/osx/debug/obj'
.....
moc_source: Cannot access directory '../bin/osx/debug/obj'
....
uic: Cannot access directory '../bin/osx/debug/ui'
[../bin/osx/debug/ui/ui_connection.h] Error 1

**Comment by uglide** [comment]
@p-golovin have you used `sudo` to clone RDM repo? looks like your user doesn't have write permissions to the directory with RDM sources

**Comment by uglide** [comment]
Please feel free to ask  questions about building issues in gitter chat.
