### ISSUE TITLE
Windows Server a black screen

### ISSUE THREAD

**Issue by cocodroid** [redis/RedisDesktopManager#3689]
RDM Version: 0.8.7.317<br>
Environment (OS name and version): Windows Server2008<br>
Redis Server Version: 3.0<br>

Steps to reproduce:
1. ...
2. ...
3. ...

![qq 20160825145821](https://cloud.githubusercontent.com/assets/11642752/17959642/406ff6e6-6ad4-11e6-924e-4919036c0a68.png)

Expected result: 

Actual Result:

**Comment by uglide** [comment]
You need to change RDM settings and install RemoteFX. More info here https://github.com/uglide/RedisDesktopManager/issues/3626
