### ISSUE TITLE
Tree item bug

### ISSUE THREAD

**Issue by yangjq4** [redis/RedisDesktopManager#3698]
RDM Version: 0.8.7.322<br>
Environment (OS name and version): Win7<br>
Redis Server Version: 2.8.24<br>

Expected result: 

Actual Result: 
![image](https://cloud.githubusercontent.com/assets/14730063/18160424/04de7102-7060-11e6-8b62-49e4fa0ecd01.png)

**Comment by uglide** [comment]
@yangjqun It's time to update your RDM to 0.8.8
This issue is already fixed.
