### ISSUE TITLE
String keys filled with PHP serialized data shown as empty string

### ISSUE THREAD

**Issue by plamendp** [redis/RedisDesktopManager#3699]
RDM Version: 8.8.*
Environment (OS name and version): Windows, Linux
Redis Server Version: 3.*

Steps to reproduce:

Create a new STRING key having this value:

`session_domain|s:20:"lms.xxxxxxxxxxxxx.com";first_time_language|b:1;multidomain_client|a:3:{s:6:"client";b:0;s:9:"logged_in";b:0;s:4:"host";s:24:"lms.xxxxxxxxxx.com";}current_lang|s:7:"english";_lang|s:2:"en";saml_current_id_account|s:1:"1";domainbranding|a:2:{s:4:"host";s:20:"lms.xxxxxxxxxxxx.com";s:9:"logged_in";b:0;}`

Expected result: 

When I open the key to see the value properly unserialized OR as plain text by default

Actual Result: 

See screenshots

![step1](https://cloud.githubusercontent.com/assets/2060234/18167415/22c90d5a-7059-11e6-8ea1-70a898897981.png)

![step2](https://cloud.githubusercontent.com/assets/2060234/18167420/27cb6f32-7059-11e6-940d-4cbdf7062a80.png)
##

**Comment by uglide** [comment]
Build-in formatter will be removed and replaced by native formatter https://github.com/RedisDesktop/rdm-native-value-formatters/issues/7
