### ISSUE TITLE
zset score sort not correctly

### ISSUE THREAD

**Issue by lizongbo** [redis/RedisDesktopManager#3700]
RDM Version: 0.8.8.33<br>
Environment (OS name and version): Mac OSX<br>
Redis Server Version: 3.0<br>

Steps to reproduce:
1. insert many score
2. open rdm ,show zset data
3. click score row title ,sort not correctly

Expected result: sort not correctly

Actual Result: zero value not sorted.

maybe sorted as string type compare,but not double value type compare.

![rdmbug2016090301](https://cloud.githubusercontent.com/assets/1670666/18224391/20f52ea6-7206-11e6-92fd-5c59958f2e40.png)

**Comment by uglide** [comment]
Fixed in 0.9.0-alpha1
