### ISSUE TITLE
occur "0Xc000007b" interruption

### ISSUE THREAD

**Issue by 970655147** [redis/RedisDesktopManager#3701]
RDM Version: 0.8.8 & 0.8.7
Environment (OS name and version): win7
Redis Server Version: <br>

Steps to reproduce:
1. loss "msvcp140.dll", then I download specified dll
1. loss "VCRuntime140.dll", then I download specified dll
2. run "rdm.exe", occur an interruption with "0Xc000007b"

Expected result: run normally 

Actual Result: got an interruption

---

hum, why such a thing happened, and how to fix it ?
thank you, look forward to your reply !

**Comment by uglide** [comment]
Hello, you need to update your win7 and reinstall msvc14 x86 runtime

**Comment by 970655147** [comment]
thank you !
