### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by jmwri** [redis/RedisDesktopManager#3702]
RDM Version: 0.8.0<br>
Environment (OS name and version): El Capitan 10.11.6<br>

I am following the steps found [on the docs](http://docs.redisdesktop.com/en/latest/install/#build-from-source).

I have cloned the repo, and installed Qt Creator and have Xcode installed.

I also ran repo/src/configure.

When I open rdm.pro in Qt it opens fine, but when I try to build the following error occurs.

> :-1: error: No rule to make target `/Users/jim/RedisDesktopManager/3rdparty/gbreakpad/src/client/mac/build/Release/Breakpad.framework', needed by`../bin/osx/debug/rdm'.  Stop.

Running repo/src/configure generates:

> Warning: coreutils-8.25 already installed
> xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
> xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
> xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
> Error: libssh2 1.7.0 already installed
> Warning: libssh2-1.7.0 already installed

How can I fix these errors?

**Comment by uglide** [comment]
Looks like you forgot to add `--recursive` to `git clone` command.

**Comment by jmwri** [comment]
Thanks @uglide, I can get it to build now! Although I can't find the built file? Would you be able to direct me to the runnable file please?

**Comment by uglide** [comment]
Check `bin` folder

**Comment by jmwri** [comment]
How can I build so that I do not need to run it in terminal?

**Comment by scoutman57** [comment]
i was wondering the same thing about running in terminal.

**Comment by revolter** [comment]
@jmwri, @scoutman57, Does running [`macdeployqt`](http://doc.qt.io/qt-5/osx-deployment.html#the-mac-deployment-tool) helps?

**Comment by uglide** [comment]
@revolter you are contributor, so just download ready-to-use binary for Mac from redisdesktop.com ;)

**Comment by revolter** [comment]
First of all, it doesn't allow me. And secondly, that can't be called a contribution, I want to fix at least one real issue.

**Comment by udoless** [comment]
I used --recursive flag, but I still get same error.

**Comment by h4ckroot** [comment]
me to !

**Comment by BraveTang** [comment]
i can't built it !!

**Comment by bpzhang** [comment]
No rule to make target `../3rdparty/qredisclient/3rdparty/hiredis/read.c', needed by `../bin/osx/debug/obj/read.o'.  Stop.
what‘s wrong ??
