### ISSUE TITLE
On windows 10 x64 ,the "value" don't show in panel

### ISSUE THREAD

**Issue by iminto** [redis/RedisDesktopManager#3708]
RDM Version: 0.8.8.384
Environment (OS name and version): win 10,x64
Redis Server Version:3.0.501

Steps to reproduce:

1.when I set a key:value with "name1":"zhangfei"

2.Using redis-cli's "get" commond ,it's ok and show the full value,but in rdm ,the value do not show in the right panel.

3.Then I tried the chinese and english,and founded that  only english words do not show in the panel.

4.The 0.8.7 version is ok.

![qq 20160908135947](https://cloud.githubusercontent.com/assets/284101/18338605/bab486a8-75cc-11e6-8d61-3cb8cd986526.jpg)
##

**Comment by uglide** [comment]
For some reason I cannot reproduce your problem:
![image](https://cloud.githubusercontent.com/assets/1655867/18342363/2d33f4f4-75b7-11e6-9c77-9532903de41e.png)

Could you please specify your GPU info?

**Comment by iminto** [comment]
I reinstalled the RDM, but it is useless。
Maybe it is just a specific example.
My GPU is NVIDIA GeForce 310M

**Comment by uglide** [comment]
Try to use latest 0.9 build https://ci.appveyor.com/project/uglide/redisdesktopmanager/branch/0.9/artifacts

**Comment by iminto** [comment]
I'm hard to say that 0.9 version having  the same problem.
My computer is really too old,so i have to use the 0.8.7 version.

**Comment by uglide** [comment]
It's Qt glitches on windows, nothing I can do about. Hopefully it will work better after migration to Qt 5.8
