### ISSUE TITLE
app/app.h:7:22: 致命错误：googlemp.h：没有那个文件或目录

### ISSUE THREAD

**Issue by miaogr86** [redis/RedisDesktopManager#3719]
fedora 22 执行 qmake-qt5 && make 报如下错误：
app/app.h:7:22: 致命错误：googlemp.h：没有那个文件或目录

**Comment by uglide** [comment]
Looks like you forgot to add `--recursive` flag to `git clone` command

**Comment by miaogr86** [comment]
git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.8 rdm && cd ./rdm
