### ISSUE TITLE
Import Connections need overwrite repeated connections config

### ISSUE THREAD

**Issue by lizongbo** [redis/RedisDesktopManager#3721]
RDM Version: 0.8.8<br>
Environment (OS name and version): Mac OSX<br>
Redis Server Version: 3.2.3<br>

Steps to reproduce:
1. open rdm ,export connections to json file
2. edit json file add more connection config
3. import connections the json file.

Expected result:  overwrite old connections

Actual Result: show repeated connections 

![rmdbug201609191739](https://cloud.githubusercontent.com/assets/1670666/18627895/1f4b4b3a-7e90-11e6-8562-ed72b9bf2174.png)
##

**Comment by uglide** [comment]
Duplicate of #3516
