### ISSUE TITLE
how to connect AWS ElastiCache Redis using rdm?

### ISSUE THREAD

**Issue by xujiajun** [redis/RedisDesktopManager#3723]
hi,

RDM Version: <br>0.8.8.33

Environment (OS name and version): <br> mac os x 10.11.6

Redis Server Version: <br>2.84

Expected result: 
 connect AWS ElastiCache Redis using rdm SSH Tunnel

Actual Result: 

can't  connect AWS ElastiCache Redis 

someone can give me some help? thanks.

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/quick-start/#how-to-connect-to-redis-elasticache-through-ec2

**Comment by MatthewHouseman** [comment]
I need to know how to do this as well.  Can you send me the same email?  Thanks...

**Comment by printedheart** [comment]
Or better yet answer here or in the documents

**Comment by tclancy** [comment]
Is there a reason not to post the answer here for others with the same issue?

**Comment by uglide** [comment]
This information was added to documentation long time ago http://docs.redisdesktop.com/en/latest/quick-start/#how-to-connect-to-redis-elasticache-through-ec2

**Comment by GenZodd** [comment]
FYI. The blog used for this is now dead so the documentation no longer provides information on how to get connected to AWS Elasticache.

**Comment by uglide** [comment]
@GenZodd thanks for the feedback. Documentation was updated.

**Please note that a VPN connection to your VPC is the best option.** https://docs.rdm.dev/en/latest/quick-start/#aws-elasticache
