### ISSUE TITLE
Brew Cask not updating

### ISSUE THREAD

**Issue by lenovouser** [redis/RedisDesktopManager#3727]
RDM Version: **-**
Environment (OS name and version): **macOS**
Redis Server Version: **-**

Steps to reproduce:

For some reason I am not getting the latest update of RDM when using [`brew cask`](https://caskroom.github.io/search) - here is their [config file](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rdm.rb)

Expected result: 
Getting updates

Actual Result:
Not getting updates

**Comment by uglide** [comment]
Currently you need subscription to download RDM dmg images. More info here https://redisdesktop.com/subscribe

**Comment by lenovouser** [comment]
Hm. Okay 😞  - thanks for the info though 👍
