### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nicolangr** [redis/RedisDesktopManager#3736]
RDM Version: 0.8.8<br>
Environment (OS name and version):  Linux Mint 18<br>
Redis Server Version: <br>

Steps to reproduce:
1. After 10 minutes RDM suddenly crash
##

**Comment by maxgalbu** [comment]
bigolo

**Comment by uglide** [comment]
@maxgalbu What ? :)

**Comment by maxgalbu** [comment]
@uglide colleagues things :)
