### ISSUE TITLE
Save button is hidden on Value editor tab

### ISSUE THREAD

**Issue by katuknow** [redis/RedisDesktopManager#3737]
RDM Version: <br>0.9.0.38
Environment (OS name and version): <br> Mac OS
Redis Server Version: <br>

Steps to reproduce:
1. Run RDM
2. Load any DB
3. Click on key name
4. Edit any value
5. Save button isn't there

Expected result: 
Press Save button and save value 
Actual Result: 
Save button is hidden (see screenshot)
<img width="1213" alt="00000024" src="https://cloud.githubusercontent.com/assets/7568825/19181046/0d001b90-8c73-11e6-9dc8-6b47fab846c1.png">
##

**Comment by revolter** [comment]
Weird, the `Save` button is showing for me when building the `0.9` branch.
