### ISSUE TITLE
Value read-only formatters are shown when user adds new row

### ISSUE THREAD

**Issue by katuknow** [redis/RedisDesktopManager#3739]
RDM Version: <br> 0.9.0.38
Environment (OS name and version): <br> Mac OS 
Redis Server Version: <br>

Steps to reproduce:
1. Run RDM and load any DB
2. Click on any key
3. Press Add row button
4. Check that HEX TABLE or PHP Serializer are in dropdown 

Expected result: read-only value formats are not available during row creation

Actual Result:  read-only value formats are shown 
##

**Comment by uglide** [comment]
Formatters combobox was removed from Add Key dialog.
