### ISSUE TITLE
Non ascii node name is garbled in tree view

### ISSUE THREAD

**Issue by truebit** [redis/RedisDesktopManager#3744]
- RDM Version: 0.8.8
- Environment (OS name and version): Mac OS X 10.11, 10.12
- Redis Server Version: not related
#### Steps to reproduce:
1. add following key-value for example:
   set test:测试:test1 test
   set test:测试:test2 test
2. open in RDM to see the tree view
#### Expected result:

 "测试" is should be displayed.
#### Actual Result:

 "测试" is garbled

**Comment by uglide** [comment]
Duplicate of #3695
