### ISSUE TITLE
rdm: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by rdm)

### ISSUE THREAD

**Issue by Somebi** [redis/RedisDesktopManager#3745]
RDM Version:0.8.0 and latest 0.9.0-alpha1
Environment (OS name and version): Ubuntu 16.04
Redis Server Version: none

For the first time program is launched without errors and when trying to launch second time in another terminal it throws errors.
Guide used from http://docs.redisdesktop.com/en/latest/install/

Steps to reproduce:
1. Launch and close few times
2. Then open new terminal and launch again

Expected result: open program

Actual Result: 

beck@beck:/$ rdm 
rdm: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by rdm)
rdm: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version`Qt_5' not found (required by rdm)
rdm: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by rdm)
rdm: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version`Qt_5' not found (required by rdm)
rdm: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by rdm)
rdm: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version`Qt_5' not found (required by rdm)
beck@beck:/$

**Comment by uglide** [comment]
Modify `rdm.sh` and add sourcing of qt-env.sh

**Comment by ghost** [comment]
How I can do this?

**Comment by Jorgevillada** [comment]
In ubuntu (16.04), **rdm.sh** is located in /usr/share/redis-desktop-manager/bin and **qt-env.sh** is located in /opt/qt56/bin/qt56-env.sh

You can add the following line.

source /opt/qt56/bin/qt56-env.sh

or modify LD_LIBRARY_PATH with /opt/qt56/lib/
export LD_LIBRARY_PATH="**/opt/qt56/lib/**":$LD_LIBRARY_PATH

**Comment by JIucToyxuu** [comment]
@Jorgevillada  I try do how you say, but this not help to me. Errors about require Qt5 still.

**Comment by Jorgevillada** [comment]
@JIucToyxuu Try verifying if qt is installed in /opt/, because when it runs ./configure, it installs it (https://github.com/uglide/RedisDesktopManager/blob/0.9/src/configure#L39) otherwise, run ./configure again.

Check if /opt/qt56/bin/qt56-env.sh exists.

**Comment by JIucToyxuu** [comment]
@Jorgevillada Qt installed on my PC. Re-configure help me repair RDM. Thanks.
