### ISSUE TITLE
Minimal Redis Sentinel support

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#3746]
> For me the most important feature is that we can connect to a Sentinel, and we're using a Redis-Instance that is writable. Current situation:
> 
> Add all Redis-servers to RDM
> Connect to first server
> Try to add key, but get an error because the node is read-only
> Connect to next server
> Try to add key, this time it succeeds, because (by luck) we connected to the server that is currently the master.
> Desired situation:
> 
> Add sentinel(s) to RDM (so instead of a Redis-Server entry, this would become a Sentinel-entry)
> Connect to "sentinel", ask for R/W server
> Try to add key
> I've read the above, and while I agree that everything proposed above is a great addition to RDM, I also believe that maybe the core functionality (auto-select a R/W server using sentinel) would be the first step, and the other steps (GUI tree representation of sentinel and masters/slaves as well as GUI commands that trigger sentinel commands) would follow in later releases. But that's just my 2 cents :).

Full Sentinel support issue: https://github.com/uglide/RedisDesktopManager/issues/3399#issuecomment-137402601
##

**Comment by obriat** [comment]
A support for role detection could be useful : indicate if the server is a Master, Slave, sentinel, if it's read only, if it's part of a shard or a cluster...

For example :
- if it's a sentinel, use a specific icon and display the elected Master : `ROLE`
- if it's a master, use a specific icon and show its slaves: `INFO Replication`.
- if it's a slave, use a specific icon and  show its master: `INFO Replication`.
- A global check could be send to validate the consistency of the whole MASTER/SLAVE/SENTINEL setup.
- For sentinels: do not allow key display, but only console launch.
 
Bonus: allow a auto discovering of the configuration when adding a sentinel: add other sentinels, the master then the salves ?
