### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: charts

### ISSUE THREAD

**Issue by Mirocow** [redis/RedisDesktopManager#3751]
RDM Version: branch 0.9<br>
Environment (OS name and version): 10.12<br>
Redis Server Version: <br>

I have error when i build with qt creator
"Project ERROR: Unknown module(s) in QT: charts"

Expected result: 

Actual Result:

**Comment by uglide** [comment]
Use pre-built dmg instead https://github.com/uglide/RedisDesktopManager/releases/download/0.9.0-alpha2/redis-desktop-manager-0.9.0.40.dmg

**Comment by damirnovosel** [comment]
I get same error message on CentOS 7.2
Any suggestion?

Thanks in advance, Damir

**Comment by uglide** [comment]
@damirnovosel  Just install Qt 5.9 from official site and build using it
