### ISSUE TITLE
Is it possible to set the default viewer?

### ISSUE THREAD

**Issue by natiki** [redis/RedisDesktopManager#3752]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: N/A<br>

Is it possible to set the default View As? I always want to view nodes as JSON and currently each time I navigate I have to select this from the drop down as it defaults to seemingly the last item in the drop down list.

![image](https://cloud.githubusercontent.com/assets/4738140/19754561/47cd76f4-9c5a-11e6-90a3-f45a593ac944.png)
##

**Comment by uglide** [comment]
Currently it's not possible but I will add it as connection advanced setting in 0.9.0-beta

**Comment by uglide** [comment]
Last selected value is memorized in RDM so no need to implement this feature
