### ISSUE TITLE
RDM 0.9.0-alpha2 crash when executing flushall

### ISSUE THREAD

**Issue by koybe** [redis/RedisDesktopManager#3757]
RDM Version: 0.9.0-alpha2<br>
Environment (OS name and version): unubtu 16.0.4LTS<br>
Redis Server Version: 3.0.6<br>

Steps to reproduce:
1. open a connection
2. open the connection's terminal

3.type the command: flushall, type enter

Expected result: clear all the cache

Actual Result: rdm crash and the cache is still alive

**Comment by uglide** [comment]
Fixed in 0.9.0-alpha5
