### ISSUE TITLE
RDM Shows Key Values for One Key Only

### ISSUE THREAD

**Issue by adstechnetwork** [redis/RedisDesktopManager#3758]
RDM Version: 0.9.0.40<br>
Environment (OS name and version): OSX 10.11.6 <br>
Redis Server Version: 3.0.7<br>

Steps to reproduce:

1. ... Click on a Key in the tree and see the value in a new tab.

2. ... If you close the tab and try another key, it will open another tab and show you.

3. ... If you don't close the tab, and click on another key, it will never show you another key but remains stuck on the first one.

Expected result: 

Actual Result:

**Comment by adstechnetwork** [comment]
So how do I get someone to look at this?  I'm a paying subscriber and this is a repeatable issue.

**Comment by cars10** [comment]
Same problem with 0.9.0_alpha3-1 on Archlinux

**Comment by uglide** [comment]
@adstechnetwork use more stable 0.8.8 for now

**Comment by uglide** [comment]
Fixed in 0.9.0-alpha4
