### ISSUE TITLE
Problem with read Java Objects

### ISSUE THREAD

**Issue by lsaletta** [redis/RedisDesktopManager#3763]
RDM Version: 0.9.0.496
Environment (OS name and version): Windows 7
Redis Server Version: 3.2.4

hi!, in my cache Redis I'm storing data serialized by the Spring Data Redis library, you can read the serialized object from Redis Desktop Manager? For example: a Java Long and more complex objects?

Attached image:
![rdm-value](https://cloud.githubusercontent.com/assets/9202654/20098210/f703fbf0-a5b2-11e6-96a9-d96d4abd03c0.png)

Regards, Luca.
Thank you.

**Comment by uglide** [comment]
@lukwolf I can implement native value formatter for RDM alpha 4
More info:
https://github.com/RedisDesktop/rdm-native-value-formatters
https://github.com/uglide/RedisDesktopManager/pull/3781
