### ISSUE TITLE
build error on ubuntu 14.04 32bit machine

### ISSUE THREAD

**Issue by jacquesjacques** [redis/RedisDesktopManager#3768]
RDM Version: <br>
Environment (ubuntu 14.04   32bit): <br>
Redis Server Version: <br>

Steps to reproduce:

1. cloned the source, ran ./ configure
git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm

2. on running source - this error: 'sys_mmap' was not declared in this scope
../3rdparty/greakpad//src/common/memory.h: 123:59 error: 'sys_mmap2' was not declared in this scope
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^
3. has no one had this issue before?, anyone know a fix?

Expected result: 

Actual Result:

**Comment by uglide** [comment]
Try to reclone rdm repo
