### ISSUE TITLE
windows console trim long lines 

### ISSUE THREAD

**Issue by limin112** [redis/RedisDesktopManager#3769]
RDM Version: 0.8.7
Environment (OS name and version): windows
Redis Server Version: <br>

Steps to reproduce:

1. go into windows console mode

2. type something until exceeds one line

3. .press ”enter“

Expected result: 
the command should executed
Actual Result: 
the command was wrong. if I resize the window large enough, same command in one line will be executed
![i0p_6ox p5et q om516v](https://cloud.githubusercontent.com/assets/1990398/20296787/bfe420ba-ab47-11e6-94d8-8679d1e98732.png)

**Comment by uglide** [comment]
Already fixed in 0.9.0-alpha3
