### ISSUE TITLE
some redis data "value" field shows with background color on windows

### ISSUE THREAD

**Issue by wuceyang** [redis/RedisDesktopManager#3770]
the data with data type "set" and "zset" has the same problem like this:
![1](https://cloud.githubusercontent.com/assets/1538757/20332685/8db739d2-abe8-11e6-908f-efbfc6c8356b.png)
![2](https://cloud.githubusercontent.com/assets/1538757/20332712/cc023106-abe8-11e6-9a8f-bcc2a81a0dea.png)

if i select all string in "value" field and copy to a blank document with other editor,it's shown and is readable.

**Comment by katuknow** [comment]
Could you provide examples of values?
