### ISSUE TITLE
Feature req: mark connection read-only.

### ISSUE THREAD

**Issue by zladuric** [redis/RedisDesktopManager#3771]
#RDM Version: 0.8.8+
Environment (OS name and version): Ubuntu 16.04 x64
Redis Server Version: any

I'd like to be able to mark a connection "read only". Any attempt to add or modify content would not work, you could only _read_ results from Redis.

I end up changing the stuff on a wrong connection, and sometimes I even use RDM to connect to `production` (yes, yes, I know!). I think this would be a nice addition.

**Comment by uglide** [comment]
Starting from version 6.0 redis-servers will support ACL which allows disabling any dangerous commands, so no need to do it in RDM.  More info here https://redis.io/topics/acl
