### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by h4ckroot** [redis/RedisDesktopManager#3773]
RDM Version: <0.8>
Environment (OS name and version): <Linux Mint 18>

Steps to reproduce:

1. git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm

Expected result: 
 Successful clone !
Actual Result: 

fatal: unable to access 'https://chromium.googlesource.com/breakpad/breakpad/': Failed to connect to chromium.googlesource.com port 443: Connection timed out

**Comment by jlongman** [comment]
It just worked for me - a transient network or host problem maybe?

**Comment by h4ckroot** [comment]
I just tried again and same issue !.

**Comment by h4ckroot** [comment]
It just worked ! :) ... thanks alot.
