### ISSUE TITLE
RDM 0.8.8.384 crashes after 10 Sec. on Windows 7

### ISSUE THREAD

**Issue by naptoon** [redis/RedisDesktopManager#3774]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): Wiondows 7<br>
Redis Server Version: 3.2.3<br>

Steps to reproduce:

1. Start RDM

2. Wait 10 seconds in active window or try to work in it

3. crashes each time after 10 seconds

Expected result: no crash

Actual Result: crash

**Comment by uglide** [comment]
I do not maintain 0.8.8 version any more. Please wait for stable 0.9 build
