### ISSUE TITLE
Why does RDM show up with a black GUI when displayed through a Remote Desktop Connection?

### ISSUE THREAD

**Issue by nick2012** [redis/RedisDesktopManager#3775]
RDM Version: 0.8.8
Environment (OS name and version): Windows 7 x64
Redis Server Version: unknown

Steps to reproduce:

1. Open RDM from a Remote Desktop PC.

Expected result: 
No black screen. :)

Actual Result: 
http://imgur.com/a/BjbPL

**Comment by uglide** [comment]
RDM requires direcx, thats why you need to enable true color in RDP settings.

**Comment by marbx** [comment]
@uglide Thank you!
RDM Version: 0.8.8

**Problem**
Black screen instead of Welcome tab on Remote Desktop Connection Manager (from Windows 7 to Windows 7).

**Solution**
In "Remote Desktop Connection Manager", set 
"Display Settings" / "Remote Desktop Settings" / "Color Depth" to 32
