### ISSUE TITLE
key tree is not normal in the left panel

### ISSUE THREAD

**Issue by taotao365s** [redis/RedisDesktopManager#3777]
RDM Version: 0.8.8<br>
Environment (OS name and version): win7 x64 <br>
Redis Server Version: 3.0 <br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 
key tree is not normal in the left panel

Actual Result: 
![image](https://cloud.githubusercontent.com/assets/1212932/20695503/86067236-b627-11e6-8897-be540ee3ff07.png)

![image](https://cloud.githubusercontent.com/assets/1212932/20695508/9bae08d8-b627-11e6-8d72-92f0185a83e2.png)

**Comment by uglide** [comment]
It's already fixed in 0.9.0-alpha3
