### ISSUE TITLE
I'm confused about the behavior of these two buttons.

### ISSUE THREAD

**Issue by xuyoze** [redis/RedisDesktopManager#3778]
RDM Version: 0.9.0.496<br>
Environment (OS name and version): windows10 x64<br>
Redis Server Version: 3.2<br>

Steps to reproduce:
1. ![20161129163650](https://cloud.githubusercontent.com/assets/2830732/20702388/914e4648-b652-11e6-978b-98b19d671dbe.png)

2. 
![20161129164005](https://cloud.githubusercontent.com/assets/2830732/20702397/9c90ee66-b652-11e6-8265-35581ab91292.png)

Expected result: 

Actual Result:

**Comment by uglide** [comment]
First Icons shows that you import something to app (arrow direction) and second not so obvious but shows that you save all your connections to disk/file, etc.

**Comment by uglide** [comment]
Usually icons with up arrow mean in UI upload or import, and with down arrow - download or export.

**Comment by uglide** [comment]
If you have better suggestions regarding this icons please share it with me.

**Comment by xuyoze** [comment]
Thanks a lot!
![20161129165150](https://cloud.githubusercontent.com/assets/2830732/20702770/362f9742-b654-11e6-8636-25639caea5f6.png)
