### ISSUE TITLE
Can't build from source on OSX - brew not listed as dependency

### ISSUE THREAD

**Issue by jlongman** [redis/RedisDesktopManager#3779]
RDM Version: 0.8
Environment (OS name and version): OSX Sierra 10.12.1

from: http://docs.redisdesktop.com/en/latest/install/
> Build on OS X
>
> Install XCode with xcode build tools
> Build RDM dependencies cd ./src && ./configure
> Install Qt 5.6
> Open ./src/rdm.pro in Qt Creator
> Run build

Build RDM dependencies fails if `brew` is not installed

Steps to reproduce:

1. With XCode and build tools installed, run `Build RDM dependencies cd ./src && ./configure` line

Expected result: 

configure executes

Actual Result: 

> z0mg:rdm longman$ cd ./src && ./configure
> ./configure: line 5: brew: command not found
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> ^C** BUILD INTERRUPTED **
> 
> z0mg:src longman$

It's probably sufficient to list brew as a dependency in the documentation.

**Comment by jlongman** [comment]
Looking quickly at `configure`, `coreutils` is only used once for a `readlink` implementation but later `libssh2`  is imported as well.

- list homebrew as dependency,
- could change to support MacPorts as well,
- eliminate homebrew by using python as a `readlink`, and then install `libssh2` as in linux (if possible) 
- no, `libssh2` requires `cmake`, back to yakshaving or homebrew/macports.

**Comment by uglide** [comment]
@jlongman Thanks for the feedback. If it possible please make PR to fix documentation and improve `configure` script on OSX. Thanks!
