### ISSUE TITLE
build 0.8.0 from source on OSX10.12.1

### ISSUE THREAD

**Issue by MiderWong** [redis/RedisDesktopManager#3783]
RDM Version: 0.8.0<br>
Environment (OS name and version): macOS Sierra(version 10.12.1)<br>
Redis Server Version: 3.2.1<br>

Build RDM 0.8.0 from source on OSX.

Steps to reproduce:

1. 
```shell
git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm
```
2. 
```shell
cd ./src && ./configure
```

3. open `./src/rdm.pro` in Qt Creator(Qt5.7)

4. run build.

Actual Result: 
```shell
:-1: warning: directory not found for option '-L/usr/local/Cellar/libssh2/1.7.0/lib'
:-1: warning: directory not found for option '-L/usr/local/Cellar/openssl/1.0.2h_1/lib'
:-1: error: library not found for -lssl
:-1: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by uglide** [comment]
Hello, Please update `qredisclient` submodule to latest version to resolve this issue.
