### ISSUE TITLE
Breakpad.xcodeproj' does not exist

### ISSUE THREAD

**Issue by ppet** [redis/RedisDesktopManager#3785]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. ...
Unzip RedisDesktopManager
cd RedisDesktopManager-0.9

2. ...
cd ./src && ./configure
Expected result: 
No error
Actual Result: 
xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.

**Comment by uglide** [comment]
You need to clone repo with `--recursive` flag instead of downloading zip file from github.
