### ISSUE TITLE
mac can‘t build

### ISSUE THREAD

**Issue by lly835** [redis/RedisDesktopManager#3786]
RDM Version: 0.8.0
Environment (OS name and version): 10.12.2 (16C67)
Redis Server Version: Redis server v=3.0.3

Steps to reproduce:

1. ...
<img width="1260" alt="qq20161216-0 2x" src="https://cloud.githubusercontent.com/assets/2225913/21251076/8c5897c0-c385-11e6-87a1-db47f64d30ac.png">

2. ...

3. ...

Expected result: 

Actual Result:

**Comment by uglide** [comment]
Hello, You forgot to run `configure` script

**Comment by lly835** [comment]
where choose configure script, i don't good at QT

**Comment by uglide** [comment]
Just follow steps described in documentation http://docs.redisdesktop.com/en/latest/install/#build-on-os-x
