### ISSUE TITLE
Cannot install OSX from source - libssh2 1.7 dependency

### ISSUE THREAD

**Issue by paulhargreaves** [redis/RedisDesktopManager#3787]
RDM Version: 0.8.8
Environment (OS name and version): macOS 10.12.2
Redis Server Version: n/a

Steps to reproduce:

1. ./configure
:src $ ./configure 
Warning: coreutils-8.26 already installed
Error: libssh2 1.8.0 already installed
Warning: libssh2-1.8.0 already installed
:src $ 

2. 
Build using QT:

...
ld: warning: directory not found for option '-L/usr/local/Cellar/libssh2/1.7.0/lib'
ld: warning: directory not found for option '-L/usr/local/Cellar/openssl/1.0.2h_1/lib'
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../bin/osx/debug/rdm] Error 1
08:34:39: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project rdm (kit: Desktop Qt 5.6.2 clang 64bit)
When executing step "Make"

Expected result: 
Linked app

Actual Result: 
Failed to link

Checking the src/configure script, it upgrades libssh2, so looks like it will always pick up version 1.8 (or newer).

**Comment by paulhargreaves** [comment]
Workaround, at least for me:

Check what versions of openssh and libssh2 are installed in /usr/local/Cellar. For me, it was libssh2/1.8.0  and openssl/1.0.2j

Edit 3rdparty/qredisclient/3rdparty/3rdparty.pri
Search for unix:mac {  section
Change version numbers as per what is installed.

Back into QT; qmake is only build option available, then do a build all.

**Comment by uglide** [comment]
Fixed in https://github.com/uglide/qredisclient/commit/a2258a4a37e9896ff5f86b19b821cdd548d3efbb and available in 0.9.0-alpha4 PR

**Comment by Cydmi** [comment]
RDM Version: 0.9
Environment (OS name and version): macOS 10.12.4
`git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm`
why? 
```
n$ cd ./src && ./configure
Updating Homebrew...
Warning: coreutils 8.27 is already installed
Error: libssh2 1.8.0 already installed
Warning: libssh2 1.8.0 is already installed
```

**Comment by linjiangl** [comment]
`macOS 10.13.2` 安装这个版本 [redis-desktop-manager-0.9.0.41.dmg](https://github.com/uglide/RedisDesktopManager/releases)
