### ISSUE TITLE
Your operation is not supported --Korora 23

### ISSUE THREAD

**Issue by ramsayleung** [redis/RedisDesktopManager#3789]
RDM Version: <br> 0.8.8
Environment (OS name and version): <br>Korora 23
Redis Server Version: <br> 3.2.2

Steps to reproduce:

1. ...download the tar.gz file from release

2. ...cd src/ ./configure

Expected result: 
it should configure ok,Korora 23 it's Fedora 23 based.
Actual Result: 
Your operation system is not supported!

**Comment by uglide** [comment]
Hello @samrayleung 
You need to modify `src/configure` file to add support for your distro.
Feel free to add your changes as PR. Thanks!
