### ISSUE TITLE
Build from source failed,it seems it is problem about the dependency

### ISSUE THREAD

**Issue by ramsayleung** [redis/RedisDesktopManager#3793]
RDM Version: <br>0.9.0-alpha3
Environment (OS name and version): <br>Korora 23
Redis Server Version: <br>3.2.2

Steps to reproduce:

1. ... download release from github

2. ...cd src/ ./configure

3. ... 
Cannot read RDM_DIR/3rdparty/qredisclient/qredisclient.pri: No such file or directory
Cannot read RDM_DIR/3rdparty/qgamp/qgamp.pri: No such file or directory
Project ERROR: Unknown module(s) in QT: charts

Expected result: 
everything should be fine, and i could make this project

Actual Result: 
Error,cannot find file ,so i add `set -ex` in `configure` file and `set -ex` in `build/common_functions` file .Then ,the log  is as below
+build_breakpad
+cd /tmp/RedisDesktopManager-0.9.0-alpha3/src/..//3rdparty//gbreakpad/
+git clone https://chromium.googlesource.com/linux-syscall-support src/third_party/lss
Cloning into 'src/third_party/lss'...
remote: Total 112 (delta 61), reused 112 (delta 61)
Receiving objects: 100% (112/112), 103.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (61/61), done.
Checking connectivity... done.
+touch README
+./configure
/tmp/RedisDesktopManager-0.9.0-alpha3/src/..//build/common_functions: line 13: ./configure: No such file or directory
Then ,i manually run this command which is in `common_functions`:`git clone https://chromium.googlesource.com/linux-syscall-support `,and i find no such file named `configure`

So is there something wrong with the Google source?

**Comment by openhoat** [comment]
+1

same for me with fedora 25

**Comment by uglide** [comment]
You should use `git clone` with `--recursive` flag to download all dependencies automatically

**Comment by ramsayleung** [comment]
@uglide i have add `--recursive`,but i still get the same error,i could not find the `configure` file ,is there some  wrong with me or the dependency

**Comment by jkinzer** [comment]
@uglide your qgamp repository no longer exists.

**Comment by wings-xue** [comment]
why close this question

**Comment by uglide** [comment]
@wings-xue because it was opened for 0.9.0-alpha3 and a ton of fixes was added since then

@jkinzer build 0.9 branch, it's ok
