### ISSUE TITLE
app failed to launch due to googlemp created children for a parent that is in a different thread

### ISSUE THREAD

**Issue by truebit** [redis/RedisDesktopManager#3794]
RDM Version: 0.9 branch latest<br>
Environment (OS name and version): macosx 10.12 <br>
Redis Server Version: not needed<br>

Steps to reproduce:

1. build mac version

2. use command `macdeployqt rdm.app`

3. try to launch the modified rdm.app

Expected result: 
launch success

Actual Result: 
crash with below logs:

> objc[42948]: Class RunLoopModeTracker is implemented in both /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Versions/5/QtCore (0x1089dfdf0) and /foo/bar/rdm.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x106dd2df0). One of the two will be used. Which one is undefined.
> objc[42948]: Class NotificationReceiver is implemented in both /usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Versions/5/QtWidgets (0x1094b3ef0) and  /foo/bar/rdm.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets (0x1078abef0). One of the two will be used. Which one is undefined.
> App font: "Open Sans" 10
> GoogleMP singleton initialized
> "fc1c45f3-32cc-4c49-91bd-be3fb3ab356e"
> **QObject: Cannot create children for a parent that is in a different thread.**
> **(Parent is GoogleMP(0x7fc4134d2af0), parent's thread is QThread(0x7fc41354d850), current thread is QThread(0x7fc4135015f0)**

NOTE: when using the original rdm.app (without `macdeployqt`), it could be launched successfully.

**Comment by uglide** [comment]
GoogleMP will removed from RDM https://github.com/uglide/RedisDesktopManager/issues/3817
