### ISSUE TITLE
RDM will crash immediatly when started on Win7 Professional 64bit

### ISSUE THREAD

**Issue by freevest** [redis/RedisDesktopManager#3798]
RDM Version: 0.8.8
Environment (OS name and version): Win7 Professional 64bit
Redis Server Version: 3.2

Steps to reproduce: RDM will crash immediatly when started on Win7 64bit.
![crash](https://cloud.githubusercontent.com/assets/12496417/22026229/2c3d63a8-dd0b-11e6-9e0f-34f08b4a9da5.png)

**Comment by uglide** [comment]
Probably you need to update your system first and then reinstall RDM
