### ISSUE TITLE
Debian testing 9 can not install successfully RDM

### ISSUE THREAD

**Issue by muyu66** [redis/RedisDesktopManager#3799]
RDM Version: 0.9.0-alpha3<br>
Environment (OS name and version): Debian 9 testing (Kernel: 4.8.0-2-amd64)<br>
Redis Server Version: 3.2.6 64bit<br>

Steps to reproduce:

1. dpkg -i ./redis-desktop-manager_0.9.0.27_amd64.deb
`dpkg: dependency problems prevent configuration of redis-desktop-manager:
 redis-desktop-manager depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.
 redis-desktop-manager depends on zlibc; however:
  Package zlibc is not installed.
 redis-desktop-manager depends on libpng12-0; however:
  Package libpng12-0 is not installed.
 redis-desktop-manager depends on libicu-dev; however:
  Package libicu-dev is not installed.
`

2. apt install -f when some errors occurred
`The following packages will be REMOVED:
  redis-desktop-manager
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.`

3. apt search libssl
`libssl1.0.2/testing,now 1.0.2j-4 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries
libssl1.0.2-dbg/testing 1.0.2j-4 amd64
  Secure Sockets Layer toolkit - debug information
libssl1.1/testing,now 1.1.0c-2 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries`

4. apt show libssl1.0.0
`Package: libssl1.0.0
State: not a real package (virtual)
N: Can't select candidate version from package libssl1.0.0 as it has no candidate
N: Can't select versions from package 'libssl1.0.0' as it is purely virtual
N: No packages found
`

If you need any information, please let me know

**Comment by dreamrover** [comment]
1. download http://ftp.br.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb
extract it as compressed file, and extract data.tar.gz to the corresponding directory.
2. download redis-desktop-manager_0.9.0.17_amd64.deb
extract it as compressed file, and extract data.tar.gz to the corresponding directory.
3. you can run it by clicking applications-->programming-->redis desktop manager

**Comment by katuknow** [comment]
We do not support Debian officially. So the best way to make RDM work is compiling from sources.
