### ISSUE TITLE
Crash Reports

### ISSUE THREAD

**Issue by mattttttttttt** [redis/RedisDesktopManager#3801]
I can't locate the information anywhere.... but, when RDM crashes, it says it is sending information to the developers.  What information is sent to the developers?? Specifically, what/if information is sent in regards to the configuration, are usernames and passwords sent?

**Comment by AntonyGarand** [comment]
I'd also like to have this information, and would like to know if there is / will be a button to disable the automatic upload  
The programs crashes quite frequently and I'd like to avoid sending dozens of reports daily
