### ISSUE TITLE
Application cannot start (0xc000007b). Click OK to close the application

### ISSUE THREAD

**Issue by blackdancers** [redis/RedisDesktopManager#3805]
RDM Version: redis-desktop-manager-0.9.0.480 <br>
Environment (OS name and version):Windows 8.1  <br>
Redis Server Version: 3.0.7<br>

Steps to reproduce:

![image](https://cloud.githubusercontent.com/assets/4956686/22814213/9c3d8618-ef8c-11e6-869d-2045aceacf61.png)

Expected result: 

Actual Result:

**Comment by errogaht** [comment]
Have it too 
![https://goo.gl/9W696r](https://goo.gl/9W696r)
windows 7 
i see it when just try to start app

**Comment by BearWwang** [comment]
Mi too  

windows 8.1 

redis  0.8.8

![qq 20170524154005](https://cloud.githubusercontent.com/assets/28646964/26391959/6e4e143c-4097-11e7-8b7d-525d98467aa1.jpg)

**Comment by BearWwang** [comment]
Dead start,have already installed DX11

**Comment by BearWwang** [comment]
我已经解决问题，在安装目录下，双击此程序就Ok了
I've solved the problem, and in the installation directory, double-clicking the program is Ok

![image](https://cloud.githubusercontent.com/assets/28646964/26392550/97e00fba-4099-11e7-92db-08ddee6ba48e.png)

**Comment by errogaht** [comment]
im install vcredist_x86.exe but bug still appears

**Comment by songleo** [comment]
me too

OS:  win7 x64
RDM: 0.8.8.384

**Comment by watchpoints** [comment]
im install vcredist_x86.exe but bug still appears

**Comment by xiaoyijun** [comment]
open vcredist_x86 in the RDM installation folder and click "Repair"

**Comment by uglide** [comment]
Added solution to known issues

**Comment by xianwei** [comment]
@BearWwang Which version do I need for "vcredist_x86.exe"? 需要下载哪个版本，我试过几个版本都不行

**Comment by uglide** [comment]
@xianwei this one https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

**Comment by sawyes** [comment]
@xianwei  it's work for me by installed vc_redist
