### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by YiiGuxing** [redis/RedisDesktopManager#3806]
: -1: error: No rule to make target `~/RedisDesktopManager-0.8.8/3rdparty/gbreakpad/src/client/mac/build/Release/Breakpad.framework', needed by `../bin/osx/debug/rdm'.  Stop.

**Comment by wjszxli** [comment]
0.8.8/3rdparty/gbreakpad/src/client/mac/build/Release/Breakpad.framework', needed by../bin/osx/debug/rdm'. Stop.

**Comment by yanbodiaoweng** [comment]
Has anyone solve it ?  I have this problem too.

**Comment by uglide** [comment]
Please ask for help in gitter chat.

**Comment by JohnOnLee** [comment]
If you getting same with and similar output from ./configure
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

run following command
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
