### ISSUE TITLE
Right pane blurred

### ISSUE THREAD

**Issue by cajnoj** [redis/RedisDesktopManager#3807]
RDM Version: 0.8.8.384
Environment (OS name and version): Windows 7 SP1 64 bit
Redis Server Version: Any

Steps to reproduce:
Unclear how to reproduce. It happened all of a sudden in a single PC.

Expected result: 
Text in right pane should be clear as in left pane

Actual Result: 
Text in right pane is blurred: greyed and with low resolution

![image](https://cloud.githubusercontent.com/assets/11817886/23103828/2b0f72c2-f6ca-11e6-91bf-588f111bb335.png)

**Comment by uglide** [comment]
It's Qt glitches on windows, nothing I can do about. Hopefully it will work better after migration to Qt 5.8
