### ISSUE TITLE
Redis desktop manager was not installed on Linux mint serena

### ISSUE THREAD

**Issue by pavhov** [redis/RedisDesktopManager#3809]
RDM Version : origin/0.8.0 <br>
Environment (OS name and version): linux mint serena <br>
Redis Server Version: Redis server v=3.2.8 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=11aa79fd2425bed9 <br>

Steps to reproduce:

1. git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm

2. cd src/

3. chmod 0777 ./configure && ./configure

4. sudo su && source /opt/qt56/bin/qt56-env.sh && qmake && make && sudo make install

Expected result: 
![screenshot_1](https://cloud.githubusercontent.com/assets/8784893/23138255/adafda96-f7bf-11e6-83e4-e73e03bfc113.png)

Actual Result: 
Linux must be finished make install command

**Comment by uglide** [comment]
I do not maintain 0.8.8 version any more. Please wait for stable 0.9 build.
