### ISSUE TITLE
Fictitious message for available update

### ISSUE THREAD

**Issue by kanevbg** [redis/RedisDesktopManager#3816]
RDM Version: 0.8.8.19
Environment (OS name and version): Ubuntu 16.04
Redis Server Version: Problem not related to server (connection)

Steps to reproduce:
Download, install and run RDM 0.8.8.19 (the subscriber packet)

Expected result: 
No notification for newer version

Actual Result: 
Got notification for newer version. But there is no such.

**Comment by uglide** [comment]
Hello @kanevbg 
Thanks, will fix it soon

**Comment by Umbraller** [comment]
@uglide why  not  update？？？The  0.9.0  version  so  bad   for   windows.   It  cannot modify  key ！

**Comment by uglide** [comment]
Should be fixed now
