### ISSUE TITLE
update!!!

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#3820]
Why redis desktop manager so long did not update? Especially Windows version, bug too much!
@uglide

**Comment by uglide** [comment]
@Umbraller What do you expect from me?
It's open source project and I do my best to find time to work on RedisDesktop, but it's quite hard. If you really need updates just clone repo and play with it, submit PR, etc. If you don't want to spend time on code - make significant donation to project in money.

No other options.
