### ISSUE TITLE
Bulk Operations

### ISSUE THREAD

**Issue by sp3tsnaz** [redis/RedisDesktopManager#3822]
It would be great to have support for operations on multiple keys. 

1. Like multiple selected keys can be deleted
2. Set TTL for multiple keys (all at once)

**Comment by BHare1985** [comment]
Any update?

**Comment by uglide** [comment]
ETA for 0.9.3 is Aug/Sept of this year

**Comment by sss4999** [comment]
###

**Comment by uglide** [comment]
Already in 2019 branch and will be released as 2019.1
