### ISSUE TITLE
Parsing errors in 0.9.0-alpha4 for JSON that parses correctly in the version I had been using (0.8.3)

### ISSUE THREAD

**Issue by russgalloway** [redis/RedisDesktopManager#3823]
RDM Version: 0.9.0-alpha4
Environment (OS name and version): OS X 10.11.6
Redis Server Version: 2.8.4 - Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-77-generic x86_64)

Steps to reproduce:

(alpha4 cloned and built from source)

JSON that was being parsed correctly on v0.8.3-2550 doesn't seem to parse in 0.9.0-alpha4.

small example: 
{"$type":"Server.Lib.Models.RecentCommentsLastSent, server","at":"2017-04-03T14:00:01.560329-05:00"}

Expected result: 
Parsed/formatted JSON like v0.8.3-2550:
{
    "$type": "Server.Lib.Models.RecentCommentsLastSent, server",
    "at": "2017-04-03T14:00:01.560329-05:00"
}

Actual Result: 
"Error: Invalid JSON"

**Comment by delagen** [comment]
It hang on switch parsing on my environment
Windows 10
Redis 3.2.4
