### ISSUE TITLE
Error during configure of 0.9 Alpha4 - Breakpad.xcodeproj is missing.

### ISSUE THREAD

**Issue by ghstridr** [redis/RedisDesktopManager#3826]
RDM Version: 0.9 Alpha4
Environment (OS name and version): OSX 10.12.3
Redis Server Version: <br>

Steps to reproduce:

1. git clone repo

2. cd into RedisDesktopManager/src

3. ./configure

Expected result: A correctly configured project ready to compile

Actual Result: Missing Files
xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.
xcodebuild: error: 'src/client/mac/Breakpad.xcodeproj' does not exist.

**Comment by uglide** [comment]
You forgot to add `--recursive` flag to `git clone` command
