### ISSUE TITLE
Error while cloning repository

### ISSUE THREAD

**Issue by p-golovin** [redis/RedisDesktopManager#3830]
Cloning into '3rdparty/qgamp'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/uglide/qgamp.git/'
fatal: clone of 'https://github.com/uglide/qgamp.git' into submodule path '3rdparty/qgamp' failed

**Comment by marianoarga** [comment]
Same here

**Comment by uglide** [comment]
Duplicate https://github.com/uglide/RedisDesktopManager/issues/3821

**Comment by marianoarga** [comment]
@p-golovin 
Try cloning alpha4 branch, as mention in duplicate issue...
https://github.com/uglide/RedisDesktopManager/tree/alpha4
