### ISSUE TITLE
Application cannot start (0xc000007b). Click OK to close the application

### ISSUE THREAD

**Issue by larkwins** [redis/RedisDesktopManager#3831]
RDM Version: 0.8.8

Environment (OS name and version): WIN7

Redis desktop manager alerts when opened:

> Application cannot start (0xc000007b). Click OK to close the application.

How to deal with this case?

PS: DirectX 9.0 has been installed successfully.

**Comment by ghost** [comment]
都是英文问题，你这写个汉语谁看的懂啊

**Comment by larkwins** [comment]
@Umbraller 

help

**Comment by uglide** [comment]
Looks like duplicate of #3805

**Comment by larkwins** [comment]
@uglide but it hasn`t been solved yet, any ideas?
