### ISSUE TITLE
where is uglide 3dparty repos?

### ISSUE THREAD

**Issue by oytunistrator** [redis/RedisDesktopManager#3832]
Git fetch errors: 
fatal: repository 'https://github.com/uglide/php-unserialize-js.git/' not found
fatal: clone of 'https://github.com/uglide/php-unserialize-js.git' into submodule path

**Comment by bbaassssiiee** [comment]
remote: Repository not found.
fatal: repository 'https://github.com/uglide/qgamp.git/' not found
fatal: clone of 'https://github.com/uglide/qgamp.git' into submodule path '/private/tmp/rdm/3rdparty/qgamp' failed
Failed to clone '3rdparty/qgamp'. Retry scheduled
Cloning into '/private/tmp/rdm/3rdparty/qredisclient'...
remote: Counting objects: 843, done.        
remote: Compressing objects: 100% (5/5), done.        
remote: Total 843 (delta 1), reused 0 (delta 0), pack-reused 838        
Receiving objects: 100% (843/843), 208.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (489/489), done.
Cloning into '/private/tmp/rdm/3rdparty/qtconsole'...
remote: Counting objects: 66, done.        
remote: Total 66 (delta 0), reused 0 (delta 0), pack-reused 66        
Cloning into '/private/tmp/rdm/src/resources/qml/3rdparty/php-unserialize-js'...
remote: Repository not found.
fatal: repository 'https://github.com/uglide/php-unserialize-js.git/' not found
fatal: clone of 'https://github.com/uglide/php-unserialize-js.git' into submodule path '/private/tmp/rdm/src/resources/qml/3rdparty/php-unserialize-js' failed
Failed to clone 'src/resources/qml/3rdparty/php-unserialize-js'. Retry scheduled
Cloning into '/private/tmp/rdm/3rdparty/qgamp'...
remote: Repository not found.
fatal: repository 'https://github.com/uglide/qgamp.git/' not found
fatal: clone of 'https://github.com/uglide/qgamp.git' into submodule path '/private/tmp/rdm/3rdparty/qgamp' failed

**Comment by diimdeep** [comment]
```
fatal: repository 'https://github.com/uglide/qgamp.git/' not found
```

**Comment by sharpred** [comment]
+1

**Comment by uglide** [comment]
Duplicate #3821 
Since 0.9.0-alpha4 is merged you can just reclone repo.
