### ISSUE TITLE
RDM Screen is black

### ISSUE THREAD

**Issue by blowsky** [redis/RedisDesktopManager#3834]
RDM Version: 0.8.8.384
Environment (OS name and version): Windows Server 2008 R2
Redis Server Version: 3.2.0

Steps to reproduce:

1. Click on RedisDesktopManager.ink

2. select a redis instance and choose a key 

3. open the key（redis server connect normal and show the key name）

Expected result: display the key value 

Actual Result: the right RDM screen is black.

In some host,It can display normal，but in this server it is not，
 I think maybe firewall cause this，so i want to ask which port does it use？

**Comment by katuknow** [comment]
You need to enable Remote FX in RDP client settings to make RDM work.
