### ISSUE TITLE
Building from source fails due to recursive cloning fail

### ISSUE THREAD

**Issue by ibriq** [redis/RedisDesktopManager#3837]
RDM Version: `latest`<br>
Environment (OS name and version): `Ubuntu`<br>
Redis Server Version: N/A<br>

Steps to reproduce:

1. Run `git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm`
2. Cloning will fail due to following error:
```
fatal: repository 'https://github.com/uglide/qgamp.git/' not found
fatal: clone of 'https://github.com/uglide/qgamp.git' into submodule path '3rdparty/qgamp' failed
```

Expected result: Recursive cloning to end up with success.

Actual Result: Recursive cloning failed.

**Comment by ruslan-malona** [comment]
Same for me. Did you find solution?

**Comment by petervnv** [comment]
I have same problem. No solution yet AFAIK

**Comment by ryanclark** [comment]
Running `git clone --recursive git@github.com:uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm` works for me (clone the 0.9 branch instead of 0.8.0)

**Comment by fawaztahir** [comment]
I tried running `git clone --recursive git@github.com:uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm` but i don't have proper permissions to read it. Output:

```
Cloning into 'rdm'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ryanclark** [comment]
Try `git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm`?

**Comment by fawaztahir** [comment]
@rynclark Thanks it worked.

**Comment by piotrkochan** [comment]
@uglide docs needs update http://docs.redisdesktop.com/en/latest/install/#build-from-source

**Comment by kanadgodse** [comment]
I cloned the master branch with `git clone --recursive https://github.com/uglide/RedisDesktopManager.git rdm && cd ./rdm` and it worked for me.

Just FYI, you would need to change the source command to qt58 as follows since that is what the master branch is using:
`source /opt/qt58/bin/qt58-env.sh && qmake && make && sudo make install`

Hope that helps!
