### ISSUE TITLE
could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by petervnv** [redis/RedisDesktopManager#3839]
On Debian 8.8 x86_64, git clone of branch 0.9 and followed all the instructions in the wiki, but when running rdm i get the following error:

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Error: Can't launch CrashReporter!
Aborted (core dumped)

**Comment by coreyog** [comment]
I'm getting this same problem on Linux Mint 18.3 x64

**Comment by uglide** [comment]
@coreyog try to do this https://github.com/uglide/RedisDesktopManager/issues/3924#issuecomment-345652988
