### ISSUE TITLE
Connection error: The proxy type is invalid for this operation

### ISSUE THREAD

**Issue by Pes8** [redis/RedisDesktopManager#3841]
RDM Version: 0.9.0-alpha4 (0.9.0.559)
Environment (OS name and version): Windows 10 Pro 64 bit
Redis Server Version: 3.2.6

I'm under a proxy that is setted correctly in the system and that have some exclusions (Redis Server url is in that esclusions).

With the proxy active I can't connect to the redis server and in RDM log there is an error: "**Connection: Connection error: The proxy type is invalid for this operation**" (seems a Qt error).

If I deactive the proxy from Windows RDM can connect to the redis server correctly.

I think the problem is that the address of the redis server is in the exclusions list of the proxy. Is a common configuration and I need the proxy active to browse all other addresses.

**Comment by nikukyugamer** [comment]
the same event occured at the same environment.
thanks for this report and I'm looking forward to update :)

**Comment by bi-kai** [comment]
2018-02-06 14:07:54 : Connection: Cancel running commands
2018-02-06 14:07:54 : Connection: Disconect on error: Connection error: The proxy type is invalid for this operation
2018-02-06 14:07:54 : Connection: > connection failed


same error on win7
0.9.0.684

**Comment by bi-kai** [comment]
I'm using `Medis` now.

**Comment by flyingnn** [comment]
same error on win10  pro x64 
redis-desktop-manager-0.9.0.751.exe
![image](https://user-images.githubusercontent.com/1114262/36953713-cff9a070-2057-11e8-8caf-7d626e4a48bc.png)

**Comment by yingtho** [comment]
When using 0.8.8 it is working fine.

**Comment by teekcode** [comment]
RDM can only connect localhost redis now? When connect redis on other machine, it shows this log.`The proxy type is invalid for this operation`

**Comment by defilerc** [comment]
The bug still exists on version 0.9.3.817, which I'm currently using. Until this is fixed, I'm disabling the proxy in order to connect.

**Comment by uglide** [comment]
@defilerc Fix will be released in 0.9.4

**Comment by NelsonReis** [comment]
Any news on this release? Could really use the new version. Thanks!

**Comment by almostjulian** [comment]
This just hit me.... any word on the release?

**Comment by bengawel** [comment]
Experiencing this issue in version 0.9.9.1218.  I am able to connect to redis using the redis-cli, but not through RDM.

**Comment by uglide** [comment]
@bengawel Could you provide more info? Do you have system proxy setting enabled in RDM settings?

**Comment by bengawel** [comment]
I do not, but it seems the issue exists whether or not system proxy settings are enabled.  I am trying to connect to an Azure Cache for Redis instance and am using RDM on Windows 10.  Sometimes it is able to connect just fine, but other times it is unable to connect giving the reason "Connection error: The proxy type is invalid for this operation."  This only seems to be the case for the Azure instance I am trying to connect to, other Redis instances I am able to connect to just fine.  I initially thought it was an issue with how the Azure instance was configured, but I am able to connect to it using the redis-cli just fine.

**Comment by siraykut** [comment]
Access by IP instead of domain name. I had the same problem and it was solved when I reached it.
