### ISSUE TITLE
May be memory leak

### ISSUE THREAD

**Issue by ZZMarquis** [redis/RedisDesktopManager#3855]
RDM Version: 0.9.0.55<br>
Environment (OS name and version): Windows 7 , 4 core CPU <br>
Redis Server Version: 2.8.2<br>

Steps to reproduce:

1. running a night

Expected result: 

Actual Result: data in redis almost unchanged, but memory increased 500M+

**Comment by xuange123** [comment]
的双方各

**Comment by uglide** [comment]
Fixed in https://github.com/uglide/RedisDesktopManager/commit/5f06b3ecf3357ccee11d94fb120eefe9b2190fce

**Comment by lastgame** [comment]
thank you !
