### ISSUE TITLE
windows server 2008 R2  remote desktop can not use

### ISSUE THREAD

**Issue by lifw555** [redis/RedisDesktopManager#3856]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): windwos server 2008 R2<br>
Redis Server Version: 3.2.0<br>

Steps to reproduce:

1. remote desktop login

2. open rdm

Expected result: right table show info

Actual Result:  black

**Comment by keslabs** [comment]
Same. Workaround?

**Comment by katuknow** [comment]
You need to enable Remote FX in RDP client settings to make RDM work.

**Comment by lifw555** [comment]
not fixed . windows server 2008 r2
