### ISSUE TITLE
delete with wrong namespace separator

### ISSUE THREAD

**Issue by cowcomic** [redis/RedisDesktopManager#3857]
RDM Version: 0.8.8.384
Environment (OS name and version): win10
Redis Server Version: 

Steps to reproduce:

1. edit connection`s advanced setting, change namespace separator to "_"

2. delete a namespace 

3. the last separator for the key pattern is not "_" but a ":", so delete error

Expected result: 

Actual Result:

**Comment by uglide** [comment]
Already fixed in 0.9
