### ISSUE TITLE
Application Keeps Crasing

### ISSUE THREAD

**Issue by aspnerd** [redis/RedisDesktopManager#3858]
RDM Version: 0.8.8.348 <br>
Environment (OS name and version): Windows 10 64bit<br>
Redis Server Version: 64bit 3.2.100 <br>

Steps to reproduce:

1. open

2. connect to server (localhost)

3. select object in database

Expected result: see cache objects

Actual Result: app crashes without error message.

**Comment by uglide** [comment]
@aspnerd How many keys do you have in db? Please paste here output from `INFO` command

**Comment by aspnerd** [comment]
At the time, 2-22?

List of unsupported commands: DUMP, RESTORE, AUTH 
Connecting ...

Connected.
localhost:0>info
"# Server
redis_version:3.2.100
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:dd26f1f93c5130ee
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:3732
run_id:f2361a012a9c87d426232d0376546bfd923fd462
tcp_port:6379
uptime_in_seconds:11297
uptime_in_days:0
hz:10
lru_clock:13374746
executable:C:\Program Files\Redis\"C:\Program Files\Redis\redis-server.exe"
config_file:C:\Program Files\Redis\redis.windows-service.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:193298400
used_memory_human:184.34M
used_memory_rss:193297352
used_memory_rss_human:184.34M
used_memory_peak:197338056
used_memory_peak_human:188.20M
total_system_memory:0
total_system_memory_human:0B
used_memory_lua:77824
used_memory_lua_human:76.00K
maxmemory:536870912
maxmemory_human:512.00M
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1506545046
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:13
total_commands_processed:1279
instantaneous_ops_per_sec:0
total_net_input_bytes:228460
total_net_output_bytes:363197890
instantaneous_input_kbps:0.01
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:2
evicted_keys:0
keyspace_hits:192
keyspace_misses:54
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:41842
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:3.28
used_cpu_user:0.48
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=22,expires=0,avg_ttl=0
db2:keys=1,expires=0,avg_ttl=0
"

localhost:0>

**Comment by aspnerd** [comment]
Why was this labeled invalid? This is a consistent issue. There is no information provided. Do you log issues somewhere in the app? A log file?

**Comment by uglide** [comment]
@aspnerd How long key names stored in your redis?

**Comment by aspnerd** [comment]
The key names are less than 20 for most of them...

**Comment by crodwell** [comment]
I've got the same issue on 64bit Win 10, is it just long key names? Mine are all 40 characters long.

**Comment by uglide** [comment]
Try to use latest 0.9 builds
