### ISSUE TITLE
Fonts are not so clear on mac

### ISSUE THREAD

**Issue by zaherg** [redis/RedisDesktopManager#3862]
*RDM Version*: 0.9.0-alpha4
*Environment (OS name and version)*: macOS
*Redis Server Version*: 3.2.9

![screen-shot-2017-07-14-12-11-35](https://user-images.githubusercontent.com/27624/28206284-ee55e8da-688d-11e7-84e1-a165ecfb460c.png)

Fonts are not so clear, fuzzy and so faded :(

**Comment by PoohOka** [comment]
Try changing UI font to the native one ;)

![redis](https://user-images.githubusercontent.com/1761107/28351926-638e5c16-6c7d-11e7-98a6-ecdfbc5f7a09.png)

**Comment by zaherg** [comment]
@PoohOka thanks for the tip, I did change it and it worked, but I noticed that the change won't take affect unless I restarted the app, which should not be the case at all.
