### ISSUE TITLE
title bar overlaps menu bar

### ISSUE THREAD

**Issue by nickykoh** [redis/RedisDesktopManager#3863]
![2017-07-14_19-03-11](https://user-images.githubusercontent.com/2995859/28209946-961dfb5a-68c7-11e7-8710-fb482b86c34a.jpg)
RDM Version: <br> 0.9.0.559
Environment (OS name and version): <br> Windows 10 Home
Redis Server Version: <br> not quite sure

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result:

**Comment by glacjay** [comment]
And the mouse position is not correct either.

**Comment by uglide** [comment]
Duplicate of #3876
