### ISSUE TITLE
Setting wont apply unless we restart the app

### ISSUE THREAD

**Issue by zaherg** [redis/RedisDesktopManager#3866]
**RDM Version:** 9 alpha 4
**Environment (OS name and version):** macOS
**Redis Server Version:** 4

**Steps to reproduce:**

1. open the settings
2. change the fonts
3. close the settings ( click ok button )

**Expected result:** 

Changing the font

**Actual Result:** 

Nothing unless you restarted the app

**Comment by uglide** [comment]
Default font for OSX will be changed in #3899.
