### ISSUE TITLE
Connection: SSH Connection error: Authentication Error

### ISSUE THREAD

**Issue by qlwz** [redis/RedisDesktopManager#3872]
RDM Version: all
Environment (OS name and version): win10
Redis Server Version: 3.2

Steps to reproduce:

 use SSH tunnel

 set private key and password 

Expected result: 
Connection OK

Actual Result: 

Connection: SSH Connection error: Authentication Error

**Comment by SvenAbels** [comment]
same problem here

**Comment by uglide** [comment]
Duplicate of #3571
