### ISSUE TITLE
Add a publish-button

### ISSUE THREAD

**Issue by kaenguruhuepf** [redis/RedisDesktopManager#3874]
RDM Version: 0.9.0.559<br>
Environment (OS name and version): WIN7<br>

It would be great to have an easy way to publish a changed value after saving it to the database.
A "publish" button located next to the save button could do this.

Another soulution could be to make the "save" configurable in a way it sends SET and PUBLISH.

**Comment by uglide** [comment]
What exactly do you need to publish after saving value?
