### ISSUE TITLE
win10 server 2008r2 等无法使用

### ISSUE THREAD

**Issue by dcdlove** [redis/RedisDesktopManager#3877]
win 10 完全不能用，win2008 黑屏

---------------------------
rdm.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------

**Comment by uglide** [comment]
Looks like you have broken vcredist_x86 installation on win10. Try reinstall it

**Comment by dcdlove** [comment]
好的我试试
