### ISSUE TITLE
can add a features for folding path if the uniq children node ?

### ISSUE THREAD

**Issue by ystyle** [redis/RedisDesktopManager#3878]
RDM Version: 0.9
Environment (OS name and version): All
Redis Server Version: All

Steps to reproduce:

1.  can add a features for folding path if the uniq children node ? like this: 
![](http://osloqpukl.bkt.clouddn.com/201717071143-a.png)

Expected result: 
![](http://osloqpukl.bkt.clouddn.com/201717071143-a.png)

Actual Result:

**Comment by uglide** [comment]
Thanks for idea

**Comment by uglide** [comment]
Duplicate of #3613
