### ISSUE TITLE
delete namespace bug

### ISSUE THREAD

**Issue by ystyle** [redis/RedisDesktopManager#3879]
RDM Version: 0.8
Environment (OS name and version): all
Redis Server Version: all

Steps to reproduce:

1. `Delete namespace`  with right click 

2. if namespace separator is not `:` , it don't show any keys 

PS:

it fond this issues will be in  [this line](https://github.com/uglide/RedisDesktopManager/blob/0.8.0/src/app/models/treeoperations.cpp#L124)
- QString pattern = QString("%1`:`*").arg(QString::fromUtf8(ns.getFullPath()));
>I think the `:*`  should be replaced by `" + this.getNamespaceSeparator() + "*`   //I will not c ++ but i think it should be so written

**Comment by uglide** [comment]
Already fixed in 0.9 branch
