### ISSUE TITLE
Unable to Display Binary Values

### ISSUE THREAD

**Issue by brntphish** [redis/RedisDesktopManager#3882]
Attempt to view key binary data. 
Use setBit to set a value using console: 
    setBit myKey 15 0

Attempt to view the value

Expected result: 
RDM recognizes it is a binary value, but will only display hex, hex table, string, JSON.
Expected rdm to display:
0000000000000000

Actual Result: 
Hex : \x00\x00

HexTable: 0000

Is this Just not possible? I am using the key to store 64 bits as triggers, and it is a pain to convert hex to binary each time when looking at troubleshooting. I AM able to retrieve an individual bit using console, but is there a reason rdm doesn't display it as binary. It knows it is a binary value.

**Comment by uglide** [comment]
Moved to https://github.com/RedisDesktop/rdm-native-value-formatters/issues/10
