### ISSUE TITLE
Able to connect to redis. But Cannot load databases.

### ISSUE THREAD

**Issue by kumarmugu** [redis/RedisDesktopManager#3888]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: 2.8.17<br>

Steps to reproduce:

1. Installed Redis and set the password

2. Test Connection - Sucess 
![image](https://user-images.githubusercontent.com/1758225/29648249-c85aec46-88bf-11e7-8ce9-89ff12f0e917.png)

3. Trying to load the database. Getting following error

Expected result: 
Able to see the databases.
Actual Result: 
![image](https://user-images.githubusercontent.com/1758225/29648233-b1d3fe9a-88bf-11e7-8dd3-aebc01977057.png)

Note1. : I am able to access the database through the program from the same machine.
Note2: I am able to connect and retrieve the database if no password set in the redis

**Comment by uglide** [comment]
Try to change execution timeout, or reduce amount of databases in config
