### ISSUE TITLE
Missing qt charts on fedora

### ISSUE THREAD

**Issue by donalddewulf** [redis/RedisDesktopManager#3894]
RDM Version: 0.9
Environment (OS name and version): Fedora 25
Redis Server Version: n/a

Steps to reproduce:

1. git clone --recursive https://github.com/uglide/RedisDesktopManager.git rdm && cd ./rdm
2. cd src
3. ./configure
4. qmake-qt5 && make

Actual Result: 
Error about missing QT charts module

Solution:
sudo yum install qt5-qtcharts-devel

Proposed:
Please add the qt5-qtcharts-devel library to the configure script or remove the sudo installs completely and tell us what dependencies we need to install.

**Comment by twf1956** [comment]
Same issue on centos 7 - except there is no qt5-qtcharts-devel package.

# yum install qt5-qtcharts-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.lstn.net
 * epel: mirrors.xmission.com
 * extras: mirror.scalabledns.com
 * remi-safe: mirrors.mediatemple.net
 * updates: mirror.scalabledns.com
 * webtatic: us-east.repo.webtatic.com
No package qt5-qtcharts-devel available.
Error: Nothing to do

Any suggestions?
