### ISSUE TITLE
Broken dependency 3rdparty/qgamp

### ISSUE THREAD

**Issue by bdh1011** [redis/RedisDesktopManager#3906]
There is broken dependency on DOCS(http://docs.redisdesktop.com/en/latest/install/) installation guide 
`git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm
`
repo `3rdparty/qgamp` is not exists...

**Comment by uglide** [comment]
Docs are updates but latest version was alias of 0.8 branch. Fixed now
