### ISSUE TITLE
Cannot see value for keys which are also folders

### ISSUE THREAD

**Issue by sullerandras** [redis/RedisDesktopManager#3907]
RDM Version: 0.9.0-dev, git hash: 438f02c293459e961d7700b24303cf8df5162eac
Environment (OS name and version): macOS 10.11.6
Redis Server Version: 3.2.6

Steps to reproduce:

For example Sidekiq creates keys like this:
```
localhost:6379> keys stat:processed*
  1) "stat:processed"
  2) "stat:processed:2017-09-17"
  3) "stat:processed:2017-09-18"
```
RDM shows the "stat:processed" folder and displays the keys inside the folder, but i see no way to display the value for the "stat:processed" key itself. I can see the value in redis-cli:

```
localhost:6379> get stat:processed
"40"
```

Expected result: clicking on a "folder" should display the value for that key if there is any.

Actual Result: no value is displayed when clicking on a "folder" which has a value.

**Comment by uglide** [comment]
Are you sure?
Here is how it looks like on latest 0.9 commit:
![image](https://user-images.githubusercontent.com/1655867/30580066-f3425840-9d23-11e7-8878-ac0ef94c638e.png)
As you can see you can open `stat:processed` key

Even if you add `stat` key you will have following result:
![image](https://user-images.githubusercontent.com/1655867/30580135-2c259eec-9d24-11e7-92c4-5c97ac3c7ca4.png)

**Comment by sullerandras** [comment]
Oh, I haven't noticed that it's in a different line then the "folder" :man_facepalming: 
Thanks for the quick reply. I'm closing this issue.
