### ISSUE TITLE
build failed: needed by `../bin/osx/debug/obj/read.o'

### ISSUE THREAD

**Issue by adolphor** [redis/RedisDesktopManager#3917]
# ENV
RDM Version: master branch <br>
Environment (OS name and version): 10.12.6<br>
Redis Server Version: 4.02<br>

# Steps to reproduce:

## 2. install hiredis by brew
```
brew install hiredis
```

## 3. Build RDM dependencies 
```
cd ./src && ./configure
```

## 4. build by QtCreator

# Result

* Expected result: 

build success

* Actual Result: 

```
:-1: error: No rule to make target `../3rdparty/qredisclient/3rdparty/hiredis/read.c', needed by `../bin/osx/debug/obj/read.o'.  Stop.
```

# Q
What should I do to solve this problem? Where is the `read.o` file? How could I get it?

**Comment by uglide** [comment]
Have you checked files in `../3rdparty/qredisclient/3rdparty/hiredis/` ?
