### ISSUE TITLE
Deleting namespaces with lots of keys

### ISSUE THREAD

**Issue by weeco** [redis/RedisDesktopManager#3918]
RDM Version: 0.8.8.834<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: <br>

Steps to reproduce:

1. Create a database with namespace containing ~2 million keys

2. Try to delete this namespace

3. See how badly that works out.
It takes many mintues until you can actually click "Delete keys" here: https://i.imgur.com/HaPkKd4.png
When one has been patient enough to delete these keys it will eventually end up with an error message saying that the bulk operation length is invalid though

Expected result: I have expected that the desktop manager wouldn't try to list the affected keys if the to be deleted namespace exceeds a specific quantity of redis keys.

Actual Result: It's apparently stuck because it is trying to list that many keys which would be affected by the delete operation. However I don't need to see the affected keys.

**Comment by restign** [comment]
when I try to delete this namespace .....find it did't work.....

**Comment by restign** [comment]
i can't delete namespace by this tool.....don't know why .hope who can help me

**Comment by JacobJohansen** [comment]
``` lua
EVAL "for i, name in ipairs(redis.call('KEYS', ARGV[1])) do redis.call('DEL', name); end" 0 pattern
```

that should be fast

**Comment by slavserver** [comment]
есть предположение, почему не удаляются массово ключи из под windows. я делаю коннект  к редиске, которая находится на сервере юбунту на 127.0.0.1 , Соответственно создаем SSH тунелинг, и мне кажется именно в туннелинге проблема. По одному ключу удалить можно, но не массово, ибо когда ставим редис-менеджер на ubuntu с редиской, а там ни какой туннелинг не нужен, все прекрасно удаляется и все отлично работает. через тунелинг на биг базах можно удалять ключи только по одному но не массово
