### ISSUE TITLE
ReJSON problem

### ISSUE THREAD

**Issue by HakanDmr** [redis/RedisDesktopManager#3919]
RDM Version: 0.8.8.384
Environment (OS name and version): Windows 10
Redis Server Version: 4.0.2

Steps to reproduce:

1. Install ReJSON module

2. Create an item by JSON.SET 

3. Click the item key on RDM

4. Get "Cannot open value tab:?" error

Expected result: Show JSON object

Actual Result: Error :)

**Comment by FerusGrim** [comment]
This issue seems to have been relegated to the 0.9.0-beta milestones which I, assume, were deleted when 0.9.0 was released. However, this issue seems to have no made the update.

Any chance we could get an updated estimate at which milestone this feature would be added? :)

@uglide

**Comment by uglide** [comment]
@FerusGrim Most likely it will be fixed in 0.9.2. In 0.9.1 I'm going to fix all regression bugs
