### ISSUE TITLE
Crashes when viewing large keys

### ISSUE THREAD

**Issue by oliversalzburg** [redis/RedisDesktopManager#3921]
RDM Version: Latest 0.8stable or 0.9alpha5
Environment (OS name and version): Windows 10
Redis Server Version: Doesn't matter

Steps to reproduce:

1. Click on a reasonably large (>100KB) key in your Redis storage.

Expected result: 
RDM shows the contents of the key.

Actual Result: 
RDM crashes.

**Comment by erizzo** [comment]
I'm also experiencing this, although my data set only recently started having these large values so I don't know if earlier versions of RDM had the same problem.
Is there a way to associate the crash report that RDM tells me it is sending to an issue like this one?

**Comment by oliversalzburg** [comment]
I sent dozens of reports over the past months. Given that this is still an issue in the latest 0.9 release and the responsiveness on the issue tracker, I doubt this will ever be addressed.

redis-commander works without crashing.

**Comment by uglide** [comment]
@oliversalzburg What kind of data do you store in keys? (JSON/Plain Text/Binary, etc)

**Comment by oliversalzburg** [comment]
@uglide JSON

**Comment by erizzo** [comment]
In my case, keys are plain text and values are Hashes, with a key named "value" whose value is JSON.

**Comment by uglide** [comment]
@oliversalzburg @erizzo 
Could you try new build https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.636/artifacts ?

**Comment by oliversalzburg** [comment]
@uglide When viewing keys in "Plain Text" mode, it works really well. Switching to "JSON" mode will turn the application into "Not Responding" state (and it did not recover even after a couple of minutes).

The key in question is a 1.8 MB JSON object.

**Comment by uglide** [comment]
I will continue to work on fixes for it https://github.com/uglide/RedisDesktopManager/pull/3929

**Comment by uglide** [comment]
First issue here: https://github.com/uglide/RedisDesktopManager/issues/3704

**Comment by oliversalzburg** [comment]
@uglide If there's anything I can do to help, please let me know. It's not clear to me how to run RDM through, for example, Visual Studio to debug it. But I'm sure I could figure it out if that would help you somehow.

**Comment by LeiYangGH** [comment]
You can find some crashed logs from windows log event viewer.
