### ISSUE TITLE
ERR unknown command 'scan' 

### ISSUE THREAD

**Issue by byronv5** [redis/RedisDesktopManager#3922]
RDM Version: v0.8.8.384<br>
Environment (Windows 10): <br>

Steps to reproduce:
1.click db0 (180)
2.alert connections tree error  ,shows "ERR unknown command 'scan' "
3.then alert keys error,shows the same info as above

but in a command-line environment it works。
i dont kown how to send pics,susks!!!

**Comment by uglide** [comment]
Whick version of redis-server do you use?

**Comment by byronv5** [comment]
3.0

**Comment by byronv5** [comment]
@uglide ，redis 2.8.19
and ‘scan’ available since version2.8

**Comment by byronv5** [comment]
ok，I see!
'scan' available since 2.8.0. @uglide ,tku

**Comment by uglide** [comment]
It's your redis-server config issue

**Comment by byronv5** [comment]
and how to fix

**Comment by uglide** [comment]
You need to double check redis-server version and make sure that scan command is allowed in redis-server configuration
