### ISSUE TITLE
Trying to list keys from remote server results in an infinite loop

### ISSUE THREAD

**Issue by oilers** [redis/RedisDesktopManager#3925]
RDM Version: 0.9.0-dev
Environment (OS name and version): Mac OS Sierra
Redis Server Version: 3.2.8

Steps to reproduce:

1. Add new connection

2. try to load keys from db0

Expected result: 
The keys are loaded

Actual Result: 
Log is filled with the following and nothing ever loads:
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61
Run command: "scan 0 MATCH * COUNT 10000"  in db  0  with timeout  60000
Bytes written to socket 61

**Comment by uglide** [comment]
Could you please provide output for `INFO` command?

**Comment by oilers** [comment]
Sure:
```
# Server
redis_version:3.2.8
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:41f8b9d1c13c10de
redis_mode:standalone
os:Linux 4.4.0-83-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:5.4.0
process_id:2110
run_id:876ff84e400c8d391092cf13e9d6da916730c69f
tcp_port:6379
uptime_in_seconds:8267559
uptime_in_days:95
hz:10
lru_clock:15779693
executable:/usr/local/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:2
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:85916736
used_memory_human:81.94M
used_memory_rss:334974976
used_memory_rss_human:319.46M
used_memory_peak:1151185712
used_memory_peak_human:1.07G
total_system_memory:8369844224
total_system_memory_human:7.80G
used_memory_lua:67584
used_memory_lua_human:66.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:3.90
mem_allocator:jemalloc-4.0.3

# Persistence
loading:0
rdb_changes_since_last_save:3
rdb_bgsave_in_progress:0
rdb_last_save_time:1508951703
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:30592904
total_commands_processed:32065870
instantaneous_ops_per_sec:0
total_net_input_bytes:3064952334
total_net_output_bytes:43802406777
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:484773
sync_full:334
sync_partial_ok:0
sync_partial_err:0
expired_keys:45762
evicted_keys:0
keyspace_hits:13814674
keyspace_misses:49854
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:3064
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:500410481
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:500300795
repl_backlog_histlen:109687

# CPU
used_cpu_sys:3053.28
used_cpu_user:4863.17
used_cpu_sys_children:717.64
used_cpu_user_children:7028.30

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=47145,expires=0,avg_ttl=0
```

**Comment by oilers** [comment]
I did do some digging into the source code and was able to work around it by setting the initial scan to pull > # of keys in my cluster (50000 in my case).  It appears to be something wrong with the way it iterates through the keys involving the cursor.

**Comment by oilers** [comment]
I was able to fix it. https://github.com/uglide/qredisclient/tree/ce0a2083437738255183f3f81b128db1f47b7a79/src/qredisclient#L404 . This need to be `processScanCommand(newCmd, callback, result);`

**Comment by uglide** [comment]
Fixed, thanks!
