### ISSUE TITLE
windows 10 64bit display adaptation issue

### ISSUE THREAD

**Issue by xijianglouis** [redis/RedisDesktopManager#3932]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. install redis-desktop-manager-0.8.0.3844 or higher version

2. current using redis-desktop-manager-0.8.8.384.exe

Expected result: 

Actual Result: 
Mouse and content dislocation (redis-desktop-manager-0.9.0.616.exe same issue)
![image](https://user-images.githubusercontent.com/15090421/32772728-bea3b722-c961-11e7-9c3b-beaf274be885.png)

**Comment by uglide** [comment]
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3876
