### ISSUE TITLE
Add support for ISCAN command (aliyun cloud)

### ISSUE THREAD

**Issue by linlz-** [redis/RedisDesktopManager#3933]
RDM Version: v0.8.8.384
Environment (OS name and version): win10
Redis Server Version: redis_version:2.8.19

Steps to reproduce:

1. scan 0 MATCH * COUNT 10000

2. ...

3. ...

Expected result: 

Actual Result: (error) ERR unknown command 'scan'

**Comment by uglide** [comment]
Could you provide output of `SCAN 0 MATCH * COUNT 10000` in redis-cli ?

**Comment by linlz-** [comment]
redis-cli also can't !

because Ali cloud is not only master slave redis. Does the cluster need to support the iSCAN command and support it?

https://help.aliyun.com/knowledge_detail/51306.html

iscan and scan are the same.

![image](https://user-images.githubusercontent.com/4684960/32976986-571f91f0-cc56-11e7-9bff-338a82ae5ce7.png)

**Comment by uglide** [comment]
@linlz- thanks for info. I will fallback to ISCAN in cases when SCAN returns `ERR unknown command 'scan'`

**Comment by linlz-** [comment]
thank you

**Comment by uglide** [comment]
@linlz- Could you test this build with ISCAN support https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.658/artifacts ?

**Comment by linlz-** [comment]
![image](https://user-images.githubusercontent.com/4684960/34404920-f12203ae-ebe2-11e7-916b-bf43f56b8fde.png)

The same mistake

**Comment by linlz-** [comment]
@uglide

**Comment by tomazi776** [comment]
@uglide Up. Why does RDM have problems with command "iscan"on Windows 10 with latest stable version for windows 2.4.5 64 bit? And how to fix it?
Screen:
![obraz](https://user-images.githubusercontent.com/30938637/98444244-e0d23d00-2110-11eb-9d5a-c7f7f9e8dbc0.png)
