### ISSUE TITLE
[feature request] building on elementary os loki

### ISSUE THREAD

**Issue by araker** [redis/RedisDesktopManager#3936]
RDM Version: 0.9<br>
Environment (OS name and version): elementary os 0.4.1. Loki <br>
Redis Server Version: <br>

Steps to reproduce:

1. I'm using the install guide from http://docs.redisdesktop.com/en/latest/install/#build-from-source 

2. When using the ./configure command I get the message 'your operational system is not supported!' 

Are there key differences between Ubuntu 16.04 and elementary OS that prevent redis desktop manager from working?

**Comment by uglide** [comment]
Hello @araker 
Supported OS versions list is hardcoded, you can try to modify `configure` script to make it work on elementary os https://github.com/uglide/RedisDesktopManager/blob/0.9/src/configure

**Comment by rismanrp** [comment]
@araker 

For elementary OS Loki you can hard code these lines into the `configure` file (after "`GetOSVersion`"):

```
os_VENDOR="Ubuntu"
os_PACKAGE="deb"
os_RELEASE="16.04"
os_CODENAME="xenial"
```

**Comment by araker** [comment]
Thanks, you both. I will give it a try.

**Comment by uglide** [comment]
I don't have time to update/test configure for Loki OS but will be happy to merge PR with Loki support.
