### ISSUE TITLE
Recursive node in Desktop Manager UI on Windows 10

### ISSUE THREAD

**Issue by CastleW** [redis/RedisDesktopManager#3940]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): Windows 10 Enterprise <br>
Redis Server Version: 3.0.501<br>

Steps to reproduce:

1. Flush the database.

2. ZADD "A:New:Key:::" 1.234 key1

3. View the database in the UI and it keeps opening more and more nodes.

Expected result: 
 Nodes 'A', 'New' and 'Key'

Actual Result: 
 Nodes 'A', 'New' and 'Key',  Nodes 'A', 'New' and 'Key',  Nodes 'A', 'New' and 'Key',  Nodes 'A', 'New' and 'Key' and it keeps on going.

**Comment by uglide** [comment]
It was fixed in 0.9 branch

![image](https://user-images.githubusercontent.com/1655867/34294951-83384ab6-e713-11e7-8c10-63418a7c1165.png)
