### ISSUE TITLE
Invisible texts in 4k display

### ISSUE THREAD

**Issue by halaei** [redis/RedisDesktopManager#3945]
RDM Version: Latest compiled from source
Environment (OS name and version): Ubuntu 17.10
Redis Server Version: irrelevant

Steps to reproduce:

1. Open rdm in a display with resolution 3840x2160 (scale 200%)

Expected result: Things should have been rendered as anyone expect. Text should be scaled, ...

 Result: look at the screenshot. Texts are too small. Texts on the buttons and tabs are cropped.
![screenshot from 2017-12-16 01-15-50](https://user-images.githubusercontent.com/7089140/34061793-f25732c8-e1fe-11e7-915c-72b4a0880a1e.png)

**Comment by halaei** [comment]
![screenshot from 2017-12-16 01-20-00](https://user-images.githubusercontent.com/7089140/34061906-4528069e-e1ff-11e7-9b1d-af5db67a322d.png)

**Comment by XCanG** [comment]
I have similar issue, but on Windows 10, for me if value is a string and I see string field, it invisible, while I can copy it and paste in other application and normally see it. This also applied on dialog for adding new values.
I don't think it related on monitor, but anyway I have 1920x1200 and RedisDesktop not maximized.

**Comment by uglide** [comment]
@XCanG your issue is related to different problem https://github.com/uglide/RedisDesktopManager/issues/3876

**Comment by jaider** [comment]
Thanks, same issue here, even though mine is not scale just using different resolution.
![image](https://user-images.githubusercontent.com/34106843/39071274-4c034b96-449b-11e8-85a2-72c872d8b260.png)
![image](https://user-images.githubusercontent.com/1471688/39071670-d4067260-449c-11e8-99f1-016a876e0138.png)
![image](https://user-images.githubusercontent.com/1471688/39071681-da2e7836-449c-11e8-9cbe-78068cf5b077.png)

**Comment by jaider** [comment]
Wow 0.9.2 Looks fine! thanks! :sunglasses:

![image](https://user-images.githubusercontent.com/1471688/39071980-d6075920-449d-11e8-9c10-022c075ef56b.png)
