### ISSUE TITLE
Redis Desktop Manager Crashed

### ISSUE THREAD

**Issue by DKDevOps** [redis/RedisDesktopManager#3950]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): Windows 7 Enterprise Service Pack 1 <br>
Redis Server Version: 4.0.0 - Ubuntu 16.04.2 LTS<br>

Steps to reproduce:

Redis Desktop Manager crashed on startup, does not load the application.

New Redis Desktop Manager is sending crash report directly to developers. This report will help us improve the stability in the feature.

Uploaded 81 of 81 KB

![redisdm](https://user-images.githubusercontent.com/29336474/34337177-5d61584c-e983-11e7-9be5-ebd7237e6a20.JPG)

**Comment by xiaodaoM** [comment]
have  you solved the problem? i have also met this quetion!

**Comment by DKDevOps** [comment]
Somehow it is working now. As instructed I updated graphic drivers and post few restarts, it worked.
