### ISSUE TITLE
Can't choose identity file from .ssh directory

### ISSUE THREAD

**Issue by talyguryn** [redis/RedisDesktopManager#3951]
RDM Version: 0.9.0-alpha4
Environment (OS name and version): macOS High Sierra Version 10.13.2 (17C88)
Redis Server Version: 3.0.6

Steps to reproduce:

1. Press «Connect to Redis Server»

2. Choose «SSH Tunnel»

3. Press «...» button on for Private Key field

Expected result: 
![screen shot 2017-12-28 at 13 34 37](https://user-images.githubusercontent.com/15259299/34408270-e6211ad0-ebd3-11e7-9149-c22e0c99ee66.png)

Actual Result: 
![screen shot 2017-12-28 at 13 31 50](https://user-images.githubusercontent.com/15259299/34408272-e82e49b0-ebd3-11e7-877b-e7bdbebd4c2c.png)

**Comment by uglide** [comment]
Hm, I cannot change it by default, but it's possible to make it visible with `⌘ + Shift + .`
