### ISSUE TITLE
RDM saves credentials in plain text

### ISSUE THREAD

**Issue by 7twin** [redis/RedisDesktopManager#3955]
RDM Version: 0.8.8.384
Environment (OS name and version): Windows 10
Redis Server Version: Stable (4.0)

Steps to reproduce:

1. Create connection

2. Setup SSH Tunnel with private key and password

3. Connect

4. Crendetials will be saved in plaintext in connections.json

It would be nice if RDM would ask for the password on connection like WinSCP, not save it in plaintext. I did try not adding a password, but then RDM just fails to connect, instead of asking for it.

**Comment by LordZardeck** [comment]
Also, when/if this ever gets implemented, it would be nice if the password field was clarified to be the SSH key password and no the ssh user password. I spent quite a long time trying to figure out why it couldn't connect, only to realize it wasn't using the ssh key in mac's keystore.

**Comment by uglide** [comment]
"Ask for password" was implemented and will be released in RDM 2021.9. Feel free to share any additional feedback in this or new issue. Thanks!
