### ISSUE TITLE
Error message 0xc000007b on start on Windows Server 2012R2

### ISSUE THREAD

**Issue by Flohack74** [redis/RedisDesktopManager#3956]
RDM Version: 0.8.8.384
Environment (OS name and version): Windows Server 2012 R2
Redis Server Version: n/a

The application wont start for me:
![image](https://user-images.githubusercontent.com/16186470/34865775-43a1f718-f77a-11e7-9353-7701aeb9bbbf.png)

**Comment by uglide** [comment]
Try to reinstall vcredist_x86.exe

**Comment by Flohack74** [comment]
Can you tell me which C redist version you are using ATM? I got a couple of them lying around...

**Comment by uglide** [comment]
Visual studio 2015

26 янв. 2018 г. 1:41 ПП пользователь "Florian Leeber" <
notifications@github.com> написал:
