### ISSUE TITLE
Don't support redis cluster in these release?

### ISSUE THREAD

**Issue by iSwfe** [redis/RedisDesktopManager#3962]
RDM Version: 
  The lastest.
Environment (OS name and version): 
  macOS 12.12 Serria
Redis Server Version: 
  v3.0.7

Steps to reproduce:
  1. Start redis cluster 7001 to 7006 on a server.
  2. Open the RDM,create a connection to 7001 and type the password.
  3. It just show one db name db0.

Expected result: 
  Connect to redis cluster and use normally.

Actual Result: 
  But no.

**Comment by uglide** [comment]
@iSwfe Currently RDM only has limited redis cluster support, it doesn't show any shards but allows you to view/edit keys in the entire cluster.
