### ISSUE TITLE
Redis CPU usage 100%

### ISSUE THREAD

**Issue by gnanm** [redis/RedisDesktopManager#3964]
We have a Redis Server running on Azure Cloud. Every 2-3 days, the Redis Service CPU usages goes to 100%. Redis performs and responds when its CPU usage is below 40-50%. When it reaches above 40%, it goes straight up to 100% within few minutes. We checked the connection and it stays in between 10 - 15. The number of operations is normal. As the service is deployed in Azure cloud, we couldn't do much on capturing the log. Thanks in advance.
![cpu_issue](https://user-images.githubusercontent.com/26423348/35425524-5b64f6d4-0229-11e8-8549-b58963814e9c.png)

**Comment by uglide** [comment]
Hello, how it is related to RDM? Try to check redis slow log.
