### ISSUE TITLE
UI: Wider area for entry keys

### ISSUE THREAD

**Issue by amadare42** [redis/RedisDesktopManager#3967]
Seems that area for key names have fixed width even considering that its parent container can be extended. It a bit inconvenient to work with keys with a fair bit of namespaces:
![screenshot](https://user-images.githubusercontent.com/3945692/35465403-56d65834-0304-11e8-90d3-3ea9438f493e.png)

It would be preferable if current value for list width was minimal value and could be extended with parent container.

I have win10 and 2 displays(4k & FullHD) in case this is specific to this configuration somehow.

**Comment by uglide** [comment]
Hello, it was fixed in 0.9 branch
