### ISSUE TITLE
RDM.exe application error

### ISSUE THREAD

**Issue by fireguy** [redis/RedisDesktopManager#3974]
RDM Version: 0.8.8.384<br>
Environment (OS name and version): Windows 7 x64 v6.1.7601<br>
Redis Server Version: unkown<br>

Steps to reproduce:

1. install completely

2. run the application

Expected result: enter the interface of RDM

Actual Result: pop-up a window like below
![tim-20180202080642](https://user-images.githubusercontent.com/3241354/35710118-aeebf93e-07f0-11e8-983a-fdc2d53c5979.png)

**Comment by fireguy** [comment]
RDM Version: 0.9.0.684 
install and run application is ok, but can not get connection and log is:

2018-02-02 08:21:42 : App log init: OK
2018-02-02 08:21:47 : Connection: Cancel running commands
2018-02-02 08:21:47 : Connection: Disconect on error: Connection error: The proxy type is invalid for this operation
2018-02-02 08:21:47 : Connection: newDDD > connection failed

**Comment by bi-kai** [comment]
same error, no avaliable version at all!!!

**Comment by uglide** [comment]
@fireguy issue with proxy will be fixed some day. You can track progress here https://github.com/uglide/RedisDesktopManager/issues/3841

For now you can try to disable proxy

**Comment by bi-kai** [comment]
Tried many version of it, helpless.
Found another software name `Medis`, and it's pretty good.
