### ISSUE TITLE
Opening/closing folders in the explorer view unreliable

### ISSUE THREAD

**Issue by mjgabriel** [redis/RedisDesktopManager#3975]
RDM Version: 0.9.0.684 <br>
Environment (OS name and version): Windows 10 Build 1709<br>
Redis Server Version: 3.0.3<br>

Steps to reproduce:

Simple, open and close folders, doesn't seem to be a particular sequence of events. Sometimes they open (or close), other times it doesn't. Folders with only a few keys (or 1) to folders with many keys to display.

By folders I mean the yellow folders by key segments.

Expected result: 
Click to open/collapse, should open or collapse given current state.

Actual Result: 
Sometimes opens/collapses, other times doesn't.

**Comment by uglide** [comment]
@mjgabriel Thanks for the issue. Will be fixed in 0.9.1

**Comment by uglide** [comment]
@mjgabriel Could you test https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.699/artifacts ?

**Comment by uglide** [comment]
![35977275-46627b72-0ceb-11e8-88a0-0d4f3a6a939d](https://user-images.githubusercontent.com/1655867/35978629-f0b8d6b8-0cee-11e8-8a2d-59c020089d2d.png)


With enabled and disabled new option called "Use server-side optimized keys loading"

**Comment by ssjunior** [comment]
@uglide Just FYI, I did a fresh build (MacOSX) from the updated repo and this behaviour is similar. In fact it is slight different, once opened (folder and db's) it will not close.

**Comment by uglide** [comment]
Should be fixed now in 0.9.0-1

**Comment by mjgabriel** [comment]
@uglide Sorry for not responding sooner, I missed the notification. I grabbed 0.9.0.738 and it appears to be functioning properly/as expected. Thank you.
