### ISSUE TITLE
rdm.exe error

### ISSUE THREAD

**Issue by dcdlove** [redis/RedisDesktopManager#3976]
RDM Version: <br>
Environment (OS name and version): windows server2012 R2 Standard<br>
Redis Server Version: 0.9.0.684<br>

Steps to reproduce:

![tim 20180203105301](https://user-images.githubusercontent.com/10043691/35762393-bc1c87fa-08d0-11e8-92e6-0c585660a38f.png)

Expected result: 

Actual Result:

**Comment by uglide** [comment]
Could you please try to reinstall Visual Studio 2015 Redistrib package?
