### ISSUE TITLE
how to download the 0.9.0.686?

### ISSUE THREAD

**Issue by jacksonwj** [redis/RedisDesktopManager#3977]
RDM Version: 0.9.0.684<br>
Environment (OS name and version): Windows 7 Pro x64<br>
Redis Server Version: 4.0.6<br>

How can I download the **0.9.0.686**?

The version is **0.9.0.686** from official website download page, but I got 404 page from github when I click it.

![image](https://user-images.githubusercontent.com/61455/35765015-ea5e3d7c-08f6-11e8-9f2d-6658878fb138.png)

Then I goto the Github Releases page, the newest file is **0.9.0.684**.

![image](https://user-images.githubusercontent.com/61455/35765036-5880ddb4-08f7-11e8-929a-b4df61261838.png)

Maybe the **0.9.0.686** fixed the bug(**0.9.0.684 missing file: libeay32.dll and ssleay32.dll**).

How can I download the **0.9.0.686**?

**Comment by uglide** [comment]
It's just typo on site. Fixed now. Thanks for reporting issue
