### ISSUE TITLE
View as: MessagePack will be removed in 0.9.0?

### ISSUE THREAD

**Issue by jacksonwj** [redis/RedisDesktopManager#3978]
RDM Version: 0.9.0.684<br>
Environment (OS name and version): Windows 7 Pro x64<br>
Redis Server Version: 4.0.6<br>

**View as: MessagePack** will be removed in **0.9.0.x**?

**Comment by uglide** [comment]
MessagePack was moved to native value formaters https://github.com/RedisDesktop/rdm-native-value-formatters
More info how to enable here: http://docs.redisdesktop.com/en/latest/features/#native-value-formatters
