### ISSUE TITLE
redisdesktopmanages doesn't unzip values

### ISSUE THREAD

**Issue by ma3yta** [redis/RedisDesktopManager#3979]
RDM Version: 0.9.0.684<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. Open gzipped value

Expected result: 
app unzip value and show data
Actual Result: 
app shows value as hex

**Comment by akalongman** [comment]
Same for PHP serialized data which contains binary symbols. I wrote custom formatter, but cannot switch on that, app shows value as hex

**Comment by uglide** [comment]
@Ma3yTa GZIP value formatter was moved to native value formaters repo https://github.com/RedisDesktop/rdm-native-value-formatters
More info how to enable here: http://docs.redisdesktop.com/en/latest/features/#native-value-formatters

**Comment by akalongman** [comment]
@uglide I think you did not understand the problem. We can not switch formatter from HEX to anything else

**Comment by uglide** [comment]
@akalongman Thanks for the update. I've created new issue #3998
