### ISSUE TITLE
RDM on windows : Openssl is missing. Please install Openssl

### ISSUE THREAD

**Issue by Itoktsnhc** [redis/RedisDesktopManager#3980]
RDM Version: 0.9.0.616
Environment (OS name and version): Windows 10 x64     Version	10.0.16299 Build 16299
Redis Server Version: Azure Redis Cache With SSL Port

Steps to reproduce:

1. Connet to Redis Server with RDM
![image](https://user-images.githubusercontent.com/11204672/35787664-c597632c-0a6a-11e8-9f48-803550d73280.png)

2.
![image](https://user-images.githubusercontent.com/11204672/35787685-ef18af08-0a6a-11e8-8840-2c8e081f4af4.png)

![image](https://user-images.githubusercontent.com/11204672/35787656-b3873a2c-0a6a-11e8-8837-80c4552ad51f.png)

**Comment by h-h-** [comment]
Same here. RDM Version 0.9.0.684 (trying to download 0.9.0.686 not possible because of error 404).
Win 10 Version 10.0.16299.192

I installed latest OpenSSL Version 1.1.0g from https://slproweb.com/download/Win64OpenSSL-1_1_0g.exe but error stays the same. I tried both: Installing dlls into windows system path and into /bin folder.

Please help

**Comment by ConcatenatedNonsense** [comment]
Can confirm that running as Administrator does not prevent this bug.

**Comment by billycc** [comment]
I also have this issue on win10 with rdm 0.9. Not sure if this is related or not, but in 0.8.8.384 I had a single pem for the 3 certs (public, authority, private). That worked for me to connect to redislabs hosted connection. After getting 0.9 upgrade prompt, I installed and opened the new app, but the connection to redis failed; I tried splitting the pem into 3 files, but same missing openssl error.

I downgraded back to rdm 0.8 and seems to be working again.

**Comment by nlarion** [comment]
Just thought I'd pile on here because the new version looks neat and I'd like to use it :) Me and my whole team uses rdm on windows 10 and can confirm after upgrading we all receive error:
![image](https://user-images.githubusercontent.com/1896858/35893503-33d80438-0b63-11e8-8b23-fe812edee3a1.png)

**Comment by mykolad** [comment]
Same issue for me.
On one machine Redis Desktop Manager works well, on another - problem with OpenSSL.

OpenSSL command line tools are installed on my machine (and available via PATH env variable)

**Comment by paval-tech** [comment]
Have same issue after update RDM to 0.9.0 version

**Comment by chs2000** [comment]
Also I have same issue after update RDM to 0.9.0 version
RDM Version 0.9.0.684
Windows 10 Version 1709 build 16299.192

**Comment by TylerAngell** [comment]
Hack until fix:

Download OpenSSL and copy libeay32.dll and ssleay32.dll to the same folder as rdm.exe (for me it was C:\Program Files (x86)\RedisDesktopManager)

This is for version 0.9.0.684

**Comment by dougludlow** [comment]
Copying those dlls work for me, unfortunately. Reverting to an older version...

**Comment by TylerAngell** [comment]
After adding the dlls you’ll need to restart redis desktop manager. Trying to connect again with the app open won’t do it.

**Comment by mleziva** [comment]
Also getting this error with version 9.0.684 on windows

**Comment by nickjbauer** [comment]
I realize this is a different issue, however my googling brought me here, so maybe this can help others?
On startup, i get: "The ordinal 354 could not be located in the dynamic link library LIBEAY32.dll"

Tried the hack, just moves the problem for me.  Getting "The ordinal 4046 could not be located in the dynamic link library LIBEAY32.dll"  Tried DLLs from openssl-0.9.8h from http://gnuwin32.sourceforge.net/packages/openssl.htm  The one that comes with RDM is ver 1.0.2c.  I think if the author can provide the exact version of the DLL used when compiling, that might help.
windows 7 system.

**Comment by uglide** [comment]
Fixed in 0.9.0-2
