### ISSUE TITLE
Broken download link on website

### ISSUE THREAD

**Issue by oliversalzburg** [redis/RedisDesktopManager#3981]
Website links to: `https://github.com/uglide/RedisDesktopManager/releases/download/0.9.0/redis-desktop-manager-0.9.0.686.exe`
Correct link: `https://github.com/uglide/RedisDesktopManager/releases/download/0.9.0/redis-desktop-manager-0.9.0.684.exe`

**Comment by uglide** [comment]
Fixed. Thanks for reporting bug
