### ISSUE TITLE
0.9.0 suggest to update to 0.9.0

### ISSUE THREAD

**Issue by oliversalzburg** [redis/RedisDesktopManager#3982]
I just installed 0.9.0.684. When I open it, I get a prompt to install 0.9.0.

![image](https://user-images.githubusercontent.com/1658949/35803620-b257770c-0a74-11e8-93ce-893904b72268.png)

**Comment by uglide** [comment]
Sorry for this :) Should be fixed now.

**Comment by oliversalzburg** [comment]
@uglide Thanks. Great job :)
