### ISSUE TITLE
Flush cache option no longer available

### ISSUE THREAD

**Issue by oliversalzburg** [redis/RedisDesktopManager#3983]
Prior to 0.9.0, the context menu of a database contained a "Flush DB" option. This options seems to have been removed in 0.9.0. I miss it 😢

**Comment by PedroNunoSantos** [comment]
I really miss this one too.

**Comment by uglide** [comment]
Will fix it in 0.9.1

**Comment by richhosek** [comment]
How can we get a previous version until the fix if available?

**Comment by PedroNunoSantos** [comment]
https://github.com/uglide/RedisDesktopManager/releases
Version 8 still has it, i am using it now.

**Comment by gdoron** [comment]
@uglide thanks a ton mate!

**Comment by thekingofcity** [comment]
I switch back to 0.8.x and when I see this -> Thank god.
The missing option isn't a feature.
