### ISSUE TITLE
Pressing up key in terminal no longer loads previous commands

### ISSUE THREAD

**Issue by nickbuckel** [redis/RedisDesktopManager#3984]
RDM Version: 0.9.0.684
Environment (OS name and version): Win 10

Steps to reproduce:

1. Connect to a server
2. Open the terminal
3. Execute a command, for example flushall
4. press up arrow on keyboard

Expected result: 
flushall command should appear in current terminal

Actual Result: 
cursor moves up a row on the terminal output

**Comment by uglide** [comment]
it's regression in 0.9.0, will be fixed in 0.9.1 
You can track progress here https://github.com/uglide/RedisDesktopManager/issues/3754
