### ISSUE TITLE
We need a Chinese mirror download address

### ISSUE THREAD

**Issue by muyu66** [redis/RedisDesktopManager#3986]
amazon s3 download speeds in China unbearable. I generally use the download service in the cloud download abroad, and then return to China. I think such excellent software should be more widely disseminated in China. So I suggest to provide China download address, if not convenient, I at an appropriate time to provide a download mirror to help you

**Comment by uglide** [comment]
@muyu66 Thanks for reaching me. Which alibaba cloud location will work best for china users?
https://www.alibabacloud.com/product/oss?spm=a3c0i.99636.675768.dnavproductsb1.6ba7604eto8wKv#pricing

**Comment by kenyxy** [comment]
yes, store a copy in alibabacloud OSS is a great idea.

**Comment by muyu66** [comment]
@uglide  I think "华东1" is the best, because in "华东1" the most developed economy and the Internet, most of the Internet companies are here.

**Comment by uglide** [comment]
@muyu66 thanks for the help. Will do

**Comment by uglide** [comment]
Added https://github.com/uglide/RedisDesktopManager/releases/tag/0.9.0-4
