### ISSUE TITLE
the front or Resolution is error

### ISSUE THREAD

**Issue by flykarry** [redis/RedisDesktopManager#3987]
RDM Version: 0.9.0
Environment (OS name and version): windows7
Redis Server Version: 4.0.8

Steps to reproduce:

![image](https://user-images.githubusercontent.com/14309127/35843794-21da31c0-0b45-11e8-9147-a8b7bacbb429.png)

**Comment by uglide** [comment]
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3876
