### ISSUE TITLE
Application is crashed when Cluster db is selected

### ISSUE THREAD

**Issue by selcukusta** [redis/RedisDesktopManager#3988]
RDM Version: 0.9.0.684<br>
Environment (OS name and version): Windows 10 Version 1607 (OS Build 14393.1593)<br>
Redis Server Version: 4.0.6<br>

Steps to reproduce:

![Reproduce](https://media.giphy.com/media/3o7WIImt4b5kl2tQpa/giphy.gif)

**Comment by selcukusta** [comment]
In addition, it works on 0.8.8.384 version.

EDİT: But can't get any information about keys.

`2018-02-06 12:27:18 : Connection: CMS - Redis Cluster > [runCommand] select 1`
`2018-02-06 12:27:18 : Connection: CMS - Redis Cluster > Response received : -ERR SELECT is not allowed in cluster mode`

**Comment by uglide** [comment]
@selcukusta Could you try this build https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.749/artifacts?

**Comment by uglide** [comment]
Should be fixed in 0.9.0-4

**Comment by selcukusta** [comment]
@uglide thank you, works like a charm.
