### ISSUE TITLE
RDM crashes on closing server info tab

### ISSUE THREAD

**Issue by vicking** [redis/RedisDesktopManager#3989]
RDM Version: _0.9.0.684_<br>
Environment (OS name and version): _Windows 10.1709 (build 16299.192)_<br>
Redis Server Version: _2.x - 3.x_<br>

Steps to reproduce:

1. Open server info (mouse click or Ctrl+I)
2. Wait data is loaded
3. Close tab 

Expected result: _Tab closes_

Actual Result: _RDM crashes_

If I try to close the tab before info has been loaded it works as expected.

**Comment by vicking** [comment]
Still, have the same issue in 0.9.0.751

**Comment by uglide** [comment]
@vicking Do you use SSH tunnel?

**Comment by uglide** [comment]
Root cause of the problem is #4000

**Comment by vicking** [comment]
yep, I use SSH tunnels
