### ISSUE TITLE
Select all in key viewer not selecting all, whitespace appearing that shouldn't be there

### ISSUE THREAD

**Issue by mjgabriel** [redis/RedisDesktopManager#3990]
RDM Version: 0.9.0.684 
Environment (OS name and version): Windows 10 Build 1709
Redis Server Version: 3.0.3
Steps to reproduce:

Select all (CTRL+A) when viewing the data stored in a key does not select all. Appears that the viewer is adding whitespace where there shouldn't be any so the selection stops when it hits the whitespace.

Expected result:
Open up the key, focus to the key viewer, hit CTRL+A and all content should selected.

Actual Result:
Selection stops when it encounters whitespace (I think). There shouldn't be whitespace in our key data.

![image](https://user-images.githubusercontent.com/6546788/35873004-53602ae2-0b1d-11e8-89e9-7225808f90f9.png)

**Comment by uglide** [comment]
@mjgabriel it's side effect of workaround for viewing large values. I will add some enhancements like context menu with "Copy value" to make it easier to use

**Comment by derekadk** [comment]
This is still happening on 0.9.3.817

CTRL-A stops at the first whitespace... which isn't actually there.

![image](https://user-images.githubusercontent.com/13877884/43120606-284f5fe2-8f5e-11e8-9eab-20d59783ac5d.png)

**Comment by uglide** [comment]
"Copy Value" was added in 0.9.5
