### ISSUE TITLE
Filter and Reload not working together

### ISSUE THREAD

**Issue by Sorcy** [redis/RedisDesktopManager#3991]
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 7 64bit
Redis Server Version: 3.2.3

**Steps to reproduce:**

1. Open a Redis DB in RDM (about 250.000 keys)
2. Add a filter to it. RDM correctly shows only the filtered keys
3. Hit the "reload" button on the db. RDM reloads the DB, but nothing is shown anymore.

To get the display back you have to empty the filter (which makes RDM read all the keys again), then reenter it.

**Expected result:** 

Filter should work across reloads of database.

**Actual Result:** 

Displays no keys after reload, as if none match the filter. Does not seem to be a problem with any special characters or anything, since even very basic test filters (three ascii characters) fail on reload.

**Comment by uglide** [comment]
I cannot reproduce it on latest builds. Looks like it was fixed :)

**Comment by Sorcy** [comment]
It's actually become worse for me in 0.9.1.771 ... now my filter doesn't match EVER. As soon as I set it, no keys are shown anymore.
