### ISSUE TITLE
"Reopen namespaces on reload" not working

### ISSUE THREAD

**Issue by jeremytm** [redis/RedisDesktopManager#3993]
RDM Version: 0.9.0.11
Environment (OS name and version): MacOS 10.13.3
Redis Server Version: 3.2.9

Steps to reproduce:

1. Connect to server
2. Open some sub-namespaces
3. Click server icon in sidebar nav
4. Click reload

Expected result:
Data would be reloaded without any change in UI, and any opened namespace folders would remain open.

Actual Result:
All folders in the tree are close.

**Comment by uglide** [comment]
@jeremytm Actually it's not a bug since this option works on database level only
