### ISSUE TITLE
Live update causes namespace folder opening and closing to become unreliable

### ISSUE THREAD

**Issue by jeremytm** [redis/RedisDesktopManager#3995]
RDM Version: 0.9.0.11
Environment (OS name and version): MacOS 10.13.3
Redis Server Version: 3.2.9

Steps to reproduce:

1. Connect to server
2. Open some sub-namespaces, and show enough keys so that the sidebar can be scrolled
3. Click database icon
4. Click "Live update" button
5. Between live updates, open various levels of namespaces, at least 3-4 levels deep
6. Attempt to continue to open and close various levels of namespaces

Expected result:
Add namespace folders should react quickly when opening and closing

Actual Result:
Some folders seem to work while others don't. All seems a bit sluggish compared to 0.8.x

**Comment by tschiman** [comment]
Agree with this bug. I have a redis instance with 78K keys and I'm having issues with opening and closing folders with live update turned off. v9 seems buggy in this respect.

**Comment by uglide** [comment]
Fixed in 0.9.8 (cooming soon)
