### ISSUE TITLE
some situation,  key seems to be infinite long,   redis desktop manager version v0.8.8.33

### ISSUE THREAD

**Issue by AaronFeng2014** [redis/RedisDesktopManager#4001]
In mac OS V0.8.8.33 , when i save a string to redis database, and key separate by : symbol,     i query it,  i found that the key seems to be infinite long, but actually the key is end with  1:1:1:1

<img width="801" alt="dingtalk20180209160004" src="https://user-images.githubusercontent.com/13704237/36017354-5bd50e12-0db2-11e8-81a4-85eb970c132c.png">

**Comment by uglide** [comment]
Hello @AaronFeng2014 
I was fixed in 0.9.0
