### ISSUE TITLE
Flush database option is no longer available

### ISSUE THREAD

**Issue by peorth80** [redis/RedisDesktopManager#4002]
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 10 PRO
Redis Server Version: Redis 3.2

Steps to reproduce:

1. Connect to any redis server

2. Right click over a database. In the previous version, I was able to choose "Flush database" to delete all the keys.

3. In this version, nothing happens: right click displays no menu. There's no way to flush a database with this version of the tool

Expected result: A way to flush a database

Actual Result:  No way to flush a database

**Comment by cristiammercado** [comment]
RedisDesktopManager Team deleted the "Flush Database" option. It was very convenient to use especially in development environments. If they could put it back it would be excellent.

**Comment by maw74656** [comment]
Why would they remove this important feature?!  Please bring it back!  Yes, you can do a flushdb from the console... but why have a GUI tool at all if one of the most frequent tasks requires dropping down to console?

**Comment by tmenier** [comment]
+1. I use this daily. Between this and the overall visual appearance on Windows, I'm downgrading to 0.8.

**Comment by maw74656** [comment]
@tmenier  I don't care for the look either, but if you shrink the font it gets a little better.  I do love the monitoring dashboards though.

**Comment by tmenier** [comment]
@maw74656 Yeah I messed around with the fonts a bit, it did help a little. I'm no font expert but at any size they just look hazy/blurry. System font helped, and making them smaller improved some of the icon/spacing issues. Still, the appearance leaves much to be desired. I prefer the cleanness of 0.8.

I do apologize for sounding a little harsh though. I know lots of folks have put MANY hours into this outstanding free tool and it has been invaluable to us. I don't want to downplay that - thanks to all the devs for their great work on this!

**Comment by uglide** [comment]
@tmenier 
Could you provide more details/screenshots on "hazy/blurry" issues? Do you use 4k monitor?

**Comment by gerrod** [comment]
@uglide Here's a screenshot from my installation; this is using Roboto font at size 10, using a standard (i.e. not a 4k) monitor. All the fonts/icons/etc look as if they're oversampled, or as if there's too much anti-aliasing turned on. I've tried a bunch of different fonts, Roboto seemed to be the best I could make things look.

![image](https://user-images.githubusercontent.com/865932/36522878-9d36785e-17ea-11e8-85a8-c180125fdd06.png)

Hope this helps, please let me know if you want more screenshots/details!

**Comment by uglide** [comment]
Fixed in 0.9.0-1

**Comment by uglide** [comment]
@gerrod Could you specify your hardware and display resolution? Do you use Intel CPU with GPU + NVIDIA GPU or something else?

**Comment by gerrod** [comment]
Hi @uglide - It's on a 1920x1200 monitor, Intel CPU, with a dedicated graphics card (something built by AMD I *think*... nothing very high-end - it's on my work machine, I can check for you tomorrow if you want a specific model).

**Comment by tmenier** [comment]
@uglide My apologies for not replying. I'll just say ditto to @gerrod 's comments, including the screenshot. Seems to describe my situation/observations exactly. Again, not my area of expertise, but 0.9 just doesn't "feel" like a native Windows app in terms of fonts, spacing, etc. whereas 0.8 did. Sorry, that's probably not very helpful. I'm sure I'll get used to this, and if Flush Database is coming back I'll gladly re-upgrade.
