### ISSUE TITLE
Why RDM uses Discrete Graphic Card, for what?

### ISSUE THREAD

**Issue by im-kulikov** [redis/RedisDesktopManager#4004]
RDM Version: 0.9.0.51+<br>
Environment (OS name and version): macOS 10.13.3 <br>
Redis Server Version: 3.x+<br>

Steps to reproduce:
1. Run application
2. Open activity monitor
3. See that rdm used `discrete` graphic card

Expected result: 
do not use high perfomance (discrete) graphics card

Actual Result: 
<img width="719" alt="activity monitor applications in last 12 hours 2018-02-13 14-07-37" src="https://user-images.githubusercontent.com/888650/36146980-827a3c82-10c7-11e8-92f0-9d7ec99e1821.png">

**Comment by uglide** [comment]
Hello @im-kulikov 
RDM is built with Qt and QML. QML engine provides cross-platform way to render UI, charts, etc and uses GPU if possible.

**Comment by im-kulikov** [comment]
after starting the application, the MacBook starts to boil... this is not the problem?

**Comment by im-kulikov** [comment]
there is two GPU:
- integrated
- discrete

sorry, but I don't understand, why your application uses discrete card for rendering..
I use many application, that build on top of QT and QML... but this confuse me only with this application

**Comment by uglide** [comment]
Ok, I see
I see relevant fix on SO https://stackoverflow.com/questions/17893849/qml-causing-switch-to-discrete-graphics
But I will need your help to test it since I don't have MacBook with 2 gpu

**Comment by im-kulikov** [comment]
@uglide ok
___

As I see... it work 🙂

0.9.0.51:
<img width="1403" alt="monosnap 2018-02-13 19-36-43" src="https://user-images.githubusercontent.com/888650/36161701-6594e864-10f5-11e8-81a8-7e40044f6362.png">

0.8.3:
<img width="1473" alt="redis desktop manager 2018-02-13 19-39-23" src="https://user-images.githubusercontent.com/888650/36161818-ae6ab74e-10f5-11e8-8b3a-f0e3775cb22b.png">
___

Yep.. this is fix issue
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        ...
     <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
</dict>
</plist>
```

**Comment by uglide** [comment]
@im-kulikov awesome, thanks for PR!
