### ISSUE TITLE
Can't add row in set

### ISSUE THREAD

**Issue by Michael-Stanford** [redis/RedisDesktopManager#4006]
RDM Version: 0.9.0.11<br>
Environment (OS name and version): OS X 10.13.2<br>
Redis Server Version: 3.0.6 running on Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-46-generic i686)

<br>

Steps to reproduce:

1. Create a new set

2. Select Add Row

3. Dialog appears, but it is impossible to type into it - it ignores keyboard input. 
Seems to be similar to "Can t add row in hash #3973"

Expected result: 
Should be able to type into the dialog.

Actual Result: 
Can't type into the dialog.

![screen shot 2018-02-14 at 5 53 36 pm](https://user-images.githubusercontent.com/2043732/36234666-e8941c78-11b1-11e8-9e1d-47952e9b774e.png)

**Comment by sacredwx** [comment]
same on windows

**Comment by uglide** [comment]
Fixed in 0.9.0-1
