### ISSUE TITLE
Custom Formatter does not get called on Binary data

### ISSUE THREAD

**Issue by MikeChristensen** [redis/RedisDesktopManager#4007]
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 10
Redis Server Version: 3.2.100

Steps to reproduce:

1. Create custom formatter (In my case it's a C# program).  Usage.json looks like:

`["C:\\Users\\michael.christensen\\Documents\\visual studio 2017\\Projects\\KeyViewer\\KeyViewer\\bin\\Debug\\KeyViewer.exe"]`

And my C# program is just:

```
    class Program
    {
        static void Main(string[] args)
        {
            if (args[0] == "--version")
                Console.WriteLine("1.0.0");

            if(args[0] == "decode")
            {
                Console.WriteLine(@"{ ""output"": ""The Results"", ""read-only"": ""true"", ""format"": ""plain_text"" }");
            }
        }
    }
```

2. Create a new string key in Redis, such as TestKey, with a value of "Hello".  View the key, and select your formatter in the "View as:" dropdown.  You'll get the "The Results" string back, so the formatter was called.

3. Now create a key with binary data in it, such as a GZIP'ed compressed string of JSON.  Now view the key and select your formatter.

Expected result: I should see "The Results", and the Base64 encoded version of my binary data should be passed into my formater.

Actual Result: It just goes back to "HEX" in the VIew As dropdown, and displays the data using the built in formater.

**Comment by MikeChristensen** [comment]
Added some logging code to my formater which confirms Redis Desktop Manager doesn't even call my program at all when I select the formater with binary data.  This must be possible, since the python-decompresser formatter works with binary data.  I'm guessing this is just broken on the current build.

**Comment by MikeChristensen** [comment]
Looks like this might be related to issue [3998](https://github.com/uglide/RedisDesktopManager/issues/3998)

**Comment by uglide** [comment]
@MikeChristensen yes it's related issues
