### ISSUE TITLE
GUI not rendered at all on projected screens

### ISSUE THREAD

**Issue by vincentvulog** [redis/RedisDesktopManager#4009]
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 10 Pro + Dual screen projected throught an USB3 DisplayLink Adapter
Redis Server Version: N/A

Steps to reproduce:

1. Install RDM

2. Project your computer screen (Windows + P) -> Remote only

3. Start RDM

Expected result: RDM should be properly rendered

Actual Result: RMD Windows are complitly blank
(RMD runs and render properly when displayed on a non projected screen)

**Comment by uglide** [comment]
Hello @vincentvulog 
What kind of DisplayLink Adapter do you have?

**Comment by vincentvulog** [comment]
Hi,



This is a Dell docking station D1000



http://www.dell.com/en-us/shop/dell-d1000-dual-video-usb30-docking-station/apd/452-bbzi/pc-accessories





*De :* Igor Malinovskiy [mailto:notifications@github.com]
*Envoyé :* lundi 19 février 2018 10:56
*À :* uglide/RedisDesktopManager <RedisDesktopManager@noreply.github.com>
*Cc :* vincentvulog <vmirine@vulog.com>; Mention <mention@noreply.github.com
>
*Objet :* Re: [uglide/RedisDesktopManager] GUI not rendered at all on
projected screens (#4009)



Hello @vincentvulog <https://github.com/vincentvulog>
What kind of DisplayLink Adapter do you have?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uglide/RedisDesktopManager/issues/4009#issuecomment-366639577>,
or mute the thread

**Comment by uglide** [comment]
@vincentvulog

Could you try this build with new command line option:
`rdm.exe --rendering-backend software`

https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.732/artifacts

**Comment by vincentvulog** [comment]
I installed the build using the link you sent (0.9.0.732)



I ran rdm.exe --rendering-backend software



And it works.



Then i also tried tu run rdm.exe (without parameters) and it also render
correctly.



*De :* Igor Malinovskiy [mailto:notifications@github.com]
*Envoyé :* vendredi 23 février 2018 16:36
*À :* uglide/RedisDesktopManager <RedisDesktopManager@noreply.github.com>
*Cc :* vincentvulog <vmirine@vulog.com>; Mention <mention@noreply.github.com
>
*Objet :* Re: [uglide/RedisDesktopManager] GUI not rendered at all on
projected screens (#4009)



@vincentvulog <https://github.com/vincentvulog>

Could you try this build with new command line option:
rdm.exe --rendering-backend software

https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.732/artifacts

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uglide/RedisDesktopManager/issues/4009#issuecomment-368042894>,
or mute the thread

**Comment by uglide** [comment]
@vincentvulog Great!

**Comment by navossoc** [comment]
This update brought me an issue...

RDM 0.9.0.731 works
RDM 0.9.0.738 crash at startup, but works with --rendering-backend software

Windows 10.0.16299.248

I have two display adapters (notebook):
Intel HD Graphics 4000: 10.18.10.4885 (DX 11)
NVIDIA GeForce GT 630M: 23.21.13.8831 (DX 11)

I tried to run RDM on both and they crash.

**Comment by uglide** [comment]
@navossoc 0.9.0-4 with fix is just released
