### ISSUE TITLE
static assertion failed: QRedisClient requires libss2 >= 1.6.0

### ISSUE THREAD

**Issue by smamran** [redis/RedisDesktopManager#4011]
RDM Version: 0.9.0
Environment (OS name and version): Ubuntu 16.04

Steps to reproduce:

1. qmake

2. make

Expected result: Build Failing

Actual Result: 
In file included from ../3rdparty/qredisclient/3rdparty/qsshclient/qxtsshchannel_p.h:33:0,
                 from ../3rdparty/qredisclient/3rdparty/qsshclient/qxtsshchannel.cpp:55:
../3rdparty/qredisclient/3rdparty/qsshclient/qxtsshclient_p.h:43:1: error: static assertion failed: QRedisClient requires libss2 >= 1.6.0
 static_assert((LIBSSH2_VERSION_MAJOR == 1) && (LIBSSH2_VERSION_MINOR >= 6), "QRedisClient requires libss2 >= 1.6.0");
 ^
Makefile:12620: recipe for target '../bin/linux/release/obj/qxtsshchannel.o' failed
make: *** [../bin/linux/release/obj/qxtsshchannel.o] Error 1

**Comment by kiyasov** [comment]
k

**Comment by uglide** [comment]
Looks like you haven't ran configure script

**Comment by smamran** [comment]
I have ran configure script. But doesn't work.
