### ISSUE TITLE
Undefined rows on second Hash page

### ISSUE THREAD

**Issue by Tasmany** [redis/RedisDesktopManager#4014]
RDM Version: 0.9.0.684
Environment (OS name and version): win10x64 Home <br>
Redis Server Version: 4.0.6<br>

Steps to reproduce:

1. Create hash with 1483 keys

2. Open in RDM, then go (set) second page

3.  Scroll to bottom 1483 position

Expected result:  last 1483 key

Actual Result: last 1483 key, and around 527 undefined rows
![image](https://user-images.githubusercontent.com/16325401/36395762-c82c3998-15cb-11e8-936a-c09b35e6a51f.png)

**Comment by uglide** [comment]
Fixed build https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.720/artifacts
