### ISSUE TITLE
The ordinal 354 could not be located in the dynamic link library LIBEAY32.dll

### ISSUE THREAD

**Issue by nickjbauer** [redis/RedisDesktopManager#4016]
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 7
Redis Server Version: <br>

Steps to reproduce:

1.  Install RDM 0.9.0.684

2. Launch

Expected result:  Opens with no error popups

Actual Result: 
On startup, i get: "The ordinal 354 could not be located in the dynamic link library LIBEAY32.dll"

Tried the suggested hack from this issue: https://github.com/uglide/RedisDesktopManager/issues/3980

It just moves the problem for me. After downloading OpenSSL for windows from here: http://gnuwin32.sourceforge.net/packages/openssl.htm

Getting "The ordinal 4046 could not be located in the dynamic link library LIBEAY32.dll" Tried DLLs from openssl-0.9.8h from  The libeay32.dll that comes with RDM is ver 1.0.2c. 

I think if the author can provide the exact version of the DLL used when compiling, that might help.

**Comment by luisuran** [comment]
Im having the same error while trying to do
keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%\.android\debug.keystore | openssl sha1 -binary | openssl base64

**Comment by uglide** [comment]
@luis-sama how it's related to this fixed issue?
