### ISSUE TITLE
Font size problem with Windows high-DPI screen

### ISSUE THREAD

**Issue by eodin** [redis/RedisDesktopManager#4017]
RDM Version: 0.9.0.684<br>
Environment (OS name and version): Win10.0.16299.248 x64<br>
Redis Server Version: any<br>

The app looks ugly even with font size 8 on Windows high-DPI screen. My display configuration is
1. 1920x1080 125% scale (laptop screen)
2. 1920x1080 100% scale (LG display)
3. 1920x1080 100% scale (LG display)

The problem description
https://support.microsoft.com/en-us/help/3025083/windows-scaling-issues-for-high-dpi-devices

![2018-02-21_15-44-03](https://user-images.githubusercontent.com/2424164/36483505-01983fde-171f-11e8-916c-6a7e7dfdabb3.png)

**Comment by uglide** [comment]
Hello @eodin 
"ugly" is not proper description for the problem :)
Is font too large on 100% scaled LG displays?

**Comment by nickjbauer** [comment]
I can comment that when my laptop switches from low to high dpi the fonts end up way too small.  I go from 2540x1440 to 3840 x 2160 - this is when i unplug my monitor

**Comment by uglide** [comment]
Both problems were fixed in 0.9.0-3
