### ISSUE TITLE
suggestion : use json as default view mode

### ISSUE THREAD

**Issue by ad34** [redis/RedisDesktopManager#4022]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. ...

open any json key in redis desktop manager 0.9.0

2. ...

notice the issue is viewed as plain text by default

3. ...
change it to json

4...
notice the plain text mode is reenabled 

Expected result: 

Actual Result: 

Checked various strings keys as viewing it as json don't seems to cause any issue, so having json by default should not cause too much trouble and should be the default mode.

**Comment by uglide** [comment]
Formatter is memorized (again) in 0.9.0-4
