### ISSUE TITLE
RDM Crashed when upgrading to 0.9.0-3

### ISSUE THREAD

**Issue by cuongle** [redis/RedisDesktopManager#4026]
RDM Version:  0.9.0-3<br>
Environment (OS name and version): Windows 10 Professional 64x <br>
Redis Server Version:  <br>

Steps to reproduce:

1. Remove old version

2. Install new version 0.9.0-3

3. Open RDM

Expected result:  It should works normally

Actual Result: Application crashed

![image](https://user-images.githubusercontent.com/198100/36667431-b99a4cc0-1ae5-11e8-8630-834d592b3c85.png)

**Comment by uglide** [comment]
@cuongle Could you try to run RDM with command line argument
`rdm.exe --rendering-backend software`
or 
`rdm.exe --rendering-backend ""`

**Comment by cuongle** [comment]
@uglide Great! It's now working, thanks

**Comment by cloverzrg** [comment]
encountered the same problem,
`rdm.exe --rendering-backend software` work

**Comment by uglide** [comment]
Fixed in 0.9.0-4
