### ISSUE TITLE
Settings directory is not writable

### ISSUE THREAD

**Issue by bincopi** [redis/RedisDesktopManager#4028]
RDM Version: 0.9.0.684
Environment (OS name and version):  Ubuntu 16.04 LTS
Redis Server Version:  3.0.6

Steps to reproduce:

1. Install RDM successfully

2. cd /usr/share/redis-desktop-manager/bin && source /opt/qt59/bin/qt59-env.sh

3. ./rdm or sh rdm.sh

Expected result: 
Application opens without error.
Actual Result: 
An error window pops up: RDM can't save connections file to settings diretory. Please change permissions or restart RDM as administrator.
Just like this:
![error](https://user-images.githubusercontent.com/10903706/36668339-f8f18e42-1b2b-11e8-8c35-01233596928d.png)
And then I run sudo ./rdm or sudo sh rdm.sh
Another error occurred:
./rdm: error while loading shared libraries: libQt5Charts.so.5: cannot open shared object file: No such file or directory
**Forgive I am not good at English, thanks to google translate. waiting for  kind man to help me.**

**Comment by uglide** [comment]
@YYGN try to create `.rdm` folder in your home dir manually and double check that you have qt59charts-no-lgpl installed

**Comment by bincopi** [comment]
@uglide thank you very much. but `.rdm`has already exists, and qt59charts-no-lgpl installed also.

**Comment by uglide** [comment]
@YYGN try to use `ldd` to figure out what is wrong with dynamic libraries
