### ISSUE TITLE
Latest installer triggers smart screen

### ISSUE THREAD

**Issue by TCBroad** [redis/RedisDesktopManager#4029]
RDM Version: 0.9.0.738
Environment (OS name and version): Windows 10 x64 16299.248
Redis Server Version: N/A

Steps to reproduce:

1. Download installer

2. Run it

Expected result: Installer starts normally

Actual Result: 

![image](https://user-images.githubusercontent.com/1906419/36669207-02e0ac84-1aec-11e8-9c84-aead89f35e82.png)

The previous version's installer runs without issue. I followed the link to the installer provided by the application, and also independently downloaded from github and the issue it present in both.

**Comment by isgallagher** [comment]
I am also getting the same.

![image](https://user-images.githubusercontent.com/25665920/36682125-8d8db09e-1ad7-11e8-8840-292f74b80f71.png)

**Comment by uglide** [comment]
I'm still open for donations for code signing cert. More info here #3655

**Comment by TCBroad** [comment]
Was the previous installer signed? If not, how come that one didn't trigger the warning?

**Comment by uglide** [comment]
Probably Windows Defender gives up after XXXX installations on different machines :)
