### ISSUE TITLE
Does not display window

### ISSUE THREAD

**Issue by maxcap888** [redis/RedisDesktopManager#4034]
RDM Version: 0.9.0.3 <BR>
Environment (OS name and version): Windows 10 <br>
Redis Server Version: <br>

Steps to reproduce:

1. .Install Redis

2. Run

Expected result: Redis Window open

Actual Result: Nothing displayed. The window is transparent with no content

**Comment by uglide** [comment]
@maxcap888 
Please try to use this build https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.747/artifacts

**Comment by uglide** [comment]
Should be fixed in 0.9.0-4
