### ISSUE TITLE
Need previous version is no cache.

### ISSUE THREAD

**Issue by uopeydel** [redis/RedisDesktopManager#4035]
RDM Version: 9^
Environment (OS name and version): window 10
Redis Server Version: lasted

Steps to reproduce:

1. Install rdm .

2. Alway cache when connect , setting else.

3. My old pc is have redis desktop manager 0.8.8.384  but i already delete install file , that version is work and i can't find that version for download.

Expected result: Can download previous version is work.

Actual Result: Can use rdm without promblem.

**Comment by uglide** [comment]
Possible duplicate of #4026
