### ISSUE TITLE
Azure connection

### ISSUE THREAD

**Issue by erossini** [redis/RedisDesktopManager#4036]
Hi guys,
I tried your app but I can't use `Azure Redis`. The connection string is a bit complicated

> my.redis.cache.windows.net:6380,password=myp[assword=,ssl=True,abortConnect=False

Is there a way to use my connection?

**Comment by uglide** [comment]
@erossini just create connection with
host `my.redis.cache.windows.net`
port `6380`
and password `myp[assword`
with enabled SSL
