### ISSUE TITLE
click TestConnetion then app is stuck

### ISSUE THREAD

**Issue by raybz** [redis/RedisDesktopManager#4038]
RDM Version: 0.9.0-alpha4
Environment (OS name and version): macOS 10.13.3
Redis Server Version: 4.0.8

Steps to reproduce:

1. connection setting => use SSH tunnel => TestConnection (if i click this button then app not work)

Expected result: show test connection is ok or not 

Actual Result: app is not work

**Comment by uglide** [comment]
Duplicate of #4000
