### ISSUE TITLE
redis-server restart upon open connection crashes application

### ISSUE THREAD

**Issue by vadru** [redis/RedisDesktopManager#4039]
RDM Version: 0.9.0.751<br>
Environment (OS name and version): Windows [Version 10.0.16299.248]<br>
Redis Server Version: 4.0.8<br>

Steps to reproduce:

1. Connect to Redis

2. Restart redis-server instance

Expected result: state disconnected for connection

Actual Result: application crash

**Comment by daisenrong** [comment]
。。。。
