### ISSUE TITLE
Scan commands is not support by some redis-server, please help!

### ISSUE THREAD

**Issue by hzysoft** [redis/RedisDesktopManager#4040]
RDM Version 0.9.0: <br>
Environment Win10: <br>
Redis Server Version: <br>

Steps to reproduce:

1. click the db0

2. ...

3. ...

Expected result: 

Actual Result: 
![default](https://user-images.githubusercontent.com/1628323/36953226-041ea23c-2054-11e8-987b-9f93e22d7942.png)

**Comment by uglide** [comment]
@hzysoft Which version of redis-server do you use?

**Comment by hzysoft** [comment]
redis_version:2.6.14

**Comment by uglide** [comment]
@hzysoft You need to use older version of RDM or upgrade your redis server (better)

**Comment by hzysoft** [comment]
Thanks uglide
