### ISSUE TITLE
Can't add multiple rows in set or hash

### ISSUE THREAD

**Issue by jeb886** [redis/RedisDesktopManager#4042]
RDM Version: 0.9.0.760
Environment (OS name and version): Win 7 Pro 6.1 Build 7601 SP1
Redis Server Version: 3.2.5

Related to #4006 and #3973 

Steps to reproduce:

1. Add set or hash

2. Add one row

3. Try to add another row

Expected result: Can add multiple rows

Actual Result: First add is successful but in subsequent attempts you can not select the Key or Value text boxes, they do not seem to be initialized

**Comment by uglide** [comment]
@jeb886 thanks for detailed bug report
