### ISSUE TITLE
Please remove the "Flush DB" quick button 

### ISSUE THREAD

**Issue by krimark** [redis/RedisDesktopManager#4043]
Am I the only one who thinks it's really dangerous to have a "Flush DB"-quickbutton so close to the "Filter keys"-button. Doing a flush could have really bad consequences and it's really easy to click it by mistake in the quick-menu.

**Comment by uglide** [comment]
@krimark Flush db has confirmation dialog to prevent clicking it by mistake in the quick-menu.
I will make text bold and red in this dialog.
