### ISSUE TITLE
When a key type is list, can't append new row twice

### ISSUE THREAD

**Issue by blacklin** [redis/RedisDesktopManager#4046]
RDM Version: 0.9.0.760
Environment (OS name and version): Windows 7
Redis Server Version: 3.2.1

Steps to reproduce:

1. connect local redis server

2. create a new key,set type list, and append a new row

3. add a new row again,The TextEdit can't get focus and typing

Expected result: can typing value

Actual Result: i can't

**Comment by uglide** [comment]
@blacklin This bug was fixed but not released yet. Please use latest build from here https://ci.appveyor.com/project/uglide/redisdesktopmanager/branch/0.9/artifacts
