### ISSUE TITLE
Test SSH connection fails

### ISSUE THREAD

**Issue by santigarcor** [redis/RedisDesktopManager#4047]
RDM Version: 0.9.999
Environment: Ubuntu 16.04

When I try to add a new SSH tunnel connection and I click test connection, it tries to connect, but it fails. The strange thing is that with the same data I can connect through my console to the server.

Steps to reproduce:

1. Build from src.

2. Create a new ssh tunnel with pem key (I use amazon generated keypem).

3. Click Test Connection.

Expected result: 
It should show that the connection was successful.

Actual Result: 
It shows `Can't connect to the redis-server`. And the console log shows this:
```
2018-03-15 07:50:49 : Connection: Connecting to SSH host...
2018-03-15 07:50:51 : Connection: Cancel running commands
2018-03-15 07:50:51 : Connection: Disconect on error: SSH Connection error(Host Key Unknown Error): 
2018-03-15 07:50:51 : Connection: Cancel running commands
2018-03-15 07:50:51 : Connection: Disconect on error: Cannot connect to SSH host
```

**Comment by zhuziyu-old** [comment]
I have this problem, too.

**Comment by uglide** [comment]
@santigarcor @zhuziyu Which key types do you use? 
libssh2 (RDM uses it under the hood) still doesn't support ECDSA or ED25519

Related PR in libssh2 https://github.com/libssh2/libssh2/pull/248

**Comment by LiberiFatali** [comment]
I also got this error in Ubuntu 16.04 after upgrading from 0.9.0 to 0.9.3
> 2018-05-14 08:43:16 : Connection: Disconnect on error: SSH Connection error(Host Key Unknown Error):

**Comment by uglide** [comment]
@LiberiFatali please specify more details: key type, etc

**Comment by LiberiFatali** [comment]
My case is exactly the same as the first post:

> RDM Version: 0.9.999
Environment: Ubuntu 16.04

> When I try to add a new SSH tunnel connection and I click test connection, it tries to connect, but it fails. The strange thing is that with the same data I can connect through my console to the server.
> 
> Steps to reproduce:
> 
> 1. Build from src.
> 
> 2. Create a new ssh tunnel with pem key (I use amazon generated keypem).
> 
> 3. Click Test Connection.
> 
> Expected result:
> It should show that the connection was successful.
> 
> Actual Result:
> It shows Can't connect to the redis-server. And the console log shows this:
> 
> 2018-03-15 07:50:49 : Connection: Connecting to SSH host...
> 2018-03-15 07:50:51 : Connection: Cancel running commands
> 2018-03-15 07:50:51 : Connection: Disconect on error: SSH Connection error(Host Key Unknown Error):
