### ISSUE TITLE
RDM crashes

### ISSUE THREAD

**Issue by pandaeuler** [redis/RedisDesktopManager#4048]
RDM Version: 0.9 84878d1
Environment (OS name and version): maxos 10.13.3
Redis Server Version: 

Steps to reproduce:
    1. open some key

    libc++abi.dylib: Pure virtual function called!

![image](https://user-images.githubusercontent.com/13249928/37502363-49f96280-290d-11e8-9c2e-bb2ed08ae3cb.png)

Expected result: 

Actual Result: 
    RDM crashes

**Comment by uglide** [comment]
Should be fixed now
