### ISSUE TITLE
Suggestion: Add default formatter options in Setting

### ISSUE THREAD

**Issue by jacksonwj** [redis/RedisDesktopManager#4051]
RDM Version: 0.9.1.771<br>
Environment (OS name and version): Windows 10 Home 16299.309<br>
Redis Server Version: 4.0.8<br>

**Is it possible to add some options in "Setting", just like this:**
- Key default view as: (combobox)
- Value default view as: (combobox)

**The RDM will load the default setting when start running or open new tab.**

**Or set the default view as in Custom Value View Formatters' table.**

The value in My Redis is formatted by Message-Pack.

But, in the Hash value:
- Hash Name: String
- Hash Value: Message-Pack

So, I installed some native value formatters (python-msgpack).

When I open RDM, click any key (Hash), double click any hash item, the RDM will like below:

![Loading forever](https://user-images.githubusercontent.com/61455/37564939-f097f5f6-2ada-11e8-9b0b-3d1edc2cf4b7.png)

I must restart the RDM, and then 
- change the Key "View as Plain Text"
- change the Value "View as python-msgpack"

only like this, I can double click any hash item, and use RDM normally.

**Is it possible to add some options in "Setting", just like this:**
- Key default view as: (combobox)
- Value default view as: (combobox)

**The RDM will load the default setting when start running or open new tab.**

**Or set the default view as in Custom Value View Formatters' table.**

**Comment by uglide** [comment]
I think that RDM just needs to remember value formatter choice for each key type. I will solve this usability issue
