### ISSUE TITLE
Data in Value don't save changes

### ISSUE THREAD

**Issue by Tar4s** [redis/RedisDesktopManager#4052]
RDM Version: **0.9.1.771**<br>
Environment (OS name and version): **Windows 10**<br>
Redis Server Version: **3.2.6**<br>

Steps to reproduce:

1. Select HashSet field TEST_EVENTS
![image](https://user-images.githubusercontent.com/13135957/37570922-29989a5a-2b07-11e8-97bb-b44a2a3307f8.png)

2. Select key 00
![image](https://user-images.githubusercontent.com/13135957/37570928-3a486fb0-2b07-11e8-89a6-d0f96b71cb58.png)

3. Select some data in Value
![image](https://user-images.githubusercontent.com/13135957/37570935-66951898-2b07-11e8-89ac-d6210b59a66a.png)

4. Delete this data
![image](https://user-images.githubusercontent.com/13135957/37570945-768a3206-2b07-11e8-9f39-45367fedd037.png)

5. Save
![image](https://user-images.githubusercontent.com/13135957/37570956-9995e2ea-2b07-11e8-870f-496676fbdb41.png)

Expected result: 
After reselected this data, value is saved

Actual Result: 
data in Value not changed (not saved)
![image](https://user-images.githubusercontent.com/13135957/37570970-c8689e64-2b07-11e8-9106-cd3530ffaeea.png)

**Comment by andykkkk** [comment]
same issue discribed here [https://github.com/uglide/RedisDesktopManager/issues/4049](url)

**Comment by nicchap** [comment]
Same here.

**Comment by Tar4s** [comment]
Yes, it's my fault. It was necessary to look first.
