### ISSUE TITLE
Custom formatter errors on valid JSON with special characters

### ISSUE THREAD

**Issue by MikeChristensen** [redis/RedisDesktopManager#4053]
RDM Version: 0.9.1.771
Environment (OS name and version): Windows 10
Redis Server Version: 3.2.100

Steps to reproduce:

Build a custom formatter.  Send it the input to decode a key:

`decode ATbQAERFU0tUT1AtQkgzTFE3Mjo0NTU1Mjo2OTc4Y2IzNTE5YjQ0N2YzOWIzYWQ2MmQ1OTgzNTk2OVN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbTGltZWFkZS5Db21tb24uTGFuZ3VhZ2UsIExpbWVhZGUuQ29tbW9uLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dLCBtc2NvcmxpYiwgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkfiwgAAAAAAAQAe797f3S1kl9ibqqSlZJrXnpOZnGGko6Sc34KSCA1T6lWByFdXJB4eGN+DpJ8sVJtLADWY99nQwAAAA==`

The results it will spit back are:

`{"output":"SER_VERSION: 1\nTYPENAME: System.Collections.Generic.List`1[[Limeade.Common.Language, Limeade.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nVERSION: REVTS1RPUC1CSDNMUTcyOjQ1NTUyOjY5NzhjYjM1MTliNDQ3ZjM5YjNhZDYyZDU5ODM1OTY5\n------------------------------\n\n[\r\n  {\r\n    \"Name\": \"English\",\r\n    \"Code\": \"en\"\r\n  },\r\n  {\r\n    \"Name\": \"Español\",\r\n    \"Code\": \"es\"\r\n  }\r\n]","read-only":true,"format":"plain_text"}`

Expected result: 

Should display as this is valid JSON.

Actual Result: 

RDM responds with:

`2018-03-19 11:27:01 : Formatter returned invalid json`

It appears to be a problem with the ñ character.  If I replace it with an "n", the problem goes away.  JSON should be able to contain any UTF8 characters.

**Comment by MikeChristensen** [comment]
It seems the output your Formatter returns must be ASCII.  Unicode characters don't work.  I can convert my JSON to ASCII and everything works, though I get question marks where characters are outside the ASCII range.  I tried the Unicode escape sequences such as "\\u00f1" but it just prints that.

**Comment by uglide** [comment]
Looks like something has changed since 2018 and I cannot reproduce this bug on Win 10 anymore. RDM correctly shows emoji and other UFT-8 symbols returned by native formatters.
