### ISSUE TITLE
Impossible to add or update field's values of a Hash

### ISSUE THREAD

**Issue by Fronda** [redis/RedisDesktopManager#4056]
RDM Version: 0.9.1.771<br>
Environment (OS name and version): Windows 10 <br>
Redis Server Version: 4.0.8<br>

Steps to reproduce:

1. Create a hash with field and value
![image](https://user-images.githubusercontent.com/4742200/37715669-e7feecee-2d1c-11e8-8b95-3a3d307d02b1.png)

2. The hash is created with the field but without the associated value
![image](https://user-images.githubusercontent.com/4742200/37715792-3d8a7eb2-2d1d-11e8-8683-f91411726b5b.png)

3. Try to update the field's value of the hash
![image](https://user-images.githubusercontent.com/4742200/37715901-7b7e7052-2d1d-11e8-9834-7657cfb3a007.png)
The value is not updated and we can see in the log, that the value is missing in the command.

4. Refresh the GUI on the hash: associated value is not updated
![image](https://user-images.githubusercontent.com/4742200/37716036-d229eb5c-2d1d-11e8-9cf5-d37e2a97e90a.png)

5. Update the field's value of the hash using redis-cli, with this command :
`127.0.0.1:6379> hset user:42 username UserChangedFromCLI`

6. Refresh the GUI on the hash: value is correctly updated
![image](https://user-images.githubusercontent.com/4742200/37716587-24a2f0d0-2d1f-11e8-8d29-1ca829848e5c.png)

7. Try to update the field's value of the hash
![image](https://user-images.githubusercontent.com/4742200/37716975-0736cc46-2d20-11e8-9a47-96d8fdc0952f.png)
The value is not updated and we can see in the log, that the value used in the command is the original value and not the new one.

Expected result:
- When a hash is created, the fields and associated values must be saved.
- When a field's value of hash is modified and saved, the value of this field must be updated with the new value.

Actual Result: 
- When a hash is created, the fields are saved but not the associated values.
- When a field's value of hash is modified and saved, the value of this field is updated with the with the original value and not the new value.

**Comment by YeongJoo-Kim** [comment]
I have the same problem.
