### ISSUE TITLE
Ужасный интерфейс в 0.9.x версиях

### ISSUE THREAD

**Issue by max-petrovich** [redis/RedisDesktopManager#4057]
RDM Version: 0.9.1
Environment (OS name and version): windows 10

Можно ли вернуть интерфейс программы, который был у 0.8.x версии? На версии 0.9.x GUI выглядит ужасно некрасиво

**Comment by uglide** [comment]
Скриншоты? Конкретные замечания?

**Comment by max-petrovich** [comment]
**Интерфейс в версии 0.8.x:**
![image](https://user-images.githubusercontent.com/13830672/37789824-f1bb1eca-2e15-11e8-9eb5-e5575c50b952.png)
**Интерфейс в версии 0.9.x:**
![image](https://user-images.githubusercontent.com/13830672/37789903-2901aba6-2e16-11e8-8917-faf3b238ffc6.png)
Можно ли сделать интерфейс как был в версии 0.8.x?

**Comment by uglide** [comment]
Вас пугают элементы с русским языком? :)

Если серьезно, то нет - инлайновое меню мне кажеться более удобным и очевидным.
Иконки возможно заменены не совсем удачно, но я открыт для предложений и пулл реквестов.

Ваш возглас об "ужасный интерфейс" считаю неконструктивным.
