### ISSUE TITLE
Cluster Functionality

### ISSUE THREAD

**Issue by wjdavis5** [redis/RedisDesktopManager#4058]
RDM Version: 0.9.1.771
Environment (OS name and version): Windows 10
Redis Server Version: 4.0.3 / Elasticache

Steps to reproduce:

1. Connect to clustered instance

I'm not sure what to expect. But what I see is several duplicated keys. This particular cluster has 6 members with 1 replica each (total of 12).
So for example when I load the keys I see this:
![image](https://user-images.githubusercontent.com/2580575/37784634-a3095b6c-2dce-11e8-836a-3402b3c4dc94.png)

However when I use redis-cli I'm not getting all these duplicated results.

It would be really nice if when connecting to a cluster, it enumerated the masters and slaves of the cluster, and then provided the option to scan the keyspace on a specific server.

As it stands using this on Clustered instances isnt working very well.

**Comment by uglide** [comment]
Currently, RDM represents cluster as single keyspace and shows keys from all master nodes.

Looks like you have found some kind of rendering issue
