### ISSUE TITLE
Icon not harmonious

### ISSUE THREAD

**Issue by homeant** [redis/RedisDesktopManager#4062]
![image](https://user-images.githubusercontent.com/28803295/37914020-d2dabac0-3148-11e8-8f02-b68aea98c4bc.png)
Icon is not harmonious, it is suggested that with the right mouse button...

**Comment by uglide** [comment]
@homeant How you suggest solving this?

**Comment by homeant** [comment]
avenue to Jane, the right mouse button!

**Comment by uglide** [comment]
it is available on left click (with loading child items) or on right click (without loading)
