### ISSUE TITLE
Value display incorrectly detecting binary values

### ISSUE THREAD

**Issue by cookieguru** [redis/RedisDesktopManager#4064]
RDM Version: 0.9.1.771<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: 3.0.6<br>

Steps to reproduce:

1. Set a value containing a null character.  For example from `redis-cli`:
```
127.0.0.1:6379> SET foo "bar\x00baz"
OK
127.0.0.1:6379> GET foo
"bar\x00baz"
```
2. View the key in RDM

Expected result: In Plain Text view, the entire key should be visible, with binary values being shown or escaped

Actual Result: The value is truncated at the null character

![plain](https://user-images.githubusercontent.com/1888809/37992314-3a0921ec-31c0-11e8-8409-37ecb4d86775.png)
![hex](https://user-images.githubusercontent.com/1888809/37992323-3dc42d40-31c0-11e8-967a-5f4994dc2d83.png)

Essentially, the view is not properly detecting binary values.  Although technically this is not a binary value since a null character is part of ASCII.

**Comment by uglide** [comment]
Value view shows plain text in UTF8 that's why it automatically switches to HEX if null character is present.

**Comment by cookieguru** [comment]
No, it does not automatically switch to HEX.  The default behavior is to show plain text (first screenshot).

**Comment by uglide** [comment]
Ah, I see
