### ISSUE TITLE
Can not install in Ubuntu 17.10 or 18.04

### ISSUE THREAD

**Issue by hoaihuongbk** [redis/RedisDesktopManager#4066]
RDM Version: 0.9.1.18
Environment (OS name and version): Ubuntu 17.10
Redis Server Version: <br>
Actual Result: 
dpkg: dependency problems prevent configuration of redis-desktop-manager:
 redis-desktop-manager depends on libpng12-0; however:
  Package libpng12-0 is not installed.
 redis-desktop-manager depends on libssh2-1; however:
  Package libssh2-1 is not installed.

**Comment by Marek00Malik** [comment]
What is the status of this bug, why is it closed ?! 
I Also have this while installing on U.18.04.

**Comment by uglide** [comment]
@Marek00Malik 
it's fixed in 0.9.4 but not yet released. If you have subscription please contact me via support@redisdesktop.com and I send you beta build

**Comment by uglide** [comment]
Fixed in 0.9.4
