### ISSUE TITLE
Help button doesn't work in pop-up with error.

### ISSUE THREAD

**Issue by piotr-lesniak** [redis/RedisDesktopManager#4077]
RDM Version: 0.9.1.771
Environment: Windows Server 2012 R2 Standard
Redis Server Version: Redis server v=4.0.1 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=ac6c9ffb15b04a74

Steps to reproduce:
1. Open RedisDesktopManager
2. Press connect to Redis Server
3. Complete Address and not correct port and check Connection. 
4. Expand redis connection and db in left pane to connect to redis db.
5. Pop-up with error message: "Cannot load databases... " appears. I try to open help using help button from this popup.

Expected result for step 5th: Help button work and do something (I really don't know what it is responsible for, maybe to print some extra logs or documentation for this kind of error).

Actual Result for step 5th: Help button doesn't work at all - no action when I click on it.
![helpbuttondoesntwork](https://user-images.githubusercontent.com/38030787/38306785-f252dcaa-3811-11e8-8010-bae937deaa69.PNG)

**Comment by uglide** [comment]
Help button appears only on Windows and I cannot hide it (no available such options in QMessageBox)
