### ISSUE TITLE
Redis port in connection settings changes when connection to redis (cluster) fails.

### ISSUE THREAD

**Issue by piotr-lesniak** [redis/RedisDesktopManager#4078]
RDM Version: 0.9.1.771
Environment: Windows Server 2012 R2 Standard
Redis Server Version: Redis server v=4.0.1 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=ac6c9ffb15b04a74

Prerequisities:
Redis cluster established. One of redis nodes doesn't work.

Steps to reproduce:
1. Open RedisDesktopManager
2. Press connect to Redis Server
3. Complete Address and port and check Connection. If passed then submit config with OK button.
![redisport_before](https://user-images.githubusercontent.com/38030787/38307145-128ae728-3813-11e8-9abe-1cf9d16b533f.PNG)

4. Expand Redis Connection and db in left pane to connect to redis db.
5. If connection fails, verify IPs from error pop-up/s
6. Go back to redis connection settings window to check connection settings.

Expected result for step 5th: IPs should be the same. In my opinion error log should contain status for every redis node from cluster. 
Actual Result for step 5th: IPs from error button are different than in connection settings.
![redisport_popup](https://user-images.githubusercontent.com/38030787/38307572-673ac062-3814-11e8-8076-b3da5d25fc22.PNG)

Expected result for step 6th: connection settings without changes.
Actual Result for step 6th: connection IP is the same, connection port is different - it changed automatically.
![redisport_after](https://user-images.githubusercontent.com/38030787/38307615-85b8048c-3814-11e8-8ba9-028e0a73e459.PNG)

**Comment by kayleyang** [comment]
me too.
