### ISSUE TITLE
Windows 10- GUI cannot display in a high resolution: 1920x1080.

### ISSUE THREAD

**Issue by letrthang** [redis/RedisDesktopManager#4086]
RDM Version: 0.9.1.771<br>
Environment (OS name and version): Windows 10 64 bit<br>
Redis Server Version: any <br>

GUI cannot display in a high resolution: 1920x1080.

step1: just click on **Setting** button to see the result.

**Comment by uglide** [comment]
Please provide screenshot for described problem

**Comment by letrthang** [comment]
It is here. see at the bottom picture.
[https://ibb.co/dt3u7H](https://ibb.co/dt3u7H)

**Comment by lovinhence** [comment]
Same problem on my pc too.

**Comment by vincenzo-antolini-os** [comment]
Same here

**Comment by uglide** [comment]
Duplicate of #4089
