### ISSUE TITLE
Ubuntu 17.10 build, package `qtdeclarative5-dev` missing

### ISSUE THREAD

**Issue by colinskow** [redis/RedisDesktopManager#4087]
Following the build instructions for Ubuntu 17.10 after a fresh clone of master I got the following error:
`Project ERROR: Unknown module(s) in QT: quick quickwigets`

It took me a while to find the correct package to install, but this fixed it:
`sudo apt-get install qtdeclarative5-dev`

This should be built into the `./configure` script.

**Comment by uglide** [comment]
Added. thanks.
