### ISSUE TITLE
Cannot update hash value

### ISSUE THREAD

**Issue by ZxYuan** [redis/RedisDesktopManager#4090]
RDM Version: 0.9.1.771
Environment (OS name and version): Windows 10 Professional
Redis Server Version: 3.2.3

Steps to reproduce:

1. choose a hash item "3" -> "0.1|0.8"

2. change its value to "0.1|0.4"

3. press "save" button

Expected result: 
Log should be "HSET xxx 3 0.1|0.4"
Actual Result: 
Log shows "HSET xxx 3 0.1|0.8"

**Comment by uglide** [comment]
it was fixed in 0.9 branch. will be released as 0.9.1-1 today
