### ISSUE TITLE
Value is not stored in hash

### ISSUE THREAD

**Issue by damonLL** [redis/RedisDesktopManager#4092]
RDM Version: 0.9.1.37 <br>
Environment (OS name and version): macOS High Sierra 10.13.3 <br>
Redis Server Version: 4.0.8<br>

Steps to reproduce:

1. Add a new hash object

2. Provide a top level key name

3. Provide the at least one row, key and value

4. Click Save

It appears that the value is not actually being saved into redis. Example:

Expected result: 

Should see the value in the UI associated with the key inside of the hash.

Actual Result: 

No value appears in the UI

Please see the output from redis-cli after adding a row to a hash:

```
127.0.0.1:6379> hgetall myhash
1) "k1"
2) ""
```

**Comment by uglide** [comment]
Fixed in 0.9.2
