### ISSUE TITLE
cluster mode get same keys

### ISSUE THREAD

**Issue by foreverhot1019** [redis/RedisDesktopManager#4094]
RDM Version: 0.9.2.806<br>
Environment (OS name and version): win10 1709<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 
get  4 same key (3 cluster node)

Actual Result: 
get  1 key

**Comment by ImRealDR** [comment]
i have same problem

**Comment by uglide** [comment]
Duplicate of #4058
