### ISSUE TITLE
RDM windows 10 to Azure - only connects to 6379

### ISSUE THREAD

**Issue by weznagwama** [redis/RedisDesktopManager#4103]
RDM Version: 0.9.2.806<br>
Environment (OS name and version): Windows 10 <br>
Redis Server Version: Azure Redis<br>

Steps to reproduce:

1. Configure Azure Redis connection as per doco

2. Config looks like this:
`        "auth": "key-goes-here",
        "host": "hostname.redis.cache.windows.net",
        "keys_pattern": "*",
        "name": "rdm_azure3",
        "namespace_separator": ":",
        "port": 6380,
        "ssh_port": 1,
        "ssl": true,
        "timeout_connect": 30000,
        "timeout_execute": 30000
    },`

3. Download and open procmon

4. Open RDM, observe the TCP connect to the incorrect port 

Expected result: RDM should connnect to redis, on the port 6380

Actual Result: ![rdm](https://user-images.githubusercontent.com/1518569/39343339-919595ea-4a1f-11e8-828d-c1775157111e.PNG)
 or https://imgur.com/a/N7nUygq

RDM only attempts to use 6379, which fails.

No form of editing configs, modifying connectionstring etc. resolves the issue.

**Comment by maxwellb** [comment]
From a recent build of 0.9 branch (0.9.6+):

![image](https://user-images.githubusercontent.com/3590441/45379813-1c275e80-b5cf-11e8-9ae6-41073f10e3d7.png)

I don't know about JSON configuration, but from the UI it looks like this:

![image](https://user-images.githubusercontent.com/3590441/45379967-7cb69b80-b5cf-11e8-9aec-9d6dedfd7a52.png)

This appears fixed or not reproducible.

**Comment by uglide** [comment]
@maxwellb thanks for info
looks like @weznagwama just forgot to enable SSL checkbox in the settings
