### ISSUE TITLE
The value is copied, but not all of it is copied.

### ISSUE THREAD

**Issue by ArchsouL** [redis/RedisDesktopManager#4110]
RDM Version: 0.9.3.817
Environment (OS name and version): Ubuntu 16.04 
Redis Server Version: 3.0.6

Steps to reproduce:

1. a value size is about 500kb json

2. I using a RDM 0.8.8.364, full size copied.
but, 0.9.3.817 is maximum 10000 characters.

**Comment by uglide** [comment]
Duplicate of #3990
