### ISSUE TITLE
build fails on macOS

### ISSUE THREAD

**Issue by peterschussheim** [redis/RedisDesktopManager#4113]
RDM Version: 0.9
Environment (OS name and version): macOS 10.13.4 (17E202)

### Steps to reproduce:

1. Build RDM dependencies cd ./src && ./configure
2. Open ./src/rdm.pro in Qt Creator
3. Run build

### Expected result: 

Expected the application to build successfully.

### Actual Result: 

```
ld: can't open -sectcreate file: ../src/resources/Info.plist
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../bin/osx/debug/rdm] Error 1
16:39:42: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project rdm (kit: Desktop Qt 5.10.1 clang 64bit)
When executing step "Make"
16:39:42: Elapsed time: 03:09.
```

<img width="649" alt="qt creator001" src="https://user-images.githubusercontent.com/3654683/39677668-f810980e-514c-11e8-850f-fda542df95a9.png">

**Comment by onlyshow** [comment]
me too
```
Error while parsing file /Users/show/WorkSpace/rdm/src/rdm.pro. Giving up.
Project ERROR: failed to parse default search paths from compiler output
Error while parsing file /Users/show/WorkSpace/rdm/src/rdm.pro. Giving up.
```

**Comment by uglide** [comment]
Probably Qt 5.10 causes this issue. I will check it

**Comment by unixcx** [comment]
I meet this too,
and I try  `cp ./resources/Info.plist.sample ./resources/Info.plist`     after  step 1.  `cd ./src && ./configure`

and it's working now, >.<

**Comment by uglide** [comment]
@unixcx thanks. added to docs
