### ISSUE TITLE
build faild on ubuntu 18.04

### ISSUE THREAD

**Issue by sumic** [redis/RedisDesktopManager#4118]
src/third_party/libdisasm/x86_format.c: In function ‘format_operand_xml.isra.3’:
src/third_party/libdisasm/x86_format.c:837:5: warning: ‘%04X’ directive output truncated writing 4 bytes into a region of size 1 [-Wformat-truncation=]
     "\t\t<absolute_address segment=\"0x%04" PRIX16 "\"",
     ^
src/third_party/libdisasm/x86_format.c:34:38: note: in definition of macro ‘STRNCATF’
         snprintf( _tmp, sizeof _tmp, fmt, data );   \
                                      ^~~
src/third_party/libdisasm/x86_format.c:837:40: note: format string is defined here
     "\t\t<absolute_address segment=\"0x%04" PRIX16 "\"",
src/third_party/libdisasm/x86_format.c:837:5: note: directive argument in the range [0, 65535]
     "\t\t<absolute_address segment=\"0x%04" PRIX16 "\"",
     ^
src/third_party/libdisasm/x86_format.c:34:38: note: in definition of macro ‘STRNCATF’
         snprintf( _tmp, sizeof _tmp, fmt, data );   \
                                      ^~~
In file included from /usr/include/stdio.h:862:0,
                 from src/third_party/libdisasm/x86_format.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output 37 bytes into a destination of size 32
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/third_party/libdisasm/x86_format.c: In function ‘x86_format_insn’:
src/third_party/libdisasm/x86_format.c:1141:24: warning: ‘|’ directive output may be truncated writing 1 byte into a region of size between 0 and 31 [-Wformat-truncation=]
         STRNCATF( buf, "|%s|", insn->prefix_string             , len );
                        ^
src/third_party/libdisasm/x86_format.c:34:38: note: in definition of macro ‘STRNCATF’
         snprintf( _tmp, sizeof _tmp, fmt, data );   \
                                      ^~~
In file included from /usr/include/stdio.h:862:0,
                 from src/third_party/libdisasm/x86_format.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 3 and 34 bytes into a destination of size 32
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/third_party/libdisasm/x86_format.c:1181:24: warning: ‘%s’ directive output may be truncated writing up to 31 bytes into a region of size 22 [-Wformat-truncation=]
         STRNCATF( buf, "\" string=\"%s\"/>\n", insn->prefix_string, len );
                        ^
src/third_party/libdisasm/x86_format.c:34:38: note: in definition of macro ‘STRNCATF’
         snprintf( _tmp, sizeof _tmp, fmt, data );   \
                                      ^~~
In file included from /usr/include/stdio.h:862:0,
                 from src/third_party/libdisasm/x86_format.c:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 15 and 46 bytes into a destination of size 32
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ar: `u' modifier ignored since `d' is the default (see `u')

ar: `u' modifier ignored since `d' is the default (see `u')

ar: `u' modifier ignored since `d' is the default (see `u')

**Comment by sumic** [comment]
tried deleting the directory and redoing git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm and it still fails

**Comment by uglide** [comment]
I don't see any issues in the provided build log. Please copy full build log to gist

**Comment by sumic** [comment]
$ source /opt/qt59/bin/qt59-env.sh
bash: /opt/qt59/bin/qt59-env.sh: No such file or directory

**Comment by uglide** [comment]
On ubuntu 18 you don't need to source anything. Qt is installed from default repo

**Comment by unliar** [comment]
i installed it on ubuntu 18.04 , [http://docs.redisdesktop.com/en/latest/install/#build-from-source](http://docs.redisdesktop.com)

- git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm

- cd src/
- sudo apt-get install zlib1g-dev
- ./configure    
- qmake && make && sudo make install

- sudo mv qt.conf qt.backup

i can only start from  "/usr/share/redis-desktop-manager/bin$ ./rdm" , no short icon on desktop

**Comment by uglide** [comment]
@unliar search for it in application menu
