### ISSUE TITLE
DoubleClick key error

### ISSUE THREAD

**Issue by j7252008** [redis/RedisDesktopManager#4119]
RDM Version: 0.9.999 <br>
Environment (OS name and version):  win7<br>
Redis Server Version: <br>

Steps to reproduce:

1. ...add a new key, any type

2. ...doubleclick key once or more

3. ...

Expected result: run normal

Actual Result:  program occurred an error "Assert objectRef == 0"

**Comment by uglide** [comment]
Duplicate of #4059
