### ISSUE TITLE
Centos 7 linking problems

### ISSUE THREAD

**Issue by jurepetrovic** [redis/RedisDesktopManager#4122]
RDM Version: branch 0.9 chechkou <br>
Environment (OS name and version): Centos 7.5
Redis Server Version: not applicable

Steps to reproduce:

I'm having troubles linking rdm. Error: 

Qt-charts are from 5.9 github branch, compiled on centos this system.
qt5-qtbase are 5.9.2 centos 7 as in the default repos.

Any ideas? 
Much appreciated, 
Jure 

[root@localhost src]# make
g++ -Wl,-O1 -Wl,-z,relro -o ../bin/linux/release/rdm ../bin/linux/release/obj/main.o ../bin/linux/release/obj/app.o ../bin/linux/release/obj/qmlutils.o ../bin/linux/release/obj/configmanager.o ../bin/linux/release/obj/connectionconf.o ../bin/linux/release/obj/connectionsmanager.o ../bin/linux/release/obj/treeoperations.o ../bin/linux/release/obj/hashkey.o ../bin/linux/release/obj/keyfactory.o ../bin/linux/release/obj/listkey.o ../bin/linux/release/obj/listlikekey.o ../bin/linux/release/obj/rejsonkey.o ../bin/linux/release/obj/setkey.o ../bin/linux/release/obj/sortedsetkey.o ../bin/linux/release/obj/stringkey.o ../bin/linux/release/obj/keysrendering.o ../bin/linux/release/obj/model.o ../bin/linux/release/obj/utils.o ../bin/linux/release/obj/abstractnamespaceitem.o ../bin/linux/release/obj/databaseitem.o ../bin/linux/release/obj/keyitem.o ../bin/linux/release/obj/namespaceitem.o ../bin/linux/release/obj/serveritem.o ../bin/linux/release/obj/treeitem.o ../bin/linux/release/obj/consolemodel.o ../bin/linux/release/obj/hex_utils.o ../bin/linux/release/obj/formattersmanager.o ../bin/linux/release/obj/largetextmodel.o ../bin/linux/release/obj/sortfilterproxymodel.o ../bin/linux/release/obj/tabsmodel.o ../bin/linux/release/obj/valueviewmodel.o ../bin/linux/release/obj/crashhandler.o ../bin/linux/release/obj/updater.o ../bin/linux/release/obj/bulkoperation.o ../bin/linux/release/obj/bulkoperationsmanager.o ../bin/linux/release/obj/tabmodel.o ../bin/linux/release/obj/tabviewmodel.o ../bin/linux/release/obj/serverstatsmodel.o ../bin/linux/release/obj/command.o ../bin/linux/release/obj/connection.o ../bin/linux/release/obj/connectionconfig.o ../bin/linux/release/obj/response.o ../bin/linux/release/obj/scancommand.o ../bin/linux/release/obj/scanresponse.o ../bin/linux/release/obj/abstracttransporter.o ../bin/linux/release/obj/defaulttransporter.o ../bin/linux/release/obj/sshtransporter.o ../bin/linux/release/obj/compat.o ../bin/linux/release/obj/sync.o ../bin/linux/release/obj/text.o ../bin/linux/release/obj/read.o ../bin/linux/release/obj/sds.o ../bin/linux/release/obj/qxtsshchannel.o ../bin/linux/release/obj/qxtsshclient.o ../bin/linux/release/obj/qxtsshprocess.o ../bin/linux/release/obj/qxtsshtcpsocket.o ../bin/linux/release/obj/qrc_lua.o ../bin/linux/release/obj/qrc_images.o ../bin/linux/release/obj/qrc_fonts.o ../bin/linux/release/obj/qrc_qml.o ../bin/linux/release/obj/qrc_tr.o ../bin/linux/release/obj/moc_app.o ../bin/linux/release/obj/moc_logger.o ../bin/linux/release/obj/moc_qmlutils.o ../bin/linux/release/obj/moc_connectionconf.o ../bin/linux/release/obj/moc_connectionsmanager.o ../bin/linux/release/obj/moc_treeoperations.o ../bin/linux/release/obj/moc_keyfactory.o ../bin/linux/release/obj/moc_model.o ../bin/linux/release/obj/moc_databaseitem.o ../bin/linux/release/obj/moc_namespaceitem.o ../bin/linux/release/obj/moc_serveritem.o ../bin/linux/release/obj/moc_consolemodel.o ../bin/linux/release/obj/moc_formattersmanager.o ../bin/linux/release/obj/moc_keymodel.o ../bin/linux/release/obj/moc_largetextmodel.o ../bin/linux/release/obj/moc_sortfilterproxymodel.o ../bin/linux/release/obj/moc_tabsmodel.o ../bin/linux/release/obj/moc_valueviewmodel.o ../bin/linux/release/obj/moc_updater.o ../bin/linux/release/obj/moc_bulkoperation.o ../bin/linux/release/obj/moc_bulkoperationsmanager.o ../bin/linux/release/obj/moc_tabmodel.o ../bin/linux/release/obj/moc_tabviewmodel.o ../bin/linux/release/obj/moc_serverstatsmodel.o ../bin/linux/release/obj/moc_connection.o ../bin/linux/release/obj/moc_abstracttransporter.o ../bin/linux/release/obj/moc_defaulttransporter.o ../bin/linux/release/obj/moc_sync.o ../bin/linux/release/obj/moc_qxtsshchannel.o ../bin/linux/release/obj/moc_qxtsshclient.o ../bin/linux/release/obj/moc_qxtsshclient_p.o ../bin/linux/release/obj/moc_qxtsshprocess.o ../bin/linux/release/obj/moc_qxtsshtcpsocket.o   -lssl -lz -lssh2 /home/jure/Downloads/rdm/3rdparty/gbreakpad/src/client/linux/libbreakpad_client.a -lQt5QuickWidgets -lQt5Charts -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Concurrent -lQt5Core -lGL -lpthread 
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libQt5Gui.so: undefined reference to `hb_font_funcs_set_nominal_glyph_func'
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libQt5Gui.so: undefined reference to `hb_font_funcs_set_font_h_extents_func'
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libQt5Gui.so: undefined reference to `hb_font_funcs_set_variation_glyph_func'
collect2: error: ld returned 1 exit status
make: *** [../bin/linux/release/rdm] Error 1

**Comment by uglide** [comment]
Looks like Qt issue on Centos

**Comment by jurepetrovic** [comment]
Hello, 

thanks for answer. 
I manually compiled qtcharts on centos and then it worked. 
I have the binaries for centos7, should anyone be interested.
not rpms though, but centos7 compiled binaries.

**Comment by botri** [comment]
Hello
I am interested in it.
Can you provide it for download

**Comment by jurepetrovic** [comment]
Hello, 

1) do a complete centos7 update
yum update

2) 
yum install qt5-qtbase-devel
yum install qt5-qtquickcontrols2

It should install all needed dependencies. 

3) 
Download qtcharts from: 
https://www.dropbox.com/s/78vc2lj1iw4tn4i/qtcharts_build.tar.gz?dl=0

I found this version to be compatible & working. Binaries are inside, try with 
"make install" only. If not, you'll have to compile (make it yourself).  Keep in mind
that my compilation was from /home/jure/Downloads folder. 

Make sure this install completes without errors!

4) 
Download rdm from: 
https://www.dropbox.com/s/l63x2c31thsyner/rdm_build.tar.gz?dl=0

This one has binaries inside too. First just try to run 
rdm/bin/releases/linux/rdm. If not, you'll have to 
make clean
make
to link the binary against yout qtcharts lib. 

5) 
Let me know if you need some details, I'll try to help you.

Regards, 
Jure
