### ISSUE TITLE
UI issues on windows 10

### ISSUE THREAD

**Issue by smirab** [redis/RedisDesktopManager#4123]
RDM Version: 0.9.3.817 <br>
Environment (OS name and version): Windows 10 <br>
Redis Server Version: 4.0.9 <br>

Steps to reproduce:

1. Open Redis Desktop Manager

2. Click on Connect to Redis Server

3. You see deformed form elements (Sections title and fields)

Expected result: 
![capture](https://user-images.githubusercontent.com/31686284/39956859-d52cc6d6-55fd-11e8-94ac-4275e592ec7d.PNG)

Actual Result:

**Comment by Jerry-Shaw** [comment]
Same here, on win 10 Pro.
Screen resolution is 1920 x 1280, 12.3 inch, but scale is set to 150%... All UI broken just as above screenshot.
But, it looks to be better when scale sets smaller. Almost OK when set to 100%, but text is too small.
