### ISSUE TITLE
Lost PHP Serializer Support

### ISSUE THREAD

**Issue by benhopper1** [redis/RedisDesktopManager#4125]
RDM Version: 0.9.1.37<br>
Environment (Mac 10.12.6): <br>
Redis Server Version: elasticache on AWS

Steps to reproduce:

1. pick key produced by LARAVEL(PHP serialized data)

Expected result: 
JSON formatted un serialized output text format

Actual Result: 
PHP serialized data with no translation

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/features/#native-value-formatters
