### ISSUE TITLE
Unable to load Keys

### ISSUE THREAD

**Issue by rahulgoti1** [redis/RedisDesktopManager#4128]
RDM Version: redis-desktop-manager-0.9.3.817<br>
Environment (OS name and version): Window-10<br>
Redis Server Version: redis-2.4.6-setup-64-bit<br>

Steps to reproduce:

1. I have connected to redis server by RDM.

2. When i select any database, then it will give me error like "Cannot load keys: Scan commands not supported by redis server"

Expected result: It should be display all keys

Actual Result: Give Error
![redis-error](https://user-images.githubusercontent.com/16923556/40405000-4cd4eb50-5e78-11e8-880a-b1c793224daf.png)

**Comment by uglide** [comment]
RedisDesktopManager supports redis-server 2.8+

**Comment by rahulgoti1** [comment]
Thank You
