### ISSUE TITLE
error: no member named 'refreshServerInfo' in 'RedisClient::Connection'

### ISSUE THREAD

**Issue by tuchief** [redis/RedisDesktopManager#4131]
RDM Version: 0.9.3
Environment (OS name and version): macos 10.13
Redis Server Version: 4.0.9

Steps to reproduce:

~/workspace/rdm/src/app/models/treeoperations.cpp:30: error: no member named 'refreshServerInfo' in 'RedisClient::Connection'
        m_connection->refreshServerInfo();
        ~~~~~~~~~~~~  ^

**Comment by uglide** [comment]
Hello, looks like you forgot to refresh submodules
