### ISSUE TITLE
VirusTotal 3/67 detects Trojan for 0.9.3.817

### ISSUE THREAD

**Issue by c33s** [redis/RedisDesktopManager#4137]
https://www.virustotal.com/#/file/c81724c167f09e7bca7bf68629f159bb835771afe2ba339bcd74466ca375f8db/detection

- Antiy-AVL Trojan/Win32.TSGeneric
- Bkav HW32.Packed.6162
- TrendMicro-HouseCall Suspicious_GEN.F47V0512

i assume it is related to https://github.com/uglide/RedisDesktopManager/issues/3685 but the issue was closed without explanation. will try to find it in gitter.

**Comment by uglide** [comment]
It's just false positives. If you don't trust to provided downloads you always can build it by yourself from source.
