### ISSUE TITLE
Cant make 

### ISSUE THREAD

**Issue by welovelain** [redis/RedisDesktopManager#4140]
git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm
cd src/
./configure
qmake-qt5 && make && sudo make install

result >
qmake-qt5 && make 
g++ -c -pipe -g -std=gnu++0x -Wno-sign-compare -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DRDM_VERSION=\"0.9.999\" -DCORE_LIBRARY -DELPP_QT_LOGGING -DELPP_STL_LOGGING -DELPP_DISABLE_DEFAULT_CRASH_HANDLING -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../3rdparty/qredisclient/src -I../3rdparty/qredisclient/3rdparty/hiredis -I../3rdparty/qredisclient/3rdparty -I../3rdparty/easyloggingpp/src -I../3rdparty/asyncfuture -I../3rdparty/gbreakpad/src -I/home/fdao/Downloads/rdm/3rdparty/gbreakpad/src/src -I. -Imodules -I/home/fdao/Downloads/rdm/src/../bin/linux/release/ui/ -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuickWidgets -isystem /usr/include/qt5/QtCharts -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -I../bin/linux/release/obj -I/usr/lib64/qt5/mkspecs/linux-g++ -o ../bin/linux/release/obj/app.o app/app.cpp
app/app.cpp: In member function ‘void Application::initQml()’:
app/app.cpp:137:9: error: ‘setSceneGraphBackend’ is not a member of ‘QQuickWindow’
         QQuickWindow::setSceneGraphBackend(QSGRendererInterface::Software);
         ^~~~~~~~~~~~
app/app.cpp:137:44: error: ‘QSGRendererInterface’ has not been declared
         QQuickWindow::setSceneGraphBackend(QSGRendererInterface::Software);
                                            ^~~~~~~~~~~~~~~~~~~~
app/app.cpp:140:9: error: ‘setSceneGraphBackend’ is not a member of ‘QQuickWindow’
         QQuickWindow::setSceneGraphBackend(m_renderingBackend);
         ^~~~~~~~~~~~
app/app.cpp:150:9: error: ‘setSceneGraphBackend’ is not a member of ‘QQuickWindow’
         QQuickWindow::setSceneGraphBackend(QSGRendererInterface::Software);
         ^~~~~~~~~~~~
app/app.cpp:150:44: error: ‘QSGRendererInterface’ has not been declared
         QQuickWindow::setSceneGraphBackend(QSGRendererInterface::Software);
                                            ^~~~~~~~~~~~~~~~~~~~
app/app.cpp:154:41: error: ‘sceneGraphBackend’ is not a member of ‘QQuickWindow’
     qDebug() << "Rendering backend:" << QQuickWindow::sceneGraphBackend();
                                         ^~~~~~~~~~~~
Makefile:1185: recipe for target '../bin/linux/release/obj/app.o' failed
make: *** [../bin/linux/release/obj/app.o] Error 1

OS: Fedora

**Comment by uglide** [comment]
Which qt version do you use?

**Comment by welovelain** [comment]
➜ qmake-qt5 --version
QMake version 3.0
Using Qt version 5.7.1 in /usr/lib64

**Comment by uglide** [comment]
to build RDM you need 5.9+
