### ISSUE TITLE
Not working for cluster setup, Redis Desktop Manager tries to connect to other nodes on private ip.

### ISSUE THREAD

**Issue by sombahadurlimbu** [redis/RedisDesktopManager#4147]
Hi i've a cluster setup of 3 master nodes & 3 slaves.
Now when i try to connect via Redis Desktop manager, it gives me error : 
"Cannot connect to cluster node privateIP:port"

My cluster is hosted in cloud servers and i'm trying to connect via my pc through Redis Desktop Manager.
Cluster is created on cloud using private ips.

Any help here?

**Comment by uglide** [comment]
You can build from source 0.9 branch with new "Change host on cluster redirects" flag in connection settings to forbid RDM to change nodes host.

**Comment by Ovajinapalli** [comment]
i am using mac and got rdm from mac store.  
my current setup is in Azure cloud and have 3 sharding nodes in each region and 1 slave to each master in each region.
not able to get data retrieived when i connect to primary redis cluster server and put name value that exists in other nodes.
Please help me.

**Comment by uglide** [comment]
@Ovajinapalli Please reply in the issue https://github.com/uglide/RedisDesktopManager/issues/4884 or contact me via email igor@redisdesktop.com
