### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by xavierzhao** [redis/RedisDesktopManager#4148]
RDM Version: 0.9 <br>
Environment (OS name and version): macos 10.13.3 (17D47)<br>
QT Version: 5.9.6

Actual Result: 

Starting /Users/xavierzhao/Documents/workspace/github/rdm/bin/osx/debug/rdm...
dyld: Library not loaded: @executable_path/../Frameworks/Breakpad.framework/Versions/A/Breakpad
  Referenced from: /Users/xavierzhao/Documents/workspace/github/rdm/bin/osx/debug/rdm
  Reason: image not found
The process was ended forcefully.
/Users/xavierzhao/Documents/workspace/github/rdm/bin/osx/debug/rdm crashed.

![image](https://user-images.githubusercontent.com/1573662/41402764-c61a3efa-6ff5-11e8-8c38-05338baa7569.png)

**Comment by uglide** [comment]
Looks like you forgot to run ./configure script
