### ISSUE TITLE
New line character before command cursor

### ISSUE THREAD

**Issue by felipefcm** [redis/RedisDesktopManager#4151]
RDM Version: 0.9.3
Environment (OS name and version): ArchLinux - 4.17.2
Redis Server Version: unstable

Steps to reproduce:

1. Open the server console by clicking in the console icon next to server name;

2. Type a command and press Enter.

Expected result: 
The command output;
Cursor returns to initial position.

Actual Result: 
The command output;
Cursor after a "new line". (The next command fails to be executed)

**Comment by uglide** [comment]
Could you please provide more details? because I cannot reproduce it on 0.9.3+git from snapcraft

**Comment by felipefcm** [comment]
Thanks, just tested on 0.9.4 and cannot reproduce anymore.
