### ISSUE TITLE
It take ages to scan

### ISSUE THREAD

**Issue by mmagdyeg** [redis/RedisDesktopManager#4152]
RDM Version: 0.9.3.817
Environment (OS name and version): Windows 10
Redis Server Version: 3.0.503
Steps to reproduce:

1. connect

2. double click db0

3. freez and not loading

Expected result: open tree

Actual Result: nothing

**Comment by uglide** [comment]
Hello. How much keys do you have? If possible please provide here output from `INFO` redis command. Also you can try to enable "Use server-side optimized keys loading (experimental)" in connection settings.
