### ISSUE TITLE
Interface displays valuable but the query is null

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [redis/RedisDesktopManager#4153]
RDM Version: 0.9.3
Environment (OS name and version): windows 7
Redis Server Version: not kown

Steps to reproduce:

Interface displays valuable but the query is null

![image](https://user-images.githubusercontent.com/27771529/41964338-4862df44-7a2c-11e8-8b56-dd75ba4e46c8.png)

Expected result: 

Actual Result:

**Comment by BrokenWingsIcarus** [comment]
![default](https://user-images.githubusercontent.com/27771529/41964393-6bb73eea-7a2c-11e8-8d41-913a45481b14.PNG)

**Comment by BrokenWingsIcarus** [comment]
![default](https://user-images.githubusercontent.com/27771529/41964444-929bc422-7a2c-11e8-84b5-d8113c31b671.PNG)

**Comment by BrokenWingsIcarus** [comment]
It does not seem like a case 。 
Who can help me！

**Comment by uglide** [comment]
@chinausers just remove ";" from the key name in console

**Comment by BrokenWingsIcarus** [comment]
A stupid mistake Forgot to add quotation marks No///
