### ISSUE TITLE
Add portable version for windows

### ISSUE THREAD

**Issue by geekyouth** [redis/RedisDesktopManager#4156]
请问win10 rdm 客户端绿色版有提供吗？
目前只有0.8的绿色版，最新版rdm已升级到0.9.3安装版，但是找不到绿色版了。
工作电脑和个人电脑使用绿色软件可以无缝切换，而且重装系统可以免安装绿色软件，希望官方发布最新的绿色版。

**Comment by Jerry-Shaw** [comment]
installed and copy from VM, and all works.

**Comment by uglide** [comment]
@Jerry-Shaw Could you please explain me the problem?

**Comment by Jerry-Shaw** [comment]
@uglide  Hi, he just wants a portable version of the latest RDM for Windows 10.

**Comment by uglide** [comment]
@Jerry-Shaw thanks a lot for clarification.

**Comment by geekyouth** [comment]
@uglide  
![image](https://user-images.githubusercontent.com/12899262/45473077-92ab9400-b768-11e8-8d98-5530b9e2881d.png)

I recommend you to use chrome's Google Translate plugin, which is very convenient.
我推荐你使用 chrome 的 谷歌翻译插件，非常方便😘

**Comment by a363533858** [comment]
尴尬

**Comment by Jerry-Shaw** [comment]
Only one request needed to be done for a portable version is to make all configurations (connections.json, etc. under the "user" folder) going back to the install path of RDM. So that we can use it anywhere with all settings and connections not losing in the same portable binary folder.

**Comment by uglide** [comment]
@Jerry-Shaw it's possible to create shortcut on Windows which starts RDM with `--settings-dir` command line option pointer to the current directory.
