### ISSUE TITLE
提交一个bug---导航栏和状态栏同一实例多次打开

### ISSUE THREAD

**Issue by geekyouth** [redis/RedisDesktopManager#4157]
提交一个bug---导航栏和状态栏同一实例多次打开

![打开同样的redis账户，难道不应该是只有一个导航面板吗？如图](http://p7fcrq2e4.bkt.clouddn.com/201818061659-20180706_165900.png)

**Comment by Jerry-Shaw** [comment]
I have no idea about this. 
But it shouldn't be a bug like you can run multiple redis-cli(s) connecting to a same server instance.

**Comment by a95241815** [comment]
yeah,it shouldn't be a bug
