### ISSUE TITLE
Centos7 install - qtmake-qt5 build step fails

### ISSUE THREAD

**Issue by ChiralMedia** [redis/RedisDesktopManager#4159]
RDM Version: 0.9 
Environment (OS name and version): Centos 7 (7-5.1804)
Redis Server Version: None yet

Steps to reproduce:

Follow install steps for Centos7 from http://docs.redisdesktop.com/en/latest/install/#build-from-source

1. git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm
2. cd src/
3. ./configure (warns “No Package qt5-qtcharts-devel available”)
4. qmake-qt5 

Expected result:  No error, able to continue with install steps

Actual Result: 
>qtmake-qt5
Project ERROR: Unknown module(s) in QT: charts

Qtmake-qt5 --version
QMake version 3.1
Using Qt version 5.9.2 in /usr/lib64

Fails in the same way using git clone https://github.com/uglide/RedisDesktopManager.git to get latest.

Error is similar to cases #66 and #3894
3894 proposes a fix, adding qt5-qtcharts-devel to the config script, but no such package exists for Centos7 hence the warning in the ./configure step.

**Comment by uglide** [comment]
Since qt5-qtcharts-devel is not available on CentOS you need to install Qt 5.9 from qt.io binary package
