### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by zhuangjiaju** [redis/RedisDesktopManager#4163]
This text is google translated, so the grammar may not be normal. RedisDesktopManager is one of the best Redis management tools I have ever used. I am also very grateful to the author for his hard work. But there is no memcached management tool on the market. See if you can consider a support for memcached by RedisDesktopManager. There should be more people who will thank you. Of course this is just a suggestion.

**Comment by uglide** [comment]
Thanks for your feedback.
