### ISSUE TITLE
cannot execute 'source /opt/qt59/bin/qt59-env.sh && qmake'

### ISSUE THREAD

**Issue by Eazyer** [redis/RedisDesktopManager#4164]
when I install it  on my ubuntu 16.04 by git clone , I haven't get the Makefile under the src folder, so that 'make' cannot work, and errors like that:
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:159: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:160: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:212: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:212: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:212: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:212: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
Info: creating stash file /home/packages/rdm/src/.qmake.stash
/opt/qt59/mkspecs/features/toolchain.prf:215: Cannot write cache file /home/packages/rdm/src/.qmake.stash: Permission denied
WARNING: OBJECTS_DIR: Cannot access directory '../bin/linux/release/obj'
WARNING: DESTDIR: Cannot access directory '../bin/linux/release'
WARNING: PRECOMPILED_DIR: Cannot access directory '../bin/linux/release/obj'
WARNING: rcc: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: rcc: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: rcc: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: rcc: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: rcc: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_predefs: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_header: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
WARNING: moc_source: Cannot access directory '/home/packages/rdm/bin/linux/release/obj'
Failure to open file: /home/packages/rdm/src/Makefile
Unable to generate makefile for: /home/packages/rdm/src/rdm.pro

Is anything changed?

**Comment by uglide** [comment]
You have issues with folder permissions
