### ISSUE TITLE
Compilation failure: 'fatal error: qsshclient.h: No such file or directory'

### ISSUE THREAD

**Issue by wanhongfu** [redis/RedisDesktopManager#4171]
RDM Version: 0.9
Environment (OS name and version): Ubuntu 18.04

Dear all, I am hitting below failure when making the code: 

> _In file included from ../3rdparty/qredisclient/src/qredisclient/connection.cpp:11:0:
../3rdparty/qredisclient/src/qredisclient/transporters/sshtransporter.h:4:10: fatal error: qsshclient.h: No such file or directory
 #include <qsshclient.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:11121: recipe for target '../bin/linux/release/obj/connection.o' failed
make: *** [../bin/linux/release/obj/connection.o] Error 1_

Actually _qsshclient.h_ can be found from: _rdm/3rdparty/qredisclient/3rdparty/qsshclient/src/qsshclient.h_

Appreciated if anybody can help, thanks

**Comment by uglide** [comment]
You can install RedisDesktopManager on Ubuntu using snapcraft https://snapcraft.io/redis-desktop-manager
