### ISSUE TITLE
[MacOS] error: failed to parse default search paths from compiler output

### ISSUE THREAD

**Issue by nosweat** [redis/RedisDesktopManager#4176]
11:57:37: Running steps for project rdm...
11:57:37: Starting: "/usr/local/Cellar/qt/5.11.1/bin/qmake" /Users/../rdm/src/rdm.pro -spec macx-g++ CONFIG+=x86_64 CONFIG+=qtquickcompiler CONFIG+=force_debug_info CONFIG+=separate_debug_info
Project ERROR: failed to parse default search paths from compiler output
11:57:37: The process "/usr/local/Cellar/qt/5.11.1/bin/qmake" exited with code 3.
Error while building/deploying project rdm (kit: Desktop)
When executing step "qmake"
11:57:37: Elapsed time: 00:00.

I followed all the steps here:

**Build on OS X**
1. Install XCode with Xcode build tools
2. Install Homebrew
3. Copy `cd ./src && cp ./resources/Info.plist.sample ./resources/Info.plist`
4. Building RDM dependencies require i.a. openssl and cmake. Install them: brew install openssl cmake
5. Build RDM dependencies `./configure`
6. Install Qt 5.9. Add Qt Creator and under Qt 5.9.x add Qt Charts module.
7. Open ./src/rdm.pro in Qt Creator
8. Run build

Tried reinstall still the same.

**Comment by uglide** [comment]
see @zxj5470 comment below

**Comment by zxj5470** [comment]
use Clang instead of gcc
