### ISSUE TITLE
[Windows] Cannot build 0.9.4 on Windows

### ISSUE THREAD

**Issue by djjsdtc** [redis/RedisDesktopManager#4177]
RDM Version: 0.9.4<br>
Environment (OS name and version): Windows 10.0.17134.165<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. build rdm.pro using QT 5.11.1

Expected result: 

Actual Result: 
LNK1181: Could not open input file libssh2.lib

**Comment by uglide** [comment]
Hello,
documentation was a bit outdated - fixed now http://docs.redisdesktop.com/en/latest/install/#build-on-windows
