### ISSUE TITLE
[Question] Why isn't a macOS binary available?

### ISSUE THREAD

**Issue by peterschussheim** [redis/RedisDesktopManager#4183]
Thank you for the work on this application, it is the best redis gui client :)

As the title asks, why isn't a macOS binary available?  I'd like to make this happen but would like to understand why it isn't currently available.

**Comment by uglide** [comment]
It's available for users with subscription https://redisdesktop.com/download
Money collected from subscriptions allow me to dedicate more time to the project development.

**Comment by peterschussheim** [comment]
Why not charge for the GNU build also?

**Comment by uglide** [comment]
Because it's my donation to the open source world.
