### ISSUE TITLE
Missing rdm desktop icon

### ISSUE THREAD

**Issue by shifters67** [redis/RedisDesktopManager#4194]
RDM Version: 0.94+fa963b7
Environment (OS name and version): Ubuntu 18.04
Redis Server Version: 4.0.9

Steps to reproduce:

1. Install the RedisDesktopManager via the snap installer

2. Installation works fine but there is no icon in the menu or when putting the .desktop file on the Desktop (just a red circle with a across through it.

**Comment by noitalihinna** [comment]
nice!

**Comment by willwh** [comment]
I installed `snapd` on Fedora 28, and then installed `redis-desktop-manager`.

I am not sure exactly where the problem resides here, but symlinking the `.desktop` shortcut to my local user's application shortcuts seems to work nicely:

```ln -s /var/lib/snapd/desktop/applications/redis-desktop-manager_rdm.desktop ~/.local/share/applications ```

My guess is that Fedora doesn't attempt to read `/var/lib/snapd/desktop/`.

**Comment by uglide** [comment]
Fixed

**Comment by tylercollier** [comment]
On Ubuntu 20.04, using its launcher tool, typing `redis` doesn't show anything. Instead, look for RDM.

**Comment by uglide** [comment]
@tylercollier this was fixed in the latest 2021.3 release 
thanks to https://github.com/uglide/RedisDesktopManager/pull/5002
