### ISSUE TITLE
Function loss: missing right click menu on floder

### ISSUE THREAD

**Issue by radcat1987** [redis/RedisDesktopManager#4198]
RDM Version: 
Environment (OS name and version):  mac os 
Redis Server Version: <br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result: 

![image](https://user-images.githubusercontent.com/1320466/44452979-8b421080-a62a-11e8-8705-35b0250eeb74.png)

**Comment by uglide** [comment]
Upgrade your RDM to 0.9.4
