### ISSUE TITLE
find a redisDeskTop Manager BUG

### ISSUE THREAD

**Issue by chenypgg** [redis/RedisDesktopManager#4211]
RDM Version: 0.9.1 ~ 0.9.5
Environment (OS name and version): windows10
Redis Server Version: all

Problem description:

Open the command window of RMD, enter select x, x is greater than the maximum DB index of the connected redis server, and the command window outputs "ERR invalid DB index" after carriage return. At this point, enter select x, x is an arbitrary number, and the command window will not reflect after carriage return. Close the command window, RDM will automatically close

**Comment by uglide** [comment]
Good one! Thanks!

**Comment by chenypgg** [comment]
My English is not good. I can only use Baidu translate.

**Comment by uglide** [comment]
@chenypgg it's good enough, thanks!
