### ISSUE TITLE
Can't connect to elasticache redis cluster via NAT instance

### ISSUE THREAD

**Issue by jeremytm** [redis/RedisDesktopManager#4221]
RDM Version: 0.9.x
Environment (OS name and version): Mac OS 10.13.6
Redis Server Version: 4.x Cluster (ElastiCache)

Steps to reproduce:

1. Setup elasticache cluster in AWS

2. Setup NAT Instance to access cluster from outside AWS VPC

3. Attempt to connect to cluster using RDM with Nat Instance

Expected result: 
Successful connection and key listing

Actual Result: 
A connection is established, but then it tries to connect to cache nodes using their internal, private IP addresses inside AWS VPC.

Suggested Solution:
We have solved this problem with ioredis (node.js client) by adding providing the mappings from each internal IP + port, to the public NAT ip + port. Something similar could be done within connection settings in RDM.

**Comment by uglide** [comment]
Hello
@jeremytm Have you tried to uncheck this setting in connection settings ?
![image](https://user-images.githubusercontent.com/1655867/45417523-01b2bb00-b68b-11e8-8d1e-7f9fe98638f7.png)

**Comment by jeremytm** [comment]
Amazing, I hadn't noticed the 'Advanced' section before. Yes this works!

Thank you!
