### ISSUE TITLE
sometimes the dendrogram cannot contract

### ISSUE THREAD

**Issue by FunctionD** [redis/RedisDesktopManager#4222]
RDM Version: 0.9.0.684<br>
Environment (OS name and version): Windows 7 ultimate sp1<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. ...Click the dendrogram of folder until you can see the key

2. ...Then you can find you can‘t contract the dendrogram with double-click or click the triangle on the left
unless you choose to refresh whole ‘db0’ or connection

3. ...It will be more clear with Chinese communication

**Comment by uglide** [comment]
You are using old version of RedisDesktopManager. Please upgrade your RDM to 0.9.6

**Comment by FunctionD** [comment]
But you no longer provide EXE file to download.

**Comment by uglide** [comment]
You can buy subscription to support farther development or contribute something (translation update, etc) to this repo to get it for free.
