### ISSUE TITLE
Debian 9 - не запускается вообще

### ISSUE THREAD

**Issue by zuart** [redis/RedisDesktopManager#4224]
Установлен через snap. Пытаюсь запустить через ярлык - никакой реакции.
Пробую запустить напрямую через консоль:
/snap/redis-desktop-manager/current/bin/desktop-launch

ln: failed to create symbolic link '/.config/dconf/user': File exists
ln: cannot remove '/.config/ibus/bus': Permission denied
./desktop-launch: строка 449: /flavor-select: Нет такого файла или каталога

Попытка другая:
/snap/redis-desktop-manager/current/opt/redis-desktop-manager/rdm

./rdm: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Как запускать-то? В чем проблема?

**Comment by uglide** [comment]
После установки через snap должна появится  команда `redis-desktop-manager.rdm` запускайте с ее помощью

**Comment by zuart** [comment]
Команда появилась, но запуск не производится все-равно.

/snap/bin/redis-desktop-manager.rdm

cannot create user data directory: /DATA/Profile/snap/redis-desktop-manager/107: Read-only file system


Путь существует, интереса ради удалил полностью /DATA/Profile/snap и перезапустил команду. Получил ту же самую ошибку, но в профиле появилась директория snap и вложенные директории...

/DATA/Profile/snap/redis-desktop-manager# ls -l
drwxr-xr-x 2 zloy zloy 4096 сен 14 15:03 107
drwxr-xr-x 2 zloy zloy 4096 сен 14 15:03 common
lrwxrwxrwx 1 zloy zloy    3 сен 14 15:03 current -> 107


И пути и права существуют, а вот запуска нет. Может какие-то логи могут помочь?

**Comment by dtr0yan** [comment]
Такая же беда

**Comment by uglide** [comment]
Проблема заключается в баге в snapcraft. Нужно сделать bind mount в стандартную директорию home https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352/20
