### ISSUE TITLE
ssh pem file linux path with dots issue

### ISSUE THREAD

**Issue by rnd49** [redis/RedisDesktopManager#4230]
When path to ssh file contains dots in folder name i.e: .ssh, .a
got error:
**Unable to extract public key from private key file: Unable to open private key file**

RDM Version: <br>
- RedisDesktopManager 0.9.6-ef394e5

Environment (OS name and version): 
- Description:	Ubuntu 16.04.5 LTS
- Release:	16.04
- Codename:	xenial

Redis Server Version: 
- 4.0.11

Steps to reproduce:

1. create folders and copy existing common usable pem file from ~/.ssh/ folder
   - :~$ mkdir without-dots
   - :~$ mkdir .with-dots
   - :~$ cp .ssh/my_pem_file.pem without-dots/
   - :~$ cp .ssh/my_pem_file.pem .with-dots/

2. choise pem file in rdm gui (without dots OK case)
![image](https://user-images.githubusercontent.com/26868471/45646080-03391480-bacb-11e8-9b77-36c23f6c00ad.png)
![image](https://user-images.githubusercontent.com/26868471/45645612-b0ab2880-bac9-11e8-9bd7-4ee9e428b09e.png)

3. choise pem file in rdm gui (with dots error case)
![image](https://user-images.githubusercontent.com/26868471/45645919-a0e01400-baca-11e8-8dc2-40cf75c7b913.png)
![image](https://user-images.githubusercontent.com/26868471/45646149-34b1e000-bacb-11e8-8792-a83c9f51c130.png)
additional log cut:
2018-09-17 22:43:50 : Connection: Connecting to SSH host...
2018-09-17 22:43:50 : Connection: Cancel running commands
2018-09-17 22:43:50 : Connection: Disconnect on error: SSH Connection error(Authentication Error): Unable to extract public key from private key file: Unable to open private key file
2018-09-17 22:43:50 : Connection: Cancel running commands
2018-09-17 22:43:50 : Connection: Disconnect on error: Cannot connect to SSH host

Expected result: 
![image](https://user-images.githubusercontent.com/26868471/45645612-b0ab2880-bac9-11e8-9bd7-4ee9e428b09e.png)

Actual Result: 
![image](https://user-images.githubusercontent.com/26868471/45646140-3085c280-bacb-11e8-9c1e-27333af9f4e7.png)

**Comment by uglide** [comment]
It's snapcraft issue https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1607067
Leaving this issue open to keep track progress on it

**Comment by Jimbolino** [comment]
the fix for this is merged
https://github.com/snapcore/snapd/pull/5845

**Comment by uglide** [comment]
@Jimbolino thanks for the link, I will update snapcraft file to use new feature

**Comment by Jimbolino** [comment]
is this bug actually fixed? i still experience the same issue.

**Comment by uglide** [comment]
@Jimbolino See note with command here http://docs.redisdesktop.com/en/latest/install/#ubuntu-archlinux-debian-fedora-centos-opensuse-etc
