### ISSUE TITLE
不支持redis集群

### ISSUE THREAD

**Issue by meiwulang** [redis/RedisDesktopManager#4231]
版本:0.9.5
问题描述：
连接集群节点，一会儿就卡死了 ，没有任何数据返回

期望：
1、支持集群配置
2、连接任意一个节点，可以查出保存在任意节点的数据

**Comment by uglide** [comment]
@wangbin123634 
Could you please specify Redis version? Do you use ssh tunnel?

**Comment by meiwulang** [comment]
redis version: redis-4.0.10
using default settings
![image](https://user-images.githubusercontent.com/24241535/45802761-4fae6b00-bcea-11e8-8052-0abc68e51024.png)

**Comment by uglide** [comment]
redis 4.0.10 is not available for windows so you have invalid connection settings
