### ISSUE TITLE
Reload value not working

### ISSUE THREAD

**Issue by jeremytm** [redis/RedisDesktopManager#4242]
RDM Version: 0.9.7.x (but has been apparent in previous versions)
Environment (OS name and version): macOS 10.13.6
Redis Server Version: 3.29, and 4.x, at least
Steps to reproduce:

1. Load a data set
(May potentially need namespaced keys + value should be JSON data)

2. Hit 'Reload value'

Expected result: Value reloads

Actual Result: Value display area goes blank, new value does not load

---

Apologies if this is something silly on my end. It's been a bug in all versions I can remember, and I assumed it would be a common use thing, and would be fixed by now. So it's probably me.

**Comment by uglide** [comment]
It's old bug. Will fix in 0.9.8 :)

**Comment by uglide** [comment]
Fixed in 0.9.8 (cooming soon)
