### ISSUE TITLE
Compile error link on win10 : fatal error LNK1104: 无法打开文件“libssh2.lib”

### ISSUE THREAD

**Issue by liulidong882004** [redis/RedisDesktopManager#4246]
RDM Version: <br>0.99
Environment (OS name and version):win10 <br>
I have followed the steps
after use  bulid  libssh2 the libssh2.lib is in  libssh2/build/src/Debug/
and I modify the 3rdparty.pri  
 LIBSSH_LIB_PATH = $$PWD/libssh2/build/src/Debug
but  still take error 
<img width="601" alt="wx20180927-153607 2x" src="https://user-images.githubusercontent.com/10649275/46130234-59484d80-c26b-11e8-9f64-bbd5406f27d2.png">
<img width="746" alt="wx20180927-153752 2x" src="https://user-images.githubusercontent.com/10649275/46130235-59e0e400-c26b-11e8-9833-df6892931a38.png">
<img width="758" alt="wx20180927-153838 2x" src="https://user-images.githubusercontent.com/10649275/46130269-7250fe80-c26b-11e8-947e-db7e59fcb025.png">

**Comment by uglide** [comment]
You can specify full path to libssh2 in LIBS

**Comment by liulidong882004** [comment]
@uglide Can you tell me more in detail? I don't know how to operate it.

**Comment by uglide** [comment]
Instead of `-llibssh2` specify here https://github.com/uglide/qsshclient/blob/master/3rdparty/3rdparty.pri#L19 full path to your `libssh2.lib`

**Comment by liulidong882004** [comment]
@uglide 
<img width="1142" alt="wx20180927-164959 2x" src="https://user-images.githubusercontent.com/10649275/46134422-6b2eee00-c275-11e8-8680-17f7b07258d7.png">
LIBS += -L$$LIBSSH_LIB_PATH -L$$OPENSSL_LIB_PATH -lZ:\Downloads\rdm\3rdparty\qredisclient\3rdparty\qsshclient\3rdparty\libssh2\build\src\Debug\libssh2.lib
like  this?
