### ISSUE TITLE
update from 0.9.0-dev to 0.9.8 or 0.9 

### ISSUE THREAD

**Issue by polearnik** [redis/RedisDesktopManager#4254]
RDM Version: 0.9 0.98 <br>
Environment (OS name and version): Linux Mint 17.3 <br>
Redis Server Version: <br>

Steps to reproduce:

1. git pull

2. git submodule update --recursive

3. cd src && ./configure

Expected result: 

Actual Result: config.status: executing depfiles commands
~/rdm/3rdparty/qredisclient/3rdparty/qsshclient ~/rdm/3rdparty/gbreakpad
/home/user/rdm/src/..//build/common_functions: row 22: ./configure: file not exist

**Comment by uglide** [comment]
Make fresh clone or add `-init` flag to submodule command
