### ISSUE TITLE
Redis GUI Issue

### ISSUE THREAD

**Issue by byazrail** [redis/RedisDesktopManager#4255]
RDM Version: 0.9.7.59
Environment (OS name and version): Mac OS 10.14
Redis Server Version: 4.0.10

Steps to reproduce:

1. Close Tabs No Name

2. Server Info Commands Processed

3. Server Info Uptime

Expected result: 

Actual Result: 
<img width="1096" alt="screen shot 2018-10-05 at 10 48 44" src="https://user-images.githubusercontent.com/5870455/46522900-c6239f00-c88c-11e8-90f5-80f730e7c580.png">
<img width="381" alt="screen shot 2018-10-05 at 10 49 07" src="https://user-images.githubusercontent.com/5870455/46522902-c6239f00-c88c-11e8-8f1b-5821632d1546.png">

**Comment by uglide** [comment]
Thanks for the feedback. I've improved server info tab (coming soon in 0.9.8 release)
![image](https://user-images.githubusercontent.com/1655867/46725005-e1731d80-cc83-11e8-8291-bd5665dc56e7.png)
![image](https://user-images.githubusercontent.com/1655867/46725016-e89a2b80-cc83-11e8-9324-a74fd9330c5c.png)
![image](https://user-images.githubusercontent.com/1655867/46725023-ef28a300-cc83-11e8-994f-d639a37c1ef8.png)
![image](https://user-images.githubusercontent.com/1655867/46725052-fea7ec00-cc83-11e8-8416-b1f5704129bb.png)

**Comment by byazrail** [comment]
@uglide Nice perfect ^_^
