### ISSUE TITLE
GUI issue when keys contain \n

### ISSUE THREAD

**Issue by ea167** [redis/RedisDesktopManager#4256]
RDM Version: 0.9.7.59<br>
Environment (OS name and version): MacOS 10.14<br>
Redis Server Version: 4.0.10<br>

Steps to reproduce:

1. Add a key contain carriage returns ( \n )

Expected result: 

Key name forced on one line

Actual Result: 

![image](https://user-images.githubusercontent.com/571650/46565896-38ff3b00-c8ca-11e8-9768-427599e5f31f.png)

**Comment by uglide** [comment]
Fixed in 0.9.8 (cooming soon)
