### ISSUE TITLE
GUI Bug 0.9.8.62 Mac OS Mojave

### ISSUE THREAD

**Issue by byazrail** [redis/RedisDesktopManager#4259]
RDM Version: 0.9.8.62
Environment (OS name and version): MacOS Mojave 10.14
Redis Server Version: -

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result: 

<img width="1595" alt="screen shot 2018-10-12 at 00 15 52" src="https://user-images.githubusercontent.com/5870455/46834842-3498bd80-cdb5-11e8-8520-8972b75ff097.png">

**Comment by jeremytm** [comment]
Got this too. It just goes black. If I drag the window to another screen the GUI shows, but it doesn't seem to react or refresh when I interact with anything.

(0.9.7 works fine on Mojave)

**Comment by uglide** [comment]
Looks like bug in Qt 5.9.6 on Mojave. Have added workaround in 0.9.8.63
