### ISSUE TITLE
Completely Black Window on MacOS Mojave

### ISSUE THREAD

**Issue by djeer** [redis/RedisDesktopManager#4260]
RDM Version: 0.9.8.62
Environment (OS name and version): MacOS 10.14 (18A391)
Redis Server Version: any

Steps to reproduce:

1. Start RDM

2. Got black screen

Expected result: rdm window

Actual Result: black window

Screenshot: https://www.dropbox.com/s/1uxbab5c0wrns1q/Screen%20Shot%202018-10-12%20at%2015.38.22.png?dl=0

**Comment by djeer** [comment]
I use compiled version (subscription)

**Comment by LiberiFatali** [comment]
same problem with Ubuntu 16.04, RDM latest version from Snap

**Comment by uglide** [comment]
@diman94 Upgrade to  0.9.8.63

**Comment by uglide** [comment]
@LiberiFatali could you provide screenshot and output from `redis-desktop-manager.rdm` command in terminal?

**Comment by ghost** [comment]
I remove and install RDM via Snap. It works now. Thanks
