### ISSUE TITLE
dependent '..\src\app\logger.h\ does not exist.

### ISSUE THREAD

**Issue by jetic83** [redis/RedisDesktopManager#4261]
RDM Version: newest (pulled 2018/10/14)<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: <br>

Steps to reproduce:

1. Follow the instructions on http://docs.redisdesktop.com/en/latest/install/#build-from-source for build on windows until Step 7

2. build project

Expected result: Build successful

Actual Result: QT error: `dependent '..\src\app\logger.h\ does not exist.` 

This file is not in the repo. Why is QT 5.9.6 expecting it? Where can I find it?

**Comment by jetic83** [comment]
I just saw that `src/app/logger.h` has been removed in commit 8bdc71851197d7863b2261d41b91706fc9d3dea8 but `rdm.pro` still lists this file as a dependent.

**Comment by jetic83** [comment]
Also I saw that I did not update the submodules of the repo. After updating/pulling the latest submodules, logger.h was still missing, but was only a warning in QT, not an error anymore.

So, QT went through, BUT I could not use the rdm.exe. When double click on the exe, the error arises "libssh2.dll was not found."

Any ideas?

![image](https://user-images.githubusercontent.com/11157551/46923689-7e69e980-cfe9-11e8-93dd-e955665bb455.png)

**Comment by jetic83** [comment]
After copying the libssh2.dll which I created in step 5 of the above build on windows guide into the .exe folder, the .exe complains about another missing dll: `Qt5Charts.dll`

Where is this one?

![image](https://user-images.githubusercontent.com/11157551/46923861-ce49b000-cfeb-11e8-88eb-9e0b8b07f234.png)

**Comment by uglide** [comment]
@jetic83 you can find in Qt lib folder
