### ISSUE TITLE
 keys are not mass deleted.

### ISSUE THREAD

**Issue by slavserver** [redis/RedisDesktopManager#4263]
RDM Version: 0.9.8.1156<br>
Environment (OS name and version): windows 10<br>
Redis Server Version: 4.0.11 ubuntu 16.04<br>

Sin a relatively large database, keys are not mass deleted. the program hangs, the connection is broken

**Comment by uglide** [comment]
Looks like a duplicate of #3918 
If you have any useful details or suggestions please add your comments there. Thanks!

**Comment by slavserver** [comment]
мне кажется трабл из за ssh тунелинга.. ведь виндой конект идет к редиске, которая на 127,0,0,1

**Comment by slavserver** [comment]
но когда ставишь версию под ubuntu, где у тебя есть непосредственный доступ без туннелирования, все работает прекрасно

**Comment by uglide** [comment]
@slavserver спасибо, я попробую проверить вашу гипотезу
