### ISSUE TITLE
Slowlog Text Rendering Issue

### ISSUE THREAD

**Issue by kfrancis** [redis/RedisDesktopManager#4264]
RDM Version: 0.9.8.1156
Environment (OS name and version): Windows Server 2016 Standard (v10.0.14393)
Redis Server Version: 3.0.504

Steps to reproduce:

1. Open RDM

2. View server info

3. View Slowlog

Expected result: To see a list of slow commands

Actual Result: The text is garbled
![on-sql01 - 199 48 102 143_58756 - remote desktop connection 2018-10-17 13 31 57](https://user-images.githubusercontent.com/67574/47105164-2a414e00-d211-11e8-8ac9-ce6fcd1f1b45.png)

**Comment by mexchip** [comment]
Would something like this be an acceptable solution?
![image](https://user-images.githubusercontent.com/2236848/47130295-9ac28c00-d25e-11e8-9bce-681fa0b8032c.png)

I've just made a PR: #4265.
