### ISSUE TITLE
Build RDM to app file in Mac

### ISSUE THREAD

**Issue by shanealynn** [redis/RedisDesktopManager#4266]
Hi guys, while the build instructions work to get a debug version running in QT Creator - are there instructions to bring this to a .app file that can be used normally on Mac? I dont think this build finishes this - the .app file created at /bin/osx/debug/rdm.app cannot be opened or executed.

**Comment by uglide** [comment]
Issues on github is for issues, not for questions.  You can ask for help in t.me chat
