### ISSUE TITLE
I'm not able to download the version for windows

### ISSUE THREAD

**Issue by pedrobacchini** [redis/RedisDesktopManager#4271]
I'm not able to download the version for windows that according to the documentation should be on this page.

https://redisdesktop.com/download

**Comment by uglide** [comment]
![image](https://user-images.githubusercontent.com/1655867/47551254-61e38080-d90a-11e8-9ec2-59105b7a0c71.png)
Hello as mentioned in the documentation you need subscription to download windows build from http://redisdesktop.com/download

**Comment by pedrobacchini** [comment]
even if you registered the following message appears:
You do not have active subscription.

**Comment by uglide** [comment]
Subscription means that you are supporting RDM or you are a contributor https://redisdesktop.com/subscribe

**Comment by pedrobacchini** [comment]
woooo ok, thx for reply.
