### ISSUE TITLE
key/value pairs are repeated

### ISSUE THREAD

**Issue by qiqiming** [redis/RedisDesktopManager#4273]
RDM Version: 0.9.8
Environment (OS name and version): macOS 10.13.6
Redis Server Version: 3.2.10

Steps to reproduce:

1. click connection

2. click db0

Expected result: 
Keys are not duplicated

Actual Result: 

Sometimes, keys are repeated
![123](https://user-images.githubusercontent.com/28074433/47542848-e2f24600-d911-11e8-9ed4-84073305c031.png)

**Comment by uglide** [comment]
@qiqiming Could you provide more details on how to reproduce this issue?
