### ISSUE TITLE
Not paid after payment

### ISSUE THREAD

**Issue by zhengxiang5965** [redis/RedisDesktopManager#4274]
RDM Version: <br>0.9.3.817
Environment (OS name and version): <br>Windows10
Redis Server Version: <br>

Steps to reproduce:
![image](https://user-images.githubusercontent.com/31379313/47544249-a9710900-d918-11e8-92b5-c5c686fe46a4.png)

Expected result: 
update version
Actual Result: 
I entered this link and made a payment, but did not update me any version.
Receipt number：2998-8476-1722-2959
Redis Desktop Manager account：472010602@qq.com

**Comment by uglide** [comment]
Hello
Special offer applies only on Windows builds and is delivered to you by email. If you need access to all builds please buy full subscription via your account on redisdesktop.com
