### ISSUE TITLE
Can't compile on windows following the docs

### ISSUE THREAD

**Issue by micdenny** [redis/RedisDesktopManager#4288]
I simply followed the instruction here: http://docs.redisdesktop.com/en/latest/install/#build-from-source trying building on windows, but I get a lot of errors while building from Qt build.

What I noticed is that the `Build libssh2 library in folder 3rdparty/qredisclient/3rdparty/qsshclient/3rdparty/libssh2 using CMake` is no longer valid, because the libssh2 dependencies has been drop with this commit https://github.com/uglide/qredisclient/commit/5dc41a51fc6a6e94695b9ac4e7a619a18cf42f75

so I don't understand this steps:

```
cmake -DCRYPTO_BACKEND=WinCNG -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./output --build .
cmake --build . --target install
mkdir build\src\release
copy output\lib\* build\src\release
```

I just tried to open the `rdm.pro`, enabled the 32bit release, but I got all these errors:

![image](https://user-images.githubusercontent.com/1633595/48258786-49995880-e416-11e8-9a9f-bdceeae2070b.png)

I can provide a virtual machine on the cloud ready to go with all the tools installed on it, the one is getting exactly that behavior, if you want the access just send me an email micdenny@gmail.com

**Comment by uglide** [comment]
This documentation is a bit outdated. I will update it.

**Comment by micdenny** [comment]
@uglide if you want a virtual machine ready-to-go just ask. I can also provide you a clean one with just vs15/vs17 pre-installed.

**Comment by uglide** [comment]
@micdenny Docs was updated

**Comment by micdenny** [comment]
@uglide the build works fine.

now, how can I include all the correct dependencies? using `windeployqt`? but which are the correct steps?

**Comment by uglide** [comment]
@micdenny 
Yes, just use `windeployqt`:
`windeployqt --release --force --qmldir ../src/qml rdm.exe`
