### ISSUE TITLE
failed to build ... connot filnd 3rdparty/qredisclient/qredisclient.pri

### ISSUE THREAD

**Issue by caiweics** [redis/RedisDesktopManager#4289]
RDM Version: <br>0.9
Environment (OS name and version): <br> Ubuntu 16.04
Redis Server Version: <br>

Steps to reproduce:

1. git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9 rdm && cd ./rdm

2.  qmake -v
QMake version 3.1
Using Qt version 5.9.2 in /home/caiwei/Qt5.9.2/5.9.2/gcc_64/lib

3. caiwei@ubuntu:~/tmp/qml/src_compile/rdm/src$ qmake 
Info: creating stash file /home/caiwei/tmp/qml/src_compile/rdm/src/.qmake.stash
Cannot read /home/caiwei/tmp/qml/src_compile/rdm/3rdparty/qredisclient/qredisclient.pri: No such file or directory

I cannt not find the expected file such as qredisclient.pri, #include <qredisclient/redisclient.h>

so I need your help

**Comment by uglide** [comment]
Try to make fresh clone or update git modules with `git submodules update --init --recursive`
