### ISSUE TITLE
Black Screen on Launch of QTCreator on MacOSX

### ISSUE THREAD

**Issue by shanealynn** [redis/RedisDesktopManager#4297]
RDM Version: 0.98
Environment (OS name and version): OSX 10.14.1

Steps to reproduce:

1. Build with src/configure. Apply fix as in other issue for "Build for Deployment Version"

2. build with QTCreator

Build process exits normally. RDM starts, but the window is completely black. You can click on buttons and see the logs, but nothing is rendered.

```
7:01:10: Starting /Users/shane/Documents/Programs/rdm/bin/osx/debug/rdm...
App font: "Helvetica Neue" 12
("en-IE")
Detected locale: "en_IE"
Permission changed
qml: Editor for type undefined is not defined!
qml: Editor for type undefined is not defined!
qml: Empty value. Skipping formatting stage
file:///Users/shane/Qt/5.9.6/clang_64/qml/QtQuick/Controls/ScrollView.qml:234:9: QML Binding: Binding loop detected for property "value"
qrc:///common/platformutils.js:7: TypeError: Cannot read property 'devicePixelRatio' of undefined
Rendering backend: ""
```
![image](https://user-images.githubusercontent.com/8168156/48638467-a376c100-e9c8-11e8-927a-f9905f34c220.png)

Secondary, and potentially (probably) not related, but clicking wildly around in the black darkness, error: 
```
Connection error: QRedisClient compiled without ssh support.
```

**Comment by uglide** [comment]
Just add `--rendering-backend auto` argument to fix black screen
