### ISSUE TITLE
where is the 0.9.9 version subscriptions site?

### ISSUE THREAD

**Issue by byazrail** [redis/RedisDesktopManager#4303]
RDM Version: 0.9.9
Environment (OS name and version): OSX
Redis Server Version: 4.10

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result: 
where is the 0.9.9 version subscriptions site?
https://redisdesktop.com/subscriptions

**Comment by uglide** [comment]
It's already there ;)
