### ISSUE TITLE
Cannot connect to SSH host by using ssh tunnel

### ISSUE THREAD

**Issue by peihuadeng** [redis/RedisDesktopManager#4306]
RDM Version: v.0.9.3.817
Environment (OS name and version): win7 pro
Redis Server Version: redis-4.0.11
Steps to reproduce:
I setup SSH tunnel with password
Here is message:
2018-11-29 22:58:35 : Connection: Connecting to SSH host...
2018-11-29 22:59:34 : Connection: Cancel running commands
2018-11-29 22:59:34 : Connection: Disconnect on error: Cannot connect to SSH host
Expected result: 
success to login redis
Actual Result: 
fail to login redis

**Comment by uglide** [comment]
Hello
Have you tried to connect with putty?

**Comment by peihuadeng** [comment]
success to connect ssh host with secureCRT which is same as putty.

**Comment by uglide** [comment]
RDM v0.9.3 is built on top of libssh2 1.8.0 which doesn't support Ed25519 and ECDSA keys. Most likely it is your case.
