### ISSUE TITLE
i am a chinese people, i only want a 1 year of FREE subscription

### ISSUE THREAD

**Issue by FmoreMore** [redis/RedisDesktopManager#4320]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result:

**Comment by onewe** [comment]
no way

**Comment by uglide** [comment]
Anyone can build RDM from source, if you want it for free - it's the way

**Comment by onewe** [comment]
😉😉😉😉
