### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by MrChocol** [redis/RedisDesktopManager#4322]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result:

**Comment by liu-wentao** [comment]
Redis Server Version: 

Steps to reproduce:
1.https://redisdesktop.com/download
2.Submit Pull Request to RDM repository on GitHub and get it merged.
Expected result:
