### ISSUE TITLE
I just want to try RDM, if the experience is good, I will consider subscribing.

### ISSUE THREAD

**Issue by pjstack-dev** [redis/RedisDesktopManager#4336]
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 

Actual Result:

**Comment by onewe** [comment]
You can build RDM from source.see http://docs.redisdesktop.com/en/latest/install/#build-from-source
