### ISSUE TITLE
No way to refresh collection on a Mac 

### ISSUE THREAD

**Issue by nello** [redis/RedisDesktopManager#4359]
Same issue as https://github.com/uglide/RedisDesktopManager/issues/1689 which should not have been closed. No right-click on Mac.

**Comment by uglide** [comment]
@nello Which version of RDM do you use?

**Comment by nello** [comment]
Hi, thanks for replying. I'm running 0.7.6, which I downloaded from SourceForge.

Neil

**Comment by uglide** [comment]
Current version is 0.9.9 has refresh button, you can build it from source or buy subscription to download it from redisdesktop.com

**Comment by nello** [comment]
Thank you
