### ISSUE TITLE
Response received : -ERR DB index is out of range

### ISSUE THREAD

**Issue by neangsinuhgo** [redis/RedisDesktopManager#4361]
Response received : -ERR DB index is out of range

**Comment by neangsinuhgo** [comment]
hi,how to fix it?

**Comment by uglide** [comment]
If you see this message in app log when you are loading list of db's - it's ok.

**Comment by neangsinuhgo** [comment]
> If you see this message in app log when you are loading list of db's - it's ok.
But i cant read the key ,the app is loading 
like this 
scan 188518 MATCH *80965 COUNT 10000
Connection: ip> Response received : Array
Connection: ip> Response received : Array
Connection:  ip > [runCommand] scan 147993 MATCH * COUNT 10000
Connection:  ip > [runCommand] scan 193550 MATCH *80965942 COUNT 10000

**Comment by uglide** [comment]
Please provide output for redis command: `INFO`

**Comment by neangsinuhgo** [comment]
> Please provide output for redis command: `INFO`

I connect the db with windows client,there are more 200000 keys, is it out of range?

**Comment by uglide** [comment]
Which version of RDM do you use?

**Comment by neangsinuhgo** [comment]
V 0.9.9
