### ISSUE TITLE
Server list always clears

### ISSUE THREAD

**Issue by mooleshacat** [redis/RedisDesktopManager#4364]
**Describe the bug**
Every time I start RDM it is blank... The connections I entered last time are gone and I have to enter all the tedious settings again. RDM should be remembering the connections I have made already.

Debian 9

**Comment by uglide** [comment]
It happens on snap update because connection settings was stored in the versioned directory. Should be fixed by https://github.com/RedisDesktop/redisdesktopmanager-snap/commit/8977a8d0bafe9ca34216d85b3cf211181f3e2fac
