### ISSUE TITLE
display publish topic 

### ISSUE THREAD

**Issue by jeremystack** [redis/RedisDesktopManager#4368]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I user the publish feature ，I don't know what tops I have.

**Describe the solution you'd like**
I want check the all topics,and display the clients connected.

**Comment by uglide** [comment]
I will add it as new tab to Server Information just like clients list, etc  
![image](https://user-images.githubusercontent.com/1655867/50422492-c1e79c00-0853-11e9-8c9e-4319f448db8c.png)
