### ISSUE TITLE
Filters are not applied when click on "Reload Namespace" button

### ISSUE THREAD

**Issue by iworker** [redis/RedisDesktopManager#4382]
I'm not sure if it's bug or expected behaviour. If you have some keys divided into namespaces, you created a filter and you want to reload all the keys in the namespace using the button "Reload Namespace", you receive all the keys from the namespace instead of filtered set of keys.

Steps:
1. Apply some filter;
2. Click on "Reload Keys in Database" (keys reloaded with applying of filter as expected);
3. Go to some namespace and click the button "Reload Namespace";

**Expected behavior**
Filtered keys from the namespace

**Actual behavior**
All the keys from the namespace

**Screenshots**
1. All the keys in redis:
![image](https://user-images.githubusercontent.com/3360296/50906266-c906d080-1435-11e9-891f-ce462d54a387.png)
2. Filter by `*test*`:
![image](https://user-images.githubusercontent.com/3360296/50906315-e0de5480-1435-11e9-9580-45369907bb3c.png)
3. Click on the "Reload Namespace" button:
![image](https://user-images.githubusercontent.com/3360296/50906346-ed62ad00-1435-11e9-911a-2acd476fc542.png)
and receive all the keys from the namespace:
![image](https://user-images.githubusercontent.com/3360296/50906370-f94e6f00-1435-11e9-9e9f-bc60f8a2f09d.png)

**Environment:**
 - macOS Mojave 10.14.2
 - redis 3.2

**Comment by uglide** [comment]
Note: to fix this bug we need to load data using namespace "filter" for scan and do post-filtering using global filter.

PS: Closing your PR for now
