### ISSUE TITLE
win10 1809 cannot open the RDM

### ISSUE THREAD

**Issue by zhangyongfeng13** [redis/RedisDesktopManager#4390]
I cannot open the RDM with the latest version 0.9.9.
My OS is windows 10 professional edition 1809.

**Comment by uglide** [comment]
@zhangyongfeng13 Please provide more info:
You cannot run the installer or installed application?

**Comment by SweetInk** [comment]
@uglide i face the same issue.after 0.9.* ,RDM could opened, but the GUI window cannot be seen.
my os is win10 professional1809

**Comment by zhangyongfeng13** [comment]
> @zhangyongfeng13 Please provide more info:
> You cannot run the installer or installed application?

I have already installed the application. My problem is the same with @SweetInk .

**Comment by uglide** [comment]
@SweetInk @zhangyongfeng13 Please download and run [Microsoft DebugView utility](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) and try to run RDM again. After that paste messages from DebugView here. Thanks!

**Comment by SweetInk** [comment]
@uglide I downloaded and ran the DebugView and then ran RDM, but I saw no log output from the DebugView

**Comment by SweetInk** [comment]
@uglide Here  is my opertation steps video: [RDM compilation and run process](https://youtu.be/P-4B-56Z0Xg).
As you see,the main window can not be shown,i am not modified the souce code, i just download it ,and open it in Qt Creator,and compilation &&  run it.

**Comment by YannySky** [comment]
@uglide i have the same problem. And I get these logs: 
[14956] App font: "微软雅黑" 11
[14956] Permission changed
[14956] qml: Editor for type undefined is not defined!
[14956] qml: Editor for type undefined is not defined!
[14956] qml: Empty value. Skipping formatting stage
[14956] Rendering backend: "software"
[14956] https://redisdesktop.com/qml/ConnectionSuggestions.qml?app_version=0.9.9.181128&platform=windows&new=true: File not found
[14956] https://redisdesktop.com/qml/News.qml?app_version=0.9.9.181128&platform=windows: File not found

**Comment by flamhaze5946** [comment]
00000001	0.00000000	[115124] Suspending	
00000002	0.55637103	[59108] App font: "Open Sans" 11	
00000003	0.63132507	[59108] ("zh-CN", "en-US")	
00000004	0.63140458	[59108] Detected locale: "zh_CN"	
00000005	0.63151217	[59108] Load translations file for locale: "zh_CN"	
00000006	0.63246685	[59108] New config already exist. Ignore old configs.	
00000007	0.63395071	[59108] Permission changed	
00000008	1.27721882	[59108] qml: Editor for type undefined is not defined!	
00000009	1.37900651	[59108] file:///D:/Softwares/RedisDesktopManager/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"	
00000010	1.38945615	[59108] file:///D:/Softwares/RedisDesktopManager/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"	
00000011	1.91372478	[59108] qml: Editor for type undefined is not defined!	
00000012	2.61803317	[59108] qml: Empty value. Skipping formatting stage	
00000013	2.69025016	[59108] file:///D:/Softwares/RedisDesktopManager/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"	
00000014	2.70280409	[59108] file:///D:/Softwares/RedisDesktopManager/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"	
00000015	2.70798135	[59108] file:///D:/Softwares/RedisDesktopManager/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"	
00000016	2.71390843	[59108] file:///D:/Softwares/RedisDesktopManager/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"	
00000017	2.84632087	[59108] qml: Ratio > 1.0. Resize main window.	



I have a similar problem when I was opening rdm. :(

**Comment by YannySky** [comment]
i just solve my problem.
1.open taskmanager.
2.find rdm process.
3.right click and choose maximize.
then the rdm window show up

it happens when i move rdm window to ext-screen and close rdm before move back.
when i disconnect ext-screen and reopen rdm, rdm is still in disconected ext-screen so i can't see it.

**Comment by flamhaze5946** [comment]
> i just solve my problem.
> 1.open taskmanager.
> 2.find rdm process.
> 3.right click and choose maximize.
> then the rdm window show up
> 
> it happens when i move rdm window to ext-screen and close rdm before move back.
> when i disconnect ext-screen and reopen rdm, rdm is still in disconected ext-screen so i can't see it.

you solved the problem which noised me, thank you for your reply !

**Comment by SweetInk** [comment]
> i just solve my problem.
> 1.open taskmanager.
> 2.find rdm process.
> 3.right click and choose maximize.
> then the rdm window show up
> 
> it happens when i move rdm window to ext-screen and close rdm before move back.
> when i disconnect ext-screen and reopen rdm, rdm is still in disconected ext-screen so i can't see it.

This also solves my problem. you're really a genius. I want to know how this works.

**Comment by uglide** [comment]
Should be solved by 3fda22761699dc9fc3ef3dd0abca7ad0235cb911
