### ISSUE TITLE
Refresh to work within the collection instead of going to db

### ISSUE THREAD

**Issue by AdityaJaiswal1** [redis/RedisDesktopManager#4395]
I find it very frustrating to go all the way to up to refresh the db. There is a shortcut for Refresh but that too work only reaching at the top of db selection. Really it that shortcut work within between of keys would be a boon.

**Comment by uglide** [comment]
Which version of RDM do you use?

**Comment by AdityaJaiswal1** [comment]
0.8.7.322

**Comment by uglide** [comment]
it is implemented in 0.9.9
