### ISSUE TITLE
./configure fails on ubuntu 16.04

### ISSUE THREAD

**Issue by wardseptember** [redis/RedisDesktopManager#4399]
wardseptember@wardseptember:~/opt/RedisDesktopManager-0.9.9/src$ ./configure 
====================================================================
Build RDM on Ubuntu: 16
====================================================================
====================================================================
Install packages required by 3rdparty deps
====================================================================
[sudo] password for wardseptember: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
automake is already the newest version (1:1.15-4ubuntu1).
libtool is already the newest version (2.4.6-0.1).
cmake is already the newest version (3.5.1-1ubuntu3).
The following package was automatically installed and is no longer required:
  libqt5quickwidgets5
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 217 not upgraded.
fatal: destination path 'src/third_party/lss' already exists and is not an empty directory.
/home/wardseptember/opt/RedisDesktopManager-0.9.9/src/..//build/common_functions: line 17: ./configure: No such file or directory

**Comment by uglide** [comment]
You just need carefully read output:
`fatal: destination path 'src/third_party/lss' already exists and is not an empty directory.`
Remove this folder from `3rdparty/breakpad`,  or just make fresh clone of RDM repo

**Comment by wardseptember** [comment]
@uglide I knew it,but I removed this folder or make fresh clone repo,still don't work.Use `sudo snap install redis-desktop-manager` then succeed.thanks.
