### ISSUE TITLE
Fix tab navigation order in connection creation form

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#44]
Currently when you open connection creation form "OK" button is selected.

Arguably it would be more suitable to select host name by default.

Then If you press tab several time the order would be:

OK -> Cancel -> Connection Settings -> Port -> Auth -> Host -> Name.

I don't know why it is set that way, but it can be changed to:

Name -> Host -> Port -> Auth -> OK -> Cancel.

In SSH Tunnel tab order is almost preserved from top to bottom except port input.

And one more issue. When selecting input fields with tabs OK button on both tabs is shows as selected but pressing enter doesn't work in this situation (do not close tab)

**Comment by uglide** [comment]
thx for feedback, I will fix it in 0.5.0
