### ISSUE TITLE
discrepancy between contents of .zip and instructions how to build from src in Windows

### ISSUE THREAD

**Issue by pluczak99** [redis/RedisDesktopManager#4408]
Basically, the 3rdparty\qredisclient folder is empty, there is no "hiredis" subfolder, therefore the instructions to build the RedisDesktopManager from source is invalid and must be corrected.

In general, forcing developers who just want to try Redis and Redis Desktop Manager to build from scratch by either buying a subscription or using inaccurate instructions is not very elegant and reminds me of times, when open source software was thrown into faces of developers with attitude of "it's free, so either use your grey matter or get lost". Not sure if anyone got to be a millionaire from subscriptions of RDM, but a basic community version binaries should be prebuilt and ready to download for those, who just start experimenting with Redis. The attitude has to look professional, not like it is looks now.

**Comment by uglide** [comment]
Hello, repo should be cloned with submodules with `--recursive` flag for `git clone` command (this is mentioned in docs BTW). 

The idea behind RDM pricing is quite simple - if you have enough money to buy expensive Windows license or Apple hardware - please support RDM via subscription or spend some time to make PR or/and build it from source. If you don't have any money - use open source free operation systems where RDM can be installed in one command via snapcraft.

**Comment by pluczak99** [comment]
> The idea behind RDM pricing is quite simple - if you have enough money to buy expensive Windows license or Apple hardware - please support RDM via subscription or spend some time to make PR or/and build it from source. If you don't have any money - use open source free operation systems where RDM can be installed in one command via snapcraft.

Thank you, I appreciate the response explaining further steps. In this case I decided to proceed with RDBTools and FastNoSQL monitoring tools, which allowed me to complete my evaluation without pulling out my bank card (cheapest subscription) or my remaining hair (building from src). Thanks again.
