### ISSUE TITLE
[UI issue] Console window, Horizontal Scrollbar and Copy block clipboard issue

### ISSUE THREAD

**Issue by illlust** [redis/RedisDesktopManager#4413]
**Describe the bug**

1. SUBSCRIBE channel on Console Window
2. Receive very long messages (in my case, over 5~6,000 column)
3. Can not drag received text block, and can not copy to clipboard
and Horizontal Scrollbar not working.
so, Can not do anything

**To Reproduce**
1. Go to Console Window
2. SUBSCRIBE channel
3. Receive very long message (6,000~)
4. Can't drag text or scroll horizontal

**Expected behavior**
Horizontal Scrollbar working on Console Window
Copy Very long text to Clipboard, and working drag.

**Screenshots**
![subscribecopy](https://user-images.githubusercontent.com/475315/52111791-0121bd80-2648-11e9-9242-3f46ffc1fd05.png)

**Environment (please complete the following information):**
 - OS & version: Windows 10 1809
 - Redis-Server version 3.2.100

**Additional context**

**Comment by uglide** [comment]
@illlust Thanks for the feedback.
