### ISSUE TITLE
Scrollbar doesn't work.

### ISSUE THREAD

**Issue by soprathi77** [redis/RedisDesktopManager#4418]
**Describe the bug**
Scroll bar on left side window where we display the list of keys doesn't work.

**To Reproduce**
1. Open RDM
2. Connect Redis instance
3. See the Cache of Keys on left side window
4. When No of keys are too many then Scroll bar appears on Left side window
5. Try to use the scroll bar and see we can't hold it to drag down or up.

**Expected behavior**
Scroll  bar should be drag able with mouse.

**Screenshots**
![image](https://user-images.githubusercontent.com/10567273/52465223-dbdf0300-2ba3-11e9-8432-ca14e275d0a0.png)

**Environment (please complete the following information):**
 - OS & version: [Windows 10 ]
 - Redis-Server version [0.9.8]

**Additional context**
Appreciate your attention.

**Comment by abhiCR7** [comment]
I'm facing the same issue, response appreciated

**Comment by uglide** [comment]
@abhiCR7 Are you facing it on 2019.1 or older version?

**Comment by uglide** [comment]
@abhiCR7 @soprathi77 Could you provide more details about your screen resolution and scaling factor?

I've tried different combinations of scaling factors on 1080p and 4k screens and cannot reproduce this bug.

**Comment by uglide** [comment]
Feel free to reopen if you still experiencing this issue on 2019.X builds and please provide more details (see my previous comment)
