### ISSUE TITLE
How to use ‘Custom Value View Formatters’？

### ISSUE THREAD

**Issue by hsyang6688** [redis/RedisDesktopManager#4427]
**Describe the bug**
How to use ‘Custom Value View Formatters’？

**To Reproduce**
1. Go to '设置‘
2. Scroll down to '‘Custom Value View Formatters'

**Expected behavior**
通过界面就可以进行相关编辑设置

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
Just read the docs: http://docs.redisdesktop.com/en/0.9/features/#native-value-formatters
