### ISSUE TITLE
Complaint

### ISSUE THREAD

**Issue by byazrail** [redis/RedisDesktopManager#4480]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hello there,
I'm sorry if I bothered you.

I'm getting really uncomfortable about something.
I'm following your project, giving money and downloading the latest version.

Lately often unnecessary issue is opening, most of them are spam and free download request.
Is it possible that we can stop this?

**Comment by uglide** [comment]
Hello @byazrail 
One possible option is to press "unwatch" button above, and change notification level to "Releases Only" so you will receive only notification about new releases. 

If you have any other comments or suggestions feel free to share.
