### ISSUE TITLE
Refreshing data from ElastiCache Cluster via NAT server with non-6379 port, reverts to 6379

### ISSUE THREAD

**Issue by jeremytm** [redis/RedisDesktopManager#4487]
**Describe the bug**
We have two clusters in elasticache, each with just one node for now. We connect to each cluster for local testing via a NAT server using different ports to route traffic.

Cluster A is accessed via NAT port 6379 : Internal port 6379
Cluster B is accessed via NAT port 6380 : Internal port 6379

Upon first connection to cluster B, we see the correct keys in RDM. However, after refreshing the connection. We see the keys from cluster A.

This means it is dangerous to work with RDM because sometimes we might think we are working with cluster B, but really we are working with cluster A.

**To Reproduce**
1. Create two clusters which you will access via NAT (which means you must untick the 'Change host on cluster redirect' setting)
2. Ensure you are connecting to one cluster via port 6379, and one via 6380 or any non-6379 port (incoming to NAT only. After NAT routing inside VPC, both clusters use port 6379)
3. Connect to cluster with non-6379 port via NAT, note the keys shown in RDM
4. Refresh data for the cluster, and note keys are now shown for the 6379 cluster.

**Expected behavior**
Connection should be maintained via port 6380 rather than reverting to 6379 somehow. The only way to see the correct keys again is to restart RDM

**Screenshots**
Cluster B: https://i.imgur.com/y0BTRa6.png
Same cluster, different keys: https://i.imgur.com/mV5Mzl1.png

**Environment (please complete the following information):**
 - OS & version: macOS 10.14.4
 - Redis-Server version 5.0.3

**Comment by uglide** [comment]
Hello @jeremytm 

Please explain in detail how your NAT instance is configured and how much shards each cluster has. It's important to understand is it RDM issue or NAT instance configuration issue.

**Comment by uglide** [comment]
@jeremytm Most likely you have following configuration issue: 


![possible_issue](https://user-images.githubusercontent.com/1655867/56894339-35ade580-6a8e-11e9-90db-ccd7e1ac6d05.png)

I recommend to use SSH Tunnel to connect to ElasticCache because it doesn't require any NAT instance configuration, so it harder to mess up with connection settings.

**Comment by jeremytm** [comment]
Both clusters have one shard, no replicas.
Both clusters operate on 6379 internally.
Only the NAT is used with 6380, which points to 6379 internally for the other cluster.

I have the "Change host on cluster redirects" setting turned off, so it should not be redirecting, right?

<img width="347" alt="Screen Shot 2019-04-30 at 10 34 40 AM" src="https://user-images.githubusercontent.com/6539834/56931354-d73b4280-6b33-11e9-87d6-72b56475a118.png">

In the meantime I will look into SSH tunnelling.

**Comment by ghoulich** [comment]
It's a bug in qredisclient!

Even if "Change host on cluster redirects" setting has been turned off, RDM will still redirect port to actual cluster node!

You can modify connection.cpp source code in qredisclient, then rebuild version 2019.3 of RDM, you can find this source file in:
[https://github.com/uglide/qredisclient/blob/master/src/qredisclient/connection.cpp](https://github.com/uglide/qredisclient/blob/master/src/qredisclient/connection.cpp)

Then, modify line 527:
`reconnectTo(m_config.host(), h.second);`
to:
`reconnectTo(m_config.host(), m_config.port());`

This line means if "Change host on cluster redirects" option is off, then use original host configuration in RDM, include host ip and port!

I have rebuilt RDM 2019.3, it works with redis cluster fine:
![rdm2019 3](https://user-images.githubusercontent.com/3353241/64310865-7e455480-cfd4-11e9-83f7-43e9446dfda6.png)

At last, don't forget install python dependencies on your machine before starting rdm application:
`pip3 install -r rdm/src/py/requirements.txt`

@uglide I think you should solve this bug in qredisclient in next release, or "Change host on cluster redirects" option won't works fine ...

**Comment by uglide** [comment]
@ghoulich It's not a bug but not covered use-case. Your suggestion breaks cluster connections with multiple nodes, so we need new option in RDM to cover all cases - "Ignore cluster port redirects"

**Comment by uglide** [comment]
AWS has upgraded ElastiCache creation page and now it's possible to create 1 node of Redis without cluster mode enabled:

![image](https://user-images.githubusercontent.com/1655867/67385186-49e52200-f59b-11e9-9bae-ada5fbba955d.png)

**Please do not use cluster mode enabled if you need only one shard.**

If you need to connect to the **existing** one-node cluster on AWS please **use TLS-over-SSH tunnel instead of NAT instance.**
