### ISSUE TITLE
cant run last version 

### ISSUE THREAD

**Issue by polearnik** [redis/RedisDesktopManager#4499]
**Describe the bug**
try to install last version from snapcraft  and cant run. I tryed  to remove old version and install but it also failed to run.

**To Reproduce**
1. installed from snap 
2. start in console env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/redis-desktop-manager_rdm.desktop /snap/bin/redis-desktop-manager.rdm
App font: "Open Sans" 11
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.82\" (uid=1000 pid=12090 comm=\"/snap/redis-desktop-manager/264/opt/redis-desktop-\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1194 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.82\" (uid=1000 pid=12090 comm=\"/snap/redis-desktop-manager/264/opt/redis-desktop-\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1194 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
"Object path cannot be empty"
("ru-RU")
Detected locale: "ru_RU"
Load translations file for locale: "ru_RU"
terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid connections config
Error: Can't launch CrashReporter!
Аварийный останов

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: Linux mint 18.3 KDE
 - Redis-Server version 3.0.6

**Additional context**

**Comment by uglide** [comment]
@polearnik 
You are trying to install unstable version. Use stable instead:
```
sudo snap remove redis-desktop-manager
sudo snap install redis-desktop-manager --stable
```
