### ISSUE TITLE
Loader для запуска консоли

### ISSUE THREAD

**Issue by Dyachenko** [redis/RedisDesktopManager#45]
При запуске консоли не понятно что происходит и RDM наверное нужно добавить лоадер
version 0.4.2
windows 7 x64

**Comment by uglide** [comment]
Ты имеешь в виду нужно добавить индикатор того, что консоль загружается?

**Comment by Dyachenko** [comment]
когда на коннекшине клацаешь правой кнопкой мыши и выбираешь консоль то контекстное меню закрывается и ничего не происходит это настораживает.

**Comment by uglide** [comment]
Начиная со следующей версии консоль будет открываться сразу и коммуникация будет происходить в отдельном потоке, поэтому консоль будет более отзывчивой.
