### ISSUE TITLE
Contributor free subscription does not work :)

### ISSUE THREAD

**Issue by bocharsky-bw** [redis/RedisDesktopManager#4503]
The https://redisdesktop.com/download website says:
> Submit Pull Request to RDM repository on GitHub and get it merged.
> Sign in with GitHub to receive your free subscription.

Though, if I sing in with my GitHub account after made a PR that was merged - it does not give me Contributor free subscription :)

**Comment by uglide** [comment]
@bocharsky-bw just cherry-picked your commit from 0.9 branch, please wait until you appear on redisdesktop.com page and press "Get free contributor subscription button" on redisdesktop.com/subscriptions page

**Comment by bocharsky-bw** [comment]
Thank you!
