### ISSUE TITLE
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):

### ISSUE THREAD

**Issue by idzireit** [redis/RedisDesktopManager#4505]
I have tried all the tutorials on the internet (which were few and far between) including any youtube tutorials on how to build and install cutter (that was non existent).  I have installed packages, tried using qtcreator and everything for me has failed.  If anyone has any suggestions or tips (greatest would be a youtube tutorial) I would greatly appreciate it (and probably so would anyone else who is having the same issues).  

These are the latest versions of cmake and qtcreator I am using:
qtcreator version 5.9.5(gcc 7.3.0, 64 bit)
cmake version     3.10.2
Here is the error I get when trying to buld using the build.sh command:

configure-plugins: Loading ./plugins.cfg ..
Removed 0 shared plugins that are already static
lrelease: could not find a Qt installation of ''
./build.sh: 67: ./build.sh: [[: not found
./build.sh: 70: ./build.sh: [[: not found
qmake: could not find a Qt installation of ''
make: *** No targets specified and no makefile found.  Stop.
Something went wrong!

In hopes someone will be able to aid with the build/installation of this,
Sincerely, 
Proteus

**Comment by uglide** [comment]
It's RDM repo and it doesn't have any `build.sh`
