### ISSUE TITLE
Breakpad.xib: patch does not apply (branch 2019.0)

### ISSUE THREAD

**Issue by HanawaBanana** [redis/RedisDesktopManager#4523]
when I clone this repo(checkout branch:2019.0). I run ./configure, get this response.
``` shell
error: patch failed: src/client/mac/sender/Breakpad.xib:1114
error: src/client/mac/sender/Breakpad.xib: patch does not apply
```

this is steps.
```shell
git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 2019.0
cd RedisDesktopManager/src/
./configure
```

it's shell screenshots.
![image](https://user-images.githubusercontent.com/33088672/56732980-6beb1c80-6791-11e9-94d8-8953e66b5f10.png)
it's Breakpad.xib screenshots.
![image](https://user-images.githubusercontent.com/33088672/56733163-f16ecc80-6791-11e9-8727-ce888e84bf0d.png)

**Environment**
mac OS version:10.14.4 (18E226)
qt version:5.12.0

**Comment by cielu** [comment]
@Hanawa , have you ever solved this problem? I have met this problem too

**Comment by HanawaBanana** [comment]
> @hanawa have you ever solved this problem? I have met this problem too

nope...
I tried 0.9.8, 0.9.999. It works. But not 2019.0.

**Comment by cielu** [comment]
> nope...
> I tried 0.9.8, 0.9.999. It works. But not 2019.0.

May not support anymore.

**Comment by uglide** [comment]
@HanawaBanana @cielu Please edit line `git apply ../breakpad_osx.patch` to `git apply -v ../breakpad_osx.patch` in `src/configure` to see why git fails to apply patch

**Comment by cielu** [comment]
@HanawaBanana  Have you ever build succeed? I build it successed

**Comment by dennismphil** [comment]
@uglide 
```
$ cat configure | grep "git apply"
    git apply -v ../breakpad_osx.patch


$ ./configure
Warning: coreutils 8.31 is already installed and up-to-date
To reinstall 8.31, run `brew reinstall coreutils`
Checking patch src/client/mac/sender/Breakpad.xib...
error: src/client/mac/sender/Breakpad.xib: No such file or directory
```

**Comment by sawyersoft** [comment]
Warning: coreutils 8.31 is already installed and up-to-date
To reinstall 8.31, run `brew reinstall coreutils`
Checking patch src/client/mac/sender/Breakpad.xib...
error: while searching for:
		<string key="IBDocument.TargetRuntimeIdentifier">IBCocoaFramework</string>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.macosx</string>
			<integer value="1050" key="NS.object.0"/>
		</object>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDevelopmentDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.InterfaceBuilder3</string>

error: patch failed: src/client/mac/sender/Breakpad.xib:1114
error: src/client/mac/sender/Breakpad.xib: patch does not apply

**Comment by sawyersoft** [comment]
![image](https://user-images.githubusercontent.com/5139862/56866739-63077e80-6a0f-11e9-9b70-9e7c5519b827.png)

**Comment by kanyways** [comment]
@uglide   

```xml
Checking patch src/client/mac/sender/Breakpad.xib...
error: while searching for:
		<string key="IBDocument.TargetRuntimeIdentifier">IBCocoaFramework</string>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.macosx</string>
			<integer value="1050" key="NS.object.0"/>
		</object>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDevelopmentDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.InterfaceBuilder3</string>

error: patch failed: src/client/mac/sender/Breakpad.xib:1114
error: src/client/mac/sender/Breakpad.xib: patch does not apply
```

**Comment by kanyways** [comment]
OS: macOS Mojave 10.14.4

**Comment by kanyways** [comment]
@HanawaBanana  @cielu   I edit line git apply ../breakpad_osx.patch to # git apply -v ../breakpad_osx.patch in src/configure, It works.

**Comment by dxsooo** [comment]
if brew run into error, breakpad_osx.patch will failed

thus you can ensure your brew never error by comment the error install scripts

```
# On OSX use coreutils package to fix absense of readlink command
# if [[ $OSTYPE == darwin* ]]; then
#   brew install coreutils || true
#   PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# fi

# brew upgrade openssl || brew install openssl || true
```

in my case is coreutils and openssl, you can install it manually

you may need to clean up before rebuild

**Comment by echokk11** [comment]
> @HanawaBanana @cielu I edit line git apply ../breakpad_osx.patch to # git apply -v ../breakpad_osx.patch in src/configure, It works.

it still not work.

```
...
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: invalid character '_' in Bundle Identifier at column 18. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: no debug symbols in executable (-arch x86_64)
Error: openssl 1.0.2r already installed
Warning: openssl 1.0.2r is already installed and up-to-date
To reinstall 1.0.2r, run `brew reinstall openssl`
```

**Comment by sundayha** [comment]
```
OS: macOS Mojave 10.14.2 (18C54)
Xcode 10.1
Build version 10B61
```
same error

**Comment by littlefisher666** [comment]
same error

**Comment by jsrpy** [comment]
same error

**Comment by cyf-hopex** [comment]
Once apply the patch, it already changed the file  3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib.
Second time run ./configure, it cannot find where to patch so it will emit this error.  
So discard the change in 3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib or comment git apply ../breakpad_osx.patch in build/common_functions may help.

**Comment by alanxiaowei** [comment]
rdm$ ./src/configure
Warning: coreutils 8.31 is already installed and up-to-date
To reinstall 8.31, run `brew reinstall coreutils`
Checking patch src/client/mac/sender/Breakpad.xib...
error: while searching for:
		<string key="IBDocument.TargetRuntimeIdentifier">IBCocoaFramework</string>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.macosx</string>
			<integer value="1050" key="NS.object.0"/>
		</object>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDevelopmentDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.InterfaceBuilder3</string>

error: patch failed: src/client/mac/sender/Breakpad.xib:1114
error: src/client/mac/sender/Breakpad.xib: patch does not apply

> @HanawaBanana @cielu Please edit line `git apply ../breakpad_osx.patch` to `git apply -v ../breakpad_osx.patch` in `src/configure` to see why git fails to apply patch

**Comment by alanxiaowei** [comment]
- 

> @HanawaBanana @cielu Please edit line `git apply ../breakpad_osx.patch` to `git apply -v ../breakpad_osx.patch` in `src/configure` to see why git fails to apply patch

rdm$ ./src/configure
Warning: coreutils 8.31 is already installed and up-to-date
To reinstall 8.31, run `brew reinstall coreutils`
Checking patch src/client/mac/sender/Breakpad.xib...
error: while searching for:
		<string key="IBDocument.TargetRuntimeIdentifier">IBCocoaFramework</string>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.macosx</string>
			<integer value="1050" key="NS.object.0"/>
		</object>
		<object class="NSMutableDictionary" key="IBDocument.PluginDeclaredDevelopmentDependencies">
			<string key="NS.key.0">com.apple.InterfaceBuilder.CocoaPlugin.InterfaceBuilder3</string>

error: patch failed: src/client/mac/sender/Breakpad.xib:1114
error: src/client/mac/sender/Breakpad.xib: patch does not apply

**Comment by xSandie** [comment]
> I edit line git apply ../breakpad_osx.patch to # git apply -v ../breakpad_osx.patch in src/configure, It works.

I edit line git apply ../breakpad_osx.patch to # git apply -v ../breakpad_osx.patch in src/configure, It works.
and 
I edit the rdm.pro, comment the lines 
```
#    debug:   DESTDIR = ./../bin/osx/debug
······
#    release {
#        CRASHREPORTER_APP.files = $$DESTDIR/crashreporter
#        CRASHREPORTER_APP.path = Contents/MacOS
#        QMAKE_BUNDLE_DATA += CRASHREPORTER_APP
#    }
``` 
and do
`qmake CONFIG-=debug && make` in cmd
then it works

**Comment by echokk11** [comment]
it interrupt here
```
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: invalid character '_' in Bundle Identifier at column 18. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: no debug symbols in executable (-arch x86_64)
Error: openssl 1.0.2s already installed
Warning: openssl 1.0.2s is already installed and up-to-date
To reinstall 1.0.2s, run `brew reinstall openssl`
```

**Comment by xSandie** [comment]
@echokk11
I comment all the lines where `brew install` appears and install them manually.

**Comment by moqimoqidea** [comment]
I have met this problem too.

**Comment by Offirmo** [comment]
Exact same problem.
