### ISSUE TITLE
Change "View as" data format error

### ISSUE THREAD

**Issue by NewGr8Player** [redis/RedisDesktopManager#4542]
**Describe the bug**
Choose "View as" to "HEX Table" and then change to "JSON",the data will be chaos.

**To Reproduce**
1. Choose one data with json-format
2. Change "View as" from "Json" to "Hex Table"
3. Change "View as" to "Json"

**Expected behavior**
Just show the data correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13497267/57602276-4d5a9300-7591-11e9-9e52-d088a7a7bef4.png)

![image](https://user-images.githubusercontent.com/13497267/57602295-577c9180-7591-11e9-8ee7-5ad6a3967559.png)

![image](https://user-images.githubusercontent.com/13497267/57602309-5fd4cc80-7591-11e9-9867-657ee6b185f8.png)

**Environment (please complete the following information):**
 - Windows 10 17763
 - 4.0.2.3

**Comment by uglide** [comment]
This bug was fixed in 2019.0. Please upgrade your RDM
