### ISSUE TITLE
How to launch it???

### ISSUE THREAD

**Issue by moldovans** [redis/RedisDesktopManager#4548]
The [QuickStart](http://docs.redisdesktop.com/en/0.9/quick-start/) describes how to use it.

The Install describes how to install it...

I installed it via the command line and from the code source on Linux Mint (ubuntu)

```
cd src/
./configure
qmake && make && sudo make install
cd /opt/redis-desktop-manager/
sudo mv qt.conf qt.backup
```
**But how the hell to open it once installed??** 

there is nothing found in the application when I search "redis"...

**Comment by uglide** [comment]
Run `/opt/redis-desktop-manager/rdm`

**Comment by moldovans** [comment]
don't you think is useful to note in a product technical documentation the point on how to launch the application?

**Comment by uglide** [comment]
I do not recommend to build RDM from source on Linux (section in docs is marked as outdated and will be removed). Just use ready-to-use snap from snap store https://snapcraft.io/redis-desktop-managerand and launch RDM by clicking on icon in your app launcher.

**Comment by drazisil** [comment]
If you installed via the snap on Debian, you start it with `/snap/bin/redis-desktop-manager.rdm`

**Comment by serhioV** [comment]
> If you installed via the snap on Debian, you start it with `/snap/bin/redis-desktop-manager.rdm`

What is Debian?

**Comment by moldovans** [comment]
@uglide, @drazisil  Please update your docs to reflect that. Nobody knows it.

**Comment by uglide** [comment]
@serhioV Added to docs
