### ISSUE TITLE
什么时候支持中文

### ISSUE THREAD

**Issue by xue253** [redis/RedisDesktopManager#4586]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by xue253** [comment]
不支持

**Comment by ge00111** [comment]
为什么不支持中文啊

**Comment by uglide** [comment]
You can select Chinese in settings
![image](https://user-images.githubusercontent.com/1655867/58621592-7047af80-82d2-11e9-92c3-ee65fbed6c5c.png)
