### ISSUE TITLE
Duplicate keys are shown in the tree

### ISSUE THREAD

**Issue by santhoshtns** [redis/RedisDesktopManager#4589]
**Describe the bug**
After connecting to the redis cache server. Expand the tree node to see that the duplicate keys are shown

**To Reproduce**
1. Go to Redis Desktop Manager
2. Click on Connect to connect to the redis server
3. Expand the nodes and notice the child nodes
4. The keys are duplicated. Each key is shown twice.

**Expected behavior**
Only one node should be shown for each key. Keys are unique.

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: Windows 10 1806
 - Redis-Server version 9.3.817

**Comment by uglide** [comment]
Please upgrade RedisDesktopManager to 2019.1

**Comment by cobolbaby** [comment]
### Screenshots

This bug is reproduced in the new version 2019.4. 

![2019-11-26 16-14-26屏幕截图](https://user-images.githubusercontent.com/11460848/69610822-8b1f9480-1067-11ea-856c-6986b806b228.png)

### Environment

OS version: Ubuntu16.04
Redis Cluster version: 5.0.6

**Comment by cobolbaby** [comment]
@uglide Could you reopen the issue :smile:

**Comment by uglide** [comment]
@cobolbaby Please specify what type of connection (direct, ssh tunnel, tls tunnel, tls-over-ssh tunnel) and redis-server (standalone or cluster) and version do you use?

**Comment by cobolbaby** [comment]
@uglide 

- connection: direct
- redis-server: cluster 5.0.6
