### ISSUE TITLE
The GUI is not visible after startup

### ISSUE THREAD

**Issue by kanevbg** [redis/RedisDesktopManager#4590]
The issues is in that the GUI is simple not visible anywhere on the screen, but the program is started according to the windows tab and the task manager. I feel like it is dragged outside of the visible area of the desktop.

**To Reproduce**
I really do not know how it came up like that. I happened firstly after using version 2019.

**Environment (please complete the following information):**
 - OS & version: Microsoft Windows [Version 10.0.17763.475]
 - Redis Desktop Manager version: redis-desktop-manager-2019.1.1346

**Comment by RahulBhammarker** [comment]
One of my colleague faced the same issue not with the redis-desktop-manager but with some other application. I could not be able to find the exact cause of it yet but just as a hack I found a solution or I would rather say a trick ;) that you can try until the fix. 

Once you have opened the application just hover over the application icon in the taskbar and then the thumbnail comes up on top of it hover over again on the thumbnail and right click there, you will find options to minimize, maximize and move the widow just click on maximize and it should appear.

**Comment by kanevbg** [comment]
@RahulBhammarker Thank you man! This helped me restore the GUI.

**Comment by ich-wangxf** [comment]
Thank you man!

**Comment by nikoduran** [comment]
Great tx!
