### ISSUE TITLE
version0.9.8.1156 db0(0) but console keys * not null

### ISSUE THREAD

**Issue by miraclekill** [redis/RedisDesktopManager#4592]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
Upgrade to 2019.1
