### ISSUE TITLE
Shortcut for "flush database" activates when editing filter text

### ISSUE THREAD

**Issue by ndamclean** [redis/RedisDesktopManager#4593]
RDM has a shortcut key for the "flush database" command (CTRL+DEL/META+DEL). In my opinion, a shortcut key for this highly destructive action is undesirable.

Additionally, the shortcut chosen is frequently used by other software as a key to "delete word after cursor" when editing a text field.

This means, that if a user is trying to edit a "filter" for keys in a database, pressing CTRL+DEL will result in a prompt to delete all keys in that database instead of deleting text after the cursor (which would be a reasonable expectation).

https://github.com/uglide/RedisDesktopManager/blob/d4d09cfbdeca99e3f169a0763ddef9c1f9b99afe/src/qml/connections-tree/menu/database.qml#L117-L118

I think there are 3 options to fix this issue:
- shortcut key combination should be removed
- shortcut key combination should be replaced with a different key combination
- UI should ignore shortcut key if user is editing a text field

**Comment by uglide** [comment]
@ndamclean I agree with your point and will remove shortcut for flush operation in 2019.2
