### ISSUE TITLE
App crash when adding row in ZSET

### ISSUE THREAD

**Issue by dmax1** [redis/RedisDesktopManager#4596]
**Describe the bug**
App crash when manually adding row in ZSET. This behavior is reproduced if one or two app windows are open

**To Reproduce**
1. select key that you want to populate
1. click "add row" and enter value and score
3. click "OK" to add and then application crash

**Expected behavior**
Row is added, however app should not close (crash)

**Environment (please complete the following information):**
 - OS & version: Windows 10 1809
 - Redis-Server version: current RedisLap
- Redis Desktop Manager: 2019.1.1346

**Comment by uglide** [comment]
Reproduced, Thanks!

**Comment by ly0929simon** [comment]
very goog, thanks!
