### ISSUE TITLE
scan a lot keys causing “BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.”

### ISSUE THREAD

**Issue by cupen** [redis/RedisDesktopManager#4599]
**Describe the bug**
view a lot keys causing redis can not working for other programs.

**To Reproduce**
Have 7M keys in a redis instance. 
Open RedisDesktopManager
1. Connect to a redis instance.
2. Go to 'left menu'
3. Click on 'db0 which has 7M keys' 
4. Waiting for a long time with 'scan keys'.
5. Run your program read from redis while waiting for 'scan keys'.
6. See error "BUSY Redis is busy running a script"

**Expected behavior**
RedisDesktopManager scan keys quietly, don't "make global lock or other similar".

**Environment**
 - OS & version: archlinux
 - Redis-Server version: 2019.1-1

**Comment by uglide** [comment]
@cupen Have you enabled this setting ?
![image](https://user-images.githubusercontent.com/1655867/59494710-65764880-8e96-11e9-8744-48a144562cfa.png)

If so just disable it and RDM will do direct scans instead of executing lua script to retrieve keys from server

**Comment by cupen** [comment]
Yes, I enabled this setting 
![image](https://user-images.githubusercontent.com/1221615/59495353-b64f6680-8ec1-11e9-8ef4-844e06a3453b.png)

As you said. I disable it, then it works good.
Thanks.
