### ISSUE TITLE
Update Windows Build Documentation on Wiki

### ISSUE THREAD

**Issue by STRATZ-Ken** [redis/RedisDesktopManager#4602]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the Windows build documentation is out of date.  

**Describe the solution you'd like**
The files and guidelines are out of date, some files don't exist.  The versions are old for Q, etc.

**Comment by sergey-v9** [comment]
+1

Have to spent a whole Friday evening to build the last version of RDM for Windows.

**Comment by STRATZ-Ken** [comment]
@dthpth Were you successful? Can you try to put some of the steps taken and/or wrong so we can push this ticket along?
Thank you!

**Comment by sergey-v9** [comment]
Sure. Thats what I have:

* Visual Studio 2017 Community installed
* Qt 5.9.8 MSVC2017 installed (with all extensions like QtCharts. not sure which ones needed)
* Python 3.7.3 amd64 installed to `C:\Python37` (the path is hard-coded I guess)
* [this one revision](https://github.com/uglide/RedisDesktopManager/tree/9ed78a0292ed21c6f66dd0b72614a90835ebe22e) of RDM cloned
* `hiredis-win.patch` applied (as described in Docs)

* also I have a [rmt_zlib](https://www.nuget.org/packages/rmt_zlib/1.2.8.5) package manually exracted to `\3rdparty\qredisclient\3rdparty\windows\rmt_zlib.1.2.8.5` 

Here is the changes I've made:

`\src\rdm.pro`:
```diff
@@ -71,10 +71,16 @@ win32 {
     QMAKE_TARGET_DESCRIPTION = "Open source GUI management tool for Redis"
     QMAKE_TARGET_COPYRIGHT = "Igor Malinovskiy (C) 2013-2019"
 
     win32-msvc* {
         QMAKE_LFLAGS += /LARGEADDRESSAWARE
+
+        # Disable C++ compiler optimizations (it fails to compile pyotherside)
+        QMAKE_CXXFLAGS_RELEASE -= -O1
+        QMAKE_CXXFLAGS_RELEASE -= -O2
+        QMAKE_CXXFLAGS_RELEASE -= -O3
+        QMAKE_CXXFLAGS_RELEASE *= -Od
     }
 
     release: DESTDIR = ./../bin/windows/release
     debug:   DESTDIR = ./../bin/windows/debug
 }
```

`\3rdparty\3rdparty.pri`:
```diff
@@ -47,10 +47,11 @@ win32* {
     win32-g++ {
         # Workaround for mingw
         QMAKE_LFLAGS_RELEASE=
     } else {
         INCLUDEPATH += $$PWD/qredisclient/3rdparty/windows/rmt_zlib.1.2.8.5/build/native/include
+        LIBS += $$PWD/qredisclient/3rdparty/windows/rmt_zlib.1.2.8.5/build/native/lib/v140/x64/Release/dynamic/zlib1.lib
     }
 
     HEADERS += $$BREAKPADDIR/common/windows/string_utils-inl.h
     HEADERS += $$BREAKPADDIR/common/windows/guid_string.h
     HEADERS += $$BREAKPADDIR/client/windows/handler/exception_handler.h
@@ -62,11 +63,10 @@ win32* {
     SOURCES += $$BREAKPADDIR/client/windows/handler/exception_handler.cc
     SOURCES += $$BREAKPADDIR/common/windows/string_utils.cc
     SOURCES += $$BREAKPADDIR/common/windows/guid_string.cc
     SOURCES += $$BREAKPADDIR/client/windows/crash_generation/crash_generation_client.cc
 
-    LIBS += -lz
 }
 
 unix:macx { # OSX
     PRE_TARGETDEPS += $$PWD/../build/gbreakpad/Products/Release/Breakpad.framework
     LIBS += $$PWD/../build/gbreakpad/Products/Release/Breakpad.framework/Versions/A/Breakpad
```

`\3rdparty\pyotherside.pri`:
```diff
@@ -1,15 +1,16 @@
 
 # Python
-PYTHON_CONFIG = python3-config
-
-QMAKE_LIBS += $$system($$PYTHON_CONFIG --ldflags --libs)
-QMAKE_CXXFLAGS += $$system($$PYTHON_CONFIG --includes)
 
 win32* {
     QMAKE_LIBS += -LC:\Python37\libs -lpython37
     INCLUDEPATH += C:\Python37\include\
+} else {
+    PYTHON_CONFIG = python3-config
+
+    QMAKE_LIBS += $$system($$PYTHON_CONFIG --ldflags --libs)
+    QMAKE_CXXFLAGS += $$system($$PYTHON_CONFIG --includes)
 }
 
 include(pyotherside/pyotherside.pri)
 
 DEFINES += PYOTHERSIDE_VERSION=\\\"$${VERSION}\\\"
```

`\3rdparty\pyotherside\src\qpython_priv.cpp`:
```diff
@@ -516,11 +516,11 @@ QPythonPriv::QPythonPriv()
 
     Py_InitializeEx(0);
     PyEval_InitThreads();
 
     // Initialize sys.argv (https://github.com/thp/pyotherside/issues/77)
-    int argc = 1;
+    const int argc = 1;
     wchar_t *argv[argc];
     argv[0] = Py_DecodeLocale("", nullptr);
     PySys_SetArgvEx(argc, argv, 0);
     PyMem_RawFree((void *)argv[0]);
 
```

After it open `rdm.pro` in QtCreator and configure it for the Release Qt version.

Hope this helps.


BTW I see more changes done for the Python path in the latest commits so my steps are outdated

**Comment by energizer77** [comment]
In latest commit the hardcoded Python folder is :
C:\Python37-x64\

For zlib I took it from there :
https://www.nuget.org/packages/zlib-msvc14-x64/

Then you put the zlib-msvc14-x64.1.2.11.7795 folder in the 3rd party folder.

**Comment by uglide** [comment]
2019 branch between tags is not stable. That's why I recommend to checkout tag 2019.1 for build from source.

**Comment by uglide** [comment]
Updated http://docs.redisdesktop.com/en/latest/install/#build-on-windows
