### ISSUE TITLE
Error transferring http://redisdesktop.com/crash-report - server replied: Request Entity Too Large

### ISSUE THREAD

**Issue by aolszowka** [redis/RedisDesktopManager#4615]
**Describe the bug**
Using Redis Desktop Manager v.0.8.8.384 attempting to connect to an old Redis Server it looks like it gets caught in a loop and then crashes; when attempting to send the crash report it gives this error:

```
---------------------------
Server error
---------------------------
Error transferring http://redisdesktop.com/crash-report - server replied: Request Entity Too Large
---------------------------
OK   
---------------------------
```

**To Reproduce**
1. Attempt to connect to the Redis Server

**Expected behavior**
I expect it to connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/2592881/60452166-30365e00-9beb-11e9-80f9-e1baf76d8e15.png)

**Environment (please complete the following information):**
 - OS & version: Windows 10 Pro Version 1803
 - Redis-Server version: Redis on Windows 3.2.100

**Additional context**
I'd love to upgrade the RDM version but I don't think I can, due to the old version of Redis Server. Even if I could I think then I'd need a license.

My guess is there is some type of connectivity problem and it just gets caught in a tight loop before failing. Installing RDM on the server in question and connecting there worked without issue.

**Comment by uglide** [comment]
0.8.8 is old and unsupported now. I recommend to upgrade RDM since your redis-server version supports `SCAN` command and it's required a minimum for using latest 2019.x versions.
Some features will not be available for your redis-server (like memory analyser which requires redis-server 4.0) but all basic features should work just fine.

**Comment by mrtruyen** [comment]
@uglide I got the same issue on version 0.9.3.817
