### ISSUE TITLE
Cannot select SSH key on Linux Mint. If entered manually, it say unable to open key file

### ISSUE THREAD

**Issue by tormit** [redis/RedisDesktopManager#4616]
File selector won't display any files in selected folder. Show hidden files is on.

![pem bug 1](https://user-images.githubusercontent.com/195688/60577716-8db3e180-9d88-11e9-90b3-7c754a85511f.png)

![pem bug 2](https://user-images.githubusercontent.com/195688/60577791-b9cf6280-9d88-11e9-90dc-369113759160.png)

If I copy the path of private key into file field and try to connect then it says "Unable to extract public key from private key file: Unable to open private key file."
Key file works fine with other applications.

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/install/#ubuntu-archlinux-debian-fedora-centos-opensuse-etc
