### ISSUE TITLE
Error prompt on startup

### ISSUE THREAD

**Issue by Christophernt** [redis/RedisDesktopManager#4619]
**Describe the bug**
Open the program and an error message appear.

**To Reproduce**
1. Double click rdm.exe
2. See error

**Expected behavior**
Open the program and no error message appear.

**Screenshots**
![Screenshots](https://user-images.githubusercontent.com/24423772/60636689-0fb80f00-9e4a-11e9-9dd6-5b67d49f0887.png)

**Environment (please complete the following information):**
 - Windows 7 sp1

**Additional context**
None

**Comment by Lvivinnie** [comment]
Have you installed the redis?

**Comment by Christophernt** [comment]
> Have you installed the redis?

No

**Comment by uglide** [comment]
This message means that you haven't installed python requirements from 'src/py/requirements.txt'

**Comment by Christophernt** [comment]
I have installed these requirements,but the problem remains.
![image](https://user-images.githubusercontent.com/24423772/61396333-10e14580-a8fa-11e9-907c-9deb017e3433.png)

**Comment by Christophernt** [comment]
> This message means that you haven't installed python requirements from 'src/py/requirements.txt'

I have installed these requirements,but the problem remains.
![61396333-10e14580-a8fa-11e9-907c-9deb017e3433](https://user-images.githubusercontent.com/24423772/61424297-9c33f880-a945-11e9-8aa7-2ea31cb6c3d6.png)

**Comment by Christophernt** [comment]
> This message means that you haven't installed python requirements from 'src/py/requirements.txt'

I have installed these requirements,but the problem remains.
