### ISSUE TITLE
版本2019.1构建不成功

### ISSUE THREAD

**Issue by xiaomao361** [redis/RedisDesktopManager#4623]
我通过tag（2019.1）或者commit（36b60425106fed94995a9d9cbe691d399b1332ee）构建出来的版本仍然显示2019.0.0，并且打开提示需要升级到2019.1后，整个APP就退出了。
以下是我的环境信息：

+  osx10.14.5
+  QMake version 3.1
+  Qt 5.11.1

**Comment by uglide** [comment]
You can bump version manually in RDM.pro file
