### ISSUE TITLE
Unable to install latest version on Windows 10

### ISSUE THREAD

**Issue by nkpun** [redis/RedisDesktopManager#4626]
When trying to install latest version of redis desktop, I keep getting error below per screenshot:

**Comment by nkpun** [comment]
Error is:
Download failed: Sendrequest error. Please install it manually and try again. $VCplus_URL.

I"m not sure what it means by install manually. That's what I'm doing it now (install manually from exe).

**Comment by uglide** [comment]
@nkpun what version are you trying to install? 2019.1?
Download and install https://aka.ms/vs/15/release/vc_redist.x64.exe
