### ISSUE TITLE
subscribe scheduled to be closed ASAP for overcoming of output buffer limits.

### ISSUE THREAD

**Issue by Benjamin142857** [redis/RedisDesktopManager#4627]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
@Benjamin142857 Please provide more details about the issue with steps to reproduce
