### ISSUE TITLE
Can't show the Desktop Window

### ISSUE THREAD

**Issue by 171563857** [redis/RedisDesktopManager#4641]
**Describe the bug**
just open the RedisDesktopManager, but only show "new upload available" Popup
can't see the window
already download again, still the case

**Comment by 171563857** [comment]
OS System: windows 10

**Comment by uglide** [comment]
Which version of RDM do you use? Could you provide screenshot of app?
It should be possible to just close update popup and use RDM without any issues.

**Comment by BlackColor** [comment]
..

**Comment by 171563857** [comment]
![image](https://user-images.githubusercontent.com/22027896/61372235-2f7b1880-a8c9-11e9-9dc5-f1326bea34f2.png)
just like this, can't show the RedisDesktopManager, thumbnail is a white window

**Comment by uglide** [comment]
Looks strange. Please install `DebugView`, re-run app and paste here logs from `DebugView`

**Comment by Jarrich** [comment]
Right click on the broken thumbnail, click Maximize. That's the workaround for now.

**Comment by 171563857** [comment]
> Right click on the broken thumbnail, click Maximize. That's the workaround for now.

I can open the window right now，but it's trouble to do this all the time.
