### ISSUE TITLE
Python.h not found when compiling

### ISSUE THREAD

**Issue by Offirmo** [redis/RedisDesktopManager#4646]
**Describe the bug**
On macOs X latest, following the build instructions http://docs.redisdesktop.com/en/latest/install/
I'm blocked at the Qt build complaining "'Python.h' file not found"

**To Reproduce**
build instructions http://docs.redisdesktop.com/en/latest/install/

**Expected behavior**
It should build

**Screenshots**
![Screen Shot 2019-07-17 at 15 19 29](https://user-images.githubusercontent.com/603503/61349106-4c522480-a8a6-11e9-8c1b-a333dc09025a.png)

**Environment (please complete the following information):**
 - macOs latest (at this time)
- python installed, reported version `brew info python` = `python: stable 3.7.4`
- Qt Creator 4.9.2 with Desktop Qt 5.9.8 clang 64 bits (5.9 as requested in the instructions)

**Comment by causlayer** [comment]
1.Get path “which python3-config”
2.Modify file /3rdparty/pyotherside.pri，PYTHON_CONFIG = $$PWD/python-3/bin/python3-config

**Comment by Offirmo** [comment]
Do I have to re-run ./configure?

**Comment by Offirmo** [comment]
Thanks, it worked! Changes made:
```
    #unix:macx {
    #  PYTHON_CONFIG = $$PWD/python-3/bin/python3-config
    #} else {
    #  PYTHON_CONFIG = python3-config
    #}
    PYTHON_CONFIG = /usr/local/bin/python3-config
```
 (I reran ./configure just in case)
Result:
![Screen Shot 2019-07-17 at 17 36 31](https://user-images.githubusercontent.com/603503/61356330-6fd29a80-a8b9-11e9-8936-69a663addc9c.png)

**Comment by uglide** [comment]
Please follow latest build instructions here http://docs.redisdesktop.com/en/latest/install/
You also need to install python requirements from `./src/py/requirements.txt`

**Comment by Offirmo** [comment]
Amazing! Thanks for supporting the free version!
