### ISSUE TITLE
Can't start 2019.2 on mac

### ISSUE THREAD

**Issue by LordZardeck** [redis/RedisDesktopManager#4653]
**Describe the bug**
I'm unable to run RDM on MacOS. The crash reporter opens, but then fails to upload crash report due to gateway error.

**To Reproduce**
1. Download RDM 2019.2
2. Install
3. Open application

**Expected behavior**
Application runs normally

**Environment (please complete the following information):**
 - OS & version: macOS 10.14.5 (18F132)
 - RDM: 2019.2

**Comment by uglide** [comment]
Hello. Sorry for inconvenience. I'm working on fix for this.

**Comment by uglide** [comment]
Finally fixed in 2019.2.140. Please download it from redisdesktop.com
