### ISSUE TITLE
Allow horizontal scrolling when viewing key values as JSON

### ISSUE THREAD

**Issue by dmjones** [redis/RedisDesktopManager#4654]
**Is your feature request related to a problem? Please describe.**

When I view values as JSON, I cannot scroll horizontally to view long lines of data. There is no horizontal scroll bar and if I move the cursor to the end of the line, it just disappears off the screen.

I'm using 2019.1-36b604s on Ubuntu 18.04.

**Describe the solution you'd like**

Horizontal scroll bars should appear when JSON data exceeds the visible width.

**Comment by yaoxiaohang** [comment]
ddd
