### ISSUE TITLE
Sign in???

### ISSUE THREAD

**Issue by roynasser** [redis/RedisDesktopManager#4665]
**Describe the bug**
On 2019.2 after runnin RDM on osx it asks me to login with a rdm account.... Why is this?? Further, if I logged in with a github account am I expected to log in how?

**To Reproduce**
Launch 2019.2 on a mac

**Expected behavior**
No obligratory sign in / telemetry should be kept to an absolute minimum and nothing should be going back and forth for a locally installed app...  I can see GDPR issues...

**Screenshots**
![image](https://user-images.githubusercontent.com/1218902/61901379-03c5e700-aef6-11e9-9b53-ae8225646a74.png)

**Environment (please complete the following information):**
- macOS 10.14.5

Reverting back to 2019.1 works normally + nothing about this extremely signifcant change on the changelog... :/

**Comment by uglide** [comment]
Hello

**Short Solution**: To sign in you should use your primary email from Github account and password which can be set here https://redisdesktop.com/set-password

**Long Story**
I'm sorry for this inconvenience. Any sign in/license dialogs are annoying and should be avoided. Unfortunately RedisDesktopManager builds are massively redistributed for free. Free - is good option when project is backed by huge/rich company and have funds for keeping up development process but RedisDesktopManager is not supported by any such company and needs some simple protection from unfair people.
RDM is fair/open project. All code is Open. Build instructions for enthusiasts and developers who willing to contribute are open. And this openness needs this (ugly) protection, which in fact doesn't violates GDPR - no telemetry data is collected, etc. Only plain/ugly in-app sign in.
