### ISSUE TITLE
RDM cannot running in Mac OS 10.15 version

### ISSUE THREAD

**Issue by AlexMasonQi** [redis/RedisDesktopManager#4669]
**Describe the bug**
On Mac OS 10.15, the RDM has crashed when I open it

**Screenshots**
![image](https://user-images.githubusercontent.com/15321930/62018973-7df4b500-b1ef-11e9-90d1-0f1c23127404.png)

**Environment (please complete the following information):**
 - OS & version: Mac OS 10.15
 - Redis-Server version: 2019.2.140

**Additional context**
No matter how many times I start it, it still crashes.Hope the developer can repair this issue later.

**Comment by uglide** [comment]
@Baymax6 Thanks for the bug report. Do you use `10.15 Developer Beta 4` ?

**Comment by AlexMasonQi** [comment]
> @Baymax6 Thanks for the bug report. Do you use `10.15 Developer Beta 4` ?

@uglide yes

**Comment by uglide** [comment]
Fixed in 2019.3 and tested on `10.15 Developer Beta 5 19A526h`
