### ISSUE TITLE
2019.3版本构建以后的一个问题

### ISSUE THREAD

**Issue by xiaomao361** [redis/RedisDesktopManager#4679]
我构建了2019.3版本的rdm，构建以后是可以使用的，但是打开的时候会有这样一个错误，提示
`cannot import module: formatters`
<img width="1204" alt="error" src="https://user-images.githubusercontent.com/10543570/62535485-1dfcaf00-b87e-11e9-9e87-12a180020bfe.png">

同时，在settings里面修改配置都是不生效的，不知道是不是跟这个错误有关系。

os：10.14.6 (18G87)
qt：5.13.0

**Comment by uglide** [comment]
You need to install python requirements as described in docs

**Comment by xiaomao361** [comment]
但是我运行这条命令了啊`pip3 install -r src/py/requirements.txt`
<img width="903" alt="pip" src="https://user-images.githubusercontent.com/10543570/62541955-6c657a00-b88d-11e9-9e19-219830242059.png">

**Comment by uglide** [comment]
Command is not correct actually, should be `pip3 install -t ../bin/osx/release -r py/requirements.txt`

**Comment by xiaomao361** [comment]
不知道是不是我这边什么诡异的问题导致的，我执行了这条命令，还是会报以前的错误。
我甚至把源码删除，重新clone代码，但是构建出来还是会报这个错误。
图是执行命令以后的release文件夹，感觉应该是对的啊
<img width="856" alt="pip" src="https://user-images.githubusercontent.com/10543570/62693375-f1bf6a80-ba04-11e9-8a0b-daebb0327ed5.png">

**Comment by xiaomao361** [comment]
啊 解决了，是我本地的一个python3路径的问题。多谢。

**Comment by JustinQiong** [comment]
> 啊 解决了，是我本地的一个python3路径的问题。多谢。

请问，最后这个问题是怎么解决的，我也遇到了

**Comment by xiaomao361** [comment]
> > 啊 解决了，是我本地的一个python3路径的问题。多谢。
> 
> 请问，最后这个问题是怎么解决的，我也遇到了

我在最后给.app文件添加依赖的时候，会报一个 找不到python3的路径错误。 可能是默认使用的是pip安装的python3，我本地是dmg包安装的python3， 所以我做了一个link链接到 需要的路径，然后 clone代码，重新编译以后，解决了这个问题。

**Comment by crackfan** [comment]
虚拟环境怎么编译 
python_wrap.h:5: error: C1083: 无法打开包括文件: “Python.h”: No such file or directory
