### ISSUE TITLE
Settings not saved after upgrade to 2019.3.150

### ISSUE THREAD

**Issue by gtoprover** [redis/RedisDesktopManager#4685]
Application run-time settings get lost between launches, including but not limited to:
- window size / position
- splitter positions
- View as dropdown

It used to work with the previous versions.

**Comment by uglide** [comment]
Hello
Sorry for the late reply.

- Window size is still remembered between launches on windows but position memorization was removed to prevent the annoying off-screen issue when RDM runs on laptops with frequently attached/re-attached screen(s).
- Splitter positions were never memorized in RDM but probably it should be.
- Selected formatter option should be memorized, but it's not and it's bug which I will address in the scope of this issue.
