### ISSUE TITLE
Network is not accessible (under proxy)

### ISSUE THREAD

**Issue by advapiIT** [redis/RedisDesktopManager#4691]
**Describe the bug**
After having updated to 2019.3 I got a popup asking me for credentials.
When I enter them I got the following message reported below

I'm under proxy so maybe it's due to that, but I don't know where to set it up.
Thanks

**To Reproduce**
Execute the application under proxy

**Expected behavior**
Should login and execute the app

**Screenshots**
![image](https://user-images.githubusercontent.com/4690086/63263994-4a56f900-c28a-11e9-9bf2-c3bc96398e65.png)

**Environment (please complete the following information):**
 - OS & version: Microsoft Windows [Version 10.0.15063]

**Comment by uglide** [comment]
Hello

Please use following **workaround:**
Open `regedit.exe` and go to
`Computer\HKEY_CURRENT_USER\Software\redisdesktop\RedisDesktopManager\app` (you can just copy this path and paste in regedit path input)
And set `useSystemProxy` to `true`

This setting will be added to sign in dialog in 2019.4

**Comment by advapiIT** [comment]
Thanks Igor,
This works, I report you BTW that for a short time the message is shown the
same (then it goes out)

Thanks again
Paolo

**Comment by advapiIT** [comment]
@uglide  has this been fixed? or just closed??

**Comment by uglide** [comment]
@advapiIT `useSystemProxy` was added to SignIn dialog in 2019.4
