### ISSUE TITLE
download link 404

### ISSUE THREAD

**Issue by jason-gao** [redis/RedisDesktopManager#4693]
https://apps.apple.com/us/app/redisdesktopmanager/id1475905948

**Comment by uglide** [comment]
@jason-gao Try this link https://apps.apple.com/cn/app/redisdesktopmanager/id1475905948

**Comment by jason-gao** [comment]
ok, thanks, if i want 0.8 version , i need to build it myself?

**Comment by uglide** [comment]
yes. Could you explain why do you need 0.8 version?

**Comment by jason-gao** [comment]
because some history reason, there is have redis server version is 2.4, new rdm version support 2.8+

**Comment by uglide** [comment]
I see. I recommend you to upgrade to more resent version because 2.4 is vulnerable. Also in most cases upgrade is super easy - just install new version, stop old version, and run new version.

**Comment by jason-gao** [comment]
yeah, thanks
