### ISSUE TITLE
Ubuntu 18.04 LTS  UI problem

### ISSUE THREAD

**Issue by Javsen** [redis/RedisDesktopManager#4694]
**Describe the bug**
UI is so big !

**To Reproduce**
my english is not well. sorry : (

i download redis-desktop-manager from snaped 

can need modify redisdesktop conf ?
i find gtk3.0 dir. how modify ?

**Environment (please complete the following information):**
Ubuntu 18.04
2019.03 version

**Comment by uglide** [comment]
Try to run RDM without Qt autoscaling http://docs.redisdesktop.com/en/latest/known-issues/
