### ISSUE TITLE
No module named 'bitstring'

### ISSUE THREAD

**Issue by samodovdi** [redis/RedisDesktopManager#4697]
**Describe the bug**
When run the program from Qt creator (or building .app file and run it) the formatters are not loaded due to this error

**To Reproduce**
1. Open rdm.pro in Qt creator
2. Run
3. See error

**Expected behavior**
No error appears and the formatters available

**Screenshots**
<img width="625" alt="image" src="https://user-images.githubusercontent.com/4929842/64054451-b9d4be80-cb8f-11e9-9c3b-5fbd4c5600ad.png">

**Environment (please complete the following information):**
 - OS & version: MacOS 10.14.4

**Comment by samodovdi** [comment]
i've installed pip dependencies as described in the manual but without -t key: pip3 install -t -r py/requirements.txt, the error is gone, but in the settings I don't see the formatters, however they are in the folder rdm.app/Contents/Resources/formatters:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/4929842/64060431-0abad600-cbd5-11e9-8e6d-3bc36994c504.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/4929842/64060437-2cb45880-cbd5-11e9-9db9-02dec5ce8f25.png">

**Comment by samodovdi** [comment]
The formatters are not listed in the settings, but they are in the "View as" dropdown list

**Comment by uglide** [comment]
Starting from 2019 RDM supports 2 formatter sources: embedded (python based) and external(custom).
On macOS custom formatters don't work from app bundle. That's why you don't see any loaded custom formatters in app settings.
