### ISSUE TITLE
Cant create kb

### ISSUE THREAD

**Issue by drskuce** [redis/RedisDesktopManager#470]
I am new to redis and your manager.  When it opens on my localhost service I see a number of dbs.  But I cannot see how to start creating content in a kb and there is no help.  Clicking on a kb does nothing. I would expect some obvious way of doing this which clearly others have discovered.  Rather than experiment I thought this should be made more clear.
Thanks
Doug

**Comment by uglide** [comment]
Hello.

I'm sorry, but what is "kb" ?

**Comment by drskuce** [comment]
knowledge base=database
I am an AI person so I use that word

I expected that I could start adding content to db0 say but I could not
discover how

**Comment by uglide** [comment]
Duplicate #29
