### ISSUE TITLE
Need to login on every start.

### ISSUE THREAD

**Issue by PeterOscarsson** [redis/RedisDesktopManager#4701]
**Describe the bug**
I need to login every time I start the application

**To Reproduce**
Start the application

**Expected behavior**
No login promt everytime

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS & version: Windows 10 1903
 - Redis-Server version: Mixed

**Additional context**
N/A

**Comment by uglide** [comment]
Hello @PeterOscarsson 

Thank you for the bug report.

Please ping me on email igor@redisdesktop.com 
I need your account email address to collect more details about the issue with login.

**Comment by uglide** [comment]
**2020 Update** 
Please use the Microsoft Store version instead https://www.microsoft.com/store/apps/9NDK76ZVZ3TM?cid=storebadge&ocid=badge

If you have purchased an annual subscription and want to switch to Microsoft Store build for free just reach me via email: igor@redisdesktop.com
