### ISSUE TITLE
Optimize large amounts of data in set

### ISSUE THREAD

**Issue by casen27** [redis/RedisDesktopManager#4704]
Using a set as the de-duplication pool,which set-key contains over 500k values,rdm crash.

It is hardly to refresh the set-key when over 1m values.

My suggestion:
Show the numbers of a set-key.Refresh the number when refresh all keys.
Only to get a tiny group of values as a sampling check.
Add a button,get all values only when needed.

Thanks.

用集合做去重池，数据量超过50w时，很容易闪崩。100w以上，刷新困难。

做去重主要两点需求：1、了解当前总数量；2、随机选一小部分检查一下是否合规。

点选键之后，当前的策略会加载该键的全部的值，100w的值大约消耗5+秒，cpu会满载，这个“获取全部值”的策略没有必要，还会影响到其他并发线程。

建议考虑优化集合在大量数据时的获取策略。

我的一种建议方案：
在集合的键GUI旁边增加数量标识，刷新键，同时刷新数量；
随机获取一页（一组/n个）即可，相当于抽样检查；
增加一个button，当用户主动需求加载全部值再获取。

谢谢。

**Comment by uglide** [comment]
@casen27 Please specify which version of RDM do you use.

**Comment by casen27** [comment]
How to get version tables?

Server:
MacOS 10.14
Redis 5.0.5
RDM 0.9.3.39

There're 10 active threads running on this mac.
And other 20 threads running on Win10x64 in LAN.
Development and testing,not for production environments.

For example:Chinese phone numbers.(3-4-4)
db0
[set]name:pool             -- 700k
[set]name:done_130    --  10k
.
.
.
[set]name:done_199    --  10k

Every time I click the name:pool,RDM crash.

**Comment by uglide** [comment]
You need to upgrade to 2019.X version, latest versions load values chunk by chunk on-demand.
