### ISSUE TITLE
RDM uses XX option of ZADD command which is incompatible with redis 2.8

### ISSUE THREAD

**Issue by HarveyJay** [redis/RedisDesktopManager#4705]
**Describe the bug**
when I open a zset key twice at the same time, it shows me two blank windows.
When I set a zset member's score, I usually got "syntax error"

**To Reproduce**
Try to change score of zset menber:
1. open a zset
2. select a member of zset
3. change score 
4. commit
5. got error

Try to open a zset twice at the same time:
1. open a zset
2. open it again
3. got two blank windows

**Screenshots**
Try to change score of zset menber:
![image](https://user-images.githubusercontent.com/26022767/65655818-18d30980-e050-11e9-8df3-b6c20dd6cf2b.png)
![image](https://user-images.githubusercontent.com/26022767/65656318-01951b80-e052-11e9-884d-96f9a589f7a0.png)

Try to open a zset twice at the same time:
![image](https://user-images.githubusercontent.com/26022767/65656351-25586180-e052-11e9-8dc9-28edc4341c8f.png)

**Environment (please complete the following information):**
 - OS : Ubuntu 18.04 
 - Redis-Server version [2.8.17]

**Additional context**

**Comment by uglide** [comment]
@Jay2Smile thanks for the bug report

**Comment by uglide** [comment]
@HarveyJay Could you please send me example of zset value which causes this issue to igor@redisdesktop.com

Thanks!

**Comment by uglide** [comment]
@HarveyJay RDM uses XX flag of ZADD command which is incompatible with your redis-server.

To resolve this issue quickly you can upgrade your redis-server to 5.0

**Comment by uglide** [comment]
The last fixes to 2.8 branch were released almost 5 years ago, so it's better to upgrade.
