### ISSUE TITLE
How to find data by a key exactly.

### ISSUE THREAD

**Issue by cupen** [redis/RedisDesktopManager#4708]
**Is your feature request related to a problem? Please describe.**
scan is slowly, it's horrible to execute `scan  MATCH` at a 16g+ RAM redis instance.

**Describe the solution you'd like**
I would like to find data by a key exactly (e.g: foo:bar).
we can reuse the `Key Filter`.
* `foo:bar:*`  scan and match
* `foo:bar:sub_name`  just get it exactly, no need to scan and match.

**Comment by uglide** [comment]
Makes sense for me. Will be implemented in 2019.5

**Comment by uglide** [comment]
Implemented. Will be released in 2019.5
