### ISSUE TITLE
Выделение, массовое удаление

### ISSUE THREAD

**Issue by slavserver** [redis/RedisDesktopManager#4709]
Здравствуйте, отличная програмка. 
Добавьте пожалуйста возможность выделения списка ключей ГАЛОЧКАМИ.... а то бывает так, что из списка тебе нужно массово удалить 75% ключей... но так как возможности отмечать галочками нет, порой приходится удалять каждый ключ вручную((
спасибо...

**Comment by uglide** [comment]
Hello,

For bulk keys removal RDM 2019.1+ offers following features:
- Delete Namespace - keys should be under one namespace (Namespace inline menu -> Delete Namespace)
- Bulk Delete by pattern (Database inline menu -> Bulk Operations -> Delete keys with filter)
