### ISSUE TITLE
How to set up the UI theme?

### ISSUE THREAD

**Issue by JayenLee** [redis/RedisDesktopManager#4726]
My source code compiled successfully opened the app into this way, may I ask where I need to configure to change this theme? The font color is white and the button is on the top

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/10287391/67000648-ce065800-f10a-11e9-93df-30550897cda0.png">

**Comment by uglide** [comment]
RDM itself doesn't support macOS dark theme yet but your build looks broken anyway. Try to use Qt 5.9.8

**Comment by BafS** [comment]
For info you can disable dark theme for this app only:
```sh
defaults write com.redisdesktop.rdm NSRequiresAquaSystemAppearance -bool yes
```

For more info: https://apple.stackexchange.com/questions/338044/can-i-turn-to-dark-mode-only-for-specific-apps-in-macos-mojave
