### ISSUE TITLE
 no ./configure under src directiory

### ISSUE THREAD

**Issue by moonwater** [redis/RedisDesktopManager#4733]
**Describe the bug**
clone source and follow the build instructions to build from source.
And there is no ./configure under src directiory

**To Reproduce**
1  git clone --recursive https://github.com/uglide/RedisDesktopManager.git
2  cd RedisDesktopManager
3  cd src
4  ./configure
zsh: no such file or directory: ./configure

**Expected behavior**
.expect ./configure available

**Environment (please complete the following information):**
 - OS & version:  linux ubuntu 18.04

**Additional context**
null

**Comment by uglide** [comment]
Building from source on linux is deprecated. Please install RDM from snapcraft https://snapcraft.io/redis-desktop-manager
