### ISSUE TITLE
Application crashed when trying to view value of key

### ISSUE THREAD

**Issue by LeiYangGH** [redis/RedisDesktopManager#4737]
**Describe the bug**
Crash when viewing the value.

**To Reproduce**
1. Install version 2019.4.175
2. Connect to my redis server without any credential and succeded. I can see the keys.
3. Then try to view the value of random key, and application exited without any hanging nor warning. 
4. Then go to windows event logs, saw crash log.

**Expected behavior**
Can view the data in string or bytes format, not crash.

**Screenshots**
If applicable, add screenshots to help explain your problem
![redisuibeforecrash](https://user-images.githubusercontent.com/5386998/67923116-c7d2aa00-fbe7-11e9-865b-08d12a49356e.JPG)
.
![rediscrashlog](https://user-images.githubusercontent.com/5386998/67923348-8a225100-fbe8-11e9-98fc-60c15ef3c78a.JPG)

**Environment (please complete the following information):**
 - OS & version: Microsoft Windows 10 Enterprise 10.0.17134  Build 17134
 - Redis-Server version 4.0.9

**Additional context**
I'm trial user.

**Comment by uglide** [comment]
Hello @LeiYangGH 
Please provide size of the values you are trying to view with `STRLEN %YOUR_KEY_HERE%` command in redis-cli or RDM terminal emulator

**Comment by LeiYangGH** [comment]
the size might be relatively large(~2mb audio). but thinking this repository has 14.2k stars, I cannot imagine it crash due to such large? size entries.
And searching other bugs i can see many similiar crashes, so now i'm not surprising.
Using python client I can get the value bytes with in 1 second, and nothing crashed.
For the gui, it might be difficult or slow to display, but at least i can first check the size and decide load all or only part or just display some message of 'cannot display', but it should never crash.
Can you explain why it crashes?

**Comment by uglide** [comment]
It's bug :) Fixed and will be released on next week as 2019.5 release (with other fixes)
