### ISSUE TITLE
Add Subscribe button near channel name in Pub/Sub Channels

### ISSUE THREAD

**Issue by mahmutbayri** [redis/RedisDesktopManager#4738]
Hi,
How can i see the data is passed by a channel, when we use pubsub? Only "channel name" is shown in "Pub/Sub Channel" tab.

Thanks.

**Comment by uglide** [comment]
Hello @mahmutbayri 

Currently you can open terminal emulator in RDM and type `subscribe %YOUR_CHANNEL_NAME%` to watch messages in channel.

I will add new button to simplify this task near to channel name in next versions of RDM.
