### ISSUE TITLE
Support CA certificates that are self signed.

### ISSUE THREAD

**Issue by cr22rc** [redis/RedisDesktopManager#4741]
I'm using the SSL option for the connection. I provided an Authority pem file. On test connection, the output is Connection error: The root certificate of the certificate chain is self-signed and, untrusted.

**Describe the solution you'd like**
A checkbox that would allow self signed certficates and connect to the server.

Redis Desktop Manager 2019.4-83abef8

**Comment by uglide** [comment]
For now you can upgrade to 2019.5-c57dd5f and use "Ignore all TLS errors" checkbox. I will add the separate checkbox for self-signed certs in 2020.0 release.

**Comment by uglide** [comment]
Merged with #4857
