### ISSUE TITLE
connection window can not be resize to click test connection  on my laptop

### ISSUE THREAD

**Issue by khanhasib** [redis/RedisDesktopManager#4742]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
Please provide more info and screenshots. Thanks.

**Comment by yoavsetoo** [comment]
I'm using ubuntu 18.
same problem.
installed application
clicked Connect to Redis server

the opened window is larger than the screen

**Comment by uglide** [comment]
@yoavsetoo please provide more details:
- screen resolution
- scaling factor
- screenshot of the problem

**Comment by yoavsetoo** [comment]
[image: image.png]




screen resolution: 1920*1080
scale factor: 100%

**Comment by uglide** [comment]
@yoavsetoo please attach screenshot via GitHub web page, otherwise it cannot be seen

**Comment by yoavsetoo** [comment]
![rdm](https://user-images.githubusercontent.com/43780771/69898030-66276c00-135c-11ea-8419-782ce0e4a6cb.png)

**Comment by yoavsetoo** [comment]
BTW version is: 2019.5-c57ddrf

**Comment by axeven** [comment]
i have the exact same problem as @yoavsetoo. ubuntu 18.04, screen resolution: 1920*1080, scale factor: 100%. the setting window is also larger than the screen.

**Comment by axeven** [comment]
![Screenshot from 2019-12-12 16-00-53](https://user-images.githubusercontent.com/6143508/70697809-c624f780-1cf8-11ea-9c62-52b416343520.png)
![Screenshot from 2019-12-12 16-00-59](https://user-images.githubusercontent.com/6143508/70697812-c6bd8e00-1cf8-11ea-86e0-7956ae6d5d9e.png)

**Comment by uglide** [comment]
@yoavsetoo  @axeven you faced with know issue - http://docs.redisdesktop.com/en/latest/known-issues/

Closing for now.
