### ISSUE TITLE
redis-desktop-manager cannot perform operatio Permission denied

### ISSUE THREAD

**Issue by smartliby** [redis/RedisDesktopManager#4743]
**Describe the bug**
➜  ~ redis-desktop-manager.rdm 
cannot perform operation: mount --rbind /mnt /tmp/snap.rootfs_VmkOqV//mnt: Permission denied

**To Reproduce**

**Expected behavior**

**Screenshots**
![选区_033](https://user-images.githubusercontent.com/16409957/68522902-651a9600-02ec-11ea-93d3-664184a18b14.png)

**Environment (please complete the following information):**
 - OS & version:ubuntu18.04

**Comment by uglide** [comment]
It looks like snapd bug https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1729576
Make sure you are on default kernel and reinstall snapd & RDM snap

**Comment by smartliby** [comment]
I had solved the problem，In my case I had a symlink for my mnt dir， remove the symlink,
rm /mnt,after that the snap applications will work.

**Comment by smartliby** [comment]
> It looks like snapd bug https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1729576
> Make sure you are on default kernel and reinstall snapd & RDM snap

I had solved the problem，In my case I had a symlink for my mnt dir， remove the symlink,
rm /mnt,after that the snap applications will work.
