### ISSUE TITLE
RDM SegFaults while trying to read an entry

### ISSUE THREAD

**Issue by petsoukos** [redis/RedisDesktopManager#4744]
**Describe the bug**
Trying to read a large cached entry (3141 Laravel* models) with RDM, but it SegFaults.
I'm caching a costly database query using Redis, and trying to view the entry within RDM. Unfortunately it crashes with SegFault(Core dumped) on the terminal.

_*Laravel is a PHP framework._

**To Reproduce**
I guess without my database entries, it is impossible to reproduce and due to sensitivity of the data stored, its not possible to share the models return by the query.

**Environment (please complete the following information):**
 - OS & version: Ubuntu 19.04
 - Redis-Server version: 5.0.3
 - RDM Version: 2019.4-83abef8

Let me know a way to help gather more info from the crash.

**Comment by petsoukos** [comment]
Crash when reading a redis entry #3704

**Comment by uglide** [comment]
@petsoukos Most likely you are experiencing #4737
Please update to 2019.5
