### ISSUE TITLE
Scroll bar is unusable

### ISSUE THREAD

**Issue by oneillci** [redis/RedisDesktopManager#4753]
**Describe the bug**
The scroll bar on list of keys in the left panel is unusable on a high DPI display (I have a high DPI display - not sure if this makes a difference as that is all I have access to).
The keys list also does not have any keyboard shortcuts (page up, down, ctrl + home etc), so navigating the list via mouse wheel is very tedious and impractical for large lists

**To Reproduce**
1. Open RDM
2. Expand a server that has > 100 keys
3. Try to use the scroll bar to scroll down - either via the down chevron or within the scroll bar itself to 'page' down
4. Observe that the scroll bar does not work and the mouse cursor changes to a column-resize cursor

**Expected behavior**
The cursor should stay as per normal when using the scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/641669/69845833-23b35000-12c6-11ea-8f2b-c10374e1d2a6.png)

**Environment (please complete the following information):**
 - Windows 10 1806
 - Redis-Server version 2019.5.176

**Additional context**

**Comment by uglide** [comment]
Hello @oneillci 
Could you please try 2020.0-beta1?
