### ISSUE TITLE
Redis tool crash while working with aws elasticache in cluster mode

### ISSUE THREAD

**Issue by KursLabIgor** [redis/RedisDesktopManager#4754]
**Describe the bug**
While set and read key form aws redis cluster tool crash. means just close.

**To Reproduce**
1. Create AWS Elasticache cluster with two shards (primary node)
2. Connect via ssh tunneling
3. Connect to Cluster
4. Try add and read key

**Expected behavior**
Tool works without crash

**Screenshots**
no

**Environment (please complete the following information):**
 - OS Ubuntu 18.04, tool version 2019.5
 - Redis-Server version 5.0.5 , 4.0.10

**Additional context**
logs

> Nov 29 12:04:40 redis-desktop-manager_rdm.desktop[444]: Event recieved: "add_key"
> Nov 29 12:04:43 redis-desktop-manager_rdm.desktop[444]: SSH keepalive. Next wake up in  5  seconds.
> Nov 29 12:04:44 redis-desktop-manager_rdm.desktop[444]: Cluster redirect
> Nov 29 12:04:46  kernel: [355469.234332] qredisclient::t[661]: segfault at 20 ip 00007f2454663db3 sp 00007f242a2cefa0 error 4 in libbotan-2.so.13.13.0[7f2453f3b000+9d6000]

**Comment by KursLabIgor** [comment]
probably crash due redirect action and ssh tunnel doesnt handle redirection and tool lost connection

**Comment by alemarcha** [comment]
I have the same problems. Did you solve this? @KursLabIgor

**Comment by KursLabIgor** [comment]
@alemarcha no. i think in scope of AWS Elasticsche this wont work since ssh tunelling doesnt handle redirects on network level. currently i'll provide access to bastion host and from bastion host use redis-cli. dont have other ideas.

**Comment by kaushall** [comment]
I'm also getting the same issue.

**Comment by uglide** [comment]
Sorry for late reply. This issue was finally fixed in 2020.0+36f6f5a0 (snapcraft)
Please update RDM
