### ISSUE TITLE
When set key ttl -1. Key got expired.

### ISSUE THREAD

**Issue by qrqhuang** [redis/RedisDesktopManager#4756]
**Describe the bug**

I need to persist key , use button `TTL` and set new TTL -1,  After then , key expired.

**To Reproduce**
Click `TTL`
Set New TTL :  -1

**Expected behavior**
Key should persist.

**Screenshots**

**Environment (please complete the following information):**
win10 1607
Desktop build :  2019.5.0

**Additional context**
I saw in log console , when set ttl to -1,  it's show with command `expire key -1`, Which right should be `persist key` .

**Comment by mia-at-speechmorphing** [comment]
I think this is how Redis operates.
if you do setex or pushex and give it expiration -1, it expires immediatelt.
if you want it not to expire, use plain set, push

**Comment by uglide** [comment]
TTL dialog is more user friendly now. If key doesn't have TTL field is empty and it's harder to remove key by mistake. Also "Persist key" button was added.
