### ISSUE TITLE
Does this work with RedisJson if so I will buy immediately. 

### ISSUE THREAD

**Issue by xtianus79** [redis/RedisDesktopManager#4760]
I am trying to use a gui that will work with REDISJSON but I can't find one. 

thanks,

**Comment by uglide** [comment]
Hello, yes it does. You can start a free 14 days trial on Windows or macOS to try RDM first before purchase.

**Comment by xtianus79** [comment]
@uglide I have always used your product and it is good.  Do you have documentation where it works with RedisJson?

**Comment by uglide** [comment]
It just works https://github.com/uglide/RedisDesktopManager/blob/2019/src/app/models/key-models/rejsonkey.cpp :)

**Comment by xtianus79** [comment]
@uglide thank you sir... I need to look no further.  redisinsights is so buggy I can't take it anymore.

**Comment by xtianus79** [comment]
@uglide you're product is so good. Man I should of asked for RedisJson a long time ago.  You should advertise that a little better.  Great product

**Comment by xtianus79** [comment]
@uglide one thing... can't make a key in RJ but that's ok

**Comment by uglide** [comment]
@xtianus79 thanks for the feedback. It will be improved in 2020.x releases
