### ISSUE TITLE
RDM constantly loses connection when working with Redis hosted on Scalegrid/Azure combo.

### ISSUE THREAD

**Issue by anagor** [redis/RedisDesktopManager#4761]
I have 2 practically similar servers I use, one is hosted directly by Azure, another is hosted on Azure but managed by ScaleGrid.
Those are standalone servers, not clusters.
Whenever I use RDM to view/edit data on Scale grid managed server, I almost every operation need to reconnect to the server because the RDM loses connection.

**Comment by uglide** [comment]
Hello, please provide more details

- OS & Version
- RDM version
- tunneling type of any (ssh/TLS)

**Comment by swordfish444** [comment]
@uglide @anagor 

We are experiencing the same issue on AWS Elasticache. Each command once connected, re-establishes SSH tunnel with our Bastion host. This is extremely problematic for us and we would greatly appreciate some attention on this ticket. 

![image](https://user-images.githubusercontent.com/3893966/74547849-9d3fff00-4f01-11ea-9abc-c3a0cab9b546.png)

* OS: OSX / Catalina / 10.15.3
* RDM version: 2019.5.70
* SSH tunneling w/ private key (TLS is **not** enabled)

**Comment by uglide** [comment]
Hello @swordfish444 
Thanks for the feedback. I'm currently working on optimizations related to proper connections re-use, instead of creating new connection each time from scratch.
Also I see from your log that RDM is doing unwanted SELECT's and it's bug.

All these problems will be addressed in the next release - 2020.0. ETA is March 16.

**Comment by uglide** [comment]
@swordfish444 @anagor 
Could you please test latest 2020.0 release and share your feedback?

**Comment by anagor** [comment]
Working with it for the past few days, so far haven't seen any disconnect
issues.

Thank you,
//Mark

**Comment by uglide** [comment]
Thank you for the feedback. I'm closing this issue then. Feel free to submit new issues if you experience this or any other problems.
