### ISSUE TITLE
Qt5.14  Not Compile

### ISSUE THREAD

**Issue by zhongguo1987** [redis/RedisDesktopManager#4762]
**Describe the bug**
windows,vs2019,QT5.14,not compile.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
VS2019 is not supported at the moment. Use VS2017 ass described in docs
