### ISSUE TITLE
page connect too large, over my screen

### ISSUE THREAD

**Issue by dangvanduc90** [redis/RedisDesktopManager#4763]
I want connect redis but ii can not click connect button, because that button is over flow my sceen
ubuntu 19.04
my screen has 1920x1080[
![Screenshot from 2020-01-20 23-05-09](https://user-images.githubusercontent.com/15909145/72740988-53e9e180-3bd9-11ea-922d-56fd6b61e6ed.png)

when i capture my screen
![Screenshot from 2020-01-20 23-06-29](https://user-images.githubusercontent.com/15909145/72742666-ca3c1300-3bdc-11ea-842d-5c9de7f2f53a.png)
so, it's ok but

actually 
![20200120_232534](https://user-images.githubusercontent.com/15909145/72742736-f0fa4980-3bdc-11ea-88cd-12f66c2d5374.jpg)
my screen can not contain all element of connect page
especially test connection button and ok - cancel button

**Comment by dangvanduc90** [comment]
please help me

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/known-issues/#application-looks-corrupted-on-my-1080p-screen-on-linux-too-small-font-andor-broken-dialogs

**Comment by dangvanduc90** [comment]
thank you, work like a charm
