### ISSUE TITLE
no-return-in-nonvoid-function

### ISSUE THREAD

**Issue by DeadMozay** [redis/RedisDesktopManager#4764]
**Describe the bug**
An error occurs during compilation
no-return-in-nonvoid-function src/app/models/key-models/rowcache.h:83

compilation was carried out for different systems, with new libraries, and older

**Environment (please complete the following information):**
 - OS & version: openSUSE Tumbleweed and openSUSE Leap 15.1
[buildlog.txt](https://github.com/uglide/RedisDesktopManager/files/4103510/buildlog.txt)

**Comment by uglide** [comment]
Fixed, thanks
