### ISSUE TITLE
RDM does not connect to the docker

### ISSUE THREAD

**Issue by eduardo-spagna** [redis/RedisDesktopManager#4765]
**Describe the bug**
I created a container with redis 5.0.7 and tried to connect using RDM and always crashes the application, forcing it to leave. I thought it would be in the docker settings or something, but in the terminal I can carry out the commands and the connection without problems

**To Reproduce**
I followed this video for installing redis with the only change being the version of redis for 5.0.7:

https://www.youtube.com/watch?v=l8-jWu61y90

**Expected behavior**
I expected to successfully connect using RDM

**Environment:**
 - OS & version: macOS Mojave version 10.14.16
 - Redis-Server version 5.0.7

**Comment by uglide** [comment]
@eduardo-spagna Which version of RDM do you use?

**Comment by uglide** [comment]
Feel free to re-open it if you still experience this issue on latest builds of RDM (2020.0+)
