### ISSUE TITLE
Cross-Compile RDM from linux to Windows

### ISSUE THREAD

**Issue by Sachin155** [redis/RedisDesktopManager#4766]
MAKEFILE GENERAL INFO.I'm using mxe lib for cross-compiling

# Makefile for building: rdm
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  rdm.pro
# Template: app
# Command: /home/ubuntu/playground/git_clone/rdm_src/src/qmake-qt5 -o Makefile rdm.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = x86_64-w64-mingw32.static-gcc

CXX           = x86_64-w64-mingw32.static-g++

DEFINES       = -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DRDM_VERSION=\"2019.0.0\" -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN

CFLAGS        = -pipe -fno-keep-inline-dllexport -O2 -g -Wall -Wextra -Wextra -ffunction-sections -fdata-sections $(DEFINES)

CXXFLAGS      = -pipe -fno-keep-inline-dllexport -g -O2 -std=gnu++11 -Wall -Wextra -Wextra -ffunction-sections -fdata-sections -fexceptions -mthreads $(DEFINES)

INCPATH       = -I. -I../3rdparty/qredisclient/src

-I../3rdparty/qredisclient/3rdparty 

-I../3rdparty/asyncfuture -I../3rdparty/gbreakpad/src

-I/home/ubuntu/playground/git_clone/rdm_src/3rdparty/gbreakpad/src/src

-I. -Imodules -I./../bin/windows/debug/ui/ 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQuickWidgets 
-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtCharts 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtWidgets 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQuick 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtGui 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQmlModels 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQml 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtNetwork 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtConcurrent 

-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtCore 

-I../bin/windows/debug/obj 
-I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/win32-g++

LINKER      =        x86_64-w64-mingw32.static-g++

LFLAGS        =        -Wl,--gc-sections -Wl,-subsystem,windows -mthreads

LIBS        =        /home/ubuntu/mxe/usr/x86_64-w64-
mingw32.static/qt5/plugins/styles/libqwindowsvistastyle.a 
-L/home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/lib /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platforms/libqwindows.a -lwinspool -lwtsapi32 /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5EventDispatcherSupport.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5FontDatabaseSupport.a -ldwrite -ld2d1 /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5ThemeSupport.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5AccessibilitySupport.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5WindowsUIAutomationSupport.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqgif.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqicns.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqico.a /home/ubuntu/mxe/usr/x86_64-w64-mingw32.static/qt5

#######################################################################
ERROR AT Compile Time 
#######################################################################

**x86_64-w64-mingw32.static-g++ -c -pipe -fno-keep-inline-dllexport -g -O2 -std=gnu++11 -Wall -Wextra -Wextra -ffunction-sections -fdata-sections -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DRDM_VERSION=\"2019.0.0\" -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -I../3rdparty/qredisclient/src -I../3rdparty/qredisclient/3rdparty -I../3rdparty/asyncfuture -I../3rdparty/gbreakpad/src -I/home/ubuntu/playground/git_clone/rdm_src/3rdparty/gbreakpad/src/src -I. -Imodules -I./../bin/windows/debug/ui/ -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQuickWidgets -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtCharts -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtWidgets -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQuick -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtGui -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQmlModels -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtQml -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtNetwork -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtConcurrent -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtCore -I../bin/windows/debug/obj -I../../../../mxe/usr/x86_64-w64-mingw32.static/qt5/mkspecs/win32-g++  -o ../bin/windows/debug/obj/autocompletemodel.o **

**modules/console/autocompletemodel.cpp

modules/console/autocompletemodel.cpp: In constructor 

'Console::AutocompleteModel::AutocompleteModel()':

modules/console/autocompletemodel.cpp:9:5: error: 'QFile' was not declared in this scope

     QFile commandsResource("://commands.json");
     ^

modules/console/autocompletemodel.cpp:10:10: error: 'commandsResource' was not declared in this scope
     if (!commandsResource.open(QIODevice::ReadOnly)) {
          ^

modules/console/autocompletemodel.cpp:15:34: error: 'commandsResource' was not declared in this scope
     QByteArray commandsJsonRaw = commandsResource.readAll();
                                  ^

modules/console/autocompletemodel.cpp: At global scope:

modules/console/autocompletemodel.cpp:50:61: warning: unused parameter 'parent' [-Wunused-parameter]

int Console::AutocompleteModel::rowCount(const QModelIndex &parent) const
                                                             ^
Makefile:9357: recipe for target '../bin/windows/debug/obj/autocompletemodel.o' failed

**make: *** [../bin/windows/debug/obj/autocompletemodel.o] Error 1**```

**Comment by uglide** [comment]
Cross-compilation is not supported. Build RDM on target device.
