### ISSUE TITLE
cannot support keydb yet?

### ISSUE THREAD

**Issue by yiliaofan** [redis/RedisDesktopManager#4767]
**Is your feature request related to a problem? Please describe.**

cannot support keydb yet?  This tool is very easy to use, thank you so much for your work. Thank you very much ~ 

KeyDB link:  https://keydb.dev/

KeyDB is fast... Really fast!
Quickly becoming known as the fastest NoSQL database in the world, KeyDB clocks in at 5X faster than Redis (node vs node). KeyDB is a popular drop in Redis alternative that people flock to because it enables you to consolidate a lot of the complexities associated with Redis. KeyDB is multithreaded with the ability to use several storage mediums natively and scale vertically. The superior architecture is enabling KeyDB to become the bridge between cache layer and traditional databases offering performance and durability.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/3670277/73726827-2f5e3f80-476b-11ea-93fd-30ee06263220.png)

thank you very much~！

**Comment by uglide** [comment]
You are running a very old version of RDM. RDM 2019.5 works with keydb just fine.
