### ISSUE TITLE
Unable to resize and not shown elements on window

### ISSUE THREAD

**Issue by mehmetcanhoroz** [redis/RedisDesktopManager#4768]
Hi,
I am using Ubuntu 18.04 Dell Vostro 5490. I can not use the application because the items, inputs etc are rendered too big and it exceeded the screen and not able to resize.

Application version is: version 2019.5

1. Open The Application
2. Then you can see the problem

![Screenshot from 2020-02-05 21-18-21](https://user-images.githubusercontent.com/16082678/73870638-7dec0680-485d-11ea-9b60-47b4d26bc621.png)
![Screenshot from 2020-02-05 21-18-26](https://user-images.githubusercontent.com/16082678/73870643-804e6080-485d-11ea-865a-75840ba0ede8.png)
![Screenshot from 2020-02-05 21-18-37](https://user-images.githubusercontent.com/16082678/73870651-82b0ba80-485d-11ea-8d0b-9fb6aff7d88a.png)
![Screenshot from 2020-02-05 21-19-04](https://user-images.githubusercontent.com/16082678/73870652-83e1e780-485d-11ea-92f9-fdba25463984.png)

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/known-issues/
