### ISSUE TITLE
Editing a JSON key removes spaces around curly braces (and some other braces)

### ISSUE THREAD

**Issue by Sorcy** [redis/RedisDesktopManager#4770]
**Describe the bug**
When saving a string key in JSON format and the view set to JSON the editor somehow removes spaces before and after curly braces. When setting the view to "Plain text" it works okay but is of course less convenient.

**To Reproduce**
1. Create a string key
2. Set the view to "JSON"
3. Insert some simple JSON with curly braces inside a string:
{"text": "My {{test}} string"}
4. Save the value
5. Reload the key
6. JSON is now { "text": "My{{test}}string" } (note missing spaces before and after curly braces)

Mostly same behavior if you use square brackets, but only removes the trailing space.

**Expected behavior**
JSON string should be saved correctly and should not remove spaces inside string values just because there are curly braces in the string.

**Environment (please complete the following information):**
 - OS & version: Windows 10 Pro
 - Redis-Server version 4.0.9

**Comment by uglide** [comment]
Thanks for the detailed bug report.
