### ISSUE TITLE
rdm\3rdparty\pyotherside\src\python_wrap.h(5): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory

### ISSUE THREAD

**Issue by Sachin155** [redis/RedisDesktopManager#4771]
hi I'm build RDM for windows 10 x86-64 
I have set the Environment as Mentioned in the Doc but I'm not able to build it for windows but I'm able to build it for linux 
Regrading Windows 10 System Environment variable info 

PATH = C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;
C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\HTML Help Workshop;
C:\Program Files (x86)\Windows Kits\10\bin\x86;
C:\Qt\Qt5.9.7\5.9.7\msvc2017_64\bin;
C:\Python37\include;
C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\;
C:\Program Files\Amazon\cfn-bootstrap\
;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64;
C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;
C:\ProgramFiles\Git\cmd;
C:\Python37\Scripts\;
C:\Python37\;
C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;

Build Gives the error at end 

c:\users\administrator\desktop\rdm\3rdparty\pyotherside\src\python_wrap.h(5): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
apputils.cpp
events.cpp
qmlutils.cpp
qcompress.cpp
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\nmake.exe"' : return code '0x2'
Stop.

________________________
And if i Search for Python.h 

C:\Users\Administrator\Desktop\rdm\src>where Python.h
C:\Python37\include\Python.h
it is able to find the hearder in the command line 
Any useful suggestion will Help a lot

**Comment by uglide** [comment]
Hello,

Issues are only for bugs and feature requests.

PS: You need  Python3-x64 to build RDM
