### ISSUE TITLE
Free text search in value

### ISSUE THREAD

**Issue by glassfox** [redis/RedisDesktopManager#4774]
Hi All,
In our case, values contains big json (view as: Json) with more than 100 lines each. To find something, we copy to clipboard value, paste it into external text editor and perform search.

It will be great to have an option to free text search insight value in "view as: Json" mode.

**Comment by uglide** [comment]
Thanks for the feedback. Will be implemented in 2020 branch

**Comment by stanaiq** [comment]
> Thanks for the feedback. Will be implemented in 2020 branch

Hi Igor. Could you please add a shortcut for the in-value search too? Ctrl+F would've been ideal. And I know that it's already used in a key search, but maybe this can be overcome.

**Comment by uglide** [comment]
Free text search was finally added to RDM and will be released as part of 2021.4 release
