### ISSUE TITLE
RDM built-in msgpack serializer failed to deserialize sometimes

### ISSUE THREAD

**Issue by iPilot** [redis/RedisDesktopManager#4781]
Some times when used MessagePack C# (https://github.com/neuecc/MessagePack-CSharp) serialized value do not shown at all. 
Serializer version 2.1.115.

Actual value (HEX): 
94 CE E9 FE E0 04 00 D7 FF 7B 81 81 40 5E 9F F0 19 C2

**To Reproduce**
Serialize value
Write to Redis
Read by RDM

**Expected behavior**
Deserialized value by RDM built-in MsgPack serializer

**Screenshots**
https://i.imgur.com/GXvhZ07.png

**Environment (please complete the following information):**
 - OS & version: Windows 10 1909
 - Redis-Server version: 5.0.0, docker, alpine

**Additional context**
Value below deserialized normally:
92 00 95 19 CF 08 D6 BE 10 A4 04 40 00 CF 08 D6 BE B3 77 8D CB 9C CB 40 4B 80 00 00 00 00 00 C0
https://i.imgur.com/AhjtT2d.png

**Comment by uglide** [comment]
Thanks for the detailed bug report.

**Comment by iPilot** [comment]
@uglide is it possible to add LZ4 decompression support for msgpack serialized values?

**Comment by uglide** [comment]
Yes, it's possible https://github.com/uglide/RedisDesktopManager/blob/2020/src/app/qcompress.cpp

**Comment by uglide** [comment]
@iPilot Please try 2020.1-beta1 builds from https://redisdesktop.com/subscriptions (Preview Builds Tab)

**Comment by iPilot** [comment]
@uglide all my cases are OK. Thx for fixing.

**Comment by uglide** [comment]
@uglide thanks for the feedback. LZ4 support will be added soon as well.

**Comment by iPilot** [comment]
@uglide Sorry, not all problems was fixed. Found one discovering another project cache, not in my cases.
https://i.imgur.com/xJrgm2P.png
Serialized Map<int, long> as one of object property throws this.
Value also now shown using view as msgpack for 2019.5 & 2020.0 versions.

**Comment by uglide** [comment]
@iPilot Please get hex string in the terminal inside RDM and post it here if possible.

**Comment by iPilot** [comment]
@uglide Sorry for not quick response.
example:
dc 00 1f cd 39 28 10 cf 08 d8 03 d5 72 0a 95 74 cd 01 ae ce 00 08 82 3a a4 37 36 32 36 cc cb 25 cf 48 d8 03 da 92 7f 05 1e cf 48 d8 03 d5 72 3a a2 e2 cc c1 c2 cd 08 69 ce 00 03 ed ea c2 c2 cc f4 cb 40 74 c9 90 de fd ef 3a 23 cb 40 48 00 00 00 00 00 00 af 32 38 20 d0 bd d0 be d1 8f d0 b1 d1 80 d1 8f a4 74 65 78 74 01 85 04 ce 00 07 9d b9 03 ce 00 03 9f 44 02 ce 00 03 78 af 01 ce 00 04 dd 38 00 ce 00 0e 00 86 cd 02 e7 c0 c0 c2 c0 92 03 91 cc 9a 00

**Comment by uglide** [comment]
@iPilot please try redis-desktop-manager-2020.1.201.exe build

**Comment by mrnom** [comment]
@iPilot I tried your example, no errors, formatting looks better now.
![#4781](https://user-images.githubusercontent.com/31620258/83278473-55a56080-a1dc-11ea-8363-793191e9c20d.png)

**Comment by iPilot** [comment]
Yeah, nice. Case works now.
