### ISSUE TITLE
Add a way to disable dark mode on MacOS

### ISSUE THREAD

**Issue by FlorinMotoc** [redis/RedisDesktopManager#4786]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I always use MacOS Dark Mode, but in some apps I prefer Light Mode.
- It would be nice to have an option inside Settings to select an Appearance between "Auto", "Light", "Dark".

**Comment by uglide** [comment]
This feature wont be implemented in RDM because you can easily disable dark mode via system settings https://apple.stackexchange.com/questions/338044/can-i-turn-to-dark-mode-only-for-specific-apps-in-macos-mojave
