### ISSUE TITLE
The font display in the Settings screen is garbled

### ISSUE THREAD

**Issue by youngyajun** [redis/RedisDesktopManager#4787]
**Environment (please complete the following information):**
 - OS & version: Win10 1909
 - Redis-Server version : 2020.0

![QQ截图20200430170058](https://user-images.githubusercontent.com/54418859/80692967-ecf79500-8b04-11ea-927c-226174c15fc0.png)

**Comment by uglide** [comment]
Thanks for the bug report. Will be fixed in 2020.1
