### ISSUE TITLE
Php serialized values not showing

### ISSUE THREAD

**Issue by PooH63** [redis/RedisDesktopManager#4789]
**Describe the bug**
Php serialized values not showing in version 2020
In version 0.8.8 displayed correctly

**To Reproduce**
1. Add value
2. Get value
3. Click view as PHP

0.8.8
![088](https://user-images.githubusercontent.com/576751/80729008-4dd89a80-8b10-11ea-8c97-c7d24588a017.jpg)

2020
![2020](https://user-images.githubusercontent.com/576751/80729038-5b8e2000-8b10-11ea-908f-8d0cdc9784ce.jpg)

Platform
windows 10

Redis server 3.2.10

**Comment by uglide** [comment]
@PooH63  Please try 2020.1-beta1 builds from https://redisdesktop.com/subscriptions (Preview Builds Tab)

**Comment by PooH63** [comment]
With arrays, json, scalar types works correctly, but with objects I get an error.
For example. simple object: 
`"O:8:\"stdClass\":2:{s:3:\"foo\";s:7:\"bar\";s:3:\"bar\";s:7:\"baz\";}"`

![object](https://user-images.githubusercontent.com/576751/83042772-b1d87b00-a04a-11ea-8fdd-7dc9428c218f.jpg)

**Comment by uglide** [comment]
@PooH63 thanks for the feedback. we will continue on fixing it :)
