### ISSUE TITLE
zset list scroll so slow 

### ISSUE THREAD

**Issue by gtsigner** [redis/RedisDesktopManager#4790]
**Describe the bug**
zset list scroll so slow , maybe the update UI problem

**Platform**
windows 10

**Comment by gtsigner** [comment]
if my list value is long string, it scrolling up very slow, maybe i think the old version zset or other list UI is good than this one

**Comment by uglide** [comment]
Fixed by https://github.com/uglide/RedisDesktopManager/commit/a977766f5c28ddc0a86acf8acf8782887119ee3a

**Comment by uglide** [comment]
@godtoy  Please try 2020.1-beta1 builds from https://redisdesktop.com/subscriptions (Preview Builds Tab)
