### ISSUE TITLE
Document update and some questions need help

### ISSUE THREAD

**Issue by WallanceLee** [redis/RedisDesktopManager#4791]
Hello, I have git clone rdm 2020 branch, but when I install and run according to the documents. I just cannot start my rdm application on my Mac OSX 10.14.6, it prompts I should download new version 2020. 
My two questions are below: 
1. Shall we determine the current version and get the remote latest version to give an update promotion? 
2. Should I update my Qt version to compile rdm from source?

**Comment by uglide** [comment]
Please see updated docs.
