### ISSUE TITLE
Errors building on Windows

### ISSUE THREAD

**Issue by yakatz** [redis/RedisDesktopManager#4792]
**Describe the bug**
Building on Windows seems to complete successfully, but the binary produced still won't run. First, the needed `dll`s are not included in the build directory (for example: `python37.dll`, `Qt5Core.dll`, `Qt5GUI.dll`, etc.), and after copying those in, the program still won't run. Opening it in the Qt Creator debugger gives the following error:

```
20:46:50: Starting C:\Users\User\source\RedisDesktopManager\bin\windows\release\rdm.exe ...
App font: "Open Sans" 11
("en-US")
Detected locale: "en_US"
QQmlApplicationEngine failed to load component
qrc:///app.qml:3 module "QtQuick.Controls" version 2.13 is not installed

Cannot update palette. Root object is not loaded.
Rendering backend: "software"
```

Are there just some steps missing in the instructions or is something else wrong?

**To Reproduce**
1. Follow the [Build from Source](http://docs.redisdesktop.com/en/latest/install/#build-from-source) instructions on Windows

**Expected behavior**
Program should run.

**Environment (please complete the following information):**
 - OS & version: Windows 10 1909
 - Redis-Server version: 5.0.9
- Qt Creator: 4.12.0
- Qt: 5.9

**Comment by andygikling** [comment]
Haha @uglide why did you close this?  No comment?  Your install instructions for Windows are just broken...  What are you too busy collecting money from Windows users for your "open source software" to deal with this?

**Comment by yakatz** [comment]
@andygikling The instructions have been updated and I am able to build successfully with the new instructions.

**Comment by uglide** [comment]
@andygikling Fix is better than any comments. GitHub automatically closes bug if fix was pushed to default branch in repo. 

PS: try to be more observant before blaming people.

**Comment by andygikling** [comment]
@uglide My sincerest apologies.
@yakatz Thank you.
