### ISSUE TITLE
Unable to get the connection window working on the Windows 10

### ISSUE THREAD

**Issue by phebbal** [redis/RedisDesktopManager#4793]
**Describe the bug**
Unable to get the connection window working on the Windows 10

**To Reproduce**
1. Go to 'Install the Redis Desktop Manager latest version and Launch' 
2. Click on 'Connect to Redis Server' and provide the redis server info
3. Scroll down to 'Test Connection', I can not see the Tes Connection. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2161385/81218065-365f4d00-8ffb-11ea-97e9-0469972daa5c.png)

**Environment (please complete the following information):**
 - OS & version: [ Windows 10 Pro]
 - Redis Desktop Manager Version : [redis-desktop-manager-2020.0.193]

**Additional context**

**Comment by uglide** [comment]
Hello,
please provide more details:
- Screen resolution
- Scaling factor in Windows settings
