### ISSUE TITLE
The latest version of the MAC doesn't have a full screen

### ISSUE THREAD

**Issue by zxuanhong** [redis/RedisDesktopManager#4799]
**Describe the bug**
The latest version of the MAC doesn't have a full screen。I downloaded it from the apple store

**Expected behavior**

**Screenshots**
* When you click full screen, it cannot be full screen. The previous version is ok.
![image](https://user-images.githubusercontent.com/62740686/81784228-2087e580-952f-11ea-9b6e-e4075d77ac47.png)

* Full-screen buttons are also programmed in the old-fashioned version style
![image](https://user-images.githubusercontent.com/62740686/81784777-f256d580-952f-11ea-80ba-1a749ee81dd8.png)
![image](https://user-images.githubusercontent.com/62740686/81784794-f71b8980-952f-11ea-95e5-4174e8dec0ab.png)

**Environment (please complete the following information):**
 - OS & version: mac  10.15.4
 - Redis-Server version :5.0.1 
 - app version: 2020.0.79

**Comment by uglide** [comment]
Thanks for the bug report. I will investigate the problem.
