### ISSUE TITLE
os x freeze (and eat 100% cpu)

### ISSUE THREAD

**Issue by batizhevsky** [redis/RedisDesktopManager#48]
Hello, Thank you for your program.

But after install I encountered a bug

I capture it in the video http://d.pr/v/fkoq

**Comment by batizhevsky** [comment]
llen posts:fresh:test:ids
(integer) 20
hlen posts:fresh:test:data
(integer) 20

 hash posts:fresh:test:data sotored json string

**Comment by uglide** [comment]
Hello,
Thanks for bug report.

What version of OS X do you use?

**Comment by batizhevsky** [comment]
10.9
