### ISSUE TITLE
GUI scaling on linux makes Redis Deskop Manager unusable on High-Resolution screens

### ISSUE THREAD

**Issue by linupi** [redis/RedisDesktopManager#4800]
**Describe the bug**
I am using the snap version of RedisDesktopManager on a linux (Ubuntu 18.04) laptop with high resolution screen (100 % scaling in Display Settings). All Dialogs in RedisDesktopManager span to a size much bigger that the display itself so the buttons a the bottom of the dialogs are unreachable.

**To Reproduce**
Click on 'Connect to Redis Server' button 

**Expected behavior**
Size of Dialog should not exceed size of screen. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3169764/81916900-c17cac00-95d4-11ea-9470-d13a088e6391.png)
as you can see the font size is much smaller than what is used by the system (see window title) and the dialog is way to big ... bigger than the screen.

**Environment (please complete the following information):**
 - OS & version: Linux Ubuntu 18.04
 - Redis-Server version 5.0.3
 - Source of Package:  Snap Store
 - Redis Desktop Manager Version: 2019.5-c57dd5f

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/known-issues/

btw, most likely was fixed by https://github.com/uglide/RedisDesktopManager/commit/5469fa3e47706490270946c7b6422f0ef46c7363
