### ISSUE TITLE
Window changes to transparent when moving window to other desktop on macOS

### ISSUE THREAD

**Issue by dreamerblue** [redis/RedisDesktopManager#4802]
**Describe the bug**
window changes to transparent when moving window to other desktop on macOS 10.15

**To Reproduce**
1. open rdm
2. drag window to other monitor's desktop space (for example, open rdm on internal screen, and then drag the window to my external monitor's desktop)
3. the window will be transparent! As desktop wallpaper shown.

**Expected behavior**
It works

**Screenshots**
<img width="1112" alt="rdm-2020080-mac-bug" src="https://user-images.githubusercontent.com/19774268/82107084-979fc280-9757-11ea-9799-c68dfd948116.png">

<img width="1080" alt="rdm-2020080-mac-bug2" src="https://user-images.githubusercontent.com/19774268/82107288-e568fa80-9758-11ea-8cf7-bf4b4ec1a0be.png">

**Environment (please complete the following information):**
 - OS & version: macOS 10.15.4
 - Redis-Server version 4.0.9

**Additional context**
redis desktop manager version: 2020.0.80

**Comment by uglide** [comment]
Fixed in 2020.1
