### ISSUE TITLE
Native formatters aren't available in macOS App Store version

### ISSUE THREAD

**Issue by naphta** [redis/RedisDesktopManager#4811]
**Describe the bug**
Native formatters aren't available in macOS App Store version

**To Reproduce**
1. Add formatters to `~Library/Containers/com.redisdesktop.rdm/Data/Library/Preferences/rdm`

**Expected behavior**
See formatter available in drop down, and a status panel available in settings menu

**Environment (please complete the following information):**
 - OS & version: macOS 10.15.4
 - 5.0.5

**Additional context**
Unable to check if subscription version has this problem as I purchased through app store.

**Comment by uglide** [comment]
Native formatters cannot be added to AppStore version due to sandboxing restrictions (running 3rdparty process is forbidden). If you lack some specific type of formatter, please provide more info and it may be added in the future releases.
