### ISSUE TITLE
не работает удаление ключей

### ISSUE THREAD

**Issue by slavserver** [redis/RedisDesktopManager#4813]
В последней версии не работает массовое удаление ключей.
Менеджер массовых операций запускается, все ок, просит потверждения на операцию, подтверждаем, но результата никакого. 
А порой  даже один ключ не получается удалить, работает через раз.
Пришлось откатиться на ноябрьскую версию((

**Comment by uglide** [comment]
Please provide more details: OS & version, redis cluster/standalone, tunneling type (TLS/SSH/TLS-over-SSH/None)

**Comment by uglide** [comment]
@slavserver Please try the latest 2020.1+9aace2ae build from snapcraft

**Comment by uglide** [comment]
Please re-open if you still experience this issue on the latest 2020.2  builds
