### ISSUE TITLE
Option missing in 2020.0.80: Allow to ignore all SSL/TLS errors

### ISSUE THREAD

**Issue by mbushman** [redis/RedisDesktopManager#4814]
**Option missing in 2020.0.80: Allow to ignore all SSL/TLS errors**
In version 2019.4.66 an option was given in the advanced settings of a connection to "Ignore all SSL/TLS errors".  This is missing in version 2020.0.80.

**Comment by uglide** [comment]
This option was renamed/inverted to **Enable Strict Mode** in TLS settings.
