### ISSUE TITLE
Failed to Delete Namespace

### ISSUE THREAD

**Issue by gorbatenkov** [redis/RedisDesktopManager#4816]
**Describe the bug**
Delete Namespace button does not delete affected keys

**To Reproduce**
1. Click on 'Delete Namespace'
2. Click on 'Delete keys'
3. Click on 'Yes'
4. Nothing happens / log is empty

**Expected behavior**
All affected keys deleted

**Screenshots**
- https://imgur.com/of84KUr

**Environment (please complete the following information):**
 - OS & version: Ubuntu 18.0.4
 - Redis-Server version 2020.0+36f6f5ao

**Additional context**
Stop working after latest update

**Comment by justoaguilar** [comment]
Same problem.
Delete keys with filter doesn't work too.

Deleting one key connected to Sentinel works.
Deleting one key connected to Master crashes.

Ubuntu: 20.04
RDM: 2020.0+36f6f5ao

**Comment by pierrelbz** [comment]
Same issue.

Ubuntu: 19.10
RDM: 2020.0+36f6f5ao

**Comment by uglide** [comment]
Fixed in 2020.0+2e72ed21. Please refresh snap

**Comment by pierrelbz** [comment]
Thanks @uglide
