### ISSUE TITLE
Popup window size not normal

### ISSUE THREAD

**Issue by vataraxia** [redis/RedisDesktopManager#4819]
**Describe the bug**
my rdm gui look bigger than usual, so that i cant find the button to proceed the delete action

**To Reproduce**
1. open rdm
2. delete some namespace
3. pop up window appear

**Expected behavior**
normal gui

**Screenshots**
![image](https://user-images.githubusercontent.com/4196934/83481509-36525000-a4c8-11ea-8d4c-74a2c027932d.png)

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - redis-cli 4.0.9

**Additional context**
I install the rdm from snap

**Comment by uglide** [comment]
http://docs.redisdesktop.com/en/latest/known-issues/
