### ISSUE TITLE
redisdestopmanager downloaded from the win10 store cannot resize and drag windows.

### ISSUE THREAD

**Issue by kvkboy** [redis/RedisDesktopManager#4823]
**Describe the bug**
The redis destop manager downloaded from the win10 store cannot resize and drag windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/30861318/84222836-2a3f4180-ab0b-11ea-9c57-112026c0d128.png)

**Environment (please complete the following information):**
 - Windows 10 Version 1903

**Comment by mrnom** [comment]
@kvkboy
What screen resolution and display scale factor are you using?

**Comment by kvkboy** [comment]
> @kvkboy
> What screen resolution and display scale factor are you using?

![image](https://user-images.githubusercontent.com/30861318/84474254-1f2c1300-acbd-11ea-86d1-3b1c87955f65.png)
