### ISSUE TITLE
RDM window size is too bigger .

### ISSUE THREAD

**Issue by jitenkumar91** [redis/RedisDesktopManager#4825]
Not able to connect to Redis server from Virtual machine because of window size.

Step To Reproduce 
1) Open RDM in VM
2) Click on connect to Redis server
3) Entered server details.
4) Observe window size is too big and due to that connect button in not visible.( Even tab is also not working)

**Comment by uglide** [comment]
@jitenkumar91 Please provide more details:
- Screen shot
- VM virtual screen resolution

**Comment by jitenkumar91** [comment]
Attaching the Screenshots.

<img width="380" alt="RDM" src="https://user-images.githubusercontent.com/66732342/84345573-5d490a00-abcb-11ea-9c74-82a916dad842.PNG">
<img width="327" alt="Resolution" src="https://user-images.githubusercontent.com/66732342/84345594-6508ae80-abcb-11ea-9732-5644aad76ecc.PNG">

**Comment by uglide** [comment]
You are using old version of RDM. Please upgrade to 2020.0

**Comment by jitenkumar91** [comment]
@uglide  thanks !
