### ISSUE TITLE
Ubuntu - Crash with fontconfig warning

### ISSUE THREAD

**Issue by bluemanos** [redis/RedisDesktopManager#4826]
**Describe the bug**
The Redis Desktop manager do not open at all.

**To Reproduce**
`$ redis-desktop-manager.rdm`

**Screenshots**
```shell
$ redis-desktop-manager.rdm 
Qt: Session management error: None of the authentication protocols specified are supported
Disable auto-scaling
Qt: Session management error: None of the authentication protocols specified are supported
App font: "Open Sans" 11
Could not create AF_NETLINK socket (Permission denied)
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.3333\" (uid=1000 pid=28285 comm=\"/snap/redis-desktop-manager/401/opt/redis-desktop-\" label=\"snap.redis-desktop-manager.rdm (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1132 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.3333\" (uid=1000 pid=28285 comm=\"/snap/redis-desktop-manager/401/opt/redis-desktop-\" label=\"snap.redis-desktop-manager.rdm (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1132 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
("en-US")
Detected locale: "en_US"
Fontconfig warning: FcPattern object weight does not accept value [50 200)
[1]    28285 segmentation fault (core dumped)  redis-desktop-manager.rdm
```
```shell
$ redis-desktop-manager.rdm -v    
Qt: Session management error: None of the authentication protocols specified are supported
Disable auto-scaling
Qt: Session management error: None of the authentication protocols specified are supported
RedisDesktopManager 2020.0+2e72ed21
```
**Environment (please complete the following information):**
 - OS & version: Ubuntu 18.04.4 LTS
 - Redis-Server version: 5.0.3

**Additional context**
I tried to reinstall the redis-desktop-manager package via snap, but nothing happened - still cant run it.

**Comment by raphaeljolivet** [comment]
Same here !

> Qt: Session management error: None of the authentication protocols specified are supported
> Disable auto-scaling
> Qt: Session management error: None of the authentication protocols specified are supported
> App font: "Open Sans" 11
> Could not create AF_NETLINK socket (Permission denied)
> propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.223\" (uid=1000 pid=11160 comm=\"/snap/redis-desktop-manager/401/opt/redis-desktop-\" label=\"snap.redis-desktop-manager.rdm (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1320 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
> nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.223\" (uid=1000 pid=11160 comm=\"/snap/redis-desktop-manager/401/opt/redis-desktop-\" label=\"snap.redis-desktop-manager.rdm (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1320 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
> "Object path cannot be empty"
> Could not create AF_NETLINK socket (Permission denied)
> Could not create AF_NETLINK socket (Permission denied)
> Could not create AF_NETLINK socket (Permission denied)
> Could not create AF_NETLINK socket (Permission denied)
> ("fr-FR")
> Detected locale: "fr_FR"
> Fontconfig warning: FcPattern object weight does not accept value [80 200)
> Erreur de segmentation (core dumped)

**Comment by wandyirawan** [comment]
same here at manjaro-i3:
```
~ redis-desktop-manager.rdm   
Disable auto-scaling
App font: "Open Sans" 11
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
("en-US")
Detected locale: "en_US"
Could not create AF_NETLINK socket (Permission denied)
Could not create AF_NETLINK socket (Permission denied)
Fontconfig warning: FcPattern object weight does not accept value [40 210)
[1]    117587 segmentation fault (core dumped)  redis-desktop-manager.rdm
```

**Comment by openhoat** [comment]
Same here with Fedora 32 :

```sh
$ redis-desktop-manager.rdm                                                                                                                                               Qt: Session management error: None of the authentication protocols specified are supported
Disable auto-scaling
Qt: Session management error: None of the authentication protocols specified are supported
App font: "Open Sans" 11
("fr-FR")
Detected locale: "fr_FR"
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    47707 segmentation fault (core dumped)  redis-desktop-manager.rdm

```

**Comment by cupen** [comment]
Same here with Archlinux, it's installed by `snapcraft install redis-desktop-manager`
```
$ snap --version
snap    2.37.4-1
snapd   2.37.4-1
series  16
arch    -
kernel  5.6.15-arch1-1

$ type redis-desktop-manager.rdm                      
redis-desktop-manager.rdm is /var/lib/snapd/snap/bin/redis-desktop-manager.rdm

$ redis-desktop-manager.rdm --version
Qt: Session management error: None of the authentication protocols specified are supported
Disable auto-scaling
Qt: Session management error: None of the authentication protocols specified are supported
RedisDesktopManager 2020.0+2e72ed21

$ redis-desktop-manager.rdm 
Qt: Session management error: None of the authentication protocols specified are supported
Disable auto-scaling
Qt: Session management error: None of the authentication protocols specified are supported
App font: "Open Sans" 11
("en-US")
Detected locale: "en_US"
Fontconfig warning: FcPattern object weight does not accept value [40 210)
[1]    210653 segmentation fault (core dumped)  redis-desktop-manager.rdm
```

**Comment by uglide** [comment]
Hell all,
It looks like some strange snap issue. Please try to clean up fontconfig cache:
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

More info here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/34

**Comment by bluemanos** [comment]
@uglide it works for me :clap: 

Admittedly in console I still have few repeating errors, but even that the app is running and working as a harm :)
```
qrc:/connections-tree/BetterTreeView.qml:78:17: QML Image: Cannot open: qrc:/images/.svg
Could not create AF_NETLINK socket (Permission denied)
```

**Comment by uglide** [comment]
@bluemanos 
Multiple errors like `Could not create AF_NETLINK socket (Permission denied)` is Qt magic blocked by sandboxed snap environment and can be safely ignored.

**Comment by bluemanos** [comment]
@uglide looks that every time I want to run RDM I have to clean up font config cache :/

**Comment by wandyirawan** [comment]
manjaro i3vm after clean upfont config, i can only run it via terminal, app is running and show but cant used..

**Comment by uglide** [comment]
@bluemanos Could you try the latest 2020.1+9aace2ae build from snapcraft?

**Comment by Kuangcp** [comment]
> Hell all,
> It looks like some strange snap issue. Please try to clean up fontconfig cache:
> 
> ```
> sudo rm /var/cache/fontconfig/*
> rm ~/.cache/fontconfig/*
> fc-cache -r
> ```
> 
> More info here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/34

1. `rm -rf ~/.cache/fontconfig`
1. `rm -rf ~/snap/redis-desktop-manager/common/.cache/fontconfig`

then fixed it. current version: "2020.4+c17a9e44"

**Comment by markoph** [comment]
Same issue. Removing `fontconfig` _(all mentioned in this thread)_ didn't help. Removing & installing rdm again helped in my case.

Version: 2020.5+65194ac4

_(Thank you for great app)_

**Comment by cukier** [comment]
> > Hell all,
> > It looks like some strange snap issue. Please try to clean up fontconfig cache:
> > ```
> > sudo rm /var/cache/fontconfig/*
> > rm ~/.cache/fontconfig/*
> > fc-cache -r
> > ```
> > 
> > 
> > More info here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/34
> 
>     1. `rm -rf ~/.cache/fontconfig`
> 
>     2. `rm -rf ~/snap/redis-desktop-manager/common/.cache/fontconfig`
> 
> 
> then fixed it. current version: "2020.4+c17a9e44"

tank you, it solved my issue with orange-app, manjaro linux...

**Comment by fsevenm** [comment]
Oh, snap is so

> > Hell all,
> > It looks like some strange snap issue. Please try to clean up fontconfig cache:
> > ```
> > sudo rm /var/cache/fontconfig/*
> > rm ~/.cache/fontconfig/*
> > fc-cache -r
> > ```
> > 
> > 
> > More info here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/34
> 
>     1. `rm -rf ~/.cache/fontconfig`
> 
>     2. `rm -rf ~/snap/redis-desktop-manager/common/.cache/fontconfig`
> 
> 
> then fixed it. current version: "2020.4+c17a9e44"

ohh, snap sometimes is really weird. Thanks, this fix the same issue in my Ubuntu 18.04.

**Comment by rabira-hierpa** [comment]
@uglide Thank you for the fix.
I had the same issue when I installed a new font and I couldn't start barrier( a snap app for KVM)
Your fix did the work for me

**Comment by srdgtr** [comment]
> > Hell all,
> > It looks like some strange snap issue. Please try to clean up fontconfig cache:
> > ```
> > sudo rm /var/cache/fontconfig/*
> > rm ~/.cache/fontconfig/*
> > fc-cache -r
> > ```
> > 
> > 
> > More info here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/34
> 
> 1. `rm -rf ~/.cache/fontconfig`
> 2. `rm -rf ~/snap/redis-desktop-manager/common/.cache/fontconfig`
> 
> then fixed it. current version: "2020.4+c17a9e44"

Thanks, that fixed it on fedora.

**Comment by uglide** [comment]
Looks like this issue was fixed in snap.
