### ISSUE TITLE
SHH TUNNEL error in Ubuntu 20.04

### ISSUE THREAD

**Issue by joaovillaoktagon** [redis/RedisDesktopManager#4838]
Hello, I think that after the last update the software stopped working with SSH TUNNEL

Ubuntu 20.04
using private key to connect to google cloud

**Comment by uglide** [comment]
@joaovillaoktagon Please test the latest 2020.1+9aace2ae build from snapcraft

**Comment by uglide** [comment]
Feel free to re-open this issue if you still can reproduce it on the latest 2020.2 build from snap
