### ISSUE TITLE
Results are white text on white background

### ISSUE THREAD

**Issue by damiensawyer** [redis/RedisDesktopManager#4842]
Version: 2020.1.209
Environment: Windows 10 version 2004
Redis Server Version: 6.0.5

Steps to reproduce:
1. Install on Windows
2. Loaded Redis via Docker with `docker run --name some-redis -p 6379:6379 -d redis`
3. Inserted some string data into redis (via cli)
4. Queried key

Expected result:
See the results in a format I could read.

Actual Result:
Resulting data was white text on a white background. Could copy and paste out, but not read.

**Comment by uglide** [comment]
@damiensawyer please provide sample of the data inserted to redis key. Do you also have any customization to windows appearance (dark/custom theme, etc) ?

**Comment by damiensawyer** [comment]
Hi. I have tried it with just basic 'set name john', and also with your demo scripts. 
```
eval "for index = 0,100000 do redis.call('SET', 'test_key' .. index, index) end" 0
eval "for index = 0,100000 do redis.call('SET', 'test_key:' .. math.random(1, 100) .. ':' .. math.random(1,100), index) end" 0
eval "for index = 0,100000 do redis.call('HSET', 'test_large_hash', index, index) end" 0
eval "for index = 0,100000 do redis.call('ZADD', 'test_large_zset', index, index) end" 0
eval "for index = 0,100000 do redis.call('SADD', 'test_large_set', index) end" 0
eval "for index = 0,100000 do redis.call('LPUSH', 'test_large_list', index) end" 0
```
I don't believe that I have any custom themes running. It's pretty much stock Windows.

**Comment by mrnom** [comment]
@damiensawyer 
Hi Damien, I was unable to reproduce this bug so far. Please try to switch to dark mode and back, let's see if it helps. Have you encountered this problem in other text inputs, for example in Add New Key dialog or maybe in other apps?

**Comment by damiensawyer** [comment]
Hi @mrnom  - thanks very much for looking. When you say dark mode, do you mean in RDM or in Windows? I couldn't see a setting in RDM. I was already using Dark Mode in Windows. I switched it to Light to no effect. I also removed Windows transparency mode to no effect. 

Never mind, feel free to close the issue. It might just be my machine. 

Thanks
