### ISSUE TITLE
Add show search count.

### ISSUE THREAD

**Issue by Rellopn** [redis/RedisDesktopManager#4843]
**Is your feature request related to a problem? Please describe.**
When there are too many matching results, the total number is not displayed.
**Describe the solution you'd like**
Have you considered a site to display the number of results like:
![image](https://user-images.githubusercontent.com/17350150/86896755-0a666200-c139-11ea-9528-3f0730a0d5b4.png)

**Comment by uglide** [comment]
Looks like not related to RDM.
