### ISSUE TITLE
Font color is white on white background

### ISSUE THREAD

**Issue by kboek** [redis/RedisDesktopManager#4846]
Updated from 2019.1 to 2020.1 and when I open a key, the value is printed in white on a white background

1. Open a DB
2. Click on a key
3. Read the key value
4. To see the value, copy all text with Ctrl+A and paste it in Notepad

 - Windows Server 2019 Datacenter
 - Redis-Server version 4.0.14 on Azure
 - Redis Desktop 2020.1.209

**Comment by uglide** [comment]
Hello,

Could you please provide screenshot?

**Comment by kboek** [comment]
<img width="926" alt="capture2" src="https://user-images.githubusercontent.com/743501/87190881-a5a33700-c2f3-11ea-85a5-9a4831bc6394.png">
<img width="1117" alt="capture1" src="https://user-images.githubusercontent.com/743501/87190883-a6d46400-c2f3-11ea-8da2-b945147a7bdb.png">

**Comment by mia-at-speechmorphing** [comment]
on Redis DesktopManager, 2020.1.15 (downloaded and installed ~2 days ago)

I see the same issue when I view data as plain text.
when I view data as JSON I can see the content, of course formatting is lost.

when I mark the text and copy it, paste yields correct format/structure for teh plain text, and a long endless line for JSON 

![rdm-asText](https://user-images.githubusercontent.com/17604334/87239759-a907f280-c3c7-11ea-9c88-0f08ed7a89e2.PNG)
![rdm-asJson](https://user-images.githubusercontent.com/17604334/87239760-ab6a4c80-c3c7-11ea-964d-2285e513dd11.PNG)

laptop, Microsoft Windows 10 Home
version 10.0.18362 Build 18362
screen resolution is (recommended) 3840x2160
display is landscape, scale factor is (recommended) 250%

**Comment by vsadams** [comment]
Same for me.

**Comment by uglide** [comment]
@kboek Could you please try 2020.2-beta1 (2020.2.221) ?

**Comment by kboek** [comment]
@uglide, problem is solved in 2020.2-beta1

**Comment by mia-at-speechmorphing** [comment]
I also see problem solved in the 2020.2.222 version.
thank you
