### ISSUE TITLE
rdm 2020.1 for mac(10.15.5) cant close the message popup "value was updated"

### ISSUE THREAD

**Issue by wxj-finbee** [redis/RedisDesktopManager#4847]
while using read-only account to update values in rdm, the popup cant be closed, and nothing can do except temernate rdm process.
redis-server is provided by aliyun cloud service with version 5.0

**Comment by uglide** [comment]
@wxj-finbee Please provide screenshot

**Comment by wxj-finbee** [comment]
![image](https://user-images.githubusercontent.com/44563554/87277638-43298100-c515-11ea-8c2a-c9217e9cb799.png)
