### ISSUE TITLE
2020.1 not publish to snapcraft.io

### ISSUE THREAD

**Issue by raphaelauv** [redis/RedisDesktopManager#4852]
Hello , I really enjoy your software , unfortunately the last stable release is not yet publish to snapcraft.io

Thank you

**Comment by uglide** [comment]
Sorry for the inconvenience.  Snapcraft build is currently broken and affected by bugs in snap system (https://github.com/uglide/RedisDesktopManager/issues/4826) but I plan to fix it on next week.

**Comment by uglide** [comment]
Build was fixed and 2020.1 is available on snapcraft
