### ISSUE TITLE
Can't launch on ubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#4853]
**Describe the bug**
Installed the application from snap. 
```
sudo snap install redis-desktop-manager
[sudo] password for mythio: 
snap "redis-desktop-manager" is already installed, see 'snap help refresh'
```

**To Reproduce**
There is .desktop file created, I don't know if this issue is from RDM or snap. So I tried to run it from `/snap/redis-desktop-manager/current/opt/redis-desktop-manager`
1. Launch terminal in the above directory
2. Run ./rdm
3. Error `"./rdm: error while loading shared libraries: libbotan-2.so.8: cannot open shared object file: No such file or directory
"`

**Expected behavior**
Expected RDM to launch but it doesn't

**Environment (please complete the following information):**
 - OS & version: Ubuntu 18.04
 - Redis-Server version: 
```
redis-server --version
Redis server v=6.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=f82f8c0da96442be
```

**Comment by uglide** [comment]
@mythio Please use stable branch in the snapcraft.

**Comment by ghost** [comment]
I am using stable branch from snapcraft

**Comment by uglide** [comment]
@mythio Please test the latest 2020.1+9aace2ae build from snapcraft

**Comment by ghost** [comment]
Yes it works! Closing this issue :)

**Comment by mazerun09** [comment]
seeing same issue with RDM version 2020.6+72258213. is there way to downgrade to 2020.1+9aace2ae using snap.
