### ISSUE TITLE
hope the appearance interface can be adapted to the origin MacOS theme.  Mac下面希望能把主题改成MacOS的模式，滚动条不用时可以自动隐藏

### ISSUE THREAD

**Issue by firstmetcs** [redis/RedisDesktopManager#4854]
I sincerely hope the appearance interface can be adapted to the origin MacOS theme，for example the scroll bar can be hidden when not using.

现在是这样的 What it looks like now
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/32634443/87621454-6e99af00-c753-11ea-9c18-d0fdfa69c862.png">

希望能改成这样的 Hope it can be like this
<img width="440" alt="image" src="https://user-images.githubusercontent.com/32634443/87621525-8cffaa80-c753-11ea-95cd-4d45de4dd6d8.png">

**Comment by uglide** [comment]
Thanks for the feedback. Fix for this issue will be released in 2020.2
