### ISSUE TITLE
Username support for Redis v6 (ACL)

### ISSUE THREAD

**Issue by MoienTajik** [redis/RedisDesktopManager#4856]
**Is your feature request related to a problem? Please describe.**
The [latest Redis version (6.0)](https://redislabs.com/blog/diving-into-redis-6/) came out with the ACL (access control list) feature. ACLs bring the concept of “users” to Redis. Each user can have a defined set of capabilities that dictate which commands they can run and on what keys.

Currently, there's no place to specify the username (or any other additional connection string parameters) in Redis Desktop Manager and so, we cannot connect to our Redis cluster with that.

**Describe the solution you'd like**
Adding username to the connection setting parameters and passing it to the Redis server.

**Comment by uglide** [comment]
Hello,
ACL support (user name field) will be released in 2020.2. ETA - end of July.
