### ISSUE TITLE
Connection failure to a redis server using a self-signed TLS setup on Mac OS

### ISSUE THREAD

**Issue by AlexisChevalier** [redis/RedisDesktopManager#4857]
**Describe the bug**
I have been using Redis Desktop Manager for a while now and we recently started using TLS on our redis configurations and I haven't been able to use the tool to connect to our redis-server setup (locally running) since. I have updated the configuration to use TLS, I use the same parameters than one of my colleagues running on linux which is able to connect to the server.

When I look at the logs in RDM, there is the following line: `SSLHandshake failed: -9824`, I googled a bit about this issue and it seems to be related to self-signed certificates on Mac OSx, but I haven't been able to find more data, it might be something else.

I have updated to the last version available (2020.1.89), and tried to disable the "strict mode" but I still can't connect.

Have I missed a configuration somewhere ? or is it an issue ?

Thanks!

**To Reproduce**
1. Configure a redis server using a self-signed certificate
2. Configure RDM to connect to this server
3. Test connection

**Expected behavior**
I am expecting to be able to connect to a redis server configured to use TLS running in docker even if the certificate is self signed

**Screenshots**
-

**Environment (please complete the following information):**
 - OS & version: Mac OS Catalina 10.15.5 (19F101)
 - Redis-Server version: 6.0.5

**Additional context**
-

**Comment by uglide** [comment]
@AlexisChevalier Could you please provide more details about cert/private key types?

RDM works just fine with self-signed TLS setup generated by `./utils/gen-test-certs.sh` script from redis repo (described in redis docs https://redis.io/topics/encryption)

**Comment by AlexisChevalier** [comment]
Sorry for the late reply, I was away for two weeks.

Thanks for your reply. I reproduced the issue using a clean environment, you can find it here: https://github.com/AlexisChevalier/redis-tls-test.

I also updated my RDM to version 2020.2.96 (through the app store).

I used the script from the redis repo to generate the setup (we're using the the same script in our env).

Here is my RDM configuration and the error message displayed when I click on "Test connection":
<img width="1303" alt="Screenshot 2020-08-24 at 12 39 18" src="https://user-images.githubusercontent.com/1269636/91036490-bab7f900-e607-11ea-850e-e1fcb9ad7b54.png">

This is the message logged in the RDM log:
`Connection: Disconnect on error: Connection error: SSLHandshake failed: -9824`

This is logged by the running redis container whenever I test the connection:
`redis_1  | 1:M 24 Aug 2020 10:46:16.818 # Error accepting a client connection: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate`

I'm new to redis so it might just be a configuration error on my end.

**Comment by AlexisChevalier** [comment]
I did some additional testing and noticed that disabling mutual TLS (`REDIS_TLS_AUTH_CLIENTS: "no"`) fixes the issue, but I'm not sure that's expected.
I don't think my colleague using Linux changed that, but I'll check with him.

EDIT: he confirmed he did not disabled mutual TLS, but he did not specified an authority in RDM, I tried that also but I end up with the same error.

**Comment by uglide** [comment]
Thanks for the detailed feedback. I'm investigating  the issue.

**Comment by uglide** [comment]
Fixed in 2020.2.235 (dmg) and 2020.2.99 (AppStore)
