### ISSUE TITLE
Formatters:Function not found

### ISSUE THREAD

**Issue by junjiangao** [redis/RedisDesktopManager#4865]
**Describe the bug**
我尝试在win10下按照文档编译RedisDesktopManager，编译成功后，运行基本功能正常。
但是启动时日志提示module 'formatters' has no attribute 'get_formatters_list‘，请问一下这个问题的原因（编译时，我修改了python的安装路径）

怀疑下面的步骤有问题
Install Python 3.7 amd64 to C:\Python37-x64.（修改了pyotherside.pri的python路径）
Install Python requirements pip3 install -r src/py/requirements.txt

**Screenshots**

![1](https://user-images.githubusercontent.com/7577432/89161441-32fd4280-d5a5-11ea-90dc-45ee50aa8a33.png)

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1909]
 - Redis-Server version [e.g. 5.0.9]

**Additional context**

**Comment by uglide** [comment]
Looks like some python dependencies are missing. You need to debug import of `formatters` module on your system.
