### ISSUE TITLE
Show warning on Windows when "localhost" is used as a host instead of 127.0.0.1

### ISSUE THREAD

**Issue by MartinKolarik** [redis/RedisDesktopManager#4867]
**Describe the bug**
When "localhost" is used as a host, creating a new connection, which seems to happen on every UI operation, is very slow (about 2 seconds). Not sure if it's specific to localhost or using a domain name in general instead of an IP address but after a bit of debugging I tried setting the host to 127.0.0.1 instead which resolved the issue.

**Expected behavior**
Should work the same way when a domain name is used.

**Environment (please complete the following information):**
 - OS & version: Windows 10 2004
 - Redis-Server version: tried 5 and 4 with the same result

**Additional context**
Using the 2020.1.15 version from windows store. Previously I was using the latest build that was available for free and that one didn't have this issue.

**Comment by uglide** [comment]
Unfortunately, this is side effect of Windows sand-boxing of Store apps. If it critical to you, you can refund your purchase on Windows Store and use subscription version instead.

**Comment by MartinKolarik** [comment]
Thanks for the quick response. I'm ok now with using the IP but it took a while to figure out so if it's can't be fixed, maybe it would be a good idea to show a warning within the UI.

**Comment by uglide** [comment]
@MartinKolarik good point
