### ISSUE TITLE
ssh tunnel: private key path

### ISSUE THREAD

**Issue by List412** [redis/RedisDesktopManager#4869]
app cant open file with ssh private key if path contains '.ssh' folder 

Version: 2020.0+2e72ed21
Environment: Ubuntu 20.04.1 LTS
Redis Server Version: 2.8.13

Steps to reproduce:

1. Create new connection using ssh tunnel
2. Paste path to my ssh key, (/home/<username>/.ssh/id_rsa')
3. Save
4. Connect

Expected result: Successful connection

Actual Result: cannot connect to server, check log for detail
log: unable to open private key file

works fine when i copy my key to home directory like '/home/<username>/id_rsa' 

![image](https://user-images.githubusercontent.com/18717159/89423676-3d0f7480-d750-11ea-98cd-a9fb1e22ee85.png)

**Comment by uglide** [comment]
@List412 please read the docs first :)
http://docs.redisdesktop.com/en/latest/install/#ubuntu-archlinux-debian-fedora-centos-opensuse-etc
