### ISSUE TITLE
rdm exit unexpected when click the tab close button 

### ISSUE THREAD

**Issue by popolw** [redis/RedisDesktopManager#4871]
rdm exit unexpected when click the tab close button 

**Screenshots**
![image](https://user-images.githubusercontent.com/3477336/89545878-7de1b900-d836-11ea-80a8-852d542c5507.png)

**Environment :**
 -device:surface pro4
 -rdm & version:2020.1.15(i got the app from msstore)
 - OS & version: [Windows 10 1909]
 - Redis-Server version [3.2.100]

**the debugview log message**
00000001	0.00000000	[820] file:///C:/Program Files/WindowsApps/35076IhorMalinovskyi.RedisDesktopManager_2020.1.15.0_x64__jrt9jtpcr47nt/QtQuick/Controls/Private/BasicTableView.qml:521:19: QML Component: Cannot create delegate	
00000002	0.00012870	[820] file:///C:/Program Files/WindowsApps/35076IhorMalinovskyi.RedisDesktopManager_2020.1.15.0_x64__jrt9jtpcr47nt/QtQuick/Controls/Private/BasicTableView.qml: Object or context destroyed during incubation

**Comment by uglide** [comment]
@popolw Could you please record screencast with steps to reproduce the crash?

**Comment by popolw** [comment]
@uglide 
1.add redis connection 
![image](https://user-images.githubusercontent.com/3477336/89554274-3b71a980-d841-11ea-9675-b1964e3d77c2.png)
2.click serverinfo icon or console icon
![image](https://user-images.githubusercontent.com/3477336/89554493-8095db80-d841-11ea-9424-7a24496affc0.png)
3.just click the tab close button and then do nothing 
![image](https://user-images.githubusercontent.com/3477336/89554781-e71af980-d841-11ea-821e-b2ac0d02074d.png)
3.wait amoment the rdm will exit with noting tips
i use DebugView tool got The log message written above
but when i use my desktop pc this problem didn't happen

**Comment by mrnom** [comment]
Under this scenario DebugView log has the same output on my PC, no crash happens though.

**Comment by popolw** [comment]
i used a huawei metabook to run rdm it also works fine。i will close the issue 

>
