### ISSUE TITLE
Incomplete display!!

### ISSUE THREAD

**Issue by KKKKKKKEM** [redis/RedisDesktopManager#4872]
When there are many values in SET (More than tens of millions), you can only see how many pages there are, and the number of elements in SET is not displayed completely

**Comment by uglide** [comment]
Hello, please provide screenshot of the issue

**Comment by KKKKKKKEM** [comment]
![image](https://user-images.githubusercontent.com/30348060/90081653-72aff100-dd40-11ea-847c-98fcf99bf93b.png)

**Comment by KKKKKKKEM** [comment]
> Hello, please provide screenshot of the issue

Can't see the complete number, and can't drag

**Comment by juliangut** [comment]
![image](https://user-images.githubusercontent.com/1104131/90142094-3dc18f80-dd7c-11ea-8739-d0ad878b78f9.png)

Navigation to a specific page or last page is hardly impossible, I can only use the arrow buttons page by page, but I cannot select a page number and go straight to it, as it was possible in previous versions

RDM version is 2020.2 (linux)

**Comment by uglide** [comment]
@juliangut RDM now loads values on demand using *SCAN commands. Please use "Search on page" text field and click "Full search" button

**Comment by juliangut** [comment]
Hi @uglide thanks for the quick answer

I need to know how to go to last page not knowing what is in that page or what to look for

My case: the key holds serializations of errors and I need to know which where the last ones. Is the re a way?

**Comment by uglide** [comment]
@juliangut you can leave field "search on page" empty and press button "Full search". RDM will load all values on one page

**Comment by juliangut** [comment]
Hi @uglide I wouldn't load 350K rows in a single page

Anyway I devised a background task, using SCAN, to keep the list clean over time so I can easily move to last page, it's currently around 10 pages long

**Comment by uglide** [comment]
@juliangut I plan to add option for LIST keys to choose loading order (first to last or last to first) in next releases.

**Comment by juliangut** [comment]
Great idea, that is a feature I'd use on a daily basis. I'll keep an eye on the releases

**Comment by uglide** [comment]
@juliangut this feature is already available in the edge channel on Snapcraft and will be soon available in the stable channel as part of 2020.7 release.
