### ISSUE TITLE
The Horizontal scrollbar doesn't appear！

### ISSUE THREAD

**Issue by firstmetcs** [redis/RedisDesktopManager#4876]
**Describe the bug**
Last time I reported an issue that let the scrollbar be hidden when not using, and got fixed. The Vertical scrollbar appears when using and seems to be right, but the Horizontal scrollbar doesn't appear when I scrolling and the width of the content wider than the window.

**Screenshots**
If applicable, add screenshots to help explain your problem
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/32634443/90353015-a314c980-e077-11ea-9223-1b6b086dd9ef.png">
.

**Environment (please complete the following information):**
 - OS & version: Mac OS 10.15.3
 - Redis-Server version 5.x

**Comment by uglide** [comment]
@firstmetcs you can simply resize treeview area when needed.
