### ISSUE TITLE
RDM 2020.2.225 does not launch on Windows Server 2019

### ISSUE THREAD

**Issue by nitmws** [redis/RedisDesktopManager#4878]
**Describe the bug**

RDM version 2020.2.225 for Windows downloaded and installed on Windows Server 2019. After launching it an error is shown: "Library VCRUNTIME140_1.dll cannot be found". After copying the vcruntime140.dll to vcruntime140_1.dll other library-internal errors are shown.

**To Reproduce**

Install 2020.2.225 on Windows Server 2019.

**Expected behavior**

Launching without an error.

**Screenshots**

None

**Environment (please complete the following information):**
 - OS & version: Windows Server 2019
 - Redis-Server version 4.x

**Additional context**

First I updated an RDM version 2020.1 - this error was shown. Then I uninstalled RDM via the Windows app setting. Then I installed version 2020.2.225 again - same error.

**Comment by uglide** [comment]
Hello,

please ensure that you have https://aka.ms/vs/16/release/vc_redist.x64.exe installed correctly on your server

**Comment by nitmws** [comment]
Ok, vc_redist.x64 installed and RDM 2020.2 launches.

I had a look at the [RDM Install page](http://docs.redisdesktop.com/en/latest/install/) but as version 2020.1 worked I didn't install the C++ 2017 distribution. Would be great to add a notice that 2020.2 may need an update of the C++ distribution to the Install page.

**Comment by uglide** [comment]
@nitmws Doc was updated. RDM installer tries to download vc_redist.x64 from the internet but sometimes it fails to do so.

**Comment by ZimGil** [comment]
@uglide This currently happens with Windows 10 when downloading via the Microsoft Store

**Comment by uglide** [comment]
@ZimGil fixed in 2020.2.28
