### ISSUE TITLE
When the stored content is too large, it will be seriously stuck

### ISSUE THREAD

**Issue by Jshf** [redis/RedisDesktopManager#4879]
![20200818170152](https://user-images.githubusercontent.com/10703553/90493960-8f4f8d00-e175-11ea-8f1d-96d782ad3215.png)
 When the stored content is too large, it will be seriously stuck, lose response, can not operate normally when viewing the content, eager to be optimized, thank you!

**Comment by justinseesdragons** [comment]
Part of the problem is a full key scan when opening the DB.  Two suggestions.
1.  With 50 million records, a full keyscan is just dumb.  Make a setting to disable this.
2.  Test with 50 million records.  Many of us use redis quite effectively for large amounts of records when a traditional database is just too slow.

**Comment by uglide** [comment]
@justinseesdragons 

Update: New page was added to docs http://docs.redisdesktop.com/en/latest/lg-keyspaces/

----

1. Use `SCAN` filter to reduce amount of loaded keys: 
1.1 right-click on databace and click on first icon
<img width="250" src="https://user-images.githubusercontent.com/1655867/91542521-aa18c300-e926-11ea-8f09-4a0322d0f9ee.png">
1.2 enter some specific `SCAN` filter to reduce amount of loaded keys
<img width="250" src="https://user-images.githubusercontent.com/1655867/91542549-b4d35800-e926-11ea-9920-ca0ad8701c56.png">
1.3 You can change default `SCAN` filter in connection settings:
<img width="250" src="https://user-images.githubusercontent.com/1655867/91543353-1eebfd00-e927-11ea-81ed-90bcc25c41f0.png">

2. It's important to use namespaced keys in such cases:
<img width="250" src="https://user-images.githubusercontent.com/1655867/91547979-5c538900-e92d-11ea-8afa-10cc1634343f.png">

50M keys, 5000 top level namespaces, 4Gb memory footprint (should be possible to load with 8Gb RAM on machine)

**Comment by Jshf** [comment]
I've split the too large key values and store them separately to improve the efficiency of reading and writing.
