### ISSUE TITLE
Where can I get newer, fixed, version as windows executable?

### ISSUE THREAD

**Issue by mia-at-speechmorphing** [redis/RedisDesktopManager#4880]
Hi
I bought RedisDesktopMnager on microsoft windows store, and there were 2 bugs which have been fixed - I tested with limited time version from redisdesktop.com but it is expired now.
I cannot build from code on my machine, unfortunately.

is there a chance to get a Windows 10 executable?
thanks
Mia

**Comment by uglide** [comment]
Hello
version 2020.2.20 is already available in Microsoft Store. Please update it.
