### ISSUE TITLE
Some nonsense output on the console and some commands can't execute

### ISSUE THREAD

**Issue by firstmetcs** [redis/RedisDesktopManager#4885]
**Describe the bug**
When I open the console and type some commands, it seems there are something wrong and nonsense output.
Besides, some commands can't get the results correctly.

**Screenshots**
<img width="430" alt="image" src="https://user-images.githubusercontent.com/32634443/91958540-12f2a780-ed3a-11ea-9680-580eba58ec13.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/32634443/91958837-7250b780-ed3a-11ea-8655-944535a7358f.png">

**Environment (please complete the following information):**
 - OS & version: MacOS 10.15.3
 - Redis-Server version 6.0.5

**Comment by hisabimbola** [comment]
Yes, I am having the same issue. I can't use the console anymore

**Comment by ranxiaoyu** [comment]
Yes, I have the same problem.

**Environment (please complete the following information):**

- OS & version: Windows10 18363.1016
- Redis-Server version 5.0.9

**Comment by hisabimbola** [comment]
Hello @uglide. I have paid version from app store

do you know when this changes will be in app store for me to update?

**Comment by uglide** [comment]
hello
@hisabimbola most likely tomorrow
