### ISSUE TITLE
The code execution cannot proceed because MSVCP140.dll was not found

### ISSUE THREAD

**Issue by jgwinner** [redis/RedisDesktopManager#4887]
**Describe the bug**
RDM loaded from the Microsoft store and installed will not run.

MSVCRT runtimes probably not installed via the installer. 

**To Reproduce**
1. Create a new Windows 10 Azure VM
2. Log in with the Azure credentials established in 1.
3. Load the Microsoft store. Log in with my Windows credentials that I purchased RDM with
4. Download and install RDM.
5. Run RDM. 

**Expected behavior**

I would expect the installer to load all prerequisits. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10425170/92127624-5be84180-edb6-11ea-81a4-407a4d9473b2.png)

**Environment (please complete the following information):**
 - OS & version: Microsoft Windows [Version 10.0.17763.1397]
 - Redis-Server version Don't know, but right from the Microsoft Store.

**Additional context**
I get that most systems end up with this installed, but it's frustrating to try to download that with a basic VM. If I was downloading and building source, I'd expect this error (and fix it), but people just loading up the Microsoft store wouldn't be that technical.

Notice I am a paying customer. Thank you for your excellent app! (and library)

**Comment by uglide** [comment]
Issue was fixed in 2020.2.28 and is published in Microsoft Store.

@jgwinner thanks for the bug report

**Comment by jgwinner** [comment]
@uglide Igor, I forgot to say something - thank you for the prompt fix! 

        == John ==
