### ISSUE TITLE
Json visualization not usable

### ISSUE THREAD

**Issue by arteny** [redis/RedisDesktopManager#4892]
**Describe the bug**
It is extremely slow performance when select view value as JSON. For instance value with more than 100 Kb, it takes several minutes to proceed, blocking all the application. My PC overall performance is good same time, so it is only a soft issue.

 - OS: Windows

**Comment by arteny** [comment]
After the last build released 2020.4.241 it became worst, several minutes of big JSON rendering, if to switch to small JSON (50 bytes), it is rendering infinitely. Applications become fully unusable.

**Comment by uglide** [comment]
@arteny Could you please provide some test JSON which causes lags on your PC?

**Comment by arteny** [comment]
> @arteny Could you please provide some test JSON which causes lags on your PC?

it is reproduced for any JSON (use any from 50 Kb size of text), it will be rendering several minutes, then if to switch to any other JSON key, even any smallest size, it is rendering infinitely :(

**Comment by Gjts** [comment]
qq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uglide/RedisDesktopManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 凌晨0:43
收件人:&nbsp;"uglide/RedisDesktopManager"<RedisDesktopManager@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [uglide/RedisDesktopManager] Json visualization not usable (#4892)





  
@arteny Could you please provide some test JSON which causes lags on your PC?
  
it is reproduced for any JSON (use any from 50 Kb size of text), it will be rendering several minutes, then if to switch to any other JSON key, even any smallest size, it is rendering infinitely :(

**Comment by uglide** [comment]
@arteny Could you try 2020.5.250 build?
