### ISSUE TITLE
cann't lanuch when I upgrade python to 3.8 on mac

### ISSUE THREAD

**Issue by kirachen1991** [redis/RedisDesktopManager#4893]
**Describe the bug**
load python absolute path？can only use python3.7？
Dyld Error Message:
  Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Applications/Redis Desktop Manager.app/Contents/MacOS/Redis Desktop Manager
  Reason: image not found

**Comment by uglide** [comment]
@kirachen1991 please specify RDM version and installation method (DMG, AppStore, build from source)

**Comment by kirachen1991** [comment]
build from source

**Comment by uglide** [comment]
just rebuild rdm with python 3.8
