### ISSUE TITLE
Version 2020.2.230 has no live update facility!

### ISSUE THREAD

**Issue by JL-Manning** [redis/RedisDesktopManager#4898]
I see in the online help, to click a button or use Ctrl-L to enable live updates. Nothing happens when I type Ctrl-L, and there is no button in the UI.

**Comment by uglide** [comment]
Live update is available currently only for key tree. Live/Auto-update for values will be added in next releases. You can track progress here https://github.com/uglide/RedisDesktopManager/issues/3733
