### ISSUE TITLE
Hope the icons can  be distinguished more clearly 

### ISSUE THREAD

**Issue by firstmetcs** [redis/RedisDesktopManager#4899]
**Is your feature request related to a problem? Please describe.**
When the connections be active, the icons still are gray, so it's hard to differentiate if the connections are active.
The icons of the group are so bright.

**Describe the solution you'd like**
Hope the icons of the connections and groups can be gray when connections are not active or connections in group are all not active; hope the icons of the connections and groups can be brighter when connections are active or there are some connections(not all) in group are active

<img width="422" alt="image" src="https://user-images.githubusercontent.com/32634443/92984485-04945080-f4dd-11ea-972e-03347997ca93.png">

**Comment by uglide** [comment]
@firstmetcs thanks for the all feedback. totally makes sense

**Comment by uglide** [comment]
Icons was harmonized a bit in late 2020 versions. Please let me know if you have any other feedback or suggestions. Thanks!
