### ISSUE TITLE
Localhost: (error: Unknown Error) on connect

### ISSUE THREAD

**Issue by mrThe** [redis/RedisDesktopManager#49]
Localhost: (error: Unknown Error) on connect.
But, if i trying to view server info or connect to console - everything works ok.

Version: 0.5.0
Ubuntu 12.04 x64 3.2.0-32-generic
Redis server version 2.2.12

**Comment by uglide** [comment]
Hello.

Thank you for your feedback. Redis Desktop Manager supports only 2.6 and 2.8 versions of Redis.
Support of older versions will be added soon. (More info in #47)

**Comment by mrThe** [comment]
Ok. Thanks for answer.
