### ISSUE TITLE
Support linux build from source

### ISSUE THREAD

**Issue by romanlex** [redis/RedisDesktopManager#4901]
I'm trying build RDM from source for linux in WSL2
WSL doesn't support snap packages :(
I cannot use RDM for windows for security reasons, there is no access to services inside Linux

How I can build rdm from source?

**Comment by uglide** [comment]
@romanlex WSL2 is not VM. It's all just plain Windows 10 with wrapping code. If your `redis-server` is running on `127.0.0.1:6379` in linux you should be able to connect to it from Windows as `127.0.0.1:6379`

In other words you can just use RDM for Windows.

**Comment by romanlex** [comment]
WSL2 is VM 
https://docs.microsoft.com/en-us/windows/wsl/compare-versions

**Comment by uglide** [comment]
@romanlex you are right about that but anyway even in WSL2 if `redis-server` is bind to `127.0.0.1:6379` you are able to access it as `127.0.0.1:6379` from Windows host.

**Comment by romanlex** [comment]
For security reason I disable this feature
From host I can connect only to :80 port

**Comment by uglide** [comment]
you can setup ssh server on Linux vm and connect to it through SSH tunnel if you need it.

WSL2 is designed more for running some server/console applications and RDM won't support WSL (unless snap support will be added eventually to WSL)
