### ISSUE TITLE
How to build from source in 2020

### ISSUE THREAD

**Issue by duyleomessi** [redis/RedisDesktopManager#4903]
I found some instructions on the internet, but for the older branch (branch was removed in 2020) and it does not work. How can I build this project from the source?

**Comment by mrnom** [comment]
@duyleomessi Please see the docs: https://docs.redisdesktop.com/en/latest/install/

**Comment by duyleomessi** [comment]
> @duyleomessi Please see the docs: https://docs.redisdesktop.com/en/latest/install/

Thank you, but I forgot to mention that I want to build it on Mx Linux. The docs only tell how to build on OS X vs Window. 

I don not want to install it using snap because Mx Linux disable  systemd by default, and Mx Linux team strongly urges users to remain with this configuration (Snap need systemd).

**Comment by uglide** [comment]
@duyleomessi We do not support officially building from source on Linux for 2 reasons:
1. Building from source on each Linux distro has different steps (installing deps, etc)
2. Linux users usually are more experienced in building software from source code.

Doc section https://docs.redisdesktop.com/en/latest/install/#build-on-os-x and https://github.com/RedisDesktop/redisdesktopmanager-snap/blob/master/snap/snapcraft.yaml provide enough information to understand what steps are required to build and install RDM from source code on particular distro.
