### ISSUE TITLE
Question: Once I build from community edition, do I need python installed on target machine?

### ISSUE THREAD

**Issue by marclallen** [redis/RedisDesktopManager#4904]
So, I was fooling around with getting these all compiled (and your compilation notes are a bit out of date, especially for Mac).  I got everything compiled and such.  But, I don't seem to be able to figure out how to run it on a machine without Python installed.  Is that just one of the requirements?  Or is there some sort of tool used to bake in a python runtime?

Thanks!

**Comment by uglide** [comment]
Hello, yes you need python3 on target machine. You can install python dependencies with pip as mentioned in step 5 in the docs  https://docs.redisdesktop.com/en/latest/install/#build-on-os-x

**Comment by marclallen** [comment]
So... your subscription-based Windows version installs python?  Or is there magic associated with that product not included in the community edition?

**Comment by uglide** [comment]
All code is open-sourced here (even Windows installer source code). Subscriptions and AppStore/Microsoft Store versions exist to support further development of this tool.

**Comment by marclallen** [comment]
I get that.  I'm just wondering if the subscription-based Windows install also deploys it's own Python installation or if it's including some sort of embedded Python library so that the user doesn't need to install Python to use your product.  I mean, installing python isn't a big deal, but I was just wondering.

**Comment by uglide** [comment]
RDM uses embedded python on all platforms

**Comment by marclallen** [comment]
I'm sorry.. I guess I'm not asking exactly the right question.  I would like to be able to put the community edition on a second Windows computer that does not have Python installed.  That doesn't seem possible.  Does the subscription-based Windows version need Python to be installed on the subscribed machine?

**Comment by uglide** [comment]
No, it doesn't require Python to be installed. Everything is pre-packaged in the installer.

**Comment by marclallen** [comment]
Thank you!
