### ISSUE TITLE
Redis cluster support - can't display values

### ISSUE THREAD

**Issue by pawel-b** [redis/RedisDesktopManager#4910]
When connecting to a Redis cluster at AWS ElastiCache I see the indication that this is a cluster, but only part of the keys are accessible, application displays:
"Loading key: X from db 0"
and nothing happens. Is it because the cluster support is not done yet?

It looks like the app displays the values only from one shard.

**Comment by uglide** [comment]
RDM fully supports cluster. Most likely you have connectivity issues. Could you please specify what kind of tunneling do you use to connect your AWS Elasticache?

**Comment by pawel-b** [comment]
OK, I figured out what was the issue. The package build script for Arch:
https://aur.archlinux.org/packages/redis-desktop-manager
fetches older version, 2020.0 which apparently had an issue with cluster. After manually updating the script to fetch 2020.3 rdm started working properly.

Thanks!
