### ISSUE TITLE
After upgrade to 2020.4 rdm.exe missing

### ISSUE THREAD

**Issue by arashberlin** [redis/RedisDesktopManager#4911]
**Describe the bug**
After upgrading from redis-desktop-manager-2020.3.231 to redis-desktop-manager-2020.4.237 the file rdm.exe is missing.

I needed to start the uninstall process separately to remove all files from the folder "C:\Program Files\RedisDesktopManager".

Then install the 2020.4 version.  Now all is file.

I think the uninstall process from the installation process is not removing all files.  This happens to me also in the previews upgrade  

**To Reproduce**
1. install 2020.3 
2. upgrade to 2020.4
3. try to start RDM
4. Rdm.exe missing in the install folder

**Expected behavior**
Uninstall of previews version should remove all files.  Upgrade should be a upgrade and not unusable to use RDM

**Environment :**
 - Windows 10 Pro, 1809 
 - Redis-Server Redis-x64 5.0.9

**Comment by uglide** [comment]
@arashberlin What kind of antivirus software do you have installed?  Most likely your antivirus removes rdm.exe file during install.

**Comment by arteny** [comment]
same for me. there were no antiviruses.
