### ISSUE TITLE
Redundant message: "Key was added. Do you want to reload keys in selected database?"

### ISSUE THREAD

**Issue by bean5** [redis/RedisDesktopManager#4913]
**Describe the bug**
When Live Update is enabled, upon adding a key, I get a redundant message: `Key was added. Do you want to reload keys in selected database?`

**To Reproduce**
1. Enable Live Update
2. Add a key via GUI
3. See error

**Expected behavior**
Key is added.

**Environment (please complete the following information):**
- redis latest/stable via snap (`6.0.8`)
- rdm latest/stable via snap (`2020.4+6a635b62`)
 - OS & version: Ubuntu 20

Great project by the way! Really decreases cost of entry!

**Comment by bean5** [comment]
Perhaps this is intended functionality because default live update (10s) isn't as fast as I expected. Feel free to close.

**Comment by uglide** [comment]
Hello,

Thanks for the feedback. It's intended behavior because on large key spaces scanning can take significant amount of time.
