### ISSUE TITLE
Can't save connection

### ISSUE THREAD

**Issue by EizFeren** [redis/RedisDesktopManager#4916]
Version: 2020.4+6a635b62
Environment: Linux Mint 20 Ulyana (Ubuntu 20.04) x64
Redis Server Version: 5.0.7

Steps to reproduce:
1. Click on "Connect to Redis Serv...".
2. Fill connection config.

Expected result: Can save new connection and use it.

Actual Result: There is no "OK" button (actually no buttons at all, see screenshot by link below)

Screenshot with issue - https://ibb.co/9YLBvJP

**Comment by EizFeren** [comment]
Maybe reason is in non-standart resolution (I'm using 1280x720 instead of recommended 1920x1080), but anyway I'm really need this resoultion, why connection window can't be usable on 1280x720?

**Comment by EizFeren** [comment]
It works fine on 1920x1080 resolution, but I can't use it now with this so small interface.

Screenshot - https://ibb.co/8BXpQxh

**Comment by uglide** [comment]
@EizFeren you overcome this issue with `QT_SCALE_FACTOR` env variable: `QT_SCALE_FACTOR=1.1 redis-desktop-manager.rdm`

Play with the value to find best scaling factor for your display configuration.
