### ISSUE TITLE
Configuration directory location doesn't follow XDG specs

### ISSUE THREAD

**Issue by pidario** [redis/RedisDesktopManager#4926]
Under linux (not snap) the configuration folder is ~/.rdm. This is in contradiction with freedesktop specifications, which state that configuration should be placed in ~/$XDG_CONFIG_HOME or, if the variable is not set, in ~/.config.
Besides, rdm already puts some config file in ~/. config/redisdesktop, so it shouldn't be too hard to accomplish, I believe. Maybe this relates to the other platforms (mac, windows, snap...) as well but I cannot confirm it.

**Comment by uglide** [comment]
This default behavior can be easily changed by passing `--settings-dir /foo/bar` command line option to RDM.
You can specify it in the rdm.desktop file to make it follow XDG specs or any custom configuration of your home folder.

**Comment by pidario** [comment]
It works, I can move my `connections.json` to `~/.config/.rdm` but for some reason, at each start the program recreates the directory `~/.rdm/formatters`.
I'm using version `2021.2`.
Thanks for the answer, I would have preferred an environment variable, or better a migration routine but that's ok.

**Comment by uglide** [comment]
You can pass `--formatters-dir` option to override default formatters dir as well.
