### ISSUE TITLE
build fails on mac with Python3.8 version

### ISSUE THREAD

**Issue by ZWLXX** [redis/RedisDesktopManager#4929]
Compile according to the instructions on the official website, but fails with Python3.8

**To Reproduce**
1.Install Xcode with Xcode build tools.
2.nstall Homebrew.
3.Copy cd ./src && cp ./resources/Info.plist.sample ./resources/Info.plist.
4.Building RDM dependencies require i.a. openssl, cmake and python3(python3.8). Install them: brew install openssl cmake python3
5.Install Python requirements pip3 install -t ../bin/osx/release -r py/requirements.txt
7.Install Qt 5.15. Add Qt Creator and under Qt 5.15.x add Qt Charts module.
8.Open ./src/rdm.pro in Qt Creator.
9.Run build.

**Expected behavior**
qpython_priv.o:-1: error: Undefined symbols for architecture x86_64:
  "_PyBool_FromLong", referenced from:
      PyObjectConverter::fromBoolean(bool) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      PyObjectConverter::fromBoolean(bool) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyBool_Type", referenced from:
      PyObjectConverter::type(_object* const&) in qpython.o
      PyObjectConverter::type(_object* const&) in qpython_priv.o
  "_PyByteArray_FromStringAndSize", referenced from:
      pyotherside_qrc_get_file_contents(_object*, _object*) in qpython_priv.o
  "_PyBytes_AsString", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::string(_object*&) in qpython.o
      PyObjectConverter::bytes(_object*&) in qpython.o
      qstring_from_pyobject_arg(_object*) in qpython_priv.o
      PyObjectConverter::string(_object*&) in qpython_priv.o
      PyObjectConverter::bytes(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
      ...
  "_PyBytes_FromStringAndSize", referenced from:
      PyObjectConverter::fromBytes(QByteArray const&) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      PyObjectConverter::fromBytes(QByteArray const&) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyBytes_Size", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::bytes(_object*&) in qpython.o
      PyObjectConverter::bytes(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
  "_PyCallable_Check", referenced from:
      QPythonPriv::call(_object*, QString, QVariant, QVariant*) in qpython_priv.o
  "_PyCapsule_Import", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      qstring_from_pyobject_arg(_object*) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
  "_PyDict_GetItemString", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyDict_New", referenced from:
      PyObjectConverter::newDict() in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      QPythonPriv::QPythonPriv() in qpython_priv.o
      PyObjectConverter::newDict() in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyDict_Next", referenced from:
      PyObjectDictIterator::next(_object**, _object**) in qpython.o
      PyObjectDictIterator::next(_object**, _object**) in qpython_priv.o
  "_PyDict_SetItem", referenced from:
      PyObjectDictBuilder::set(_object*, _object*) in qpython.o
      PyObjectDictBuilder::set(_object*, _object*) in qpython_priv.o
  "_PyDict_SetItemString", referenced from:
      QPython::importNames_sync(QString, QVariant) in qpython.o
      QPython::importModule_sync(QString) in qpython.o
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyErr_Clear", referenced from:
      QPythonPriv::importFromQRC(char const*, QString const&) in qpython_priv.o
  "_PyErr_Fetch", referenced from:
      QPythonPriv::formatExc() in qpython_priv.o
  "_PyErr_Format", referenced from:
      pyotherside_QObject_repr(_object*) in qpython_priv.o
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_setattro(_object*, _object*, _object*) in qpython_priv.o
      pyotherside_QObjectMethod_repr(_object*) in qpython_priv.o
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
  "_PyErr_NormalizeException", referenced from:
      QPythonPriv::formatExc() in qpython_priv.o
  "_PyErr_Occurred", referenced from:
      PyObjectListIterator::~PyObjectListIterator() in qpython.o
      PyObjectListIterator::~PyObjectListIterator() in qpython.o
      PyObjectListIterator::~PyObjectListIterator() in qpython_priv.o
      PyObjectListIterator::~PyObjectListIterator() in qpython_priv.o
  "_PyErr_Print", referenced from:
      QPythonPriv::formatExc() in qpython_priv.o
  "_PyErr_SetString", referenced from:
      qstring_from_pyobject_arg(_object*) in qpython_priv.o
      pyotherside_qrc_get_file_contents(_object*, _object*) in qpython_priv.o
      pyotherside_qrc_list_dir(_object*, _object*) in qpython_priv.o
  "_PyEval_GetBuiltins", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyEval_InitThreads", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyEval_RestoreThread", referenced from:
      QPythonPriv::~QPythonPriv() in qpython_priv.o
  "_PyEval_SaveThread", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyExc_AttributeError", referenced from:
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_setattro(_object*, _object*, _object*) in qpython_priv.o
  "_PyExc_ReferenceError", referenced from:
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_setattro(_object*, _object*, _object*) in qpython_priv.o
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
  "_PyExc_RuntimeError", referenced from:
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
  "_PyExc_TypeError", referenced from:
      pyotherside_QObject_repr(_object*) in qpython_priv.o
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_setattro(_object*, _object*, _object*) in qpython_priv.o
      pyotherside_QObjectMethod_repr(_object*) in qpython_priv.o
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
  "_PyExc_ValueError", referenced from:
      qstring_from_pyobject_arg(_object*) in qpython_priv.o
      pyotherside_qrc_get_file_contents(_object*, _object*) in qpython_priv.o
      pyotherside_qrc_list_dir(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_setattro(_object*, _object*, _object*) in qpython_priv.o
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
  "_PyFloat_AsDouble", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::floating(_object*&) in qpython.o
      PyObjectConverter::floating(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
  "_PyFloat_FromDouble", referenced from:
      PyObjectConverter::fromFloating(double) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      PyObjectConverter::fromFloating(double) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyFloat_Type", referenced from:
      PyObjectConverter::type(_object* const&) in qpython.o
      PyObjectConverter::type(_object* const&) in qpython_priv.o
  "_PyGILState_Ensure", referenced from:
      QPython::addImportPath(QString) in qpython.o
      QPython::importNames_sync(QString, QVariant) in qpython.o
      QPython::importModule_sync(QString) in qpython.o
      QPython::evaluate(QString) in qpython.o
      QPython::call_internal(QVariant, QVariant, bool) in qpython.o
      QPython::getattr(QVariant, QString) in qpython.o
      QPython::pythonVersion() in qpython.o
      ...
  "_PyGILState_Release", referenced from:
      QPython::addImportPath(QString) in qpython.o
      QPython::importNames_sync(QString, QVariant) in qpython.o
      QPython::importModule_sync(QString) in qpython.o
      QPython::evaluate(QString) in qpython.o
      QPython::call_internal(QVariant, QVariant, bool) in qpython.o
      QPython::getattr(QVariant, QString) in qpython.o
      QPython::pythonVersion() in qpython.o
      ...
  "_PyImport_AppendInittab", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyImport_ExecCodeModule", referenced from:
      QPythonPriv::importFromQRC(char const*, QString const&) in qpython_priv.o
  "_PyImport_ImportModule", referenced from:
      QPython::importNames_sync(QString, QVariant) in qpython.o
      QPython::importModule_sync(QString) in qpython.o
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyImport_ImportModuleLevel", referenced from:
      QPython::importModule_sync(QString) in qpython.o
  "_PyIter_Next", referenced from:
      PyObjectListIterator::next(_object**) in qpython.o
      PyObjectListIterator::next(_object**) in qpython_priv.o
  "_PyList_Append", referenced from:
      PyObjectListBuilder::append(_object*) in qpython.o
      PyObjectListBuilder::append(_object*) in qpython_priv.o
  "_PyList_AsTuple", referenced from:
      QPythonPriv::call(_object*, QString, QVariant, QVariant*) in qpython_priv.o
  "_PyList_Insert", referenced from:
      QPython::addImportPath(QString) in qpython.o
  "_PyList_New", referenced from:
      QPython::importModule_sync(QString) in qpython.o
      PyObjectConverter::newList() in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      PyObjectConverter::newList() in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyLong_AsLongLong", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::integer(_object*&) in qpython.o
      PyObjectConverter::integer(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
  "_PyLong_FromLong", referenced from:
      PyObjectConverter::fromInteger(long long) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      PyObjectConverter::fromInteger(long long) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyMapping_Check", referenced from:
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
      QPythonPriv::importFromQRC(char const*, QString const&) in qpython_priv.o
  "_PyMapping_GetItemString", referenced from:
      QPythonPriv::importFromQRC(char const*, QString const&) in qpython_priv.o
  "_PyMapping_Size", referenced from:
      pyotherside_QObjectMethod_call(_object*, _object*, _object*) in qpython_priv.o
  "_PyMem_RawFree", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyModule_AddIntConstant", referenced from:
      _PyOtherSide_init in qpython_priv.o
  "_PyModule_AddObject", referenced from:
      _PyOtherSide_init in qpython_priv.o
  "_PyModule_AddStringConstant", referenced from:
      _PyOtherSide_init in qpython_priv.o
  "_PyModule_Create2", referenced from:
      _PyOtherSide_init in qpython_priv.o
  "_PyObject_Call", referenced from:
      QPythonPriv::closing() in qpython_priv.o
      QPythonPriv::call(_object*, QString, QVariant, QVariant*) in qpython_priv.o
  "_PyObject_CallMethod", referenced from:
      QPythonPriv::formatExc() in qpython_priv.o
  "_PyObject_GetAttrString", referenced from:
      QPython::importNames_sync(QString, QVariant) in qpython.o
      QPython::getattr(QVariant, QString) in qpython.o
  "_PyObject_GetIter", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::list(_object*&) in qpython.o
      PyObjectConverter::list(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
  "_PyObject_Repr", referenced from:
      QPython::call_internal(QVariant, QVariant, bool) in qpython.o
  "_PyObject_Str", referenced from:
      QPythonPriv::formatExc() in qpython_priv.o
  "_PyRun_StringFlags", referenced from:
      QPythonPriv::eval(QString) in qpython_priv.o
  "_PySet_Type", referenced from:
      PyObjectConverter::type(_object* const&) in qpython.o
      PyObjectConverter::type(_object* const&) in qpython_priv.o
  "_PySys_GetObject", referenced from:
      QPython::addImportPath(QString) in qpython.o
      QPython::pythonVersion() in qpython.o
      QPythonPriv::importFromQRC(char const*, QString const&) in qpython_priv.o
  "_PySys_SetArgvEx", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_PyTuple_GetItem", referenced from:
      QPython::pythonVersion() in qpython.o
  "_PyTuple_New", referenced from:
      QPythonPriv::closing() in qpython_priv.o
  "_PyTuple_Size", referenced from:
      QPython::pythonVersion() in qpython.o
  "_PyType_GenericNew", referenced from:
      _PyOtherSide_init in qpython_priv.o
  "_PyType_IsSubtype", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::type(_object* const&) in qpython.o
      PyObjectConverter::qObject(_object*&) in qpython.o
      pyotherside_QObject_repr(_object*) in qpython_priv.o
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      pyotherside_QObject_setattro(_object*, _object*, _object*) in qpython_priv.o
      pyotherside_QObjectMethod_repr(_object*) in qpython_priv.o
      ...
  "_PyType_Ready", referenced from:
      _PyOtherSide_init in qpython_priv.o
  "_PyUnicode_AsUTF8String", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::string(_object*&) in qpython.o
      qstring_from_pyobject_arg(_object*) in qpython_priv.o
      PyObjectConverter::string(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o
  "_PyUnicode_FromFormat", referenced from:
      pyotherside_QObject_repr(_object*) in qpython_priv.o
      pyotherside_QObjectMethod_repr(_object*) in qpython_priv.o
  "_PyUnicode_FromString", referenced from:
      QPython::addImportPath(QString) in qpython.o
      PyObjectConverter::fromString(char const*) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      QPythonPriv::formatExc() in qpython_priv.o
      PyObjectConverter::fromString(char const*) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "_PyUnicode_Join", referenced from:
      QPythonPriv::formatExc() in qpython_priv.o
  "_Py_CompileStringExFlags", referenced from:
      QPythonPriv::importFromQRC(char const*, QString const&) in qpython_priv.o
  "_Py_DecodeLocale", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "_Py_Finalize", referenced from:
      QPythonPriv::~QPythonPriv() in qpython_priv.o
  "_Py_InitializeEx", referenced from:
      QPythonPriv::QPythonPriv() in qpython_priv.o
  "__PyObject_New", referenced from:
      PyObjectConverter::fromQObject(QObjectRef const&) in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      pyotherside_QObject_getattro(_object*, _object*) in qpython_priv.o
      PyObjectConverter::fromQObject(QObjectRef const&) in qpython_priv.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython_priv.o
  "__PyObject_NextNotImplemented", referenced from:
      PyObjectConverter::type(_object* const&) in qpython.o
      PyObjectConverter::type(_object* const&) in qpython_priv.o
  "__Py_Dealloc", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::string(_object*&) in qpython.o
      PyObjectConverter::~PyObjectConverter() in qpython.o
      PyObjectConverter::~PyObjectConverter() in qpython.o
      PyObjectListBuilder::append(_object*) in qpython.o
      PyObjectDictBuilder::set(_object*, _object*) in qpython.o
      PyObjectListIterator::~PyObjectListIterator() in qpython.o
      ...
  "__Py_FalseStruct", referenced from:
      pyotherside_qrc_is_file(_object*, _object*) in qpython_priv.o
      pyotherside_qrc_is_dir(_object*, _object*) in qpython_priv.o
  "__Py_NoneStruct", referenced from:
      PyObjectConverter::type(_object* const&) in qpython.o
      PyObjectConverter::fromTime(ConverterTime) in qpython.o
      PyObjectConverter::fromDateTime(ConverterDateTime) in qpython.o
      PyObjectConverter::none() in qpython.o
      _object* convert<QVariant, _object*, QVariantConverter, PyObjectConverter>(QVariant) in qpython.o
      pyotherside_send(_object*, _object*) in qpython_priv.o
      pyotherside_atexit(_object*, _object*) in qpython_priv.o
      ...
  "__Py_TrueStruct", referenced from:
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython.o
      PyObjectConverter::boolean(_object*&) in qpython.o
      pyotherside_qrc_is_file(_object*, _object*) in qpython_priv.o
      pyotherside_qrc_is_dir(_object*, _object*) in qpython_priv.o
      PyObjectConverter::boolean(_object*&) in qpython_priv.o
      QVariant convert<_object*, QVariant, PyObjectConverter, QVariantConverter>(_object*) in qpython_priv.o

**Screenshots**
![image](https://user-images.githubusercontent.com/6198390/96897548-4abbd700-14c1-11eb-9983-fdb98cf0274b.png)

**Environment (please complete the following information):**
 - OS & version:Mac 10.15.7

**Additional context**
some peopel use python3.7 compile success

**Comment by uglide** [comment]
RDM supports compilation with python3.8. Please ensure that you have the latest version of 2021 branch.
Let me know if you still experiencing this issue.
