### ISSUE TITLE
Latest commit does not copy liblz4.a to destination

### ISSUE THREAD

**Issue by WallanceLee** [redis/RedisDesktopManager#4934]
According to INSTALL instruments, I use Qt Creator included in Qt-5.15 suite to build Redis Desktop Manager. But I got an error which means libliz4.a hasn't in the directory of /path/to/rdm/3party/lz4/build/cmake directory. Thanks for solution of this problem.

**Comment by 3979275** [comment]
I also encountered this problem while building.

**Comment by tianjianchnbytedance** [comment]
I just got the same problem. By searching and going into lz4's build configuration, I found a way to generating the liblz4.a file
```bash
cd rdm/3party/lz4/build/cmake
cmake -DLZ4_BUNDLED_MODE=ON  .
make
```
Hopes that helps.

**Comment by tianjianchn** [comment]
I just got the same problem. By searching and going into lz4's build configuration, I found a way to generating the liblz4.a file
```bash
cd rdm/3party/lz4/build/cmake
cmake -DLZ4_BUNDLED_MODE=ON  .
make
```
Hopes that helps.

**Comment by uglide** [comment]
@tianjianchn please submit PR to the docs. thanks!

**Comment by wpblank** [comment]
> I just got the same problem. By searching and going into lz4's build configuration, I found a way to generating the liblz4.a file
> 
> ```shell
> cd rdm/3party/lz4/build/cmake
> cmake -DLZ4_BUNDLED_MODE=ON  .
> make
> ```
> 
> Hopes that helps.

thanks!

**Comment by uglide** [comment]
Docs was fixed
