### ISSUE TITLE
Support For macOS Big Sur 

### ISSUE THREAD

**Issue by kevin547** [redis/RedisDesktopManager#4936]
The newest version of RDM（2020.5）  crash on macOS11

**Comment by uglide** [comment]
@kevin547 thanks for the bug report. Which version do you use DMG or AppStore?

**Comment by uglide** [comment]
Both versions of RDM works fine on macOS Big Sur:
![VirtualBox_macOS_13_11_2020_15_58_21](https://user-images.githubusercontent.com/1655867/99079929-45860f80-25c9-11eb-9ff2-3f2645cd5437.png)

Please provide more details about the crash.

**Comment by kevin547** [comment]
error info:
Process:               RDM [963]
Path:                  /Volumes/*/RDM.app/Contents/MacOS/RDM
Identifier:            com.redisdesktop.rdm
Version:               0.0.0 (0.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RDM [963]
User ID:               501

Date/Time:             2020-11-17 09:23:30.745 +0800
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        4A3C2BA0-34A6-31D5-CFC0-18D2244E7DA4


Time Awake Since Boot: 480 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 9F6FFF1F-4096-355B-B037-8DCE73A7AA42
Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Volumes/*/RDM.app/Contents/MacOS/RDM
  Reason: image not found
Binary Images:
       0x108ebf000 -        0x1090e3fff +com.redisdesktop.rdm (0.0.0 - 0.0.0) <69591602-3EE4-3A64-86B8-C00D7838FCEC> /Volumes/*/RDM.app/Contents/MacOS/RDM
       0x109160000 -        0x10916cfff +org.qt-project.QtQuickWidgets (5.15 - 5.15.1) <E0A39EC4-8D01-3727-913F-78F48F0EBC27> /Volumes/*/RDM.app/Contents/Frameworks/QtQuickWidgets.framework/Versions/5/QtQuickWidgets
       0x109178000 -        0x109252fff +org.qt-project.QtCharts (5.15 - 5.15.1) <988FA227-CAAF-3E9F-8F9D-A764DA219297> /Volumes/*/RDM.app/Contents/Frameworks/QtCharts.framework/Versions/5/QtCharts
       0x1092fb000 -        0x10932ffff +org.qt-project.QtSvg (5.15 - 5.15.1) <27183220-BB79-3244-855D-DEB6E1ABBF11> /Volumes/*/RDM.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x10934d000 -        0x109793fff +org.qt-project.QtWidgets (5.15 - 5.15.1) <BB49658D-E6CB-3356-A50B-A457DA9A7E80> /Volumes/*/RDM.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x1098fa000 -        0x109c3efff +org.qt-project.QtQuick (5.15 - 5.15.1) <9D0FE8F2-BE17-3F6D-89AA-B8567B1A9F71> /Volumes/*/RDM.app/Contents/Frameworks/QtQuick.framework/Versions/5/QtQuick
       0x109d72000 -        0x10a25afff +org.qt-project.QtGui (5.15 - 5.15.1) <A3012528-1CA3-3322-838D-90DCA263BC1E> /Volumes/*/RDM.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10a373000 -        0x10a3cbfff +org.qt-project.QtQmlModels (5.15 - 5.15.1) <53C9D06C-CB52-35DB-88F1-06854E3E58AA> /Volumes/*/RDM.app/Contents/Frameworks/QtQmlModels.framework/Versions/5/QtQmlModels
       0x10a3eb000 -        0x10a744fff +org.qt-project.QtQml (5.15 - 5.15.1) <E17B4DE0-095F-31C9-A554-3C762813C49A> /Volumes/*/RDM.app/Contents/Frameworks/QtQml.framework/Versions/5/QtQml
       0x10a7ef000 -        0x10a8fffff +org.qt-project.QtNetwork (5.15 - 5.15.1) <F8625E5F-DEF7-31AC-A6D1-C01DE9573CFF> /Volumes/*/RDM.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10a94a000 -        0x10a94efff +org.qt-project.QtConcurrent (5.15 - 5.15.1) <4CFD588E-8514-39EE-9101-C70FBCA8AAFC> /Volumes/*/RDM.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x10a952000 -        0x10aec1fff +org.qt-project.QtCore (5.15 - 5.15.1) <A65B58AE-D97C-3E82-92E9-4036029FED48> /Volumes/*/RDM.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x114c2a000 -        0x114cc5fff  dyld (832.7.1) <2705F0D8-C104-3DE9-BEB5-B1EF6E28656D> /usr/lib/dyld
    0x7fff203ba000 -     0x7fff20855fff  com.apple.CoreFoundation (6.9 - 1770.106) <7EBD4941-5978-33EF-98FB-724BB81E92C8> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff22b0e000 -     0x7fff22bbbfff  com.apple.framework.IOKit (2.0.2 - 1845.50.1) <18A1F263-4AE2-3F9B-A38F-50BEB00B43D1> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22c14000 -     0x7fff23970fff  com.apple.AppKit (6.9 - 2022.10.104) <FA93F8CC-AB69-3E81-AC53-3FA08704738C> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff26510000 -     0x7fff26516fff  com.apple.DiskArbitration (2.7 - 2.7) <2E613BB2-B956-3668-9B33-1464DBC83611> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff282ea000 -     0x7fff2840ffff  com.apple.Metal (244.32.6 - 244.32.6) <6BB79960-68EA-3CB9-89D9-E8A11B8C9491> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff2a45d000 -     0x7fff2a46ffff  libz.1.dylib (76) <0AF4F195-1F20-3F59-B09F-31E7249890D5> /usr/lib/libz.1.dylib
    0x7fff2fef0000 -     0x7fff2fef0fff  com.apple.CoreServices (1122.5.1 - 1122.5.1) <070D2800-D014-34E3-AAA9-CB7199EFC728> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff6b3d8000 -     0x7fff6b3e7fff  com.apple.opengl (18.0.50 - 18.0.50) <245D7013-B161-397D-9989-500B639ECDF3> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6dd13000 -     0x7fff6dd1afff  com.apple.agl (3.3.4 - AGL-3.3.3) <9A62C140-2B9B-341C-A4F2-B90BB88DE758> /System/Library/Frameworks/AGL.framework/Versions/A/AGL

Model: MacBookPro14,1, BootROM 429.50.1.0.0, 2 processors, Dual-Core Intel Core i5, 2.3 GHz, 8 GB, SMC 2.43f10
Graphics: kHW_IntelIrisGraphics640Item, Intel Iris Plus Graphics 640, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1669)
Bluetooth: Version 8.0.1f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en5
Network Service: Wi-Fi, AirPort, en0
Network Service: Thunderbolt Bridge, Ethernet, bridge0
USB Device: USB 3.0 Bus
USB Device: USB 2.0 BILLBOARD
USB Device: USB2.0 Hub
USB Device: 4-Port USB 2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB 10/100 LAN
USB Device: USB Billboard Device
USB Device: USB3.0 Hub
USB Device: 4-Port USB 3.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4

**Comment by kevin547** [comment]
intall python3.7
