### ISSUE TITLE
./rdm error while loading shared libraries

### ISSUE THREAD

**Issue by a-ahmed** [redis/RedisDesktopManager#4937]
**Describe the bug**
after install rdm via snap when i go to this path in terminal "/snap/redis-desktop-manager/current/opt/redis-desktop-manager" and execute "./rdm"
i got the following error
"./rdm: error while loading shared libraries: libbotan-2.so.15: cannot open shared object file: No such file or directory"
I installed libbotan-2 libbotan-2-dev but it doesn't work

ubuntu version 18.04
rdm version: 2020.5+65194ac4

**Comment by uglide** [comment]
Run RDM as `redis-desktop-manager.rdm`

**Comment by a-ahmed** [comment]
command not found 
[https://imgur.com/xJmp3Nm](url)

**Comment by uglide** [comment]
@a-ahmed you mistyped command, there are no spaces
