### ISSUE TITLE
Dark Mode on windows

### ISSUE THREAD

**Issue by ToxicMushroom** [redis/RedisDesktopManager#4939]
**Describe the bug**
There is no switch, config or automatic detection for dark mode on windows

**To Reproduce**
1. Go to windows settings
2. Click on Personal Settings
3. Click on Colors
4. Select Dark as your color

**Expected behavior**
When you relaunch the app it should detect the windows setting and change the appearance like shown on the homepage https://rdm.dev/ in the about section

**Environment (please complete the following information):**
 - OS & version: Windows 20H2
 - Redis-Server version: (not related)
 - RDM: 2020.5.41 (windows store)

**Comment by uglide** [comment]
RDM currently supports dark theme only on macOS. Support on Windows is not implemented yet in Qt https://bugreports.qt.io/browse/QTBUG-72028

I will post updates in this issue.

**Comment by uglide** [comment]
Initial dark mode support for Windows 10 was added in 2020.7 and will be released in Microsoft Store soon.
