### ISSUE TITLE
Cant't connect to server via ssh tunnel with private key

### ISSUE THREAD

**Issue by anton-reviakin** [redis/RedisDesktopManager#4940]
**Describe the bug**
Can't connect via ssh tunnel with private key. Can't select the key...
Also try copy from Log (click right mouse button - select Copy item) - not copy

**To Reproduce**
1. Create or edit connection
2. Click on radiobutton SSH Tunnel
3. Select file: click on "/mnt" - empty, go to /mnt/storage - empty, go to /mnt/storage/DATA - empty
4. Put direct path to key file - Can't connect to server (unable to extract public key from private key)

**Screenshots**
![2020-11-22_16-33](https://user-images.githubusercontent.com/11661817/99906571-8fb17400-2ce0-11eb-886f-c25c13ad20a8.png)

**Environment (please complete the following information):**
 - OS & version: Ubuntu 20.04
 - Redis-Server version Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923

**Comment by uglide** [comment]
It's not bug in RDM, snap is sandboxed environment with limited permissions to your filesystem. https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352/3
