### ISSUE TITLE
Could not load the QT  platform plugin "xcb"

### ISSUE THREAD

**Issue by a-ahmed** [redis/RedisDesktopManager#4941]
when i execute the command : redis-desktop-manager.rdm 
I got the following error 
"Could not load the QT  platform plugin "xcb"" 

kindly check the following screenshot

screenshot:
https://imgur.com/YZMKF38

ubuntu version 18.04
rdm version: 2020.5+65194ac4

**Comment by uglide** [comment]
Please check you Xserver configuration and make sure that you have latest version of `snapd` installed.
Mot likely you faced this `snapd` bug https://bugs.launchpad.net/snapd/+bug/1819318
