### ISSUE TITLE
Formatter for PHP serialized values

### ISSUE THREAD

**Issue by ronzyfonzy** [redis/RedisDesktopManager#4942]
**Problem:** I am using RDM to view some cache stuff from my PHP application. The values are serialized and there is currently no option to format/deserialize that value in the preview.

<img width="500" alt="CleanShot 2020-11-24 at 09 06 40@2x" src="https://user-images.githubusercontent.com/722464/100066324-3c046f00-2e35-11eb-8b90-495b60548f8f.png">

**Solution you'd like**: Have an option in `View as` dropdown for **PHP serialized**

<img width="500" alt="CleanShot 2020-11-24 at 09 11 45@2x" src="https://user-images.githubusercontent.com/722464/100066400-58081080-2e35-11eb-8714-6859c20936a1.png">

**Comment by uglide** [comment]
Hello @ronzyfonzy 
PHP Serializer is included in RDM already but currently is broken in AppStore version of RDM.

**Comment by ronzyfonzy** [comment]
Ow nice. Thank you @uglide. Will wait for new version in AppStore.

**Comment by alfiqmiq** [comment]
Any update? I'm using current version from Microsoft Store.

**Comment by uglide** [comment]
@alfiqmiq PHP formatter is available in the latest Microsoft Store version. Please post here screenshot of the Log drawer in RDM if you experience any issues.

**Comment by alfiqmiq** [comment]
sure, sth about 2 hours i'll be near computer so i do some screenshots and
send it to you

RDM i bought in saturday or sunday so as i think this is latest version (in
Microsoft Store)

pon., 15 lut 2021 o 15:52 Igor Malinovskiy <notifications@github.com>
napisał(a):

**Comment by alfiqmiq** [comment]
[image: image.png]

[image: image.png]

[image: image.png]

pon., 15 lut 2021 o 15:52 Igor Malinovskiy <notifications@github.com>
napisał(a):

**Comment by alfiqmiq** [comment]
Embedded formatter php error: keys must be str, int, float, bool or None,
not bytes (value:
b'cookieInfo|i:1;isWholesale|i:0;storageOnly|i:1;isLogged|i:0;itemListType|s:3:"std";itemListNum|i:64;search|a:1:{s:5:"group";s:1:"2";}sr22|a:2:{s:3:"sex";s:7:"0,1,2,3";s:4:"size";s:68:"17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39";}')

pon., 15 lut 2021 o 21:02 Marek Lisiecki <alfiqmiq@gmail.com> napisał(a):

**Comment by alfiqmiq** [comment]
And small suggestion:

[image: image.png]

please give different icons for different keystypes

[image: image.png]

pon

>

**Comment by uglide** [comment]
@alfiqmiq Images are not rendered from the email. Please attach them on Github.

**Comment by alfiqmiq** [comment]
wt., 16 lut 2021 o 11:42 Igor Malinovskiy <notifications@github.com>
napisał(a):

**Comment by alfiqmiq** [comment]
> Embedded formatter php error: keys must be str, int, float, bool or None, not bytes
>  (value: b'cookieInfo|i:1;isWholesale|i:0;storageOnly|i:1;isLogged|i:0;itemListType|s:3:"std";itemListNum|i:64;search|a:1:{s:5:"group";s:1:"2";}sr22|a:2:{s:3:"sex";s:7:"0,1,2,3";s:4:"size";s:68:"17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39";}')


![image](https://user-images.githubusercontent.com/9507245/108052671-c4696900-704c-11eb-9577-cfa85e896304.png)
![image](https://user-images.githubusercontent.com/9507245/108052709-d0552b00-704c-11eb-903c-e5f27f2e73c4.png)
![image](https://user-images.githubusercontent.com/9507245/108052731-d814cf80-704c-11eb-8d25-4761e7e67e31.png)

**Comment by alfiqmiq** [comment]
And small suggestion, please add different icons for different key types

![image](https://user-images.githubusercontent.com/9507245/108053314-8a4c9700-704d-11eb-901e-7b14b11616e1.png)
![image](https://user-images.githubusercontent.com/9507245/108053348-93d5ff00-704d-11eb-8d7c-3b479058b77d.png)

**Comment by uglide** [comment]
@alfiqmiq thanks for the provided screenshots. 

Different icons cannot be added because RDM doesn't load key types before loading the key value.
This allows reducing the number of commands sent by RDM to redis-server (for example, for 1M keys RDM will need to send 1M `TYPE` redis commands)

**Comment by alfiqmiq** [comment]
> @alfiqmiq thanks for the provided screenshots.
> 
> Different icons cannot be added because RDM doesn't load key types before loading the key value.
> This allows reducing the number of commands sent by RDM to redis-server (for example, for 1M keys RDM will need to send 1M `TYPE` redis commands)

ok so maybe after read key You can update icon ? it would be nice (suggestion only)

**Comment by alfiqmiq** [comment]
> > Embedded formatter php error: keys must be str, int, float, bool or None, not bytes
> > (value: b'cookieInfo|i:1;isWholesale|i:0;storageOnly|i:1;isLogged|i:0;itemListType|s:3:"std";itemListNum|i:64;search|a:1:{s:5:"group";s:1:"2";}sr22|a:2:{s:3:"sex";s:7:"0,1,2,3";s:4:"size";s:68:"17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39";}')
> 
is this enough info or You need sth more ?

**Comment by uglide** [comment]
@alfiqmiq this is enough for investigation, thank you

**Comment by alfiqmiq** [comment]
any progress?

**Comment by alfiqmiq** [comment]
> @alfiqmiq thanks for the provided screenshots.
> 
> Different icons cannot be added because RDM doesn't load key types before loading the key value.
> This allows reducing the number of commands sent by RDM to redis-server (for example, for 1M keys RDM will need to send 1M `TYPE` redis commands)

### From REDIS 6 you can use

```
SCAN 0 TYPE string
SCAN 0 TYPE list
```

and so on...

so solution is very simple for now - detect version, use scan :-)

**Comment by uglide** [comment]
@alfiqmiq Fix is available in preview build 2021.3.292 on https://rdm.dev/subscriptions
You can start free trial to access preview build. ETA in Microsoft Store is March 5th.

> > @alfiqmiq thanks for the provided screenshots.
> > Different icons cannot be added because RDM doesn't load key types before loading the key value.
> > This allows reducing the number of commands sent by RDM to redis-server (for example, for 1M keys RDM will need to send 1M `TYPE` redis commands)
> 
> ### From REDIS 6 you can use
> ```
> SCAN 0 TYPE string
> SCAN 0 TYPE list
> ```
> 
> and so on...
> 
> so solution is very simple for now - detect version, use scan :-)

Unfortunately, it's not that easy even for Redis 6. redis-server supports modules and it means that RDM should detect all installed modules first and somehow figure out all possible key types added by enabled modules.

**Comment by uglide** [comment]
@alfiqmiq  Also suggested approach will increase server load by `N` (number of scan type requests to redis-server) times:

https://redis.io/commands/scan

> It is important to note that the TYPE filter is also applied after elements are retrieved from the database, so the option does not reduce the amount of work the server has to do to complete a full iteration, and for rare types you may receive no elements in many iterations.

**Comment by alfiqmiq** [comment]
And what about bug with php serialized object ?

**Comment by uglide** [comment]
See my reply https://github.com/uglide/RedisDesktopManager/issues/4942#issuecomment-782045888

> @alfiqmiq Fix is available in preview build 2021.3.292 on https://rdm.dev/subscriptions
> You can start free trial to access preview build. ETA in Microsoft Store is March 5th.

**Comment by alfiqmiq** [comment]
ok i'll check this today

**Comment by alfiqmiq** [comment]
ok in 2021.3.292, php sessions are displayed correctly thanks a lot

pt., 19 lut 2021 o 16:11 Igor Malinovskiy <notifications@github.com>
napisał(a):

**Comment by alfiqmiq** [comment]
Today is March 5th, but don't see any update in Microsoft store.

pt., 19 lut 2021 o 16:11 Igor Malinovskiy <notifications@github.com>
napisał(a):

**Comment by alfiqmiq** [comment]
still doesn't see anu upgrade

pt., 5 mar 2021 o 14:50 Marek Lisiecki <alfiqmiq@gmail.com> napisał(a):

**Comment by uglide** [comment]
@alfiqmiq sorry for the delay. The new release will be published tomorrow.

**Comment by uglide** [comment]
@alfiqmiq New build was published in Microsoft Store. Please update.
