### ISSUE TITLE
Windows Cannot Be Resized

### ISSUE THREAD

**Issue by pjobson** [redis/RedisDesktopManager#4945]
None of the windows can be resized.  This is problematic on my systems as the OK/Save buttons on dialogs appear off screen.  There's no way to get to them to change them.

**To Reproduce**

1. Click Connect to Redis Server OR Settings
2. Attempt to resize windows to bring OK or Save button into view.
3. Realize attempts are futile.

**Expected behavior**

Windows should be resizable like normal applications.  

**Screenshots**

**Environment (please complete the following information):**
 - Linux Mint 20
 - 3200x1800 Resolution
 - 2x Interface Scaling 
    - this is probably what causes the problem, though reducing it makes the font in the OS too small for me to read

**Additional context**

You can see in my screen shots that the buttons at the bottom of these windows are off screen, also the close (X) for the application is off screen.  I can drag the application horizontally to get to the (X) to close it, but I cannot drag the context windows off screen to confirm my settings / connection preferences.

![RDS New Connection](https://user-images.githubusercontent.com/1482547/100252706-2ca52480-2f0e-11eb-9b7f-2f6b4f5dca97.png)
![RDS Settings](https://user-images.githubusercontent.com/1482547/100252707-2ca52480-2f0e-11eb-9e4a-bc91de71fe8d.png)

**Comment by uglide** [comment]
@pjobson you overcome this issue with QT_SCALE_FACTOR env variable: QT_SCALE_FACTOR=1.1 redis-desktop-manager.rdm

Play with the value to find the best scaling factor for your display configuration.
