### ISSUE TITLE
AppImage build?

### ISSUE THREAD

**Issue by catpreneur** [redis/RedisDesktopManager#4947]
**Is your feature request related to a problem? Please describe.**
Portability. Some distros don't have snapcraft and not everyone wants to use it.

**Describe the solution you'd like**
AppImages are decentralized and portable. They're easy to update and integrate with every distro.

I've been trying to get an AppImage build for RDM, but have had partial success. I'm happy to contribute my work if there's interest.

**Comment by uglide** [comment]
Hello,

Snapcraft allows to easily build and distribute apps without much hassle. That's the main reason why RDM is distributed on Linux with Snapcraft.

Nonetheless, I'm open to AppImage if it can provide a better experience for Linux users with the same amount of effort. 

Please share your work as repo/gist/links/etc and I will try to help make it up and running.

**Comment by catpreneur** [comment]
Hi,

Really appreciate you offering support.

Here's my gist containing the build script (I use docker) as well as the error message I'm getting when trying to run it.

https://gist.github.com/oofdog/a59f8f6baa9b256b70f3b092ee6cb2d3

This isn't fully up to date as I'm trying out other methods of installing the right Qt versions, but I'm still in the weeds.

**Comment by uglide** [comment]
@oofdog you can check this repo with ready-to-use RDM appimage builds https://github.com/pidario/rdm-build

Also, I decided to make flatpak packaging for RDM and publish it to flathub.

**Comment by catpreneur** [comment]
Awesome! Thank you!
