### ISSUE TITLE
Connection: AUTH ERROR 连不上带密码的redis

### ISSUE THREAD

**Issue by xjxjin** [redis/RedisDesktopManager#4956]
目前使用的版本是：2020.6.144

![image](https://user-images.githubusercontent.com/35513148/102171766-3d740500-3ed2-11eb-886e-153d3650d91c.png)
![image](https://user-images.githubusercontent.com/35513148/102171847-744a1b00-3ed2-11eb-93e4-8d21ce598f3b.png)

**Comment by uglide** [comment]
@xjxjin your password is incorrect, try to change it if it redis-server or ensure that you entered/copied it correctly if its cloud redis.

if you need further assistance with this problem please provide more details:
- redis deployement type
- redis version

**Comment by xjxjin** [comment]
redis deployement：sentinel
redis version：Redis server v=4.0.14 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=a9546b4e3153e7e3
我用 RDM 0.9.9.72  可以连接上去
