### ISSUE TITLE
JSON 格式化失败

### ISSUE THREAD

**Issue by Bophie** [redis/RedisDesktopManager#4958]
文本内容包含Map结构数据时无法正常进行JSON格式化
如：
{"abilityScore":0,"channel":0,"cheatMoney":0.0,"createTime":1608028289914,"items":{"map":{1001:{"count":4,"id":1001}}},"level":0,"loginTime":1608028289914,"nickName":"彩虹","onlineTime":0,"payMoney":0.0,"playerId":1,"primary":1,"serverId":1,"userId":1}

**Comment by uglide** [comment]
@Bophie your JSON is not valid
