### ISSUE TITLE
window的客户端某一个库经常连接不上

### ISSUE THREAD

**Issue by Hypoxicfire** [redis/RedisDesktopManager#4959]
![image](https://user-images.githubusercontent.com/53009572/102871864-ec3bb680-4479-11eb-8def-6495a1449f42.png)

**Comment by uglide** [comment]
@lhq1995 please provide steps to reproduce the issue and more details about your redis-server (version, etc) and enabled tunnels if any (tls/ssh/tls-over-ssh)

**Comment by Hypoxicfire** [comment]
目前更新版本后没出现过这个问题
