### ISSUE TITLE
树形列表可以置顶吗?  Can the tree list be topped?

### ISSUE THREAD

**Issue by whiteS18** [redis/RedisDesktopManager#4962]
当非树形列表比较多的时候,如果需要查看树形列表需要经常进行下拉操作,希望可以将树形列表默认置顶展示,或者可以手动配置.

When there are many non-tree lists, if you need to view the tree list, you need to frequently perform drop-down operations.I hope that the tree list can be displayed on the top by default, or it can be configured manually.

**Comment by uglide** [comment]
@whiteS18 thanks for the feedback. totally makes sense to add such config option
