### ISSUE TITLE
Connection: Disconnect on error: Too many cluster redirects. Connection aborted.

### ISSUE THREAD

**Issue by Holinc19** [redis/RedisDesktopManager#4973]
**Connection: Disconnect on error: Too many cluster redirects. Connection aborted.**
It always stays in loading key and gets disconnect on error.
Redis cluster is created by shell `create-cluster`.

**Environment:**
 - OS & version:  Windows 10 1909
 - Redis-Server version:  6.0.6
 - RDM-GUI version:  2020.7.270

**Comment by uglide** [comment]
Hello

Please provide output of 
`CLUSTER INFO` and `CLUSTER SLOTS` redis-server commands

**Comment by Holinc19** [comment]
> Hello
> 
> Please provide output of
> `CLUSTER INFO` and `CLUSTER SLOTS` redis-server commands

RDM Redis Console
Connecting...
Connected to cluster.
127.0.0.1(127.0.0.1:30005)>CLUSTER INFO
"cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:377
cluster_my_epoch:370
cluster_stats_messages_ping_sent:614009
cluster_stats_messages_pong_sent:613684
cluster_stats_messages_fail_sent:1264
cluster_stats_messages_auth-req_sent:290
cluster_stats_messages_auth-ack_sent:90
cluster_stats_messages_update_sent:41
cluster_stats_messages_sent:1229378
cluster_stats_messages_ping_received:613513
cluster_stats_messages_pong_received:611433
cluster_stats_messages_fail_received:1166
cluster_stats_messages_auth-req_received:254
cluster_stats_messages_auth-ack_received:94
cluster_stats_messages_update_received:32
cluster_stats_messages_received:1226492
"

127.0.0.1(127.0.0.1:30005)>CLUSTER SLOTS
1) 1) "10923"
   2) "16383"
   3) 1) "127.0.0.1"
      2) "30006"
      3) "92a28b8a7d82ad9740b6d5dfdfb2a7f90ef7a81b"

   4) 1) "127.0.0.1"
      2) "30003"
      3) "e1320c8465b566ed6cefd02a95d2c98c09c983d6"


2) 1) "5461"
   2) "10922"
   3) 1) "127.0.0.1"
      2) "30005"
      3) "f83c15be822ca8f0fe8530c9e3fc9492073278a7"

   4) 1) "127.0.0.1"
      2) "30002"
      3) "d609e118affa2a885581fa1591af4f517064f4c9"


3) 1) "0"
   2) "5460"
   3) 1) "127.0.0.1"
      2) "30004"
      3) "58f70d8825545fb52fe7e4e2fd8852d362098e40"

   4) 1) "127.0.0.1"
      2) "30001"
      3) "11856bdff5e1ff0b3d223e8108365ee2624bd747"

**Comment by Holinc19** [comment]
**The RDM-GUI log menu output** :

Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] PING
Connection: 127.0.0.1 > [runCommand] INFO ALL
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: Reconnect to 127.0.0.1:30006
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] scan 0 MATCH * COUNT 10000
Connection: Reconnect to 127.0.0.1:30004
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] scan 0 MATCH * COUNT 10000
Connection: Reconnect to 127.0.0.1:30005
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] scan 0 MATCH * COUNT 10000
Connection: 127.0.0.1 > connected
Connection: Reconnect to 127.0.0.1:30006
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] type sys_parameter:{ATTACH_KEY}
Connection: Reconnect to 127.0.0.1:30004
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] PING
Connection: 127.0.0.1 > [runCommand] INFO ALL
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: Reconnect to 127.0.0.1:30006
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] type sys_parameter:{ATTACH_KEY}
Connection: Reconnect to 127.0.0.1:30004
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] PING
Connection: 127.0.0.1 > [runCommand] INFO ALL
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: Reconnect to 127.0.0.1:30006
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] type sys_parameter:{ATTACH_KEY}
Connection: Reconnect to 127.0.0.1:30004
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] PING
Connection: 127.0.0.1 > [runCommand] INFO ALL
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: Reconnect to 127.0.0.1:30006
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] type sys_parameter:{ATTACH_KEY}
Connection: Reconnect to 127.0.0.1:30004
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] PING
Connection: 127.0.0.1 > [runCommand] INFO ALL
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: Reconnect to 127.0.0.1:30006
Connection: Cluster detected
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] type sys_parameter:{ATTACH_KEY}
Connection: Reconnect to 127.0.0.1:30004
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] PING
Connection: 127.0.0.1 > [runCommand] INFO ALL
Connection: 127.0.0.1 > [runCommand] CLUSTER SLOTS
Connection: Reconnect to 127.0.0.1:30006
Connection: 127.0.0.1 > connected
Connection: 127.0.0.1 > [runCommand] type sys_parameter:{ATTACH_KEY}
Connection: Disconnect on error: Too many cluster redirects. Connection aborted.

**Comment by uglide** [comment]
@Holinc19 thanks for the detailed info. I'm investigating the problem.

**Comment by uglide** [comment]
@Holinc19 Please download the latest build rdm-2021.0.278.exe and post here output from RDM log menu.

**Comment by Holinc19** [comment]
@uglide Perhaps there is some wrong in my redis cluster config. I have upgraded to rdm-2021.0.278.exe and there is no response while accessing to the key. So I can't click the log menu.

**Comment by Holinc19** [comment]
![image](https://user-images.githubusercontent.com/28728567/106736705-c4329c00-6650-11eb-831c-0f3091ee05b5.png)
