### ISSUE TITLE
Managed redis on digitalocean

### ISSUE THREAD

**Issue by eldair** [redis/RedisDesktopManager#4975]
**Describe the bug**
Connecting to managed redis on digitalocean is not possible via SSH tunnel. It never connects, just 'pending'.

**Environment (please complete the following information):**
 - OS & version: Windows 10 latest
 - Redis-Server version: 6 (same issue with v5)

**Comment by uglide** [comment]
@Eldair Could you please explain why do you need an SSH tunnel for digitalocean managed redis?

DigitalOcean allows you to whitelist allowed IP addresses that have access to redis from the internet. 

Connection with SSH tunnel is possible but you need to enable TLS-over-SSH checkbox
![image](https://user-images.githubusercontent.com/1655867/105511951-31514380-5cd9-11eb-8b1d-b19aabd440d6.png)
 in RDM connection settings to make it work and ensure that your instance (where SSH server is hosted) has access to redis-cluster.

**Comment by eldair** [comment]
Because I don't have fixed IP address.
I tried that option but I get error it won't connect almost immediately and there is nothing in the log.

**Comment by uglide** [comment]
@Eldair Have you allowed access from instance IP address to redis-server?

**Comment by eldair** [comment]
If you mean the server I use as tunnel then yes, my app on that server can connect to redis without issues.

**Comment by uglide** [comment]
@Eldair also double check that you **Left Username field in RDM empty** as mentioned in docs http://docs.rdm.dev/en/latest/quick-start/

DigitalOcean shows wrong connection settings by default.

If you still struggle with the connection problem please post here screenshot of the Log drawer in RDM.

**Comment by eldair** [comment]
@uglide Yeah, I tried that. I also tried adding `tls://` before server address (this is required in my app to connect) which also doesn't work. Here is my configuration and error(s):

![Screenshot 2021-01-25 103624](https://user-images.githubusercontent.com/470003/105687975-5cb27900-5ef9-11eb-92f8-18d26f3a40c6.png)
![Screenshot 2021-01-25 103406](https://user-images.githubusercontent.com/470003/105687982-5f14d300-5ef9-11eb-882e-30d7f4392af2.png)
![Screenshot 2021-01-25 103648](https://user-images.githubusercontent.com/470003/105687987-61772d00-5ef9-11eb-909b-37abc4c8f511.png)

**Comment by uglide** [comment]
@Eldair Please run https://docs.microsoft.com/en-us/sysinternals/downloads/debugview ,try again to connect in RDM and post here log from DebugView. It will help to understand what's going wrong. Thanks!

**Comment by eldair** [comment]
@uglide here it is 
![image](https://user-images.githubusercontent.com/470003/105689703-61782c80-5efb-11eb-851c-0eb3924de266.png)

**Comment by uglide** [comment]
@Eldair I've noticed that your Address (redis-server host) looks quite short comparing to what I get on DigitalOcean. Are you sure that redis-server host is entered correctly?
Also I recommend to use *Public* host name (just remove **private-** from the beginning)

**Comment by eldair** [comment]
@uglide It is definitely correct address (redis-do-user-......db.ondigitalocean.com). I tried both with and without **private-**, same error and log message.
I also tried couple of different servers as tunnels (all of which are able to connect to redis by themselves)

**Comment by uglide** [comment]
@Eldair Your system certificate db may be broken. Try to:

1. Install Win32 OpenSSL
2. Make port forwarding to redis-server via SSH tunnel on your local Win 10 PC or just allow connections from your current IP
3. Run this command on Win 10 PC:
```
openssl s_client -connect YOUR_DO_REDIS_HOST:PORT  -showcerts
```

**Comment by eldair** [comment]
@uglide What should I see there?
There is cert chain and SSL verification: OK

**Comment by uglide** [comment]
@Eldair  If it shows cert chain then your system certs are ok. Which version of RDM do you use?

**Comment by eldair** [comment]
Latest one, from 2-3 days ago

**Comment by eldair** [comment]
@uglide any chance the fix is coming soon?

**Comment by uglide** [comment]
@Eldair Unfortunately, I cannot reproduce this problem on freshly created Digital Ocean managed redis instances. 
Digital ocean uses TLS certificates from Let's Encrypt and your problem  may be related to some cert issue (like https://letsencrypt.org/caaproblem/)

You can try to create new redis instance on Digital Ocean and try to connect to it. It will show the direction of further investigation (problem with cert or problem with your OS)

**Comment by eldair** [comment]
@uglide I found the issue -.- I remembered that I had installed software issued by Serbian government (used for reading IDs via card reader) and that it adds some certificates. Once I removed it everything works fine.

**Comment by uglide** [comment]
@Eldair glad to hear that 👍
