### ISSUE TITLE
Navigation is awkward on the connections/database/key panel

### ISSUE THREAD

**Issue by prkemp** [redis/RedisDesktopManager#4979]
The navigation pane that shows the connections, databases and key hierarchy is difficult to navigate.  Suppose you have hundreds of entries, and want to navigate up and down the list.  Home/End/Page up/Page down keys don't have any effect.  Additionally, the scroll bar is hidden.  To grab the scroll bar on that window you have to scroll with the mouse scroll wheel and quickly grab the scroll bar before it disappears.

**Describe the solution you'd like**
Home/End/Page up/Page down keys should work the same way as in common Windows applications.
The scroll bar should always be available.  No need to hide it.

**Comment by prkemp** [comment]
Hi, the behaviour hasn't changed despite the fix.  Could you take another look pls.

**Comment by uglide** [comment]
@prkemp which version of RDM do you use?

**Comment by prkemp** [comment]
Currently running 2021.2.285, thanks.
