### ISSUE TITLE
RDM can't completely display all of the binary values in the hex table.

### ISSUE THREAD

**Issue by slightcycle** [redis/RedisDesktopManager#4981]
![Selection_002](https://user-images.githubusercontent.com/46361779/106121524-9eaa1c00-6192-11eb-8b31-d7a746988eac.png)
  Hi, very nice to be here. There is a problem when I used the RDM on my ubuntu18 operating system to manage the Redis-DB on my embedded device, I found that there was a binary array that could not be displayed completely if I chose the "Hex Table" format. Is there anything wrong with using this software?

**Comment by uglide** [comment]
Hello @slightcycle 

Please provide example of the binary string that cannot be displayed. Thanks!

**Comment by slightcycle** [comment]
Hello everyone,

      Sorry for delayed reply. These are 57 bytes of binary data I want 
to store in the Redis database:

0x12 0x08 0x00 0x10 0x01 0x18 0x02 0x20 0x03 0x28 0x04 0x30 0x05 0x38 
0x06 0x40 0x07 0x48 0x08 0x12 0x08 0x00 0x10 0x11 0x18 0x12 0x20 0x13 
0x28 0x14 0x30 0x15 0x38 0x16 0x40 0x17 0x48 0x18 0x12 0x08 0x00 0x10 
0x21 0x18 0x22 0x20 0x23 0x28 0x24 0x30 0x25 0x38 0x26 0x40 0x27 0x48 0x28.

Thanks.
