### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by shuohao** [redis/RedisDesktopManager#4983]
<img width="491" alt="微信截图_20210201113838" src="https://user-images.githubusercontent.com/4637107/106412304-6d776780-6482-11eb-89ae-e0033dd2699a.png">
<img width="491" alt="微信截图_20210201113855" src="https://user-images.githubusercontent.com/4637107/106412316-72d4b200-6482-11eb-9f7e-652af5aa5d35.png">

**2560x1440  150%**

**Comment by Jerry-Shaw** [comment]
Another UI bug, 
![image](https://user-images.githubusercontent.com/13212198/114192698-60925b00-9980-11eb-861b-5ea21be39844.png)

**Comment by uglide** [comment]
@Jerry-Shaw thanks for the feedback. Please specify screen resolution and Windows scaling factor.

**Comment by Jerry-Shaw** [comment]
@uglide Screen resolution is 3840 x 2160, scale is 225%

**Comment by uglide** [comment]
Fixed and will be released as part of 2021.4.

**Comment by Jerry-Shaw** [comment]
Yeah, fixed, and much better on scrolling now
