### ISSUE TITLE
Build on Windows Error

### ISSUE THREAD

**Issue by whiteS18** [redis/RedisDesktopManager#4985]
Hello, I use the source code to compile according to the [documentation](https://docs.rdm.dev/en/latest/install/)，when I open 
Open ./src/rdm.pro in Qt Creator. Choose the Desktop Qt 5.15.x MSVC2019 64bit > Release build profile. And run build.
Qt Creator shows
'lld-link' is not recognized as an internal or external command,
operable program or batch file.
jom: D:\rdm\build-rdm-Desktop_Qt_5_15_2_MSVC2019_64bit-Release\Makefile.Release [..\bin\windows\release\rdm.exe] Error 1
jom: D:\rdm\build-rdm-Desktop_Qt_5_15_2_MSVC2019_64bit-Release\Makefile [release] Error 2
13:55:50: 进程"C:\Users\scw\msvc_make.bat"退出，退出代码 2 。
Error while building/deploying project rdm (kit: Desktop Qt 5.15.2 MSVC2019 64bit)
When executing step "Make"
13:55:50: Elapsed time: 00:00.

![image](https://user-images.githubusercontent.com/31566522/106704818-b1f03800-6627-11eb-9e45-54e75fd7f34c.png)

Here is my OS Info
Windows 10 Professional  20H2
version 19042.746

**Comment by uglide** [comment]
@whiteS18 For some reason QtCreator picked up llvm compiler instead of msvc. You need to double check your kit settings and make sure that MSVC2019 64bit is installed correctly on your system.

**Comment by whiteS18** [comment]
@uglide

Okay,now I'm choose compiler as msvc type.
![image](https://user-images.githubusercontent.com/31566522/106858837-33fe6080-66fd-11eb-8071-90011feaa7d2.png)
![image](https://user-images.githubusercontent.com/31566522/106858883-41b3e600-66fd-11eb-9507-a1b047c81259.png)
![image](https://user-images.githubusercontent.com/31566522/106858916-4ed0d500-66fd-11eb-9816-543b4110ab76.png)
And I'm sure MSVC2019 64bit was installed on my system
![image](https://user-images.githubusercontent.com/31566522/106858653-f568a600-66fc-11eb-863e-2708544b0831.png)
but it show's :
 LNK1181: 无法打开输入文件“D:\rdm\3rdparty\lz4\build\cmake\Release\lz4.lib”
Lnk1181: unable to open input file "D:\RDM\3rdparty\lz4\build\cmake\release\lz4. Lib"
![image](https://user-images.githubusercontent.com/31566522/106859221-ad964e80-66fd-11eb-9af7-64c9889a48fb.png)
