### ISSUE TITLE
Cannot load keys: ERR unknown command 'iscan'

### ISSUE THREAD

**Issue by jimbreckel** [redis/RedisDesktopManager#4995]
I just purchased this and I connect to redis server on localhost and when I click on db I get: Cannot load keys: ERR unknown command 'iscan'

**Comment by uglide** [comment]
Hello @jimbreckel 
Which version of redis-server do you use? 
Modern versions of RDM support only redis-server > 2.8 and if `SCAN` command is blocked/renamed or unavailable you will see mentioned error message.

**Comment by jimbreckel** [comment]
It was an old version installed. I upgraded and it works now. Sorry.

**Comment by romico** [comment]
If you can't find the 'SCAN/ISCAN' command, you can check the 'rename-command' in 'redis.conf'.
