### ISSUE TITLE
关闭tab页的时候，程序崩溃V2020.1，操作系统：Win10专业版

### ISSUE THREAD

**Issue by LEIHAOYUAN** [redis/RedisDesktopManager#4997]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
@LEIHAOYUAN Please provide steps to reproduce the issue. Do you use Windows Surface?

**Comment by LEIHAOYUAN** [comment]
Win10专业版

**Comment by LEIHAOYUAN** [comment]
first step：Filter a key click to view details
second step：Select another key to see the details
third step：Close one of the tabs，then software crashes

**Comment by uglide** [comment]
@LEIHAOYUAN Please specify the full RDM version with build number

**Comment by erictangtao** [comment]
first step：Filter a key click to view details
second step：Select another key to see the details
third step：Close one of the tabs，then software crashes

**Comment by uglide** [comment]
@erictangtao If you are experiencing the same issue please provide RDM version you are using.
