### ISSUE TITLE
Latest Update to Apple Mac store is VERY broken

### ISSUE THREAD

**Issue by edgework** [redis/RedisDesktopManager#4998]
**Describe the bug**
It just doesn't work any more.  It doesn't load most of the keys,  if I refresh it will sometimes load them.  But will never load all the keys. 

**To Reproduce**
Run on  macOS  10.15.7  (catalina)

**Expected behavior**
it works

**Environment (please complete the following information):**
 - OS & version: macOS  10.15.7  
 - Redis-Server version    Redis server v=3.2.5 sha=00000000:0 malloc=libc bits=64 build=112b103d6428f815

**Additional context**
RDM worked fine before the last update.  Pulling the old version from backups works just as it used to but now I need to disable automatic updates in the Mac App Store

**Comment by uglide** [comment]
@edgework thank you for the bug report
Could you please specify more details about your connection to redis-server? Do you use TLS/SSH or TLS-over-SSH tunnel? Is it cluster/sentinel or standalone redis-server?

If possible please send me a screencast of the problem to email igor@rdm.dev

**Comment by edgework** [comment]
No TLS/SSH. This is a stand alone server on the local machine. Here's the config

`{
        "auth": "",
        "filter_history": {
            "*": 25
        },
        "host": "127.0.0.1",
        "name": "local",
        "port": 6379,
        "timeout_connect": 60000,
        "timeout_execute": 60000
    }`


I don't have the latest version any more, this is from App Store so I can't just get any version. I needed to grab the old version from a backup.  If you want to send me a build to try etc. I would be happy to help.  edgework@wongo.com

**Comment by uglide** [comment]
**Update**: Fix for collapsing icon in the Connection tree was released in 2021.3.176 and it's already available in the AppStore. If anyone is still experiencing any issues please drop the line in this issue. thanks!

**Comment by uglide** [comment]
Version 2021.3.177 is available in Apple AppStore and allows to configure how namespaced keys are rendered in tree.

@edgework if you have any feedback please share it here or ping me on email igor@rdm.dev
Thanks!
