### ISSUE TITLE
The icon of the app in taskbar is too small

### ISSUE THREAD

**Issue by firstmetcs** [redis/RedisDesktopManager#5006]
The icon of the app in taskbar is too small, hope can be improved

![image](https://user-images.githubusercontent.com/32634443/110914868-e86d5100-8351-11eb-84ee-d017c560ee03.png)

THE APP IS DOWNLOADED IN MICROSOFT STORE

**Comment by uglide** [comment]
@firstmetcs thanks for the feedback.

**Comment by firstmetcs** [comment]
When will the issue can be improved？？？

**Comment by uglide** [comment]
@firstmetcs fix will be released as part of the next release on Microsoft Store.

**Comment by uglide** [comment]
@firstmetcs Fixed version 2021.4.74 is already available in the Microsoft Store
Let me know if you have any other suggestions or feedback. Thanks!
