### ISSUE TITLE
Add new key Type ReJSON 

### ISSUE THREAD

**Issue by kristianwestg** [redis/RedisDesktopManager#5010]
Im not able to add a new key with ReJSON type, it is possible to see and update keys witch is already inserted with JSON.SET, but it would be very nice to add new keys in the RDM gui with ReJSON.

Thanks!

--
Kristian

**Comment by ghost** [comment]
Does this feature will be in any future release?

**Comment by uglide** [comment]
@Kamil93 Yes, it is planned for RDM 2021.8. ETA is mid of Sept 2021
