### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by yinxiulong** [redis/RedisDesktopManager#5020]
rdm
Disable auto-scaling
段错误 (核心已转储)

**Comment by uglide** [comment]
@yinxiulong 
Hello, Which OS and version of RDM do you use?

**Comment by yinxiulong** [comment]
Manjaro 发自 网易邮箱大师 在2021年03月29日 22:40，Igor Malinovskiy 写道： @yinxiulong Hello, Which OS and version of RDM do you use? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by uglide** [comment]
The latest builds on snapcraft look stable. Please try to use them and feel free to re-open this issue if you still seeing this bug.
