### ISSUE TITLE
ubuntu20.4 系统下 无法输入中文  输入法不唤起

### ISSUE THREAD

**Issue by yuntian001** [redis/RedisDesktopManager#5023]
**Describe the bug**
ubuntu20.4 系统下 无法输入中文 输入法不唤起

版本为RDM - GUI for Redis 2021.3+648029F9

**Comment by uglide** [comment]
@yuntian001 The issue was fixed in the edge channel in Snapcraft 
```
sudo snap refresh --edge redis-desktop-manager
```
