### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by liangweidonggood** [redis/RedisDesktopManager#5024]
![20210401231515](https://user-images.githubusercontent.com/6304507/113315928-65338f80-9340-11eb-9b94-c59102aa9f1c.png)
\RedisDesktopManager-2021\src\app\models\connectionsmanager.cpp:131: error: C2039: "setId": 不是 "ServerConfig" 的成员、
请问这是什么问题

**Comment by uglide** [comment]
Hello, you need to update qredisclient
