### ISSUE TITLE
Dark background on selected option, while font is also dark.

### ISSUE THREAD

**Issue by teneon** [redis/RedisDesktopManager#5025]
**Describe the bug**
The issue is that text color of the font is black, while the background color for the selected option (in the left menu) is dark blue.Which basically means, you can't even see what u have selected. It is very annoying, is it possible to fix this somehow? Or is there a workaround? I couldn't find any color settings in settings.

**Screenshots**
![](https://i.imgur.com/5qBGGL7.png)

**Environment (please complete the following information):**
 - OS & version: Kubuntu Linux 20.04
 - Redis-Server version [e.g. 6.0.6]

**Comment by uglide** [comment]
The issue was fixed in 2021.7+3b773fb4 which is available in edge channel on snapcraft
