### ISSUE TITLE
Add support for Magento compressed session data

### ISSUE THREAD

**Issue by kanevbg** [redis/RedisDesktopManager#5028]
I'm always frustrated when I had to inspect data in redis, stored by Magento 1/2 system, as it is using compression and the data is not readable straight-away when inspecting.

I'd like to have a "View as" option which support decompression.
The type of compression used by default in Magento is gzip, however there is option and implementation for snappy, lzf and lz4. If all of these can be supported it will be even better.

**Comment by uglide** [comment]
Hello @kanevbg 
RDM currently supports automatic decompression of GZIP and LZ4 by finding corresponding "magic" header https://github.com/uglide/RedisDesktopManager/blob/2021/src/app/qcompress.cpp#L16

Could you provide sample of the data created by Magento? It will help to figure out why it's not decompressed automatically in RDM. Thanks!

**Comment by kanevbg** [comment]
[sample-hex.txt](https://github.com/uglide/RedisDesktopManager/files/6264538/sample-hex.txt)
here it is, viewed as hex

**Comment by kanevbg** [comment]
Is it reproducible?

**Comment by uglide** [comment]
@kanevbg sorry for the late reply. Build-in decompression doesn't work due to `gz:` prefix in your value.
I'm trying to setup test Magento environment to play with all kind of cache compression types and get all possible combinations of values to add proper support for it in RDM.

**Comment by uglide** [comment]
@kanevbg Could you please specify which platform/OS do you use?

I've added support for Magento compression/decompression for `gzip` and `lz4`  in #5130 and will be grateful if you could try preview build with these changes.

**Comment by kanevbg** [comment]
I will do. Using on windows 10 Pro 21H1 x64. Will be great if you add support for zstd too, I can test that too.

**Comment by uglide** [comment]
Yes, general zstd support will be also included. But I don't see zstd in Magento settings here https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-session.html :)

**Comment by kanevbg** [comment]
Its not documented but is available trough the actual adapter magento used: \Cm_Cache_Backend_Redis
Use like this
![image](https://user-images.githubusercontent.com/11477130/142454812-11cb2d03-c0f5-4450-9942-8a16b4442837.png)
php zstd extension is required too.

**Comment by uglide** [comment]
@kanevbg thanks for the hint. Will try it out.

**Comment by uglide** [comment]
@kanevbg Please sign in with your account on rdm.dev and go to https://rdm.dev/subscriptions
In the "Preview Builds" tab you can download `rdm-2021.9.384.exe` which includes Magento automatic decompression for cache and sessions.

Please share your feedback. Thanks!

**Comment by kanevbg** [comment]
![image](https://user-images.githubusercontent.com/11477130/142641101-7c83198a-357d-46f4-b974-dfe0ba241f14.png)
seems fine
however FPC html data is not readable
![image](https://user-images.githubusercontent.com/11477130/142641279-0df06433-436e-4e8e-84f6-028d640a8d99.png)
EDIT: the data is readable only the first time data of key is decoded, every other time fails until key reload

EDIT 2: and here the data is always undecoded:
![image](https://user-images.githubusercontent.com/11477130/142642028-f1f34046-3608-418f-b8e5-f20fa7396386.png)

**Comment by uglide** [comment]
@kanevbg thanks. will double-check

**Comment by kanevbg** [comment]
In order to reproduce test will cache entries which has more than one keys which should be decoded. In the above case t & d are both to be decoded

**Comment by uglide** [comment]
@kanevbg added fix in `rdm-2021.9.385.exe`

**Comment by uglide** [comment]
@kanevbg Please let me know if you have any other feedback or faced any other issues. Thanks!

**Comment by kanevbg** [comment]
In this field the issue is not solved, other cases are fixed.
![image](https://user-images.githubusercontent.com/11477130/142858890-ebe42446-6830-4a59-83f7-56e4ccd6f6b8.png)
