### ISSUE TITLE
How to connect Redis Sentinel using RDM in ubuntu

### ISSUE THREAD

**Issue by sontn15** [redis/RedisDesktopManager#5031]
Dear support team,

I want to connect to Redis sentinel, but I dont know how to connect.

Please help me, thank so much!

**Comment by uglide** [comment]
Hello, @sontn15 
You just need to specify connection settings for redis-sentinel (usually different port like 26379, etc) and click on added connection to connect. If you have any particular issues feel free to contact me via email igor@rdm.dev or just leave here comment with screenshots and details. Please do not post any secrets (passwords, etc) here.

**Comment by sontn15** [comment]
I have 3 IP server sentinel redis
IP: 10.x.x.37, 10.x.x.38, 10.x.x.39
username, password.

I dont connect to sentinel redis.

**Comment by sontn15** [comment]
![image](https://user-images.githubusercontent.com/68374544/114359222-edfec680-9b9d-11eb-831c-8c24002f8641.png)
My port of redis sentinel is 26379

**Comment by uglide** [comment]
@sontn15 Please post here screenshot of the Log drawer in RDM (Log button in right top corner of the main window).

**Comment by sontn15** [comment]
I'm sorry, I connected to Redis Server!

I close bug
