### ISSUE TITLE
[v-2021.3.177]还没之前版本好用，连集群卡的一匹。白瞎正版支持...

### ISSUE THREAD

**Issue by fulldog** [redis/RedisDesktopManager#5032]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
@fulldog Please describe in detail what kind of issue you faced with. Also please provide a screenshots to simplify explanation of the occurred problem.
