### ISSUE TITLE
Linux version is different than screenshots (light theme)

### ISSUE THREAD

**Issue by valamorgon** [redis/RedisDesktopManager#5042]
Screenshots of RDM is always dark theme, but linux version is in light theme.

Also there is no theme option in settings.

I downloaded my RDM from: https://aur.archlinux.org/packages/redis-desktop-manager/ but upstream is https://redisdesktop.com/

![image](https://user-images.githubusercontent.com/23139757/116617695-ce5df100-a946-11eb-9ccf-c47b936b33ab.png)

 - OS is: Manjaro 21.0.2
 - Redis-Server version is: 2021.3.0

**Comment by teneon** [comment]
This is exactly the same issue as i am having. Hopefully they fix it asap :D

**Comment by uglide** [comment]
Switch for theme switching will be added in 2021.4 to the Settings dialog.

**Comment by uglide** [comment]
The dark-mode switch is available in the edge channel in Snapcraft:
![image](https://user-images.githubusercontent.com/1655867/120298203-8da12100-c2d2-11eb-8bfd-ee1175396815.png)
