### ISSUE TITLE
Can't clear SSH key path field

### ISSUE THREAD

**Issue by LocalHeroPro** [redis/RedisDesktopManager#5046]
**Describe the bug**
Can't login to redis using SSH Tunnel when redis is on other server - using password or private key.

**To Reproduce**
1. Click on Connect To Redis Server.
2. Fill up data as shown on screen.

**Expected behavior**
Login to redis server via SSH hoop.

**Screenshots**
![image](https://user-images.githubusercontent.com/42643563/117304033-9b06ef00-ae7d-11eb-9a5c-691071efb86c.png)

**Environment (please complete the following information):**
 - OS & version: Linux Mint
 - Redis-Server version 6

**Comment by uglide** [comment]
Please provide a screenshot of the Log drawer in RDM with error message.

**Comment by LocalHeroPro** [comment]
```log
Connection: Connecting to SSH host...
Connection: Disconnect on error: SSH Connection error(Authentication Error): Unable to extract public key from private key file: Unable to open private key file
```
It's possible if I have auto connect with 'all' CLI from my PC using Private Key and RDM EVEN if I select Password option try to connect using that key?

**Comment by uglide** [comment]
If you are using RDM from snap, most likely you haven't enabled access to SSH keys in permissions as described in documentation: 

```
sudo snap connect redis-desktop-manager:ssh-keys
```

**Comment by LocalHeroPro** [comment]
True it's help to connect using key and passphase, but how to connect using only password?

**Comment by uglide** [comment]
Remove private key path.

**Comment by uglide** [comment]
On Linux, you just need to clear SSH key field to do so.
