### ISSUE TITLE
购买订阅怎么是这样呢，是我网络问题吗

### ISSUE THREAD

**Issue by tjlizz** [redis/RedisDesktopManager#5049]
![image](https://user-images.githubusercontent.com/33169073/118204502-e7ab8500-b490-11eb-8d37-0fa2114d8731.png)

**Comment by uglide** [comment]
Hello, your question is not clear. Why are you trying to access cn.rdm.dev instead of https://rdm.dev?

**Comment by tjlizz** [comment]
![2021-05-14-16-04-14](https://user-images.githubusercontent.com/33169073/118240900-1bf16680-b4ce-11eb-9d67-2729668d36bf.gif)

**Comment by uglide** [comment]
Thanks for the screencast. It should work now.
