### ISSUE TITLE
get detail item return s.t stupid 

### ISSUE THREAD

**Issue by Heartsky** [redis/RedisDesktopManager#5052]
<img width="1070" alt="Screen Shot 2021-05-18 at 9 37 39 PM" src="https://user-images.githubusercontent.com/13728327/118671357-9816e180-b821-11eb-9100-588b4cb04379.png">
 this is my list .
I click to a item to see detail 
and app show s.t :  
<img width="1205" alt="Screen Shot 2021-05-18 at 9 37 24 PM" src="https://user-images.githubusercontent.com/13728327/118671523-bd0b5480-b821-11eb-903b-8eae2191b6d2.png">
The app did not run 

Do you test the app before throwing  it into app store ?

**Comment by uglide** [comment]
Hello @Heartsky 
Thanks for the feedback. You have php formatter selected that's why you are receiving error that value cannot be decoded as php serialized data. You can fix this issue simply by changing  formatter back to plain text.

Format detection will be improved in the next releases this year.

**Comment by Heartsky** [comment]
please see my image carefully, result is not the value of key .

**Comment by uglide** [comment]
Yes, I see that details are not cleared from previous error. We clean this mess up in the next release.

**Comment by Heartsky** [comment]
I select a text and no error here but the app show error.

**Comment by uglide** [comment]
Could you please record screen cast of the issue? It will help me to understand it better. Thanks!

**Comment by Heartsky** [comment]
I have a list,  a hash. I store some data in both of them.
first I click to view detail a field in hash , app show error -> ok show error for this field
then I close the pop up error  and  open detail of a key in my list. if my data in list error, please show their error. but you show error of the other key. this is basic test for an app
