### ISSUE TITLE
Any action starts new connection. Old connections remain active.

### ISSUE THREAD

**Issue by varemel** [redis/RedisDesktopManager#5059]
Thanks for neat and useful tool. Really appreceate it.

**Describe the bug**
Any action start new connection. Old connections remain active.
After some time number of connections from RDM to Redis is more than 200.

**To Reproduce**
1. Open RDM
2. Unfold db0
3. Refresh db0 keys (icon "Reload keys in Database") or click different keys in database
4. Check Log  (icon on top right). Every action is accompanied with new connection command (Connection: 192.168.1.200 > connected".

**Expected behavior**
I understand that when you subscribe you need to have separate connection to listen for events. But new connection is established every read value operaton in db. Maybe I dont understand something, please explain.

**Screenshots**
![001254](https://user-images.githubusercontent.com/84812777/119565801-17bd2700-bdb3-11eb-91c8-46bda05d1fa4.png)
![001253](https://user-images.githubusercontent.com/84812777/119565806-1986ea80-bdb3-11eb-8fb8-d068bc947b24.png)
![001252](https://user-images.githubusercontent.com/84812777/119565815-1b50ae00-bdb3-11eb-971e-38856dcb962f.png)

**Environment (please complete the following information):**
Ubuntu 20.04.2
RDM version 2021.3+648029f9
Redis version=6.2.3

**Comment by uglide** [comment]
Hello @varemel 
Thank you for the detailed bug report. Fix for this issue was submitted in #5060 and will be available after merge in the Snapcraft

**Comment by varemel** [comment]
Thanks!
