### ISSUE TITLE
編譯出現這個問題的

### ISSUE THREAD

**Issue by kuustudio** [redis/RedisDesktopManager#5063]
16:52:10: Running steps for project rdm...
16:52:10: Configuration unchanged, skipping qmake step.
16:52:10: Starting: "F:\Qt\Tools\QtCreator\bin\jom.exe" 
	F:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DRDM_VERSION=\"2021.3.0-dev\" -DENABLE_EXTERNAL_FORMATTERS -DPYOTHERSIDE_VERSION=\"1.5.8\" -DNDEBUG -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I..\src -I. -I..\3rdparty\qredisclient\src -I..\3rdparty\qredisclient\3rdparty -I..\3rdparty\qredisclient\3rdparty\asyncfuture -IC:\Python37-x64\include -I..\3rdparty\pyotherside\src -I..\3rdparty\lz4\lib -I..\3rdparty\zlib-msvc14-x64.1.2.11.7795\build\native\include -I..\src -I..\src\modules -I./../bin/windows/debug/ui/ -IF:\Qt\5.15.0\msvc2019_64\include -IF:\Qt\5.15.0\msvc2019_64\include\QtQuickWidgets -IF:\Qt\5.15.0\msvc2019_64\include\QtCharts -IF:\Qt\5.15.0\msvc2019_64\include\QtSvg -IF:\Qt\5.15.0\msvc2019_64\include\QtWidgets -IF:\Qt\5.15.0\msvc2019_64\include\QtQuick -IF:\Qt\5.15.0\msvc2019_64\include\QtGui -IF:\Qt\5.15.0\msvc2019_64\include\QtANGLE -IF:\Qt\5.15.0\msvc2019_64\include\QtQmlModels -IF:\Qt\5.15.0\msvc2019_64\include\QtQml -IF:\Qt\5.15.0\msvc2019_64\include\QtNetwork -IF:\Qt\5.15.0\msvc2019_64\include\QtConcurrent -IF:\Qt\5.15.0\msvc2019_64\include\QtCore -I..\bin\windows\release\obj -I/include -IF:\Qt\5.15.0\msvc2019_64\mkspecs\win32-msvc -Fo..\bin\windows\release\obj\ @C:\Users\Bear\AppData\Local\Temp\qpython_worker.obj.13472.594.jom
qpython_worker.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(49): error C2589: “long”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(49): error C2062: 意外的类型“long” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(51): error C2589: “unsigned”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(51): error C2062: 意外的类型“__int64” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(83): error C2589: “long”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(83): error C2062: 意外的类型“long” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(85): error C2589: “unsigned”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(85): error C2062: 意外的类型“__int64” 
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DRDM_VERSION=\"2021.3.0-dev\" -DENABLE_EXTERNAL_FORMATTERS -DPYOTHERSIDE_VERSION=\"1.5.8\" -DNDEBUG -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I..\src -I. -I..\3rdparty\qredisclient\src -I..\3rdparty\qredisclient\3rdparty -I..\3rdparty\qredisclient\3rdparty\asyncfuture -IC:\Python37-x64\include -I..\3rdparty\pyotherside\src -I..\3rdparty\lz4\lib -I..\3rdparty\zlib-msvc14-x64.1.2.11.7795\build\native\include -I..\src -I..\src\modules -I./../bin/windows/debug/ui/ -IF:\Qt\5.15.0\msvc2019_64\include -IF:\Qt\5.15.0\msvc2019_64\include\QtQuickWidgets -IF:\Qt\5.15.0\msvc2019_64\include\QtCharts -IF:\Qt\5.15.0\msvc2019_64\include\QtSvg -IF:\Qt\5.15.0\msvc2019_64\include\QtWidgets -IF:\Qt\5.15.0\msvc2019_64\include\QtQuick -IF:\Qt\5.15.0\msvc2019_64\include\QtGui -IF:\Qt\5.15.0\msvc2019_64\include\QtANGLE -IF:\Qt\5.15.0\msvc2019_64\include\QtQmlModels -IF:\Qt\5.15.0\msvc2019_64\include\QtQml -IF:\Qt\5.15.0\msvc2019_64\include\QtNetwork -IF:\Qt\5.15.0\msvc2019_64\include\QtConcurrent -IF:\Qt\5.15.0\msvc2019_64\include\QtCore -I..\bin\windows\release\obj -I/include -IF:\Qt\5.15.0\msvc2019_64\mkspecs\win32-msvc -Fo..\bin\windows\release\obj\ @C:\Users\Bear\AppData\Local\Temp\pyobject_ref.obj.13472.625.jom
pyobject_ref.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(49): error C2589: “long”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(49): error C2062: 意外的类型“long” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(51): error C2589: “unsigned”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(51): error C2062: 意外的类型“__int64” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(83): error C2589: “long”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(83): error C2062: 意外的类型“long” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(85): error C2589: “unsigned”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(85): error C2062: 意外的类型“__int64” 
	cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DRDM_VERSION=\"2021.3.0-dev\" -DENABLE_EXTERNAL_FORMATTERS -DPYOTHERSIDE_VERSION=\"1.5.8\" -DNDEBUG -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I..\src -I. -I..\3rdparty\qredisclient\src -I..\3rdparty\qredisclient\3rdparty -I..\3rdparty\qredisclient\3rdparty\asyncfuture -IC:\Python37-x64\include -I..\3rdparty\pyotherside\src -I..\3rdparty\lz4\lib -I..\3rdparty\zlib-msvc14-x64.1.2.11.7795\build\native\include -I..\src -I..\src\modules -I./../bin/windows/debug/ui/ -IF:\Qt\5.15.0\msvc2019_64\include -IF:\Qt\5.15.0\msvc2019_64\include\QtQuickWidgets -IF:\Qt\5.15.0\msvc2019_64\include\QtCharts -IF:\Qt\5.15.0\msvc2019_64\include\QtSvg -IF:\Qt\5.15.0\msvc2019_64\include\QtWidgets -IF:\Qt\5.15.0\msvc2019_64\include\QtQuick -IF:\Qt\5.15.0\msvc2019_64\include\QtGui -IF:\Qt\5.15.0\msvc2019_64\include\QtANGLE -IF:\Qt\5.15.0\msvc2019_64\include\QtQmlModels -IF:\Qt\5.15.0\msvc2019_64\include\QtQml -IF:\Qt\5.15.0\msvc2019_64\include\QtNetwork -IF:\Qt\5.15.0\msvc2019_64\include\QtConcurrent -IF:\Qt\5.15.0\msvc2019_64\include\QtCore -I..\bin\windows\release\obj -I/include -IF:\Qt\5.15.0\msvc2019_64\mkspecs\win32-msvc -Fo..\bin\windows\release\obj\ @C:\Users\Bear\AppData\Local\Temp\qpython_priv.obj.13472.609.jom
qpython_priv.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(49): error C2589: “long”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(49): error C2062: 意外的类型“long” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(51): error C2589: “unsigned”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(51): error C2062: 意外的类型“__int64” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(83): error C2589: “long”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(83): error C2062: 意外的类型“long” 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(85): error C2589: “unsigned”:“::”右边的非法标记
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\cstdint(85): error C2062: 意外的类型“__int64” 
jom: G:\GithubSource\RedisDesktopManager\build-rdm-Desktop_Qt_5_15_0_MSVC2019_64bit-Release\Makefile.Release [..\bin\windows\release\obj\qpython_worker.obj] Error 2
jom: G:\GithubSource\RedisDesktopManager\build-rdm-Desktop_Qt_5_15_0_MSVC2019_64bit-Release\Makefile.Release [..\bin\windows\release\obj\qpython_priv.obj] Error 2
jom: G:\GithubSource\RedisDesktopManager\build-rdm-Desktop_Qt_5_15_0_MSVC2019_64bit-Release\Makefile.Release [..\bin\windows\release\obj\pyobject_ref.obj] Error 2
jom: G:\GithubSource\RedisDesktopManager\build-rdm-Desktop_Qt_5_15_0_MSVC2019_64bit-Release\Makefile [release] Error 2
16:52:13: The process "F:\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project rdm (kit: Desktop Qt 5.15.0 MSVC2019 64bit)
When executing step "Make"
16:52:13: Elapsed time: 00:03.

**Comment by uglide** [comment]
It's not clear why your MSVC cannot compile Python/PyOtherSide from this log

**Comment by kuustudio** [comment]
I found the problem, because the local environment stdint.h file I modified, resulting in compilation errors
