### ISSUE TITLE
RDM win10 unable to start

### ISSUE THREAD

**Issue by qinyudong89** [redis/RedisDesktopManager#5065]
RDM The startup report “cannot save the settings file”

**Comment by uglide** [comment]
@qinyudong89 Hello,
Which version of RDM do you use? (compiled from source code, Microsoft Store, Subscription)

**Comment by qinyudong89** [comment]
windows rdm-2021.4.352.exe

**Comment by uglide** [comment]
This error message means that RDM cannot write to your user directory for some reason. You can try to specify custom directory via a shortcut by adding command-line argument to rdm.exe: `--settings-dir C:\example`
