### ISSUE TITLE
can't use SSH Tunnel 

### ISSUE THREAD

**Issue by amoyiki** [redis/RedisDesktopManager#5073]
**Describe the bug**
can't use SSH Tunnel 
OpenSSH_8.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
![](http://img.amoyiki.com/error/001.png)
** /var/log/secure **
![](http://img.amoyiki.com/error/002.png)
Jul  3 10:50:46 amoyiki sshd[3261]: Connection closed by 120.36.254.111 port 40940 [preauth]
Jul  3 10:50:46 amoyiki sshd[3263]: Accepted publickey for root from 120.36.254.111 port 40948 ssh2: RSA SHA256:XXXXXXXXXX
Jul  3 10:50:46 amoyiki sshd[3263]: pam_unix(sshd:session): session opened for user root by (uid=0)
Jul  3 10:50:46 amoyiki sshd[3263]: error: server_request_direct_tcpip: invalid target port
Jul  3 10:50:51 amoyiki sshd[3263]: error: server_request_direct_tcpip: invalid target port
Jul  3 10:50:56 amoyiki sshd[3263]: error: server_request_direct_tcpip: invalid target port
Jul  3 10:51:01 amoyiki sshd[3263]: error: server_request_direct_tcpip: invalid target port
Jul  3 10:51:06 amoyiki sshd[3263]: error: server_request_direct_tcpip: invalid target port
Jul  3 10:51:11 amoyiki sshd[3263]: error: server_request_direct_tcpip: invalid target port

**Comment by amoyiki** [comment]
bug use Another Redis DeskTop Manager can access it
![](http://img.amoyiki.com/error/003.png)
**log**
Jul  3 10:56:33 amoyiki sshd[4726]: Postponed publickey for root from 120.36.254.111 port 39939 ssh2 [preauth]
Jul  3 10:56:33 amoyiki sshd[4726]: Accepted publickey for root from 120.36.254.111 port 39939 ssh2: RSA SHA256:CewbW0Uckzb7avkf3ZPMXG9HRUn9gnpHeKldZTSBuRs
Jul  3 10:56:33 amoyiki sshd[4726]: pam_unix(sshd:session): session opened for user root by (uid=0)

**Comment by uglide** [comment]
@amoyiki You are using outdated RDM version, please upgrade.
