### ISSUE TITLE
AWS ElastiCache connection does not work through SSH tunnel

### ISSUE THREAD

**Issue by frankiejarrett** [redis/RedisDesktopManager#5081]
**Describe the bug**
According to [the docs](https://docs.rdm.dev/en/latest/quick-start/) AWS ElastiCache is supposed to work through an SSH tunnel, but it does not. My EC2 instance is working and I have verified that this exact same configuration works on [TablePlus](https://tableplus.com/) but not RDM.

**To Reproduce**
1. Create a new connection with an ElastiCache hostname
2. Enter SSH tunnel host/user and select SSH key
3. Check the "Enable TLS-over-SSH" option as the docs instruct
4. Will not connect

**Expected behavior**
I expect to be able to connect via SSH tunnel.

**Screenshots**
<img width="639" alt="Screen Shot 2021-07-10 at 3 31 34 PM" src="https://user-images.githubusercontent.com/522158/125175773-edbd9980-e193-11eb-9c23-da0b5842b349.png">

**Environment (please complete the following information):**
 - OS & version: macOS Big Sur 11.4
 - Redis-Server version: 5.0.5

**Additional context**
None

**Comment by uglide** [comment]
@fjarrett Please provide a screenshot of errors in Log drawer in RDM (button at the top right corner of main window)

**Comment by frankiejarrett** [comment]
@uglide here is the log output:

```
Connection: Connecting to SSH host...
Connection: SSH tunnel established. Connecting to redis-server...
Connection: Disconnect on error: SSH connection established, but encrypted connection to redis failed
```

**Comment by frankiejarrett** [comment]
@uglide I just tried again this time without `Enable TLS-over-SSH` checked and the connection worked. Strange, I thought I tried that last week, but I guess not.

**Comment by uglide** [comment]
@fjarrett if I understood correctly your instance doesn't have TLS enabled that's why your connection failed.
