### ISSUE TITLE
Microsoft Store cannot receive updates.

### ISSUE THREAD

**Issue by rawvoid** [redis/RedisDesktopManager#5084]
**Describe the bug**

The Microsoft Store cannot receive updates, the last version of the `RDM` version is `2021.4`

**To Reproduce**

**Expected behavior**

When a new version is released, it should be published to the Microsoft Store.

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: Windows 10 pro 20H2
 - Redis-Server version: 6.0

**Additional context**

**Comment by uglide** [comment]
Store versions are released with delays due to Store reviews and additional testing. Microsoft Store update will be published on the next week.

**Comment by aomsweet** [comment]
Hi. @uglide

**Comment by rawvoid** [comment]
Hi. @uglide 

I still can't get updates in the Microsoft Store. The current version of RDM is 2021.4.

**Comment by uglide** [comment]
@aomsweet sorry for the delays but Microsoft Store has issues with uploading/beta channels for 2 weeks. We also suffer from not being able to upload/test RDM releases to the beta channel on MStore. Maybe it's related to undergoing Win11 release. Anyway, I hope that 2021.7.79 will be available soon on MStore. I will keep you posted.

**Comment by rawvoid** [comment]
@uglide  thanks for your reply. I'm looking forward.

**Comment by uglide** [comment]
@aomsweet 2021.7.79 should be available for you in MStore already.

**Comment by rawvoid** [comment]
@uglide Thank you, it has been upgraded.

**Comment by rawvoid** [comment]
Hi, @uglide   2021.8 was released for more than a week, but the Microsoft Store cannot get the update.  Thanks.

**Comment by uglide** [comment]
Store version updates are usually delayed for 1-2 weeks due to additional testing and translations updates.

**Comment by uglide** [comment]
@aomsweet 2021.8 is already available in MS Store

**Comment by rawvoid** [comment]
Hi, @uglide  Thank you very much. ☕️

**Comment by rawvoid** [comment]
Hi, @uglide 
I'm sorry, I can't update to 2022.3 on the Microsoft Store. Did you forget to update 😂? Thanks.

**Comment by uglide** [comment]
Some minor regression was found in 2022.3 that's why release to MS Store is delayed. It will be available in a couple of days.

**Comment by rawvoid** [comment]
@uglide I see. Thanks for your reply.
