### ISSUE TITLE
Duplicated databases in the list

### ISSUE THREAD

**Issue by Bec-k** [redis/RedisDesktopManager#5086]
Version is in header of app:
![image](https://user-images.githubusercontent.com/65600131/126120336-7b552ef6-6e30-48c4-8348-d27cedba9d1a.png)

**Comment by uglide** [comment]
Hello,

Please provide steps to reproduce and more information about your connection (SSH tunnel, TLS, etc)

**Comment by uglide** [comment]
Feel free to reopen this issue with more details which will help to reproduce the issue.
