### ISSUE TITLE
No response when clicking rdm.exe, Redis Desktop Manager cannot be started

### ISSUE THREAD

**Issue by Surrin1999** [redis/RedisDesktopManager#5096]
**Describe the bug**
No response when clicking rdm.exe, Redis Desktop Manager cannot be started

**I have installed the VC++2015-2019 environment** according to the [guide](https://docs.rdm.dev/en/latest/install/), and the installation package is downloaded from https://rdm.dev/subscriptions
But after the installation is complete, there is no response after clicking rdm.exe, and Redis Desktop Manager cannot be started

**Screenshots**
![image](https://user-images.githubusercontent.com/37960540/128678251-355204c8-b4df-47ee-beb7-f1976578023d.png)
![No response](https://user-images.githubusercontent.com/37960540/128678703-e91188c8-6936-432c-bceb-0d2c06cbc2cf.gif)

**Environment (please complete the following information):**
 - OS & version: Windows 10 20H2
 - Redis-Server version : latest，download from https://rdm.dev/subscriptions

**Comment by uglide** [comment]
Hello, Please download https://docs.microsoft.com/en-us/sysinternals/downloads/procmon , collect the startup event log, and send it to igor@rdm.dev

Let me know if you have any questions on how to run ProcMon

Thanks!

**Comment by Surrin1999** [comment]
> Hello, Please download https://docs.microsoft.com/en-us/sysinternals/downloads/procmon , collect the startup event log, and send it to [igor@rdm.dev](mailto:igor@rdm.dev)
> 
> Let me know if you have any questions on how to run ProcMon
> 
> Thanks!

I have sent Logfile.pml to igor@rdm.dev, please check

**Comment by uglide** [comment]
Thanks for all the feedback. I didn't spot anything suspicious in your log file. Could you also run https://docs.microsoft.com/en-us/sysinternals/downloads/debugview and collect debug output from there and post it here?

**Comment by Surrin1999** [comment]
> Thanks for all the feedback. I didn't spot anything suspicious in your log file. Could you also run https://docs.microsoft.com/en-us/sysinternals/downloads/debugview and collect debug output from there and post it here?

Ok. Please check [No response.LOG](https://github.com/uglide/RedisDesktopManager/files/6953606/No.response.LOG)

**Comment by uglide** [comment]
@Surrin1999 looks like you have off-screen issue after disconnecting external monitor. Press Alt+Space and Move RDM window to you current screen or just maximize it

**Comment by Surrin1999** [comment]
> @Surrin1999 looks like you have off-screen issue after disconnecting external monitor. Press Alt+Space and Move RDM window to you current screen or just maximize it

Do you need a complete screenshot? Unfortunately, there is indeed no response....
![No response](https://user-images.githubusercontent.com/37960540/128692698-19e344cb-8004-4fa7-9e91-7e322ade0926.gif)

**Comment by uglide** [comment]
Does the RDM icon appear on the task bar?

**Comment by Surrin1999** [comment]
> Does the RDM icon appear on the task bar?

Sure
![image](https://user-images.githubusercontent.com/37960540/128693479-a9264955-06a5-45b8-b6d0-0fca7c7e3fce.png)

**Comment by uglide** [comment]
Please follow this advice https://github.com/uglide/RedisDesktopManager/issues/5096#issuecomment-895107361
No need to run it with admin rights.

To ensure that RDM off-screen window is active - click on it in the task bar after launch.

**Comment by Surrin1999** [comment]
> Please follow this advice [#5096 (comment)](https://github.com/uglide/RedisDesktopManager/issues/5096#issuecomment-895107361)
> No need to run it with admin rights.
> 
> To ensure that RDM off-screen window is active - click on it in the task bar after launch.

I sent the gif to igor@rdm.dev, cause github only can upload the file less than 10MB.

**Comment by Surrin1999** [comment]
> Does the RDM icon appear on the task bar?

I’m very sorry that I misunderstood what you meant. I have sent a new email, please check
![image](https://user-images.githubusercontent.com/37960540/128741334-d4278015-aec3-4a7b-981f-ef4ec49eaaae.png)

**Comment by aluujane** [comment]
> Please follow this advice [#5096 (comment)](https://github.com/uglide/RedisDesktopManager/issues/5096#issuecomment-895107361) No need to run it with admin rights.
> 
> To ensure that RDM off-screen window is active - click on it in the task bar after launch.

 I have the same problem.I have installed the VC++2015-2019 environment. But I found that I can open rdm2020.2 . None of the above versions can be run 
![微信截图_20211123202436](https://user-images.githubusercontent.com/51196793/143023626-96729321-0787-4cd3-bc81-8aba1ed1bfe8.png)

**Comment by uglide** [comment]
@aluujane Do you use official builds? Please download https://docs.microsoft.com/en-us/sysinternals/downloads/procmon , collect the startup event log, and send it to igor@rdm.dev

**Comment by aluujane** [comment]
> @aluujane Do you use official builds? Please download https://docs.microsoft.com/en-us/sysinternals/downloads/procmon , collect the startup event log, and send it to [igor@rdm.dev](mailto:igor@rdm.dev)

I have tried many versions, including the official version, which are the same.RDM2020.2 and below are normal. Mail sent, please check.

**Comment by uglide** [comment]
@Surrin1999 @aluujane Please try rdm-2021.9.390.exe from https://rdm.dev/subscriptions

**Comment by aluujane** [comment]
> @Surrin1999 @aluujane Please try rdm-2021.9.390.exe from https://rdm.dev/subscriptions

 I can't see rdm-2021.9.390.exe, only linux-2021.9

**Comment by uglide** [comment]
@aluujane should be visible now, if still not visible please switch language to English

**Comment by uglide** [comment]
@aluujane Could you share feedback after using the preview build?

**Comment by aluujane** [comment]
> Could you share feedback after using the preview build?

 I tried rdm-2021.9.390, but it still couldn't run.

**Comment by uglide** [comment]
@aluujane Do you have network mounted disks in explorer? Could you provide fresh log from ProcMon with rdm-2021.9.390 build?

**Comment by aluujane** [comment]
> @aluujane Do you have network mounted disks in explorer? Could you provide fresh log from ProcMon with rdm-2021.9.390 build?


I do not have a network disk, the mail has been sent to the mailbox, please check it.

**Comment by uglide** [comment]
I found that there is some unknown problem with RDM/RESP on old Intel CPU's like i7-2670QM
Unfortunately, I don't have enough time to investigate this problem further. I recommend trying to run RESP.app on another PC/Laptop.

**Comment by MihaxXx** [comment]
Just for the record, it looks like RESP is experirencing the same problem on Intel Xeon E3-1270v2, which in one generation newer than i7-2670QM, but crash happens after opening some keys. [Intel® Software Development Emulator](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html) might be useful here, you can run RESP using it `sde.exe -hsw -- resp.exe` but anyway it results in significant slowdown.
