### ISSUE TITLE
Can't save value after edit

### ISSUE THREAD

**Issue by anton-reviakin** [redis/RedisDesktopManager#5098]
**Describe the bug**

**To Reproduce**
1. Open any key and edit value
2. Click on Save or ctrl+s
4. and nothing...

**Environment (please complete the following information):**
 - OS & version: Windows 10 19042.1165
 - Redis-Server version 5.0.3

**Comment by uglide** [comment]
Please provide more info:
- RDM version
- key type
- size of the value (aprox)
- tunneling type if any (SSH/TLS/TLS-over-SSH)

**Comment by uglide** [comment]
Feel free to reopen this issue with more details which will help to reproduce the issue.
