### ISSUE TITLE
服务器信息界面显示不全

### ISSUE THREAD

**Issue by yinhuan1218** [redis/RedisDesktopManager#5099]
![image](https://user-images.githubusercontent.com/67767897/130037870-8eac8131-f136-4ee2-87de-a9d09b886eaf.png)

**Comment by uglide** [comment]
Thanks for the feedback!

**Comment by yinhuan1218** [comment]
哪个版本会上线这个修复

**Comment by uglide** [comment]
@maguoliang888 Do you use RDM from rdm.dev or from Microsoft Store?

**Comment by yinhuan1218** [comment]
rdm.dev

**Comment by uglide** [comment]
@maguoliang888 please download rdm-2021.8.367.exe preview build from https://rdm.dev/subscriptions
