### ISSUE TITLE
Copy on Terminal

### ISSUE THREAD

**Issue by Eleisonchr** [redis/RedisDesktopManager#5100]
Why does the Copy function on terminal board not work? Sometimes I need to get subscribe results from this screen and I can't.
As there is no text wrap and there is also no cursor or horizontal scroll bar, it is difficult to analyze the content.
Could you implement this in future releases?

**Comment by uglide** [comment]
@Eleisonchr Please provide more info about the RDM version and OS name/family and version.

**Comment by Eleisonchr** [comment]
Hi. Thanks for replying.
Follow the requested data:

RDM 2021.7.79
OS Windows 10  Pro - 19042.1165

**Comment by Eleisonchr** [comment]
I am can't copy yet; 
Posting image to you see about I´m say.
![Copy Error](https://user-images.githubusercontent.com/3289070/151176119-b7f29bda-5092-437c-ba75-340100f534af.png)
