### ISSUE TITLE
能不能保存账号密码，或者使用key的方式？在中国如果不翻墙登录不上

### ISSUE THREAD

**Issue by longqioo** [redis/RedisDesktopManager#5103]
能不能保存账号密码，或者使用key的方式？在中国如果不翻墙登录不上
每次登录很麻烦，能不能多重的登陆api接口或者使用秘钥的方式

**Comment by uglide** [comment]
Hello,

Sorry for the inconvenience. I recommend switching to Microsoft/Apple Store versions of RDM which is fully offline.
Please contact me by email igor@rdm.dev if you want to get a refund for the purchase made on our website.
