### ISSUE TITLE
ReJSON encoding issue

### ISSUE THREAD

**Issue by steven89** [redis/RedisDesktopManager#5106]
**Is your feature request related to a problem? Please describe.**
There is a known ReJSON encoding issue when retrieving data via `JSON.GET` command
https://github.com/RedisJSON/RedisJSON/issues/98

This issue is fixed by putting the option `noescape` after the key e.g. `JSON.GET my-key noescape`

Currently when using RDM with ReJSON and JSON view you get this (*plain text view also has the issue*):
<img width="240" alt="Screen Shot 2021-09-05 at 7 36 19 PM" src="https://user-images.githubusercontent.com/609271/132136159-f4ce528d-6225-4f9d-bdeb-565a39091ad4.png">

**Describe the solution you'd like**
- Either have an option in the settings to use `noescape` when retrieving ReJSON value
- Or add an option in the value viewer to turn on `noescape`

**Comment by uglide** [comment]
@steven89 thanks for the hint. Will be added in the next release.
