### ISSUE TITLE
Wrong value deleted from SET if it was paginated in UI

### ISSUE THREAD

**Issue by sergey-v9** [redis/RedisDesktopManager#5108]
**Describe the bug**
similar to #5066 
If you paginate the SET in the UI to page 2 and then hit "Delete Row" button it deletes wrong value from the SET (from page 1).

**To Reproduce**
1. Fill the SET with values from 0 to 120.
2. Open that SET in RDM; Navigate to page 2; Click on the row with value "104"; Hit the "Delete Row" button
3. Navigate to page 1;
4. See the row with value "4" was deleted.

**Expected behavior**
Row with value "104" should be deleted; row with value "4" should exist.

**Screenshots**
- ![image](https://user-images.githubusercontent.com/4435150/132400177-b7a17448-07af-4300-9e6a-a52dcbb1dd49.png)

- ![image](https://user-images.githubusercontent.com/4435150/132400193-265fd016-c398-4a8a-aa17-cf1ad68bcf8b.png)

**Environment:**
RDM: 2021.7.0
Redis version: KeyDB 6.0.13
OS: Windows 10 21H1 19043.1165

**Comment by uglide** [comment]
@sergey-v9 Thanks for the bug report. This stupid mistake was fixed and the fix will be released as part of 2021.8 release
