### ISSUE TITLE
missing file VCRUNTIME140.DLL

### ISSUE THREAD

**Issue by devil-kobe** [redis/RedisDesktopManager#5110]
When i installed the rdm.exe,  missing file VCRUNTIME140.DLL
![image](https://user-images.githubusercontent.com/68525607/132479052-776a422d-584b-408a-8263-336c4cbc799e.png)

**Comment by uglide** [comment]
@devil-kobe Please specify which version of RDM do you use

**Comment by uglide** [comment]
Feel free to reopen this issue with more details which will help to reproduce the issue.
