### ISSUE TITLE
403配置不生效，求大佬帮忙看一看

### ISSUE THREAD

**Issue by mwangli** [redis/RedisDesktopManager#5111]
用test用户登录，访问没有权限的接口，接口报错，返回状态码400
![image](https://user-images.githubusercontent.com/48406369/132951652-cfca7ebd-8f7d-4fd8-850d-c36447954cbf.png)
自定义处理器中的DEBUG代码也没有触发，直接报异常AccessDeniedException
![image](https://user-images.githubusercontent.com/48406369/132951764-42b2e7b4-0dfe-428a-b605-0047833be94e.png)

**Comment by uglide** [comment]
@mwangli How this is related to RDM?
