### ISSUE TITLE
双击db2库的键时  会闪退

### ISSUE THREAD

**Issue by Wananme** [redis/RedisDesktopManager#5112]
如下图，我想刷新下dict:sys_dict， 双击以后整个软件就闪退了，好几次了
![image](https://user-images.githubusercontent.com/45476748/133391213-bfcc2eda-20e2-4913-b82a-c267f788cd42.png)

**Comment by uglide** [comment]
@Wananme Please specify RDM version.

**Comment by Wananme** [comment]
姓名：林文炅
电话：15359055909
***@***.***
 
发件人： Igor Malinovskiy
发送时间： 2021-09-27 21:34
收件人： uglide/RedisDesktopManager
抄送： lin wen jiong; Mention
主题： Re: [uglide/RedisDesktopManager] 双击db2库的键时 会闪退 (#5112)
@Wananme Please specify RDM version.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by uglide** [comment]
Feel free to reopen this issue with more details which will help to reproduce the issue.
