### ISSUE TITLE
Support Zstd compression/decompression

### ISSUE THREAD

**Issue by rawvoid** [redis/RedisDesktopManager#5114]
**Describe the solution you'd like**

Hi.  @uglide 

Zstd seems to have a good performance in speed and compression ratio, so can RDM provide automatic decompression support for this?

[https://github.com/facebook/zstd](https://github.com/facebook/zstd)
![image](https://user-images.githubusercontent.com/70388114/133870450-45994ac6-8d00-44e8-a411-75eb8537082d.png)

**Comment by uglide** [comment]
@aomsweet thanks for the suggestion. Will be added in 2021.9

**Comment by uglide** [comment]
Will be released as part of 2021.9 release

**Comment by rawvoid** [comment]
Great! Thank you very much.
