### ISSUE TITLE
Big Sur 11.6

### ISSUE THREAD

**Issue by productdevbook** [redis/RedisDesktopManager#5115]
![CleanShot 2021-09-20 at 15 27 16](https://user-images.githubusercontent.com/38668796/134002149-de2cfd89-86b1-4c6e-8e19-986ec1b49e85.png)

**Comment by uglide** [comment]
@productfrontenddeveloper Please provide more information about RDM and your OS:
- RDM version
- RDM installation source (DMG, AppStore, Build from source)
- CPU Architecture (M1/Intel x86)

**Comment by productdevbook** [comment]
2021.7
DMG
Intel x86

**Comment by uglide** [comment]
@productfrontenddeveloper please specify full RDM version like 2021.7.X

**Comment by productdevbook** [comment]
https://github.com/uglide/RedisDesktopManager/releases/tag/2021.7

**Comment by uglide** [comment]
@uglide Tag on GitHub doesn't specify the build number. Is it 3rdparty DMG build or build downloaded from rdm.dev?

I need to know the exact build number to be able to reproduce the issue.

**Comment by productdevbook** [comment]
rdm-2021.99.0

**Comment by uglide** [comment]
Looks like it is a 3rd party build and most likely you cannot run it because it's not signed.

**Comment by productdevbook** [comment]
I'll buy it from the App Store, but can you give me a discount coupon because I'm a student?

**Comment by uglide** [comment]
@productfrontenddeveloper I believe that App Store doesn't have discount codes but you can purchase RDM Annual Subscription from our website https://rdm.dev with 30% discount code `HELLO_RDM`
