### ISSUE TITLE
View As : Snappy

### ISSUE THREAD

**Issue by uriah-chs** [redis/RedisDesktopManager#5117]
**Is your feature request related to a problem? Please describe.**
We gzip compress data we store for values.  I can't view the data natively using any of the built in viewers.

**Describe the solution you'd like**
A good solution would have an option under the value viewer under the "View As" drop down for "gzip" that, when selected, would attempt to decompress the value to show it's plain text version.  Ideally if the content wasn't actually gzip data it would display a message about the conversion failure and then show the plain text version.

**Comment by uglide** [comment]
RDM supports GZIP but your data should have "magic  header" `1f 8b` for automatic decompression https://github.com/uglide/RedisDesktopManager/blob/2021/src/app/qcompress.cpp#L17

Could you please provide a sample of data or specify which programming language and/or library do you use for data compression/serialization?

**Comment by uriah-chs** [comment]
Ah, thank you, that makes sense.  Upon further research, it appears the developer isn't using gzip at all, they are actually using snappy compression (http://google.github.io/snappy/) via a python library (https://pypi.org/project/python-snappy/).  Apologies for the misinformation.  Is there anything that can be done to support snappy compression?

**Comment by uglide** [comment]
More compression algorithms will be added to RDM in 2021.9 (ETA is Oct 2021)

**Comment by uriah-chs** [comment]
That's great!  Do you know if snappy is in the currently targeted list?

**Comment by uglide** [comment]
Yes, it is

**Comment by uglide** [comment]
@uriah-chs Hi, Could you specify which OS do you use? I will prepare a preview build with Snappy decompression for you to beta test.

**Comment by uglide** [comment]
Snappy support was added and will be released as part of 2021.9

**Comment by Srinu3366** [comment]
We are using snappy with windows OS and are more than happy to beta test it.
