### ISSUE TITLE
Dialog UI Bug

### ISSUE THREAD

**Issue by 18853477039** [redis/RedisDesktopManager#5120]
**Describe the bug**
Dialog UI error when delete dir

**To Reproduce**
1. Go to 'anythere'
2. Click on 'dir->delete namespace->delete key（in dialog）'
3. See error

**Expected behavior**
right dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/45444079/136732131-4d462b0f-fab4-424d-985d-14021efa2b46.png)

**Environment (please complete the following information):**
 - OS & version: [ubuntu20.04]
 - Redis-Server version [2021.7+8875ef52]

**Additional context**

**Comment by uglide** [comment]
This issue was fixed in 2021.9
