### ISSUE TITLE
how to filter the data by some letters

### ISSUE THREAD

**Issue by edetime** [redis/RedisDesktopManager#5127]
i cann't search data by my key words like  '%abc% or abc* '

**Comment by uglide** [comment]
https://docs.rdm.dev/en/latest/lg-keyspaces/#use-specific-scan-filter-to-reduce-loaded-amount-of-keys

**Comment by edetime** [comment]
ok,thanks very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uglide/RedisDesktopManager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uglide/RedisDesktopManager] how to filter the data by some letters (Issue #5127)





 
https://docs.rdm.dev/en/latest/lg-keyspaces/#use-specific-scan-filter-to-reduce-loaded-amount-of-keys
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
