### ISSUE TITLE
分析内存占用显示问题

### ISSUE THREAD

**Issue by gwzy** [redis/RedisDesktopManager#5129]
分析内存占用时，显示占用内存大小时会显示成负值，形如-2.00847e+09 bytes

**Comment by uglide** [comment]
@gwzy Please provide a screenshot for a better understanding of the issue. Thanks!

**Comment by gwzy** [comment]
![image](https://user-images.githubusercontent.com/1751076/145317568-9c228417-82d0-42cc-aea9-27dc22a3a4e4.png)

**Comment by gwzy** [comment]
![image](https://user-images.githubusercontent.com/1751076/145317790-93cd40aa-f0e9-4118-a066-c34790f4986b.png)

**Comment by uglide** [comment]
Fixed and will be released as part of the next release.
