### ISSUE TITLE
Windows: Not all window title bars are dark in dark mode

### ISSUE THREAD

**Issue by yinhuan1218** [redis/RedisDesktopManager#5133]
**Is your feature request related to a problem? Please describe.**
windows深色模式下，标题栏没有变成深色

**Describe the solution you'd like**
windows深色模式下，标题栏变成深色

**Comment by uglide** [comment]
ATM Windows API doesn't provide a clean way to deal with this problem. You can manually change title bar color in Windows Theme settings to workaround this problem.

**Comment by HEEKDragonOne** [comment]
mac 怎么改变背景色啊

**Comment by yinhuan1218** [comment]
1.2022.0的版本的标题栏也可以变成深色了，非常感谢，我会继续支持rdm的
![image](https://user-images.githubusercontent.com/67767897/156124967-fec4f5a1-9eef-4d65-a8d0-796272599411.png)


2.如果可以的话，能否把设置界面的标题栏也变成深色😄
![image](https://user-images.githubusercontent.com/67767897/156125024-c5100acc-9b89-4a88-aa8b-64c6b43f4d1f.png)

**Comment by uglide** [comment]
Currently, I use a dirty hack but I will look at how it can be solved globally for all windows.

**Comment by yinhuan1218** [comment]
ok

**Comment by yinhuan1218** [comment]
发现了一个新的地方也需要适应暗色模式
![image](https://user-images.githubusercontent.com/67767897/165283648-653ec55a-d2bc-48fc-b5af-6a7050367c21.png)
