### ISSUE TITLE
MAC OS X Update setup instructions

### ISSUE THREAD

**Issue by causlayer** [redis/RedisDesktopManager#5138]
cd 3rdparty/lz4/build/cmake
cmake -DLZ4_BUNDLED_MODE=ON  .
make
cd 3rdparty/brotli
cmake -DBUILD_SHARED_LIBS=OFF
make
cd 3rdparty/snappy
cmake -DHAVE_LIBLZO2=0 -DHAVE_LIBLZ4=0 && make
cd 3rdparty/zstd/build/cmake
cmake ./ && make

I don’t know if I set it right, but it can be used normally

**Comment by uglide** [comment]
Create PR with update to the docs
