### ISSUE TITLE
Sending command to master in replication handshake: -Writing to master: Unknown error

### ISSUE THREAD

**Issue by iM7ss** [redis/RedisDesktopManager#5139]
Dear, 

I'm facing an issue where the service suddenly hangs (It works perfectly fine but on random occasions it hangs) 
Note that I'm connecting to localhost ,  Windows server 
with the error: 
"Sending command to master in replication handshake: -Writing to master: Unknown error"

this happens randomly and the only way to solve it is to restart the service.
Looking forward hearing back from you, 

Thanks,
Mahmood

**Comment by uglide** [comment]
@iM7ss Please specify more information about your Redis server version, deployment scheme, etc

**Comment by uglide** [comment]
@iM7ss Looks like you have Redis issue as described here https://stackoverflow.com/questions/40274767/redis-slave-sending-command-to-master-in-replication-handshake-writing-to-ma

It's not related to RDM so I'm closing the issue.
