### ISSUE TITLE
Application fails to start on Ubuntu 21.10

### ISSUE THREAD

**Issue by mabzzz** [redis/RedisDesktopManager#5141]
Hello,

The application fails to start on Ubuntu 21.10 (Impish) and throws the following error:
```bash
$ env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/redis-desktop-manager_rdm.desktop /snap/bin/redis-desktop-manager.rdm
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
```

**Steps to reproduce the behavior:**
1. Install latest version available on Snap
```bash
$ sudo snap install redis-desktop-manager
redis-desktop-manager 2021.9.1+78f60248 from Igor Malinovskiy (uglide) installed
```
2. Check installed version
```bash
$ snap list redis-desktop-manager
Name                   Version            Rev  Tracking       Publisher  Notes
redis-desktop-manager  2021.9.1+78f60248  568  latest/stable  uglide     -
```
3. Try to run the application with desktop shortcut
=> Nothing happens
4. Extract exec command from desktop config file
```bash
$ cat /var/lib/snapd/desktop/applications/redis-desktop-manager_rdm.desktop | grep Exec
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/redis-desktop-manager_rdm.desktop /snap/bin/redis-desktop-manager.rdm
```
5. Try to run exec command
```bash
$ env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/redis-desktop-manager_rdm.desktop /snap/bin/redis-desktop-manager.rdm
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
```

**Environment:**
 - OS & version: Ubuntu 21.10 (Impish)
 - RDM version: 2021.9.1+78f60248 (rev 568)
 - Redis-Server version: N/A

**Comment by kuza** [comment]
Hi, there is the problem in Wayland session. I turn to X11, and RDM is working.

**Comment by uglide** [comment]
Hello @mabzzz 
Thanks for the bug report. Please use the Flathub version as a workaround https://flathub.org/apps/details/dev.rdm.RDM

I will post an update as soon as Snapcraft version will be fixed.

**Comment by mabzzz** [comment]
Thanks @uglide , indeed the Flathub version works fine. I'll switch back to the Snapcraft version once it will be fixed.

**Comment by triptips-top** [comment]
@uglide I also need Flathub version, but link expired.

**Comment by uglide** [comment]
@triptips-top  The app was renamed. Please use this link https://flathub.org/apps/details/app.resp.RESP

**Comment by uglide** [comment]
The fix was added to Snap and will be available soon in the edge channel.

**Comment by mabzzz** [comment]
Thank you @uglide
