### ISSUE TITLE
Crash when showing specific chars

### ISSUE THREAD

**Issue by Jerry-Shaw** [redis/RedisDesktopManager#5142]
**Describe the bug**
Crash when click on rows with specific chars like "12\xD4\xC2 07, 2021 3:43:44 \xCF\xC2\xCE\xE7". Don't know how it comes. From a game log.

**To Reproduce**
1. Select a list and lpush some data with some specific char
2. Click on on the row
3. Crashed

**Expected behavior**
Show the content below

**Screenshots**

![1638865050(1)](https://user-images.githubusercontent.com/13212198/144992835-ec973a63-f21a-4d2a-84c3-d2961b150b8f.jpg)
![1638865111(1)](https://user-images.githubusercontent.com/13212198/144992841-825377aa-27f7-45b6-acd4-6dcc6426ed5e.jpg)

**Environment (please complete the following information):**
 - Windows 11 Pro
 - Redis-Server version [5.0.14]
 - RDM version 2021.9

**Additional context**

**Comment by Jerry-Shaw** [comment]
data copied from console: 
12\xD4\xC2 07, 2021 3:43:44 \xCF\xC2\xCE\xE7 zombie.Lua.LuaManager RunLuaInternal\x0D\x0A

**Comment by uglide** [comment]
@Jerry-Shaw thanks for the bug report. I'm investigating the issue.

**Comment by uglide** [comment]
Could you please try preview build rdm-2021.9.394.exe?

**Comment by Jerry-Shaw** [comment]
Ah, I got "Internal Server Error" when click on renew subscription. How can I download the preview build version?

**Comment by uglide** [comment]
@Jerry-Shaw Fixed, please try again

**Comment by Jerry-Shaw** [comment]
@uglide Yup, it is fixed in 2021.9.394. Thanks.

**Comment by uglide** [comment]
@Jerry-Shaw Thanks for beta testing. Appreciate it.
