### ISSUE TITLE
Show string/number values (that are not JSON) automatically as Plain Text when viewing as JSON

### ISSUE THREAD

**Issue by ea167** [redis/RedisDesktopManager#5144]
As the viewer pane keeps the state ("View as..."), switching between keys that contain JSON or simple strings is tedious and require way too many clicks.
The problem is that the viewer does NOT display anything when viewing as JSON with non-json content.

It would be much more convenient to select "View as JSON", and when the content is not JSON-parsable, just display the raw value as plain text.

**Comment by uglide** [comment]
@ea167 thanks for the feedback
By the look of it, you are facing the problems which were fixed in 2021.9
2021.9 is currently in the beta testing stage and will be published the next week.

Could you specify which OS do you use?

**Comment by ea167** [comment]
Hello Igor,

First of all, congrats for your great work!

Here is my OS info:








Best,

--Eric

**Comment by uglide** [comment]
Unfortunately, GitHub doesn't upload images from the email replies. Could you attach it using web page?

**Comment by ea167** [comment]
Oops, sorry Igor! Let's try again:

<img width="239" alt="2021-12-10 at 10 29 AM" src="https://user-images.githubusercontent.com/571650/145625291-01180a95-8c46-4f05-a81f-d809278dc4f2.png">

<img width="227" alt="2021-12-10 at 10 42 AM" src="https://user-images.githubusercontent.com/571650/145625388-96f758bc-b76b-4713-a1df-b13a51a810b5.png">

**Comment by uglide** [comment]
@ea167 RDM 2021.9.227 was published in the Apple AppStore. Feel free to reopen this issue if you still experience the same issue with the new version.
