### ISSUE TITLE
Such junk software is also interesting to charge

### ISSUE THREAD

**Issue by gongzhx1998** [redis/RedisDesktopManager#5147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by gongzhx1998** [comment]
1、Frequent abnormal exit
2、Refresh no response

**Comment by uglide** [comment]
@gongzhx1998  Thanks for sharing your opinion but it doesn't help to make it any better 

Please describe in which cases/steps you are experiencing crashes, which OS do you use, and which RDM version you are currently using.

If you can provide a screencast with the recorded crash it would help a lot to reproduce and fix the problems.

**Comment by uglide** [comment]
*UPDATE:*

A major problem was found in underlying libraries which leads to random RDM crashes on Windows. Fix was published as part of the 2021.9 release on https://rdm.dev and will be published soon on MS Store.

@gongzhx1998 if you are on Windows please upgrade to 2021.9
