### ISSUE TITLE
When click on Analyze Used Memory - duplicate folder

### ISSUE THREAD

**Issue by LocalHeroPro** [redis/RedisDesktopManager#5148]
In normal order, `vendor_cache` is on bottom. After calculating size, it's show as duplicated on top.
![image](https://user-images.githubusercontent.com/42643563/145596105-0b51f173-84e7-4c28-beb2-a9b70b2fc602.png)

**Comment by uglide** [comment]
@LocalHeroPro  please specify which version of RDM do you use

**Comment by LocalHeroPro** [comment]
Version: 2021.9.1+78f60248

**Comment by uglide** [comment]
@LocalHeroPro thanks! Will try to reproduce

**Comment by uglide** [comment]
@LocalHeroPro You can enable "Show namespaced keys on top" in RDM settings to workaround this problem.

**Comment by LocalHeroPro** [comment]
![image](https://user-images.githubusercontent.com/42643563/146387962-11d34909-6eb4-4474-bb02-75433caf9483.png)
With enabled option what you mention.

**Comment by uglide** [comment]
The fix was merged and will be available soon on Flathub and Snapcraft edge channel. Please try the latest version and let me know if you still experience any issues.

Looking forward to your reply.
