### ISSUE TITLE
Updated icon for Big Sur & Monterey

### ISSUE THREAD

**Issue by qinxin0720** [redis/RedisDesktopManager#5149]
macOS Big Sur & Monterey is updating all the system icons with a rounded-rectangle shape and a front-facing perspective. Some 3rd party developers including Adobe, Microsoft etc. are converting their app icons to match up with these system icons as well.
![68747470733a2f2f646576656c6f7065722e6170706c652e636f6d2f64657369676e2f68756d616e2d696e746572666163652d67756964656c696e65732f6d61636f732f696d616765732f6d61696c2d70686f746f732d707265666572656e6365732d6269672d7375722e706e67](https://user-images.githubusercontent.com/28943828/145681092-8242ad34-2dbe-4061-9724-e3444bd50024.png)
![68747470733a2f2f646576656c6f7065722e6170706c652e636f6d2f64657369676e2f68756d616e2d696e746572666163652d67756964656c696e65732f6d61636f732f696d616765732f707265766965772d78636f64652d746578742d656469742d6269672d7375722e706e67](https://user-images.githubusercontent.com/28943828/145681095-44aab8a6-e87e-4e3f-be94-3d2959d0a4e0.png)
Could we get an updated icon that follows more closely to the rounded-rectangle shape with a front-facing perspective so that the icon style is consistent with others in Big Sur & Monterey? This will help RDM not to look out of place in the dock and Launchpad.

**Comment by uglide** [comment]
The icon was updated and this change will be released as part of 2022.1 release

**Comment by qinxin0720** [comment]
thanks
