### ISSUE TITLE
problem with auto fresh key 

### ISSUE THREAD

**Issue by Jack-bytes** [redis/RedisDesktopManager#5152]
My db just have one key. when I open auto fresh, the key's number is increasing continuously.  I downloaded the rmd in MStore. The version is latest;

![98e313a2642a722f5810eaaad91692c](https://user-images.githubusercontent.com/59460227/146501657-17a079d3-db44-49c4-9520-af68c1e99ce6.png)

**Comment by uglide** [comment]
Thank you for the bug report. Fix will be released soon. I will post an update here as soon as will be published in MS Store.
