### ISSUE TITLE
SSH-Tunnel via public key with Flatpak not working

### ISSUE THREAD

**Issue by ms-zlab** [redis/RedisDesktopManager#5153]
**Describe the bug**
The current flatpak has no access to the home directory.

**To Reproduce**
1. Go to 'https://flathub.org/apps/details/dev.rdm.RDM'
2. Click on 'install it'
3. Use Connection with SSH-Tunnel and Key-File
4. Try to Connect
5. See in the log: Connection: Connecting to SSH host...
Connection: Disconnect on error: SSH Connection error(Authentication Error): Unable to extract public key from private key file: Unable to open private key file

**Expected behavior**
The home directory can be accessed.

**Environment (please complete the following information):**
 - POP OS 20.04
 - Redis-Server version 6.0.5 (AWS)
 

**Additional context**
When i add to the run-command `--filesystem=home`, then the application has access to my keyfile and everything is working.
(final command is: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --filesystem=home --command=rdm dev.rdm.RDM`)
The access should be defined in the "Context section from the application metadata" (see: https://www.systutorials.com/docs/linux/man/1-flatpak-run/)

**Comment by uglide** [comment]
Hello, @ms-zlab
Thank you for the feedback. Could you clarify where do you store your ssh key? Is it default `$HOME/.ssh` location? I'm asking because access to the whole `$HOME` may be. considered as security/permissions flaw by many Linux users :)

I would appreciate it if you submit an actual fix to https://github.com/flathub/dev.rdm.RDM/blob/master/dev.rdm.RDM.json as PR.

Thank you!

**Comment by ms-zlab** [comment]
I stored my keys in `~/.ssh/id_rsa_*`.
I found this documentation: https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html?highlight=filesystem#filesystem-permissions
In the description they say, you could also use something like `--fileystem=home/.ssh:ro`, for security it will be better.

if i found time, i will try, look like flathub will use the finish-args for this part.

**Comment by yswtrue** [comment]
Same problem here, even though I use the pem content 
```
Connection: Disconnect on error: SSH Connection error(Authentication Error): Unable to extract public key from private key file: Unable to open private key file
```

**Comment by yswtrue** [comment]
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --filesystem=/home/yswtrue/.ssh:ro --command=resp app.resp.RESP
```
this command works for me

**Comment by thiagobraga** [comment]
Hi guys, could you help me? I'm trying to create a SSH tunnel to use with ElastiCache but I'm not being able to do that.

```
External: Can't load list of available formatters from extension server: O protocolo "" é desconhecido, 
Connection: Connecting to SSH host...
Connection: Disconnect on error: SSH Connection error(Authentication Error): Unable to extract public key from private key file: Unable to open private key file
```

The command I'm running:
```sh
flatpak run \
  --branch=stable \
  --arch=x86_64 \
  --filesystem=/home/thiago/.ssh:ro \
  --command=resp app.resp.RESP
```

My settings:
![image](https://user-images.githubusercontent.com/993684/181363047-fdaf56a8-8f1f-4d27-b9d4-0ce5202ac1a4.png)

RESP.app version 2022+1092fb7

Thanks

**Comment by uglide** [comment]
@thiagobraga You need to update RESP.app to 2022.4.2

**Comment by thiagobraga** [comment]
Hi, sorry for the long delay. Now I'm using RESP.app 2022.4.2 but the error is still there. I can connect to Redis server from bastion host, the same I'm using as tunnel. It's a PEM key, is there some problem in it?

![image](https://user-images.githubusercontent.com/993684/186770454-0bdc7b57-3f83-4287-aefd-09901bd2f84c.png)
![image](https://user-images.githubusercontent.com/993684/186770642-3d65b909-9018-413c-b9bf-2ab4682729d0.png)
![image](https://user-images.githubusercontent.com/993684/186770964-051b2e31-4fe8-46d7-aed8-6458abe12e6b.png)

---

@uglide Did you see my message? I'm still getting errors when connecting to Redis using a bastion host.

**Comment by uglide** [comment]
@thiagobraga please try to recreate connection from scratch or at least reselect private key.
