### ISSUE TITLE
can not use pickle protocol to show data in ui interface

### ISSUE THREAD

**Issue by calmzhu** [redis/RedisDesktopManager#5165]
**To Reproduce**

-  save a pickle serialized data to redis
- check it in rdm ui.

**Expected behavior**
show the value in pickle protocol

**Screenshots**
But now it always automatic jump to HEX protocol after choose pickle
![image](https://user-images.githubusercontent.com/10286576/147548521-f0f91a0a-f41d-43bd-a2d6-5c54180409c4.png)

And last  ,Which version of [pickle protocol](https://docs.python.org/zh-cn/3/library/pickle.html)is supported here
**Environment (please complete the following information):**
 - OS & version: [MacOS 12.1]
 - Redis-Server version [6.2.6]

**Comment by uglide** [comment]
Hello, @calmzhu 
RDM doesn't automatically try to decode pickle format but you should be able to select it from the formatters dropdown.
RDM uses python3.8/3.9 so it should recognize all protocol versions.
