### ISSUE TITLE
keep "view as" format

### ISSUE THREAD

**Issue by maidiries** [redis/RedisDesktopManager#5166]
Version before support this. When you choose a format to show a key content, for example JSON, this format is saved. Then when you open a new key content, application remember last choose and show key content with JOSN format.

Current version don't remember last format.

**To Reproduce**
1. Open any key content
2. Click on 'View as:' and choose some format
3. Go to another key content
4. Format showed with 'Plain text'

**Expected behavior**
Remember last choose for 'View as' on key contents

**Environment:**
 - OS & version: Windows 10
 - Redis-Server version 2021.10.103

**Comment by uglide** [comment]
Fixed in 2022.0
