### ISSUE TITLE
I like the former icon and application name

### ISSUE THREAD

**Issue by dolorain** [redis/RedisDesktopManager#5168]
Can we change them back?

**Comment by dolorain** [comment]
bcz for now its reallly sucks, and like a nuclear button
![image](https://user-images.githubusercontent.com/17894063/147806978-460a4b51-382c-4a86-b344-fbd487e34196.png)

**Comment by uglide** [comment]
Unfortunately, we are under pressure of different trademark holders, that's why all these renamings are happening. If you came up with a better name and domain which doesn't violate any trademark laws - let me now. I will be happy to find a better name.

**Comment by dolorain** [comment]
icon in ligth theme
![image](https://user-images.githubusercontent.com/17894063/147813635-06738c05-fbf9-4687-84bc-ad49da5d84aa.png)
icon in dark theme
![image](https://user-images.githubusercontent.com/17894063/147813643-95851965-dba9-443a-bb24-75bddcad83ee.png)
its better right?
but i have no idea for the name
