### ISSUE TITLE
The menu bar cannot be displayed in 2k monitor

### ISSUE THREAD

**Issue by chenb0319** [redis/RedisDesktopManager#5171]
I bought RedisDesktopManager(version 2021.10.108) in microsoft store. The menu bar cannot be displayed in 2k monitor(16:10 2240X1400 14 inch notebook). I can't move or close the RedisDesktopManager. 

<img width="1120" alt="RESP" src="https://user-images.githubusercontent.com/30946869/148326751-942ac392-d722-40e0-aab7-96d2273ffcb9.png">

<img width="1120" alt="win" src="https://user-images.githubusercontent.com/30946869/148326764-4a8cf7ad-741b-4f78-b915-04d521a63902.png">

OS & version: Windows 10 21H1  zoom and display: 150%
RedisDesktopManager: 2021.10.108

**Comment by hahahhhh** [comment]
same issue, have you find a solution?

**Comment by uglide** [comment]
@chenb0319 @hahahhhh please try 2022.2.121 from MS Store. Let me know if you still have this issue with the new version.

**Comment by chenb0319** [comment]
the bug is fixed. so great!
