### ISSUE TITLE
App Crashes when loading db 13 with lots of data in a queue system in redis

### ISSUE THREAD

**Issue by talkquazi** [redis/RedisDesktopManager#5172]
Bug:
The app crashes and started to crash about a month ago when loading databases with lots of data in a queue system such as through a tool like bee-queue. Any time I attempt to load the db with 31,800+  items it just closes the app without any errors. This was not the case back in December before you started updating the app to be RESP.app.

Expected Behavior:
To not crash and to show the data as the app used to before Decembers updates.

Environment:
 - Windows 10 21H2 & Windows 11 21H2
 - KeyDB v6.2.1

Notes:
The crash is not due to using a multithreaded fork of Redis aka KeyDB.

**Comment by uglide** [comment]
Hello, 
Which version of RESP.app/RDM are you using?
Is db 13 is the last db with data in KeyDB?
Do you use any tunneling (ssh/tls)?

**Comment by talkquazi** [comment]
Which version of RESP.app/RDM are you using?
2021.10.108

Is db 13 is the last db with data in KeyDB?
14 is blank and 15 has data so the answer to that is no.

Do you use any tunneling (ssh/tls)?
no

------------------------------------------------------------------
Do other db's with the same or similar types of queue data crash? 
yes

**Comment by uglide** [comment]
@talkquazi unfortunately I cannot reproduce this issue. Please collect more debug info:

1. Install WinDbg Preview https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86?activetab=pivot:overviewtab
2. Run RESP.app from WinDbg Preview: `File -> Start debugging -> Launch app package -> Search for "resp" -> Launch`
3. Press `GO` green arrow in the left top corner
4. Reproduce the crash
5. Run `.dump /mf C:\Users\YOUR_USER_NAME_HERE\Desktop\resp.dump` command to create dump. Use command input to run the command: ![photo_2022-01-12_11-22-00](https://user-images.githubusercontent.com/1655867/149131146-1f59ec2c-dafd-455b-995e-4f64404ccd06.jpg)
6. Send dump to igor@resp.app

Please let me know if you need any help with collecting the dump.

**Comment by talkquazi** [comment]
When using WinDbg Preview and launching the app the app crashes citing an exception. So I am unable to send you a dump of the problem as the app won't launch in debug mode from WinDbg.

`Microsoft (R) Windows Debugger Version 10.0.22473.1005 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff6`73e50000 00007ff6`74293000   resp.exe
ModLoad: 00007ff9`c2e10000 00007ff9`c3005000   ntdll.dll
ModLoad: 00007ff9`c1530000 00007ff9`c15ee000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ff9`c0550000 00007ff9`c0818000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ff9`c14c0000 00007ff9`c152b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ff9`c1000000 00007ff9`c1125000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ff9`c0e60000 00007ff9`c1000000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ff9`c0980000 00007ff9`c09a2000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ff9`c1130000 00007ff9`c115b000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ff9`c09b0000 00007ff9`c0abd000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ff9`c0c10000 00007ff9`c0cad000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ff9`c0cb0000 00007ff9`c0db0000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ff9`c1fa0000 00007ff9`c26e4000   C:\WINDOWS\System32\SHELL32.dll
ModLoad: 00007ff9`3a440000 00007ff9`3a78a000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\libcrypto-1_1-x64.dll
ModLoad: 00007ff9`c1db0000 00007ff9`c1e5e000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ff9`c2ba0000 00007ff9`c2c3e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ff9`c17a0000 00007ff9`c183c000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ff9`38a80000 00007ff9`38ee2000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\botan.dll
ModLoad: 00007ff9`c0820000 00007ff9`c0976000   C:\WINDOWS\System32\CRYPT32.dll
ModLoad: 00007ff9`3a2e0000 00007ff9`3a43d000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Charts.dll
ModLoad: 00007ff9`31b60000 00007ff9`320a1000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Widgets.dll
ModLoad: 00007ff9`c27d0000 00007ff9`c28fa000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ff9`c1160000 00007ff9`c14b5000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ff9`31760000 00007ff9`31b5b000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Quick.dll
ModLoad: 00007ff9`310a0000 00007ff9`3175d000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Gui.dll
ModLoad: 00007ff9`30d20000 00007ff9`31092000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Qml.dll
ModLoad: 00007ff9`38930000 00007ff9`38a7b000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Network.dll
ModLoad: 00007ff9`308f0000 00007ff9`30d20000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\python38.dll
ModLoad: 00007ff9`c2cc0000 00007ff9`c2d15000   C:\WINDOWS\System32\SHLWAPI.dll
ModLoad: 00007ff9`3b510000 00007ff9`3b5a1000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\MSVCP140.dll
ModLoad: 00007ff9`a0080000 00007ff9`a008c000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\VCRUNTIME140_1.dll
ModLoad: 00007ff9`9aeb0000 00007ff9`9aec9000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\VCRUNTIME140.dll
ModLoad: 00007ff9`30320000 00007ff9`308e9000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Core.dll
ModLoad: 00007ff9`bdf10000 00007ff9`bdfae000   C:\WINDOWS\SYSTEM32\UxTheme.dll
ModLoad: 00007ff9`be100000 00007ff9`be12f000   C:\WINDOWS\SYSTEM32\dwmapi.dll
ModLoad: 000002ad`cb2d0000 000002ad`cb2e9000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\VCRUNTIME140.dll
ModLoad: 000002ad`cb2d0000 000002ad`cb899000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Core.dll
ModLoad: 00007ff9`bc7d0000 00007ff9`bca34000   C:\WINDOWS\SYSTEM32\d3d11.dll
ModLoad: 00007ff9`bedd0000 00007ff9`beec4000   C:\WINDOWS\SYSTEM32\dxgi.dll
ModLoad: 00007ff9`bf8f0000 00007ff9`bf9bb000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007ff9`bf8b0000 00007ff9`bf8eb000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ff9`b7750000 00007ff9`b775a000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007ff9`a84c0000 00007ff9`a84dd000   C:\WINDOWS\SYSTEM32\MPR.dll
ModLoad: 00007ff9`c03e0000 00007ff9`c040e000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007ff9`af160000 00007ff9`af179000   C:\WINDOWS\SYSTEM32\NETAPI32.dll
ModLoad: 00007ff9`b5e10000 00007ff9`b5e37000   C:\WINDOWS\SYSTEM32\WINMM.dll
ModLoad: 000002ad`cb2d0000 000002ad`cb899000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5Core.dll
ModLoad: 00007ff9`85720000 00007ff9`8578d000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\Qt5QmlModels.dll
ModLoad: 00007ff9`9c4a0000 00007ff9`9c4a9000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\MSVCP140_1.dll
ModLoad: 000002ad`cb2e0000 000002ad`cb2e9000   C:\Program Files\WindowsApps\35076IhorMalinovskyi.RedisDesktopManager_2022.0.113.0_x64__jrt9jtpcr47nt\MSVCP140_1.dll
ModLoad: 00007ff9`bfa10000 00007ff9`bfa1c000   C:\WINDOWS\SYSTEM32\NETUTILS.DLL
ModLoad: 00007ff9`b09f0000 00007ff9`b0a18000   C:\WINDOWS\SYSTEM32\SRVCLI.DLL
ModLoad: 00007ff9`bfd30000 00007ff9`bfd3c000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
(2704.4998): Break instruction exception - code 80000003 (first chance)
ntdll!LdrpDoDebuggerBreak+0x30:
00007ff9`c2ee06b0 cc              int     3`

**Comment by uglide** [comment]
@talkquazi Could you record a screencast with steps to reproduce the crash? Maybe I'm missing something. You can send it to email igor@resp.app if it contains any sensitive data. Thanks!

**Comment by talkquazi** [comment]
Well the app is crashing when selecting items. It crashes when trying to debug it. I am going to just give up for now and find another app that works. Best of luck fixing these bugs!

**Comment by uglide** [comment]
@talkquazi you can sign up on the website and I will enable free subscription for you, so you will be able to roll back to previous version that works for you. It will also help because knowing last "good" version will allow to eliminate changes which caused regression.

**Comment by uglide** [comment]
@talkquazi Also recently I have been discovered that RESP.app is crashing when opening key values on old Intel CPUs. 
So maybe it is also your case.

**Comment by talkquazi** [comment]
That might be the case as the PC i am using it on is an old i7. My guess is you are missing some crypto library or instruction that newer cpu's have built into them.

**Comment by uglide** [comment]
@talkquazi Fixed build is available on the website resp-2022.1.436.exe and also will be soon released to MS Store

**Comment by talkquazi** [comment]
Thank you I will test it out and verify if it's working or not for me.

**Comment by talkquazi** [comment]
Confirmed this solved the problem. Thanks again for actually supporting your product!

**Comment by uglide** [comment]
@talkquazi Thanks for reporting about the problem! Sometimes it's hard to reproduce the bug but bug reports with different pieces of information help me to understand what is wrong.
