### ISSUE TITLE
the app icon is displayed abnormally

### ISSUE THREAD

**Issue by qinxin0720** [redis/RedisDesktopManager#5173]
RESP.app version: 2021.10.236
macOS version: 12.1(21C52)

<img width="536" alt="截屏2022-01-09 下午1 46 40" src="https://user-images.githubusercontent.com/28943828/148671060-68a0a420-f30d-41bd-915b-edac1771655e.png">
<img width="801" alt="截屏2022-01-09 下午1 46 53" src="https://user-images.githubusercontent.com/28943828/148671064-0bf7fa56-468d-4887-bfb2-bcb7f6383f52.png">

in Dock:
open app:
<img width="394" alt="截屏2022-01-09 下午2 02 59" src="https://user-images.githubusercontent.com/28943828/148671216-403e1f8e-8bb2-44aa-b2ae-217c13dab94e.png">

close app:
<img width="326" alt="截屏2022-01-09 下午2 03 10" src="https://user-images.githubusercontent.com/28943828/148671218-213f7eca-2089-477a-881e-9cd8a344bb08.png">

**Comment by yhl452493373** [comment]
the same...
