### ISSUE TITLE
Error in the last step of installing redisdesktop(安装redisDesktop报错）

### ISSUE THREAD

**Issue by GodloveJoseph** [redis/RedisDesktopManager#5174]
**Describe the bug**
An error was reported during the installation of redisDeskTop.(安装redisDeskTop的过程中报错)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38186395/148898291-91c08976-f246-40e5-a065-1aa0e725daef.png)

**Environment (please complete the following information):**
 - OS & version: 
 -[windows 10 企业版 19042.508，Windows Feature Experience Pack 120.2212.31.0]
![image](https://user-images.githubusercontent.com/38186395/148898596-7807b713-5ca4-4eb9-981c-f4d8fa95a16f.png)

 - Redis-Server version
 - Server version 安装的版本 [rdm-2021.10.406] [rdm-2021.9.399]

**Additional context**

**Comment by GodloveJoseph** [comment]
![image](https://user-images.githubusercontent.com/38186395/148899904-0883434d-ef7f-4e06-a9f2-ef59ebf1c73e.png)

**Comment by GodloveJoseph** [comment]
The compressed package after installation is in the attachment.（安装过后的压缩包在附件中。）
![image](https://user-images.githubusercontent.com/38186395/148900595-46e5d304-d4e5-4b2f-abcb-cec379cdcde5.png)
![image](https://user-images.githubusercontent.com/38186395/148900652-d60e6cfc-d351-49bc-8335-b04d09a6c5c4.png)
![image](https://user-images.githubusercontent.com/38186395/148900691-465cc3a3-e5c2-4659-9a83-b603a46943f6.png)

**Comment by uglide** [comment]
Please download VC_redist_x64 manually and install it before installing RESP.app https://aka.ms/vs/16/release/VC_redist.x64.exe
