### ISSUE TITLE
mac os monterey missing icon 

### ISSUE THREAD

**Issue by causlayer** [redis/RedisDesktopManager#5182]
mac os 12.1，no problem after opening the app，please see the red box in the first picture:
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/7320355/150691445-c874fb01-cdc8-4c8f-ae7e-54c1d3b8d83d.png">
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/7320355/150691506-a7817413-691d-4695-86f6-0168362ee54c.png">

**Comment by uglide** [comment]
Looks like a local issue. Ensure that you have the latest changes and haven't modified resp.pro file.

**Comment by causlayer** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7320355/151380633-5a097ed6-7ed8-4334-8415-49ccac04dbbe.png">
Still not working, an icon will appear under the application, but there is still no icon in the application

**Comment by uglide** [comment]
Fixed in https://github.com/uglide/RedisDesktopManager/commit/b9b3b350030080a5ddf67bebbbfd050b36d86bb4

**Comment by causlayer** [comment]
solved

Igor Malinovskiy ***@***.***> 于2022年1月27日周四 23:43写道：
