### ISSUE TITLE
Copy on Terminal not avaiable

### ISSUE THREAD

**Issue by Eleisonchr** [redis/RedisDesktopManager#5183]
I am can't copy yet;
I report this error in #5100;
Posting image to you see about I´m say.
![Copy Error](https://user-images.githubusercontent.com/3289070/151176694-e998154e-b920-46a6-ba66-8b0fee9a8d89.png)

**Comment by uglide** [comment]
@Eleisonchr Please use `ctrl + c` to copy output from a terminal emulator.  If there is any specific reason why this should be added to the context menu - please explain.

**Comment by Eleisonchr** [comment]
Ok it works fine with `ctrl+c` but it would be nice to put a copy menu item, just for UX purposes. thank you very much for your attention

**Comment by uglide** [comment]
@Eleisonchr Thanks for the feedback!
