### ISSUE TITLE
build on windows failds

### ISSUE THREAD

**Issue by ShoJinto** [redis/RedisDesktopManager#5184]
**Describe the bug**
Hi, leader~~
I Compile according to the instructions from `2021` or `2022` branch，all report errors.

such as ：
```c++
E:\WorkSpace\rdm\src\app\models\connectionsmanager.cpp:133: error: C2027: 使用了未定义类型“QUuid”
E:\WorkSpace\rdm\3rdparty\qredisclient\src\qredisclient\connectionconfig.h:120: error: C2027: 使用了未定义类型“QSet<T>”
with
[
    T=QString
]
E:\WorkSpace\rdm\src\app\models\connectionsmanager.cpp:133: error: C3861: “createUuid”: 找不到标识符

E:\WorkSpace\rdm\src\app\models\connectionsmanager.cpp:133: error: C2027: 使用了未定义类型“QUuid”
```

I don't know Why do syntax errors occur? Is the code merged into the master branch without successful debugging?
There are still other dependencies that are not explained in the description document, resulting in omission. Please explain them to the leader. Thank you!!!
**To Reproduce**
Follow with : https://docs.redisdesktop.com/en/latest/install/#build-from-source
**Build on Windows** Selection

I find related issue such as : #4985 

**Screenshots**
- Errors:
![image](https://user-images.githubusercontent.com/7844516/151312846-6f687ad4-bdff-4be3-99ba-7294c1d7bdb9.png)
- QtCreator:
![image](https://user-images.githubusercontent.com/7844516/151314254-1723ac81-104e-4801-b798-bbe2509a71af.png)
- Underlying dependency Library
![image](https://user-images.githubusercontent.com/7844516/151314446-aadd74f3-5898-4de0-b811-f61c8be50db2.png)
- Compiler:
![image](https://user-images.githubusercontent.com/7844516/151314956-e01220cb-5963-43e8-8b11-7b5ecd819365.png)
![image](https://user-images.githubusercontent.com/7844516/151317676-f7c6accc-7bfa-4615-87a9-711f38eb07be.png)

**Environment (please complete the following information):**
 - OS & version: Microsoft Windows [Version 10.0.19044.1466]
 - Redis-Server version [e.g. 4.0.1]

**Additional context**

**Comment by ShoJinto** [comment]
Oops!!! I found my QT version wrong! It is being replaced to 5.15.2, and the final result will be fed back later. I'm so sorry!!

**Comment by uglide** [comment]
Ok, I'm closing this issue for now.

**Comment by ShoJinto** [comment]
Hay! everybody. I wrote an article about this compilation process

https://shojinto.github.io/posts/RDM-%E4%BB%8E%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91/
