### ISSUE TITLE
ssh tunnel not compatibility with new version of openssh

### ISSUE THREAD

**Issue by Dead-Echo** [redis/RedisDesktopManager#5186]
For security reason we recently upgrade our Redis Server  (base on CentOS 7.9) OpenSSH/OpenSSL up to 8.8p1/1.1.1m.
Then we found RDM ssh tunnel with pirvate key authentication (key type rsa)mode failed to connect the redis server, I try to bulid a test env to debug. I find RDM work well when I change ssh tunnel with password authentication mode, I guess that's because OpenSSH or OpenSSL had changed  something  at protocol level, RDM may need a patch to fix it.
![RDM_ERROR](https://user-images.githubusercontent.com/39609746/151473305-b3400948-bd67-44b6-b19a-382bfdfda9bc.jpg)

**Comment by uglide** [comment]
Please provide more information about your private key. Also, ensure that RESP.app has permissions to your private key and it's in PEM format.

**Comment by uglide** [comment]
@Dead-Echo I've reproduced the issue. Please try preview build resp-2022.0.422.exe

**Comment by uglide** [comment]
Fix was released as part of 2022.0 release. If you have any questions please let me know.

**Comment by Dead-Echo** [comment]
I have just try 2022.0  release, but my github account seems need to buy subcription.I can't  verify it, unfortunately

**Comment by uglide** [comment]
@Dead-Echo Your trial subscription hasn't expired yet. You just need to sign in with your GitHub account on the website to access preview downloads.

**Comment by Dead-Echo** [comment]
![image](https://user-images.githubusercontent.com/39609746/152900056-0ac44666-c485-4380-b6b4-7018ff1d6c77.png)
I think that means I should buy subcription to use preview version?

**Comment by uglide** [comment]
@Dead-Echo looks like you have multiple accounts and one of them has expired subscription. click on the cancel button and sign in with the account that is linked to your GitHub.

**Comment by Dead-Echo** [comment]
We changed ssh-key type from rsa to ed25519,then rdm-2021.10.406 back to normal.

**Comment by Dead-Echo** [comment]
I build Linux Desktop env to test(base on CentOS 7.9 via startx),I try snap but failed to run resp,change to flathub setup 2022.0 release success,but rsa-key and ed25519 all got error.Did this version have ssh-tunnel function?

**Comment by Dead-Echo** [comment]
![Uploading RESP_error.jpg…]()

**Comment by uglide** [comment]
@Dead-Echo Please share the output of  `snap info redis-desktop-manager ` command. It should be something like:

```
ame:      redis-desktop-manager
summary:   RESP.app - GUI for Redis ® (formerly RedisDesktopManager)
publisher: –
store-url: https://snapcraft.io/redis-desktop-manager
license:   unset
description: |
  Cross-platform GUI management tool for Redis
commands:
  - redis-desktop-manager.resp
tracking:     latest/edge
refresh-date: today at 16:04 EET
channels:
  latest/stable:    2022.0.2+f79a564f 2022-02-09 (598) 1GB -
  latest/candidate: ↑                                      
  latest/beta:      ↑                                      
  latest/edge:      2022.0.2+f79a564f 2022-02-09 (598) 1GB -
installed:          2022.0.2+f79a564f             (x3) 1GB -
```

**Comment by Dead-Echo** [comment]
[root@xxxx ~]# flatpak info app.resp.RESP
Ref: app/app.resp.RESP/x86_64/stable
ID: app.resp.RESP
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2022-02-03 18:36:38 +0000
Subject: Update RedisDesktopManager to 2022.0 (4de57699)
Commit: eb9cb59bf4a64f7d97c1fea2f365bfa177ced6cb6b8c3aca9de1c6f36f33b2fe
Parent: b34eed62d5c4a611c535cde4e0a92ab89a25349aab383ad1dd65399d0b1df19d
Location: /var/lib/flatpak/app/app.resp.RESP/x86_64/stable/eb9cb59bf4a64f7d97c1fea2f365bfa177ced6cb6b8c3aca9de1c6f36f33b2fe
Installed size: 210.7 MB
Runtime: org.kde.Platform/x86_64/5.15-21.08
Sdk: org.kde.Sdk/x86_64/5.15-21.08

**Comment by uglide** [comment]
@Dead-Echo use test branch instead:
```
flatpak install --user https://dl.flathub.org/build-repo/75771/app.resp.RESP.flatpakref
flatpak run --branch=test app.resp.RESP
```

**Comment by Dead-Echo** [comment]
![image](https://user-images.githubusercontent.com/39609746/153229500-a0e859fa-3a9d-408e-bca2-07c05ac7d4af.png)

**Comment by Dead-Echo** [comment]
![image](https://user-images.githubusercontent.com/39609746/153230158-3e42f169-9ec1-47b3-8488-4037c896e90c.png)
key permission problem？600 not enough？
![ssh_key](https://user-images.githubusercontent.com/39609746/153230904-76a4daff-d9d4-4099-8294-43a5180c43bd.jpg)

**Comment by Dead-Echo** [comment]
test env detail: 
server&client CentOS 7.9  OpenSSH 8.8p1 OpenSSL 1.1.1m
client desktop type gnome

**Comment by uglide** [comment]
@Dead-Echo by default RESP.app has access only to `~/.ssh` folder, you can copy your ssh key there or add more permissions using command line arguments to flatpak

**Comment by Dead-Echo** [comment]
thanks，I move private key to ~/.ssh everything back to normal, rsa-key and ed25519-key both work well.
