### ISSUE TITLE
Build 2021.10.406 is totally broken

### ISSUE THREAD

**Issue by andrey-denisenko** [redis/RedisDesktopManager#5187]
[Everything at screencast](https://www.youtube.com/watch?v=sTZFng9tEwQ)

1. Old build said "go get update"
2. I installed new one
3. It launched after installation and when I tried to click "gear" to change IP of my Redis server.
4. Everything stuck and do nothing.
5. In addition it continue to say "go get update"

**Comment by uglide** [comment]
@andrey-denisenko Hi, thanks for reaching out. Let's solve your problems one by one.

**1st problem:**
Looks like you have the old version installed in C:/Program Files/RedisDesktopManager and that's the version that you run when you type "Re" in Start menu. Try to remove it first.

**2nd problem with the frozen new version:**
Could you please record a screencast and show the actions which you perform before the new version is stuck?

**Comment by andrey-denisenko** [comment]
Probably I've figured how it got frozen. When I tried to click at RDM with no reaction.

![изображение](https://user-images.githubusercontent.com/26914037/152018100-93ea0caf-b63f-479a-9e39-c75ab641c945.png)

Most likely that message box was shown, but somehow it wasn't visible on screen.
So while that messageBox is not closed, main window is blocked for any interactions.

**Comment by andrey-denisenko** [comment]
**1st problem:**
I've uninstalled RDM completely. And installed latest version from scratch.
So now it's fine.

**2nd problem**
https://www.youtube.com/watch?v=6hdaHK9sQBw

**Comment by uglide** [comment]
You can right click on connection to open inline menu without trying to connect. That way you can work around issue with blocked modal window.

I will investigate why this happens. Thanks for the details.

**Comment by andrey-denisenko** [comment]
> You can right click on connection to open inline menu without trying to connect. That way you can work around issue with blocked modal window.

That works! Thanks!

**Comment by uglide** [comment]
@andrey-denisenko Looks like "Edit connection settings" modal window is rendered off-screen in your case but I cannot reproduce it on my Windows setups. Could you provide more details about your PC/Laptop: 
- Windows version with build (winver)
- Display number and resolution
- CPU/GPU models

Looking forward to your reply. Thanks!

**Comment by uglide** [comment]
Feel free to reopen this issue by providing more information for the investigation.
