### ISSUE TITLE
Global View as Format setting required

### ISSUE THREAD

**Issue by calmzhu** [redis/RedisDesktopManager#5190]
Choose one key, it was view as PlainText, I can manualy change it to json or some else.
![image](https://user-images.githubusercontent.com/10286576/152644040-99a9161f-ad86-4636-9222-581a296181bb.png)
We have lots of keys in redis and most of them are same format[Not Plain Text].So each time view key,must set format first.
hope to allow  change  default view as format.

**Comment by uglide** [comment]
@calmzhu please download preview build 2022.0 from the website https://resp.app, default formatter for connection is available already. More info https://github.com/uglide/RedisDesktopManager/releases/tag/2022.0
