### ISSUE TITLE
Cannot select pickle format

### ISSUE THREAD

**Issue by fredgido** [redis/RedisDesktopManager#5192]
**Describe the bug**
Cannot select from formats dropdown the pickle format.

**To Reproduce**
1. Go to a item
2. Click on View as: dropdown
3. See pickle isn't there

**Expected behavior**
Pickle show be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/17598829/153393496-b687de95-4406-467b-b879-84988ed6077d.png)

**Environment (please complete the following information):**
 - Ubuntu 
 - 2022.0.2+f79a564f

**Additional context**
I used to be able to see pickle.

**Comment by uglide** [comment]
Hello, Please update to 599 build which contains the fix for this problem
