### ISSUE TITLE
windows has a light titlebar even thought in dart mode ???

### ISSUE THREAD

**Issue by ancion** [redis/RedisDesktopManager#5199]
**Describe the bug**
Windows version is laways light titlebar even thought  changed dart mode !!

**Environment :**
 -  Windows 11 22000
 - Redis-Server version 2022.0

**Comment by uglide** [comment]
ATM Windows API doesn't provide a clean way to deal with this problem. You can manually change title bar color in Windows Theme settings to workaround this problem.

**Comment by ancion** [comment]
> ATM Windows API doesn't provide a clean way to deal with this problem. You can manually change title bar color in Windows Theme settings to workaround this problem.

ATM Windows  ?= Automated Teller Machine Windows ?  I can't understand. This system use RDM?

**Comment by ancion** [comment]
> ATM Windows API doesn't provide a clean way to deal with this problem. You can manually change title bar color in Windows Theme settings to workaround this problem.

ATM Windows  ?= Automated Teller Machine Windows ?  I can't understand. This system use RDM?

**Comment by ancion** [comment]
> ATM Windows API doesn't provide a clean way to deal with this problem. You can manually change title bar color in Windows Theme settings to workaround this problem.

In new version of windows 11, MS start support a Mica style titlebar for tranditional software with light and dark mode.

**Comment by uglide** [comment]
@ancion I have found a workaround and added a fix for this. It will be available soon in 2022.1 builds.

**Comment by ancion** [comment]
> 

The pop up  settings window is still  a blight title bar. @uglide
