### ISSUE TITLE
Cannot run RDM after snap update

### ISSUE THREAD

**Issue by polearnik** [redis/RedisDesktopManager#5200]
**Describe the bug**
I try to start RDM but bin file dissapear. Old link was /snap/bin/redis-desktop-manager.rdm 
I update to edge channel but also cannot find any exe files
rdm command in terminal show that this program not exist

**Environment (please complete the following information):**
 - Linux Mint 

**Additional context**

**Comment by uglide** [comment]
The binary file was renamed to `resp`. Execute it as `redis-desktop-manager.resp` now
