### ISSUE TITLE
The height of the App cannot be reduced

### ISSUE THREAD

**Issue by PhilHannent** [redis/RedisDesktopManager#5202]
**Describe the bug**
In maximised view the App appears as you would expect. However the Windows view is bigger than my screen layout.

My screen is 2560x1440 and scaled 150% on Windows 11.

**To Reproduce**
Open the app and it starts in Windows mode. double clicking the title bar can maximize it, but switching back to windowed mode causes the max height to be the same.

**Expected behavior**
To be able to make the window height < 1440.

**Screenshots**
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/813874/154852036-952ac2c8-784b-4ed4-a964-99cf0fcfc549.png">

**Environment (please complete the following information):**
 - Windows 11 with the latest patches

**Additional context**
None

**Comment by uglide** [comment]
Fixed in 2022.2 and released in MS Store.
