### ISSUE TITLE
Filtering by value.

### ISSUE THREAD

**Issue by Real-Gecko** [redis/RedisDesktopManager#5203]
**Is your feature request related to a problem? Please describe.**
It's more question than feature request.

**Describe the solution you'd like**
I use Redis as a backend for Celery task results which are stored in JSON format. Some of this tasks failed to execute which is reflected in a value
```JSON
{
  "status": "FAILURE",
  "result": {
  ...
  }
}
```
Is there a way to filter all the keys by `FAILURE` `status`?

**Comment by uglide** [comment]
As I remember Celery stores results in Redis `list` and you can use text search provided by RESP.app:
<img width="743" alt="Screenshot 2022-02-23 at 14 05 33" src="https://user-images.githubusercontent.com/1655867/155316593-62d15a63-c1e7-4baa-8205-8345c111d9ef.png">

By default RESP.app search only on loaded page. If you need to search across all pages - click on the "Full Search" button.

**WARNING!** Full search loads all values into memory and you need to have enough free RAM to load all values. 
I **do not recommend** to use full search on large values.

**Comment by Real-Gecko** [comment]
Sorry for delay. Actually Celery stores each job result as a string:
![image](https://user-images.githubusercontent.com/2231969/155720549-5a4e38d7-47e9-4a28-8923-baa96c5d7f1d.png)
Is there a way to filter this way?

**Comment by uglide** [comment]
Oh, In that case, the only way is to override the default celery task backend with a custom one that uses Redis list.
