### ISSUE TITLE
Unable to scroll down when showing Server Info

### ISSUE THREAD

**Issue by doggy8088** [redis/RedisDesktopManager#5214]
**Describe the bug**
I can't see bottom text of the Server Info page.

**To Reproduce**
1. Connect to Redis Server
3. Click on 'Server Info'
4. I can't scroll down to see full information in that page.

**Expected behavior**

I expected to see bottom info by scrolling down the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/88981/158349269-d6153f20-bbf4-475d-b75e-a4ee80c91bfc.png)

**Environment (please complete the following information):**
 - OS & version: `Microsoft Windows [Version 10.0.19043.1586]`
 - Redis-Server version `6.0.14`

**Additional context**

N/A

**Comment by uglide** [comment]
@doggy8088 What screen resolution and scaling factor do you use?

**Comment by doggy8088** [comment]
@uglide 

150%

2560x1440

![image](https://user-images.githubusercontent.com/88981/158537654-80f4390b-627d-4fce-afec-8166f7268352.png)

**Comment by uglide** [comment]
Fixed in 2022.4.2
