### ISSUE TITLE
RESP takes over thirty minutes to display the inital screen.

### ISSUE THREAD

**Issue by jgwinner** [redis/RedisDesktopManager#5224]
**Describe the bug**
The app won't open

**To Reproduce**
1. Go to the Microsoft app store
2. Check for updates. Just says "Open"
3. Click "Open"
4. Wait half an hour. No RESP window open
5. If you look in the task manager, the RESP app is there, running, but no window. 
6. It will eventually open, but it takes forever. Frankly, I went to sleep last night, so it might have been several hours.
7. This happens on 2 different PC's. I have to do production support, so I'm reticent about upgrading the servers past the last version. 
8. Any Redis-CLI opens up very promptly. 

**Expected behavior**
It basically takes hours for the window to first appear, if it ever does. Seriously - hours. Everything is up to date, and I have paid for the license. I had a production issue and had to solve it with an Azure VM - very old - version of the app, which worked great, if a tad slow.

I also tried removing the app from the control panel and then adding it again from the store (I paid for the license). It still just hangs. 

**Screenshots**
Nothing to screenshot

**Environment (please complete the following information):**
 - OS & version: 2 machines:
      - [Windows 10 [Version 10.0.19043.1586]]
      - Windows 10 [Version 10.0.19042.1561] (busy busy busy, need a vacation)
 - Redis-Server version - can't get there, but from CLI it's redis_version:5.0.14

**Additional context**

**Comment by uglide** [comment]
Hello @jgwinner 
Thanks for the bug report. Do you have mounted/unmounted network shares/drives in the explorer?

**Comment by jgwinner** [comment]
I have some network drives, yes. If I'm not accessing the files on some of them, they are unmounted. 

Why would RESP need to access drive shares? This doesn't affect any other of my dev tools until I access those drives.

That's virus-like activity to scan files that I'm not opening. I'm not accessing any of those drives from RESP.

Unrelated - I hope you and yours are all safe. Terrible times!

== John ==

**Comment by uglide** [comment]
I'm safe, thanks for your support.

It's a bug in the underlying component from Qt framework. It stupidly uses wrong WinApi call which iterates all drives including mounted over network to draw the list of all destinations in File Dialogs

As a workaround you can temporary remove network drives from explorer.

I have draft fix for this problem and if you don't mind to test it I can add you to beta testers group in MS Store.

**Comment by uglide** [comment]
@jgwinner please send me an email from your MS Store account to igor@resp.app if you're interested in testing preview build. Thanks!

**Comment by jgwinner** [comment]
Oh, I feel for you, QT can be a hassle.

Sure, will do!

== John ==

**Comment by uglide** [comment]
@jgwinner Please let me know if the beta build fixes the issue. Thanks!

**Comment by jgwinner** [comment]
Ah - sorry, I emailed but didn't update here. I can't really easily duplicate it, as I had to drop that file share; I DO have other file shares that are sometimes not connected, and RESP comes up pretty quickly now.

So I think I'll say it's closed, if it happens again I'll let you know!
