### ISSUE TITLE
Can't add new connection 

### ISSUE THREAD

**Issue by polearnik** [redis/RedisDesktopManager#5233]
**Describe the bug**
Then I try to add or modify connection it just close app

**To Reproduce**
1.open app
2. Click on 'Connect To redis Server'
3.All is closed

**Environment (please complete the following information):**
 - linux mint 20.3
 - Redis server v=6.0.6 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=d463d609620685c0

**Additional context**

running from console 

/snap/bin/redis-desktop-manager.resp
Gtk-Message: 14:49:41.333: Failed to load module "xapp-gtk3-module"
Enable auto-scaling
TLS support: "OpenSSL 1.1.1f  31 Mar 2020"
App font: "Open Sans" 11
Values font: "Ubuntu Mono"
qrc:/connections/ConnectionSettignsDialog.qml:735: TypeError: Cannot read property 'sshHost' of undefined
qrc:/connections/AskSecretDialog.qml:12: TypeError: Cannot read property 'name' of undefined
qrc:/value-editor/AddKeyDialog.qml:96: TypeError: Cannot read property '-1' of undefined
Rendering backend: "software"
qml: Is Embedded formatters module loaded: true
qml: Embedded formatters: [[binary,true],[cbor,true],[msgpack,false],[php,false],[pickle,true]]
Ошибка сегментирования (стек памяти сброшен на диск)

**Comment by uglide** [comment]
Thanks for the bug report. For now you can switch to stable channel on Snapcraft.

**Comment by uglide** [comment]
2022.4.2 was released to the edge and stable channels and this issue doesn't reproduce anymore.
