### ISSUE TITLE
key数据多的时候，存在查询不到内容的情况

### ISSUE THREAD

**Issue by nuo010** [redis/RedisDesktopManager#5237]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
@nuo010 Please record a screencast that captures described issue and send it to igor@resp.app
Thanks!

**Comment by uglide** [comment]
Feel free to reopen this issue by providing more details.
