### ISSUE TITLE
Centos 7 - RDM is not working any more

### ISSUE THREAD

**Issue by ymittal75** [redis/RedisDesktopManager#5239]
**Describe the bug**

The last working build for redis desktop manager was 2021.6+2af6b985 (541) on centos7. After updating to latest stable build the app is not working any more and keep on hanging from desktop icon. running from terminal we get below error
**error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory** OR please suggest to revert to previous versions

Please fix this

**Comment by uglide** [comment]
Try to use flathub version of RESP.app https://flathub.org/apps/details/app.resp.RESP

**Comment by ymittal75** [comment]
Awesome!!! this works fine

Thank you so much
