### ISSUE TITLE
复制hash类型的值的快捷操作

### ISSUE THREAD

**Issue by buhtigub** [redis/RedisDesktopManager#5240]
可以在复制hash类型时，不用key和value分开复制吗？

**Comment by uglide** [comment]
Could you explain your request with a screenshot? Thanks!

**Comment by buhtigub** [comment]
> Could you explain your request with a screenshot? Thanks!

![image](https://user-images.githubusercontent.com/50066608/170195957-c969f4de-af1d-4fd0-8ce5-898282fe5d92.png)
快速复制图中hash类型的key1对应的所有，包含key 1下面的每一个键和对应的值

**Comment by uglide** [comment]
@kynightyk Do you mean export of all values of the hash to JSON or csv/xlsx?

**Comment by buhtigub** [comment]
> @kynightyk Do you mean export of all values of the hash to JSON or csv/xlsx?

I would like to copy this key to  another redis server

**Comment by uglide** [comment]
https://docs.resp.app/en/latest/bulk-operations/#copy-keys-from-one-redis-server-to-another
