### ISSUE TITLE
Icon missing after building

### ISSUE THREAD

**Issue by causlayer** [redis/RedisDesktopManager#5244]
After building with the latest code, it is found that the icon of the generated RESP.app is not displayed, please see the screenshot

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/7320355/171319941-102baffd-c2d5-4ba7-b189-9492c0b2093b.png">

**Comment by uglide** [comment]
You just need to replace the old Info.plist with a new one to make it work properly.
