### ISSUE TITLE
Get errors while startup app

### ISSUE THREAD

**Issue by echocde** [redis/RedisDesktopManager#5245]
**Describe the bug**

**To Reproduce**
Startup resp.app then see the errors in logs.

TLS support: "Secure Transport, macOS 12.4"
App font: "Helvetica Neue" 12
Values font: "Monaco"
("en-CN", "zh-Hans-CN", "ja-CN")
Detected locale: "en_CN"
qrc:/connections/ConnectionSettignsDialog.qml:769: TypeError: Cannot read property 'sshHost' of undefined
qrc:/connections-tree/BetterTreeView.qml:92:9: Unable to assign [undefined] to QQmlComponent*
qrc:/connections/AskSecretDialog.qml:12: TypeError: Cannot read property 'name' of undefined
qrc:/value-editor/AddKeyDialog.qml:96: TypeError: Cannot read property '-1' of undefined
Rendering backend: "software"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:/python//formatters/__init__.py\", line 1, in <module>\n    from .binary import BinaryFormatter\n\n  File \"qrc:/python//formatters/binary.py\", line 1, in <module>\n    import bitstring\n\nModuleNotFoundError: No module named 'bitstring'\n"
qml: Is Embedded formatters module loaded: false

**Comment by uglide** [comment]
Most warnings are safe except for the error about Python dependencies. You just need to set up Python and dependencies correctly.
