### ISSUE TITLE
打开软件报错

### ISSUE THREAD

**Issue by luke-zhang580** [redis/RedisDesktopManager#5248]
**Describe the bug**
<img width="1007" alt="CleanShot 2022-06-08 at 20 29 22@2x" src="https://user-images.githubusercontent.com/45325652/172616552-9416f7e3-dbe7-4375-99c1-f8f7c6de400f.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & version: [e.g. Windows 10 1806]
 - Redis-Server version [e.g. 5.0.1]

**Additional context**

**Comment by uglide** [comment]
Please download the 2022.3.47 build.
