### ISSUE TITLE
Extension Server client sends `decode` instead of `encode` request

### ISSUE THREAD

**Issue by fuelen** [redis/RedisDesktopManager#5251]
**Describe the bug**
I'm unable to trigger encode request to my extension server

**To Reproduce**
1. Try to add new key
2. Select custom formatter
3. Click save

OR

1. Select existing key
2. Select custom formatter
3. Edit it
5. Ctrl + S

**Expected behavior**
call encode endpoint

**Screenshots**
![image](https://user-images.githubusercontent.com/588762/173880977-4c43459d-112e-4c61-88ec-442ad96746af.png)

**Environment (please complete the following information):**
 - OS & version: Arch Linux

**Comment by uglide** [comment]
My bad. I was in a rush to release it and haven't properly cleaned up the encoding part :) Should work fine now with the latest commit from the 2022 branch. Do you use RESP.app from Flathub?

**Comment by fuelen** [comment]
yes, from flathub

**Comment by uglide** [comment]
@fuelen please try this test build 
```
flatpak install --user https://dl.flathub.org/build-repo/93997/app.resp.RESP.flatpakref
```

**Comment by fuelen** [comment]
@uglide it works! Thank you!
