### ISSUE TITLE
Can support config how many items to scan? Scan 10000 item cost 27 milliseconds at most.

### ISSUE THREAD

**Issue by javalover123** [redis/RedisDesktopManager#5252]
**Is your feature request related to a problem? Please describe.**
Scan 10000 item cost 27 milliseconds at most.

**Describe the solution you'd like**
Can support config how many items to scan?

**Comment by uglide** [comment]
Thanks for the request. I agree that it makes sense to expose it as a config option because for local/dev environments it's so annoying to wait :)

@javalover123 Have you had a chance to check/try https://docs.resp.app/en/latest/extension-server/ ?

**Comment by javalover123** [comment]
I'll try late, lgtm

**Comment by uglide** [comment]
Implemented in 2022.4.2
