### ISSUE TITLE
Filter still doesn't work

### ISSUE THREAD

**Issue by webmake** [redis/RedisDesktopManager#5255]
**Describe the bug**
It seems that bug has been not resolved https://github.com/uglide/RedisDesktopManager/issues/4382

**Expected behavior**
Filtered keys from the namespace

**Screenshots**
![image](https://user-images.githubusercontent.com/5016464/178928416-8bb99177-e90b-4cd5-a459-01b77ee7f835.png)

**Environment (please complete the following information):**
Ubuntu 20.04.4 LTS
redis:5
RDM 2022.2+c787819a

**Additional context**
As I see there is run command:
`Connection: redis docker > [runCommand] scan 0 MATCH *[rate_limiter][sms_delay][572aab4f-d83f-14bf-a8d7-94928e0d04fe]* COUNT 10000`

**Comment by uglide** [comment]
@webmake You are using an invalid glob style pattern. Square brackets `[]` are special characters in glob style syntax just like in regex. RESP.app doesn't auto-escape it automatically. In your case, the valid expression will be
```
*\[rate_limiter\]\[sms_delay\]\[572aab4f-d83f-14bf-a8d7-94928e0d04fe\]*
```

After applying this expression you won't see namespace `shared_user` at all.

**Comment by webmake** [comment]
Maybe it should be user-friendly then, let's say if copied text from anywhere, and it could do a search without modifying it? What do you think?

**Comment by uglide** [comment]
First of all, the app doesn't modify anything, as I mentioned above it just sends your *glob style pattern* to Redis https://redis.io/commands/scan#the-match-option
There is no easy way to understand whether the user is aware of *glob style pattern* syntax or not. If you have any suggestions on how to improve user experience please share your thoughts.
