### ISSUE TITLE
click log button show

### ISSUE THREAD

**Issue by causlayer** [redis/RedisDesktopManager#5258]
show:External: Can't load list of available formatters from extension server: Protocol "" is unknown
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/7320355/182737049-058d2926-6fbb-4f76-95a5-aefc933529a5.png">
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/7320355/182738912-9fe2505c-a387-4e0e-8963-27c6786b8762.png">

**Comment by Ray2310** [comment]
解决了吗? 我也是突然这样了

**Comment by uglide** [comment]
@causlayer @Ray2310, you can safely ignore this message.

**Comment by Ray2310** [comment]
我已经解决了，原因: ip发生了变化，去虚拟机或者linux系统下 ，用IP addr 查看新的ip地址，然后重新连接REST

**Comment by Ray2310** [comment]
> @causlayer @Ray2310, you can safely ignore this message.
I have solved it, the reason: the ip has changed, go to the virtual machine or linux system, use IP addr to check the new ip address, and then reconnect to REST
