### ISSUE TITLE
"Import keys from RDB file" is not working on MacOS 

### ISSUE THREAD

**Issue by umax-imagination-media** [redis/RedisDesktopManager#5265]
**Describe the bug**
this feature is not working on the MacOS version of the app. I am using MacOS Monterey version 12.4 and tried all available MacOS versions of the RESP app from https://resp.app/subscriptions/downloads and I am getting the same issue for all of them - I am not able to select the RDB file for "Path to RDB file" in the "Bulk Operations Manager" window because when I am clicking on the "Select File" button - the MacOS file dialog is showing under the "Bulk Operations Manager" window and I am not able to switch focus to the MacOS file dialog anyhow (even if I move the top window to the side, I can't click on anything in the MacOS file dialog.

https://github.com/uglide/RedisDesktopManager/pull/4595#issuecomment-1239802177
**To Reproduce**
1. Connect to the redis server
2. Select DB
3. Click on "Bulk Operations" icon
4. Click on "Import keys from RDB file" icon
5. Click on "Select File" button
6. See the error - not able to focus on the MacOS file dialog

**Expected behavior**
Import from RDB file is working 

**Screenshots**
![image](https://user-images.githubusercontent.com/108946938/188964560-80db6231-661b-4f4a-882e-abaf8ee809d5.png)

**Environment (please complete the following information):**
 - OS & version: MacOS Monterey version 12.4
 - Redis-Server version: 5.0.14

**Additional context**
-

**Comment by uglide** [comment]
Hello @umax-imagination-media 

Thanks for the bug report. This regression issue was fixed and is available in resp-intel-2022.4.44.dmg and resp-arm64-2022.4.58.dmg. Downloads are available on https://resp.app/subscriptions/downloads

**Comment by u-maxx** [comment]
good morning @uglide! Thank you for the fast feedback and fix! I have confirmed that there is no issue with selecting the RDB file in the new version, but unfortunately, import is not working, it is showing the message "Success  Bulk Operation Finished" but no keys imported to any DB 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/2717220/189064789-3f308e66-cbc1-4dd4-96c1-b5ba04f78ef7.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/2717220/189064855-ec4dfd96-6b6b-43f2-a098-06bcea8dca28.png">

**Comment by uglide** [comment]
Could you try to press "Show Matched keys" to determine if the underlying rdbtools package can recognize the RDB file. Also, please provide a screenshot of the "Log" drawer:
<img width="1432" alt="Screenshot 2022-08-12 at 11 31 37" src="https://user-images.githubusercontent.com/1655867/189065831-073fb33a-5912-44a7-a021-0ff780d0d60e.png">

**Comment by u-maxx** [comment]
Sure, there is "Cannot get the list of affected keys" message 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/2717220/189066282-9f50673b-c65b-4636-a183-05091d8d6241.png">

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/2717220/189066668-01545344-c651-4bae-ba40-c8a2ea540206.png">

**Comment by uglide** [comment]
@u-maxx Could you also share the output in the Log drawer? Instructions on how to open in in my previous message

**Comment by u-maxx** [comment]
Sure, sorry, I pasted the wrong second screenshot. 
![image](https://user-images.githubusercontent.com/2717220/189067495-07a73937-2c1d-4588-93bf-3c1d4fe7dd76.png)


I am connecting to the Redis server via ssh tunnel because the Redis server is running inside the docker container.

**Comment by u-maxx** [comment]
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/2717220/189068004-ab2e148a-01a6-4aee-9676-d9683d523df0.png">
`Connection: redis-server doesn't support AUTH command or ismisconfigured. Trying to proceed without password. (Error:ERR wrong number of arguments for 'auth' command)`

`Formatters: Return value of PyObject call is NULL: Traceback (most recent call last):`
`  File "qrc:/python//rdb/__init__.py", line 56, in rdb_list_keys
    process_command(callback, path_to_rdb, db,
 File "qrc:/python//rdb/__init__.py", line 35, in process_command
    parser = rdbtools.RdbParser(callback=callback, filters=filters, ignore_values=scan_keys)
TypeError: __init__() got an unexpected keyword argument 'ignore_values'
`

**Comment by uglide** [comment]
@u-maxx Thanks. It's a packaging bug. Please try resp-arm64-2022.4.59.dmg build. Thanks!

**Comment by u-maxx** [comment]
@uglide thank you for the fastest bugfixes and great support! 
 The previous bugs are fixed, but for some reason it is importing only ~7300 keys (I have made few tests and this value is changing from 7299-7301) from the 29770 keys which are shown in the "Matched keys:" area: 

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/2717220/189074465-9708a42f-5f61-4b37-8dee-4e8b79bdaa38.png">

As you can see the loading message is showing "Processed: 29565" message, but it is loading for a few minutes w/o progress (I have tested a few times). If I click on the main window - the import window disappears and then if I click on "Reload Keys in Database" icon  for db0 - it is showing 7299 keys 
<img width="832" alt="image" src="https://user-images.githubusercontent.com/2717220/189075419-99a501b1-aeef-45d4-8b49-9f01605c32c4.png">

The RDB file which I am trying to import is 31,6 MB  and should have 29770 keys (according to the info from Matched keys) 
Here are the logs: 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/2717220/189075730-0b6e4c24-c5a3-436c-b5e5-ccd5c1c11298.png">

Would be great to import the full RDB file.

**Comment by u-maxx** [comment]
I have tried to wait for more than 1h w/o clicking anywhere during the import loading animation, but as result, it was still loading, and after clicking on the main window - it was showing the same result as in my previous comment - only 7299 keys were imported.

**Comment by uglide** [comment]
@u-maxx Please try build resp-arm64-2022.5.62.dmg from the website. Thanks!

**Comment by u-maxx** [comment]
Hello @uglide! Thank you for the update, unfortunately, I am not able to find the **resp-arm64-2022.5.62.dmg** build on the website, the latest available is "macOS Apple Silicon —  2022.4.59"
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/2717220/189866757-5ff82b8c-c8a2-4837-8a6f-9ea1d3d4612c.png">
 Could you please check if the links on the website are correct?

**Comment by u-maxx** [comment]
Oh, sorry, I see the "macOS Apple Silicon —  2022.5.62" on the "Preview Builds" tab. Checking.

**Comment by uglide** [comment]
@u-maxx yes, it's on the preview builds tab

**Comment by u-maxx** [comment]
I have tried to import the same RDB file and got the following error: 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2717220/189867690-f4194aef-51b0-41d7-8f30-d3a1652da718.png">
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/2717220/189867850-23c51939-6a75-4b3e-934a-225d748b2271.png">

As a result the same amount of keys were imported - 7301 of 29770 keys from RDB file (according to the info from Matched keys)

**Comment by uglide** [comment]
@u-maxx  Where your rdb file comes from? Is it produced by Redis v5?

**Comment by u-maxx** [comment]
It is from Redis server v=6.2.0 

`redis-server -v
Redis server v=6.2.0 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=bb6d0fd02006ff98`

**Comment by uglide** [comment]
@u-maxx you need to upgrade your local redis to v6 first

**Comment by u-maxx** [comment]
Ok, thank you for the help! I will give it a try, it is set to v6 in the config files for my docker setup but looks like because of a bug in that docker tool (warden) it has used Redis v5.

**Comment by uglide** [comment]
RESP.app uses a modified version of https://github.com/sripathikrishnan/redis-rdb-tools which has limited RDB support (only standard types are supported). For your use case, it should work fine if redis versions are the same. If your rdb file contains keys created by redis modules then you need to filter them out with regex like `sess_.+`

**Comment by u-maxx** [comment]
I am still getting the same error and number of keys imported even on Redis v6.2.7, 
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/2717220/189888943-98f7c546-b15f-45c9-bddc-76db92e9c4ab.png">
<img width="908" alt="image" src="https://user-images.githubusercontent.com/2717220/189889164-8a1092ef-1d21-4425-ac39-22188475b1ff.png">
Do you think this error is caused by the data inside my RDB file? 
I can't use the regex for RDB file since it is not a regular text file. Do you know any way to ignore some keys during export from Redis server to RDB file?

**Comment by u-maxx** [comment]
The error message during import is `Cannot execute command ERR unknown command `ef81c109dacbceb8e94b`, with args beginning with:`

**Comment by uglide** [comment]
@u-maxx  There is a field for that in the RESP.app import dialog:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/1655867/189897551-a71b8533-9fa2-4f34-932f-b5341e7e0b9a.png">

You just need to update default regex there.

**Comment by uglide** [comment]
@u-maxx It might be a good idea to just replace rdb file in local redis if it's just in a local container.

**Comment by u-maxx** [comment]
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/2717220/189898387-a2b37775-aa61-4ddc-9aa9-4ac55bb1a559.png">
<img width="890" alt="image" src="https://user-images.githubusercontent.com/2717220/189898501-ac607e23-bf0b-4752-acfc-7615bf6bc390.png">
There is only 1 key matching the text from the error message, and if I use the regex feature which you have mentioned - this key is imported w/o issues.  So I am not sure what is causing the error then on the full RDB file. 

I know about the possibility to manually replacing the RDB file, and tried that but Redis server was overwriting my file, so I started trying to use your tool for RDB import.

**Comment by u-maxx** [comment]
@uglide  thank you a lot for the help! I was able to find out why I was not able to import all the keys from RDB dump - the reason was that the data which were stored in the RDB is the sessions, which have expiration date, so during the import Redis was ignoring the info which has expired 🤯
