### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by kpvt001** [redis/RedisDesktopManager#5283]
**Describe the bug**
Many errors, such as "fatal error: 'snappy-stubs-public.h' file not found", "error: use of undeclared identifier 'QRegExp'",  etc.

**To Reproduce**
1. run git clone https://github.com/RedisInsight/RedisDesktopManager.git --recursive
2. open resp.pro
3. select build release
4. click build project resp

**Environment (please complete the following information):**
 - macos 13.2

**Comment by nicolgo** [comment]
Is there some update for this bug? or Can someone give a short guide to help us to build the project successfully? the readme file is too simple.

**Comment by nicolgo** [comment]
Is there update for this bug? I follow the /doc/install.md, it seems outdated, Is there someone can update the doc or fix the bug?

**Comment by nicolgo** [comment]
Hi @kpvt001 ,
you can follow the guide in [doc/install](https://github.com/RedisInsight/RedisDesktopManager/blob/2022/docs/install.md#quick-install) to build a release version. or you can follow [guide](https://docs.resp.app/en/latest/install/#build-from-source) to build a version. open the project directly will be failed.
