### ISSUE TITLE
redisinsight silent install documentation

### ISSUE THREAD

**Issue by fedesoundsystem** [redis/RedisDesktopManager#5293]
Hi,
there's no documentation about what switches are available to use the redisinsight windows installer
I tried to use the /?, /help, --help and so, and no switch tells me no info.
I found here about the /S (uppercase, as lowcase doesn't work regardless Windows doesn't mind about cases) but using it installs redisinsight for me only, I want to silently install it for all users.

**Comment by Rogue-Tek** [comment]
You can use these switches to install it silently for all users:
/AllUsers /S
Make sure to use capitals on the "A" and the "U" in AllUsers too. Just like you did on the "/S"

**Comment by fedesoundsystem** [comment]
That worked!
I couldn't find that swith anywhere, thank you for the answer!

**Comment by Rogue-Tek** [comment]
No problem. Yeah, I was searching for the same thing when I came across your post. I couldn't find it documented anywhere either. It took a little digging to figure it out.
