### ISSUE TITLE
Extend list of unsupported commands

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#53]
EXIT is unsupported too, but it is missing in note in console.
![selection_027](https://f.cloud.github.com/assets/539001/1436330/c0e0e0da-4154-11e3-9f69-51273829639e.png)

**Comment by uglide** [comment]
EXIT command is not supported by Redis, so RDM not supports it too :)

**Comment by loginwashere** [comment]
Oh, I'm sorry. I was mistaken by redis-cli )
