### ISSUE TITLE
Big data issue

### ISSUE THREAD

**Issue by Dyachenko** [redis/RedisDesktopManager#56]
RDM doesn't work with big data.
I want to open key with type hash which contain about 102585 fields.
when I do this RDM is not responding.

Win 7 x64 
RDM 0.5.1
Redis version 2.6.2
Connecting type SSH tunnel

**Comment by uglide** [comment]
Hello,

For benchmark I used Lua script:

``` lua
eval "for i = 1, 1000000 do redis.call('HSET', 'largeHash', i, i) end" 0

```

Redis Desktop Manager 0.6.0 works pretty fine:
![15-11-2013 11-44-33](https://f.cloud.github.com/assets/1655867/1549004/92a1963c-4dda-11e3-86ed-99c387809375.png)
