### ISSUE TITLE
Open new key in current tab and add possibility to open key in separate tab

### ISSUE THREAD

**Issue by Dyachenko** [redis/RedisDesktopManager#57]
Есть предложение не открывать просмотр значения ключа в новой табке т.к. их приходится постоянно закрывать, мне кажется лучше сделать по аналогу с браузером и открывать новую табку только по нажатию колесом на ключе, в противном случае показывать значения в текущей вкладке.

**Comment by stalker-druid** [comment]
действительно..
или что-то вроде "зафиксировать вкладку", если надо чтоб она не закрывалась автоматически..
вариант?

**Comment by dtr0yan** [comment]
+1

**Comment by loginwashere** [comment]
+1

**Comment by IhOrrr1** [comment]
+1

**Comment by uglide** [comment]
Implemented in 0.6.1
