### ISSUE TITLE
ssh tunnel port range

### ISSUE THREAD

**Issue by krzysztofantczak** [redis/RedisDesktopManager#59]
It seems that it's not possible to use port higher than 10000 for ssh tunnel.

**Comment by uglide** [comment]
Hello,

Thanks for your feedback. I will increase it to 65 536.

**Comment by dtr0yan** [comment]
65535 is enough :)

**Comment by nilskp** [comment]
LOL, now I'm kinda worried :-)

**Comment by uglide** [comment]
Please don't worry. I'm just excited about playing with big random numbers :)

**Comment by uglide** [comment]
Fixed in 0.6.0
