### ISSUE TITLE
when tunneling please prompt for password instead of storing it in plaintext

### ISSUE THREAD

**Issue by rtanaka** [redis/RedisDesktopManager#600]
Ideally support for ssh keys listed here would be nice as listed here: https://github.com/uglide/RedisDesktopManager/issues/32

In the meantime, it would be nice to remove the requirement to store the password as plaintext and prompt for it instead.

**Comment by uglide** [comment]
I will implement ssh keys support ( #32 )  and encryption of connection settings ( #30 )
