### ISSUE TITLE
Ubuntu 13.10 support

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#64]
Tried installing rdm on Ubuntu 13.10 machine and it installed fine but when I launch rdm this error occur:

```
$ /usr/share/redis-desktop-manager/bin/rdm
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

After that I tried installing xcb:

```
$ sudo apt-get install xcb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  xcb
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 22,9 kB of archives.
After this operation, 91,1 kB of additional disk space will be used.
Get:1 http://ua.archive.ubuntu.com/ubuntu/ saucy/universe xcb amd64 2.4-4.3 [22,9 kB]
Fetched 22,9 kB in 0s (58,7 kB/s)
Selecting previously unselected package xcb.
(Reading database ... 207893 files and directories currently installed.)
Unpacking xcb (from .../archives/xcb_2.4-4.3_amd64.deb) ...
Processing triggers for man-db ...
Setting up xcb (2.4-4.3) ...
```

But message about missing xcb remain after that the same.

**Comment by uglide** [comment]
Probably problem in your system, on clean 13.10 installed from scratch - Redis Desktop Manager works fine. 

![ubuntu](https://f.cloud.github.com/assets/1655867/1550172/c6fefda8-4dfc-11e3-84fb-fd6cbe4990b2.png)

**Comment by thibaultdalban** [comment]
Hello,

Same problem for me.
@loginwashere, have you find a solution ?

Thx

**Comment by loginwashere** [comment]
No, @thibaultdalban, this issue was somehow resolved by itself after some time and a couple of packages installed.

Though I haven't tried to find the package which helped, I have suspicion that it was Skype.

Installation of libxcb might help, but I don't know for sure.

**Comment by thibaultdalban** [comment]
Ok, I'll try to install the lib...

Thank you.
Le 30 déc. 2013 17:31, "Dmitriy Savchenko" notifications@github.com a
écrit :

**Comment by loginwashere** [comment]
Also, giving more information about version of rdm you are trying to install and about your environment probably will help find the source of problem.

**Comment by Robert-Leleu** [comment]
Same problem with Musescore (using Mint16MATE64)
BTW Skype is installed.
