### ISSUE TITLE
Implement db key filtering

### ISSUE THREAD

**Issue by loginwashere** [redis/RedisDesktopManager#65]
At the moment during key search rdm look for key across all redis instances and there is no way of restricting search to specific redis server.

This process will take significant time if user have many large redis instances.

It would be useful to have ability of selecting redis instance to search and if no instances were selected, perform search across all of them.

**Comment by uglide** [comment]
Implemented: 0.7.9.512 (OS X) and 0.7.9.809 (Windows)
