### ISSUE TITLE
Colon as tree item separator

### ISSUE THREAD

**Issue by AlexKovynev** [redis/RedisDesktopManager#652]
I am save mac address in a key, and see not fine picture.
Maybe this can be an option?

**Comment by uglide** [comment]
Yes, it can. Thanks for feedback.

**Comment by RKelln** [comment]
Same issue, different data (but still colons), would be nice to be able to set the "delimiter" character.

**Comment by uglide** [comment]
Implemented in 0.7.6
![2-13-2014 12-37-25 pm](https://f.cloud.github.com/assets/1655867/2158876/eac27802-949a-11e3-8289-063b49787706.jpg)
