### ISSUE TITLE
Keys listing order

### ISSUE THREAD

**Issue by dtr0yan** [redis/RedisDesktopManager#66]
Please output the keys in alphabetical order. It's hard to find something when keys look like this 
![screen](https://f.cloud.github.com/assets/1052805/1561441/552de176-5031-11e3-8934-4762cd33b038.png)

Thanks

**Comment by dtr0yan** [comment]
v0.5.2

**Comment by dtr0yan** [comment]
Oh, I see it fixed on 0.6.0

**Comment by dtr0yan** [comment]
This small bug need to be fixed I think
![screen- 2013-11-18 - 11-25 2](https://f.cloud.github.com/assets/1052805/1561515/7f34e90e-5033-11e3-9b08-3ddcd6fc0757.png)

**Comment by uglide** [comment]
Thanks, I will fix it

**Comment by uglide** [comment]
I fixed it in 0.6.0, but starting from 0.7.0 sorting will be optional.
