### ISSUE TITLE
distortion code, wo can't read

### ISSUE THREAD

**Issue by binlaniua** [redis/RedisDesktopManager#678]
![image](https://f.cloud.github.com/assets/5960462/1951562/472af09e-8184-11e3-843a-468a470edb17.png)

**Comment by uglide** [comment]
Can you provide sample string for testing?

**Comment by candyman888** [comment]
I have the same problem all keys display in this format.  Clicking on any entry gives me a message "Can not load key value. Key was removed or redis-server went away."  I'm on Windows XP.  Haven't been able to get past this to use the software.

**Comment by uglide** [comment]
Duplicate of #1718
