### ISSUE TITLE
Не обновляется список серверов. Не отображаются свежедобавленные сервера.

### ISSUE THREAD

**Issue by stalker-druid** [redis/RedisDesktopManager#69]
Если открыть хотя бы одну вкладку (ключ), то при добавлении новых серверов их не видно в списке. Чтоб увидеть их приходится закрывать приложение и запускать его заново.

**Comment by uglide** [comment]
Не воспроизводиться на версии 0.6.0-DP1

**Comment by stalker-druid** [comment]
возможно оказывает на это влияние версия OS
у меня win xp 64
