### ISSUE TITLE
Set focus on Add Connection modal window

### ISSUE THREAD

**Issue by stalker-druid** [redis/RedisDesktopManager#70]
Мне кажется было б удобнее, если б при добавлении нового или редактировании существующего коннекта не приходилось тыкать мышкой по открывшимуся окну, а сразу вводить данные.

**Comment by loginwashere** [comment]
Проверил на всякий случай еще раз - при открытии окна создания или редактирования соединения фокус перемещается на поле host. Далее по форме можно перемещаться вниз (tab) и вверх (shift + tab)

Если данный вариант навигации не работает или работает отлично от описанного, наверно стоит описать версию rdm и окружение.

Ubuntu 13.10, redis-desktop-manager_0.6.0_i386.

**Comment by uglide** [comment]
В Windows фокус остается на главном окне, скорее всего поведение одинаково для всех версий.

**Comment by uglide** [comment]
Fixed in 0.6.2
