### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by cnuco** [redis/RedisDesktopManager#729]
[Client] RDM version: 0.7.5
Platform: WindowsXP sp3 32bit
[Server] Redis version: 2.6.
Platform:Linux 2.6.18-164.el5xen x86_64
Mode: Master-Slaver
![error](https://f.cloud.github.com/assets/1930533/1991771/b716ea20-84a4-11e3-880c-718c3e1b8c36.jpg)

**Comment by uglide** [comment]
Fixed in 0.8.0
