### ISSUE TITLE
Improve validation and add fields trimming in connection form

### ISSUE THREAD

**Issue by stalker-druid** [redis/RedisDesktopManager#73]
Бывает при копировании хоста случайно копируется пробел, который не всегда сразу бывает обнаружен. Это чревато длительным и нервным поиском причин невозможности законектиться..
Хорошо б чтоб в этом случае пробелы удалялись или хотя бы предупреждалось о их наличии.

**Comment by uglide** [comment]
Implemented in 0.6.0
