### ISSUE TITLE
Word wrap for too long values

### ISSUE THREAD

**Issue by dtr0yan** [redis/RedisDesktopManager#74]
![screen- 2013-11-20 - 18-51 2](https://f.cloud.github.com/assets/1052805/1583895/309f2b24-5204-11e3-8dd7-480e8a18cea1.png)

Please improve values readability with word wrapping

**Comment by uglide** [comment]
Hi!

Thanks for feedback!
I currently work on value views :) 
It will look like this:
![20-11-2013 19-07-32](https://f.cloud.github.com/assets/1655867/1584060/50847924-5206-11e3-980b-897ab134237e.png)

**Comment by uglide** [comment]
Implemented in 0.6.1
