### ISSUE TITLE
keys rendering bug

### ISSUE THREAD

**Issue by dtr0yan** [redis/RedisDesktopManager#76]
version 0.6.1-dev

Steps to reproduce:
1. open any redis connection
2. Click on db
3. Click on Reload in context menu on this connection before this db rendered

Expected: connection is reload and we can see db list.
Actual: list is blank, see next image
![screen- 2013-11-21 - 18-28 2](https://f.cloud.github.com/assets/1052805/1593351/065245d8-52ca-11e3-95e1-8883a611e64d.png)

**Comment by uglide** [comment]
Fixed in 0.6.1
