### ISSUE TITLE
Implement autoupdate on Windows

### ISSUE THREAD

**Issue by bashmach** [redis/RedisDesktopManager#80]
It might be very cool to have some chance to update the application in one-click. Anything that will help to rid off the current painful process of update - redirecting to the site, downloading, installation, fail of installation because application is still opened, installation again.
##

**Comment by uglide** [comment]
There are a couple of problems, which can be solved without implementation of Updater. 
1. Application must give direct link to installer, so you will need just one click to download installer.
2. Installer will close Redis Desktop Manager if it running (on Windows)

Updater will be great feature, but so far I need to implement many other important features. Thats why I moved this feature to the 1.0.0 milestone.

**Comment by bashmach** [comment]
No worries. I switched back to linux, so I'm more than satisfied with the update process now :)

**Comment by uglide** [comment]
I chaged scope for this feature, because on OSX users already can autoupdate RDM via Homebrew and for Ubuntu users PPA will be available as well (#3575)

**Comment by uglide** [comment]
It took only 7 years to fix this issue :smile_cat: . Starting from today auto-updated RDM is available from Microsoft Store https://www.microsoft.com/store/apps/9NDK76ZVZ3TM
