### ISSUE TITLE
Feature request: Confirmation dialogue on delete

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#838]
#### Feature request: Confirmation dialogue on delete

I think that it should be appropriate to pop a confirmation dialogue upon key deletion. That is, when a user clicks the deletion button when viewing a key, there should be some pop up to confirm this action. 

![Screenshot](https://f.cloud.github.com/assets/690145/2044516/23328ca4-89ec-11e3-952c-b2176dc49c92.png)

**Comment by uglide** [comment]
Fixed in 0.7.6

**Comment by samhk222** [comment]
I was about to open a Feature request for this item ... it's possible to put this behaviour in the settings? Because i like to delete without the confirmation ... it saves a lot of time in my case ... 

Sorry to bother! Thanks!
