### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#839]
This is a low priority issue.

The font used is most likely the default font, or a font I don't have (using Ubuntu). I think it would be better to specify a sans-serif font since it would look more appropriate and elegant. See image below.

![Font issue](https://f.cloud.github.com/assets/690145/2045416/fff31fb8-89f7-11e3-91fd-42d73914e722.png)

P.S. I would had tried to solve this myself, but I fail to compile the code myself (make fails). I don't have the time to find out why now, so I'm leaving it to you. Perhaps I'll figure it out later. Thank you!

**Comment by uglide** [comment]
Fixed
