### ISSUE TITLE
window crash when reload connection

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#84]
My pc :
Linux sha 3.5.0-37-generic #58-Ubuntu SMP Mon Jul 8 22:10:28 UTC 2013 i686 athlon i686 GNU/Linux

My colleague's pc is win7 64bit system.

And what I am doing:
1. start desktop manager, then we'll see the data
2. in terminal, add a data to redis
3. back to manger, and find that data do not refleshed, I cannot find the the newly add data in manager
4. so , I select manager, and right click the mouse, there will be reload menu
5, when I click it, the whole window crash. And I must restart it.

Sorry for reply late.

**Comment by uglide** [comment]
Hello!

Please describe steps to reproduce this bug. Thanks!

**Comment by ghost** [comment]
My pc :

Linux sha 3.5.0-37-generic #58-Ubuntu SMP Mon Jul 8 22:10:28 UTC 2013 i686 athlon i686 GNU/Linux

And what I am doing:
1. start desktop manager, then we'll see the data
2. in terminal,  add a data to redis
3. back to manger, and find that data do not refleshed, I cannot find the the newly add data in manager
4. so , I select manager, and right click the mouse, there will be reload menu
5, when I click it, the whole window crash. And I must restart it.

My colleague's pc is win7 64bit system.

Sorry for reply late.

**Comment by uglide** [comment]
Do you use latest version of Redis Desktop Manager - 0.6.2 ?

**Comment by ghost** [comment]
yes, the version is :

redis-desktop-manager_0.6.2_i386_ubuntu.deb

**Comment by MrAntix** [comment]
Me too, same steps as described above

Unhandled exception at 0x5406193B (Qt5Gui.dll) in redis-desktop-manager.exe: 0xC0000005: Access violation reading location 0x00000014.

windows 8.1 64bit
RDM v0.6.2

**Comment by uglide** [comment]
Hello guys!

Please try new version 0.7.1 - http://redisdesktop.com/download

**Comment by TobyMosby** [comment]
I can't find the issue I submitted that duplicates this. But had same trouble with 0.7.1-0.7.3, yet I find (on Windows) this is resolved quite nicely in latest update (0.7.4).
