### ISSUE TITLE
set db_number 20 exit

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#86]
when i input "set db_number 20" in command line, I can get the result of "OK", but i reload in RDM, it's crashing and exit.I install redis by default, so I only have database 0-15.

**Comment by uglide** [comment]
Hello!

Please describe steps to reproduce this bug. Thanks!

**Comment by ghost** [comment]
1.start redis-server
2.start redis-cli and execute command 'set db_number 20'
3.start RDM, click localhost, select db0(1), select db_number.
4.right click localhost and reload.
the crash is happened.

**Comment by uglide** [comment]
It's strange, because I can't reproduce this bug. Do you use latest version of Redis Desktop Manager - 0.6.2 ?

**Comment by uglide** [comment]
Duplicate of #84
