### ISSUE TITLE
Delete namespaces from db [$110 awarded]

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#89]
> It's great that rdm groups similar keys by :. What would be awesome is the ability to delete all children  belonging to this node easily. For e.g., if I have 2 keys A:12, A:13, RDM groups them both under A. It  would be nice to be able to delete all items under A in a single go.
##

**Comment by dmagliola** [comment]
+1!

**Comment by plamendp** [comment]
The only thing that keeps me a bit away from Redis Desktop Manager is this missing feature, wich is a key for me, because I have to handle many keys. I have to switch to other tools to do that.  What is the final bounty to make you implement this one?  :-)

**Comment by uglide** [comment]
@plamendp post $100+ and it will increase development speed of this feature :-)

**Comment by plamendp** [comment]
@uglide  Fair enough. Will do. As long as it won't take .... 1 year :-)

**Comment by uglide** [comment]
@plamendp if I have time/resources to work on the project, first release candidate with multi bulk operations (namespace deletion, bulk renaming, etc) will be in September

**Comment by plamendp** [comment]
Done. Can't wait. Good luck.

**Comment by uglide** [comment]
@plamendp awesome, thanks

**Comment by uglide** [comment]
@plamendp Which Operations System do you use?

**Comment by uglide** [comment]
@plamendp please ping me via email `u.glide@gmail.com` . I need your email to send you night build with this new feature

**Comment by uglide** [comment]
Implemented in 0.8.7. Try it in latest Windows night build https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.8.6.302/artifacts

**Comment by SAnDAnGE** [comment]
This feature is not working for different key separators. I am using "." as key separator and it always tries to delete a.b:*
