### ISSUE TITLE
фильтр по ключам

### ISSUE THREAD

**Issue by stalker-druid** [redis/RedisDesktopManager#9]
Хотелось бы иметь фильтр по ключам. Бо найти искомый ключ среди тысяч - проблемотично. Было б круто, если б фильтр поддерживал регулярки. Ну или хотяб возможность выбирать показывать или прятать результаты удовлетворяющие фильтру. Это здорово поможет находить данные, несоответствующие принятому в базе формату.

**Comment by uglide** [comment]
Key search implemented in 0.4.0, thanks for feedback!

![06-10-2013 13-19-30](https://f.cloud.github.com/assets/1655867/1276516/0a57083a-2e71-11e3-9665-6f0b6b3a8edd.png)
![06-10-2013 13-20-44](https://f.cloud.github.com/assets/1655867/1276517/0d81f7c2-2e71-11e3-8448-cf79cd5ebff6.png)
