### ISSUE TITLE
отображение значений удаленных ключей как пустых

### ISSUE THREAD

**Issue by stalker-druid** [redis/RedisDesktopManager#90]
Ситуация, когда ключ присутствует в дереве, но реально он уже удален с редиса..
Сейчас, если кликнуть на этот ключ - покажет, что он пустой..
Но это не соответствует истине.. может стоит как-то изменить поведение? Написать, что он удален, например.. или крестиком в дереве пометить после того как узнали, что он удален..
Или может еще как, но дать знать, что самого ключа нет, а не только значения в нем..

**Comment by uglide** [comment]
done
